<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
    <ProjectReference Include="..\SharpProof.Summaries\SharpProof.Summaries.csproj" />
  </ItemGroup>
</Project>
