global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.Loader;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using NUnit.Framework;
global using SharpProof.Attributes;
global using SharpProof.Effects;
global using SharpProofCapability = SharpProof.Effects.EffectContractCapabilityKind;
global using SharpProofEffect = SharpProof.Effects.EffectContractKind;
