<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
    <ProjectReference Include="..\SharpProof.Specs\SharpProof.Specs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Smt.Test" />
    <InternalsVisibleTo Include="SharpProof.Fuzz" />
    <InternalsVisibleTo Include="SharpProof.Verify.Test" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
  </ItemGroup>
</Project>
