// <auto-generated>
// Generated by scripts/Generate-ProjectionCatalog.ps1 from
// SharpProof.Projection.catalog.json.
// Declarative projection tables only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Verify;

internal static class VerificationProjections
{
    internal static AbstentionReason MapFailure(
        BackendFailureReason reason
    )
    {
        return reason switch
        {
            BackendFailureReason.UnsupportedEncoding => AbstentionReason.UnsupportedEncoding,
            BackendFailureReason.ResourceLimit => AbstentionReason.ResourceLimit,
            BackendFailureReason.Timeout => AbstentionReason.Timeout,
            BackendFailureReason.Unavailable => AbstentionReason.BackendUnavailable,
            BackendFailureReason.InfrastructureFailure => AbstentionReason.InfrastructureFailure,
            _ => AbstentionReason.MalformedBackendResult
        };
    }
}
