// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable

namespace SharpProof.BuildTasks;

internal static class LauncherRuntimeCompanionInventory
{
    internal static string[] FileNames { get; } = [
        "SharpProof.CompilerArtifact.dll",
        "SharpProof.Host.dll",
        "SharpProof.Ir.dll",
        "SharpProof.Specs.dll",
        "SharpProof.Worker.Protocol.dll",
        "System.IO.Pipelines.dll",
        "System.Text.Encodings.Web.dll",
        "System.Text.Json.dll",
    ];
}
