<Project>
  <Import Project="$(MSBuildThisFileDirectory)SharpProof.Release.props" />

  <PropertyGroup>
    <MicrosoftZ3PackageVersion>4.12.2</MicrosoftZ3PackageVersion>
    <Nullable Condition="'$(Nullable)' == ''">enable</Nullable>
    <ImplicitUsings Condition="'$(ImplicitUsings)' == ''">enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>

    
    <EnableVsixPackaging Condition="'$(EnableVsixPackaging)' == 'true'">true</EnableVsixPackaging>
    <EnableVsixPackaging Condition="'$(EnableVsixPackaging)' != 'true' AND '$(BuildingInsideVisualStudio)' == 'true'">true</EnableVsixPackaging>
    <EnableVsixPackaging Condition="'$(EnableVsixPackaging)' != 'true' AND '$(BuildingInsideVisualStudio)' != 'true'">false</EnableVsixPackaging>
    
    
    <IsPackable Condition="'$(MSBuildProjectName)' == 'SharpProof.Vsix'">false</IsPackable>
    
    
    <NoWarn Condition="'$(MSBuildProjectName)' == 'SharpProof.Vsix'">$(NoWarn);NU5026</NoWarn>
    
    
    <DefaultItemExcludes Condition="'$(MSBuildProjectExtension)' == '.sln'">$(DefaultItemExcludes);SharpProof.Vsix\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
