<Project>
  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)SharpProof.Attributes\SharpProof.Attributes.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)SharpProof.Analyzer\SharpProof.Analyzer.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)SharpProof.Symbolic\SharpProof.Symbolic.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)SharpProof.ProofCore\SharpProof.ProofCore.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <Analyzer Include="$(MSBuildThisFileDirectory)SharpProof.Attributes\bin\$(Configuration)\netstandard2.0\SharpProof.Attributes.dll" />
  </ItemGroup>
</Project>
