<Project>
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoPackageAnalysis>true</NoPackageAnalysis>
  </PropertyGroup>
  <Target Name="_SharpProofPrepareCommonNuspecProperties">
    <PropertyGroup>
      <_SharpProofNuspecPrefix>version=$(SharpProofPackageVersion);configuration=$(Configuration);repositorycommit=$(RepositoryCommit)</_SharpProofNuspecPrefix>
      <_SharpProofNuspecSuffix>authors=$(Authors);license=$(PackageLicenseExpression);readme=$(PackageReadmeFile);copyright=$(PackageCopyright);projecturl=$(PackageProjectUrl);repositorytype=$(RepositoryType);repositoryurl=$(RepositoryUrl)</_SharpProofNuspecSuffix>
    </PropertyGroup>
  </Target>
</Project>
