<Project>
  <PropertyGroup>
    <Authors>$(SharpProofPublisher)</Authors>
    <PackageCopyright>Copyright (c) $(SharpProofPublisher)</PackageCopyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>$(SharpProofProjectUrl)</PackageProjectUrl>
    <RepositoryUrl>$(SharpProofProjectUrl)</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryCommit Condition="'$(RepositoryCommit)' == ''">$(GITHUB_SHA)</RepositoryCommit>
  </PropertyGroup>
</Project>
