<Project>
  <PropertyGroup>
    <SharpProofPublisher>Alex Yorke</SharpProofPublisher>
    <SharpProofVersionPrefix>1.0.0</SharpProofVersionPrefix>
    <SharpProofAssemblyVersion>$(SharpProofVersionPrefix).0</SharpProofAssemblyVersion>
    <SharpProofPackageVersion>$(SharpProofVersionPrefix)-preview.1</SharpProofPackageVersion>
    <Version>$(SharpProofPackageVersion)</Version>
    <AssemblyVersion>$(SharpProofAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(SharpProofAssemblyVersion)</FileVersion>
    <InformationalVersion>$(SharpProofPackageVersion)</InformationalVersion>
    <SharpProofProjectUrl>https://github.com/alexyorke/SharpProof</SharpProofProjectUrl>
  </PropertyGroup>
</Project>
