// <auto-generated>
// Generated by scripts/Generate-ApiSpecCatalog.ps1 from
// SharpProof.Specs/DefaultApiSpecCatalog.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Specs;

public enum SpecEvidenceKind
{
    Documented,
    Observed
}

[Flags]
public enum SpecEffect
{
    None = 0,
    Unknown = 1 << 0,
    ReadsReceiverState = 1 << 1,
    ReadsArgumentState = 1 << 2,
    WritesReceiverState = 1 << 3,
    WritesArgumentState = 1 << 4,
    ReadsAmbientState = 1 << 5,
    WritesAmbientState = 1 << 6,
    InputOutput = 1 << 7,
    Synchronization = 1 << 8,
    NativeCode = 1 << 9,
    Reflection = 1 << 10,
    Nondeterminism = 1 << 11
}

public enum SpecAllocationBehavior
{
    None,
    MayAllocate,
    Unknown
}

public enum SpecThrowBehavior
{
    DoesNotThrow,
    MayThrow,
    Unknown
}

public enum SpecTerminationBehavior
{
    Terminates,
    Unknown
}

public enum SpecNullness
{
    NotApplicable,
    NonNull,
    MaybeNull,
    Null,
    Unknown
}

public enum SpecCardinality
{
    NotApplicable,
    Empty,
    NonEmpty,
    Exact,
    Unknown
}

public enum SpecTargetMemberKind
{
    Constructor,
    Method,
    PropertyGet
}

public enum SpecVariableRole
{
    Receiver,
    Parameter,
    Result
}

public sealed record SpecEvidence(SpecEvidenceKind Kind, string Source);
public sealed record SpecEffectFacet(SpecEffect Effects, SpecEvidence Evidence);
public sealed record SpecAllocationFacet(SpecAllocationBehavior Behavior, SpecEvidence Evidence);
public sealed record SpecThrowFacet(
    SpecThrowBehavior Behavior, ImmutableArray<string> ExceptionMetadataNames, SpecEvidence Evidence);
public sealed record SpecTerminationFacet(
    SpecTerminationBehavior Behavior, SpecEvidence Evidence);
public sealed record SpecNullnessFacet(SpecNullness Result, SpecEvidence Evidence);
public sealed record SpecCardinalityFacet(
    SpecCardinality Result, int? ExactCount, SpecEvidence Evidence);

public enum ApiSpecReferenceFamily
{
    Unspecified,
    MicrosoftNetCoreReferencePack,
    NetStandardReferencePack,
    NetFrameworkReferenceAssemblies,
    MicrosoftNetCoreRuntime,
    SharpProofPackage
}

public sealed record ApiSpecFacets(
    SpecEffectFacet Effects, SpecAllocationFacet Allocation,
    SpecThrowFacet Throws, SpecNullnessFacet Nullness,
    SpecCardinalityFacet Cardinality,
    SpecTerminationFacet? Termination = null);

public sealed record ApiSpecAssemblyIdentity(
    string Name,
    string PublicKeyToken,
    ApiSpecReferenceFamily ReferenceFamily =
        ApiSpecReferenceFamily.Unspecified);

public sealed record ApiSpecTarget(
    string WitnessIdentifier, string DocumentationCommentId,
    string ContainingTypeMetadataName, SpecTargetMemberKind MemberKind,
    string MemberName, bool IsStatic, int GenericArity,
    IrTypeKind? ReceiverType, ImmutableArray<IrTypeKind> ParameterTypes,
    IrTypeKind? ResultType,
    ImmutableArray<ApiSpecAssemblyIdentity> ApprovedAssemblies);

public abstract record SpecTermDeclaration(IrTypeKind Type);

public sealed record SpecVariableDeclaration(SpecVariableRole Role, int Ordinal, IrTypeKind Type)
    : SpecTermDeclaration(Type);

public sealed record SpecBooleanDeclaration(bool Value)
    : SpecTermDeclaration(IrTypeKind.Boolean);

public sealed record SpecIntegerDeclaration(long Value)
    : SpecTermDeclaration(IrTypeKind.Integer);

public sealed record SpecStringDeclaration(string Value)
    : SpecTermDeclaration(IrTypeKind.String);

public sealed record SpecNullDeclaration(IrTypeKind Type)
    : SpecTermDeclaration(Type);

public sealed record SpecUnaryDeclaration(
    IrUnaryOperator Operator, SpecTermDeclaration Operand, IrTypeKind Type)
    : SpecTermDeclaration(Type);

public sealed record SpecBinaryDeclaration(
    IrBinaryOperator Operator, SpecTermDeclaration Left,
    SpecTermDeclaration Right, IrTypeKind Type)
    : SpecTermDeclaration(Type);

public sealed record SpecConditionalDeclaration(
    SpecTermDeclaration Condition, SpecTermDeclaration WhenTrue,
    SpecTermDeclaration WhenFalse, IrTypeKind Type)
    : SpecTermDeclaration(Type);

public sealed record SpecLengthDeclaration(SpecTermDeclaration Value)
    : SpecTermDeclaration(IrTypeKind.Integer);

public sealed record SpecPostconditionDeclaration(SpecTermDeclaration Condition, SpecEvidence Evidence);

public sealed record ApiSpecDeclaration(
    ApiSpecTarget Target, ApiSpecFacets Facets,
    ImmutableArray<SpecPostconditionDeclaration> Postconditions);

public sealed record SpecVariableInfo(
    SpecVarId Id, SpecVariableRole Role, int Ordinal, IrTypeKind Type);

public sealed record SpecPostcondition(
    SpecTermDeclaration Condition, SpecEvidence Evidence);

public sealed class ApiSpecTemplate
{
    internal ApiSpecTemplate(
        SpecId id, ApiSpecTarget target, ApiSpecFacets facets,
        ImmutableArray<SpecVariableInfo> variables, SpecVarId? receiver,
        ImmutableArray<SpecVarId> parameters, SpecVarId? result,
        ImmutableArray<SpecPostcondition> postconditions)
    {
        (Id, Target, Facets, Variables) = (id, target, facets, variables);
        (Receiver, Parameters, Result, Postconditions) =
            (receiver, parameters, result, postconditions);
    }

    public SpecId Id { get; }
    public ApiSpecTarget Target { get; }
    public ApiSpecFacets Facets { get; }
    public ImmutableArray<SpecVariableInfo> Variables { get; }
    public SpecVarId? Receiver { get; }
    public ImmutableArray<SpecVarId> Parameters { get; }
    public SpecVarId? Result { get; }
    public ImmutableArray<SpecPostcondition> Postconditions { get; }
}

public sealed partial class ApiSpecTable
{
    public const string DefaultTableIdentity = "SharpProof.ApiSpec.Default";
    public const string DefaultTableVersion = "5";

    private static ImmutableArray<ApiSpecDeclaration> CreateDefaultDeclarations()
    {
        ImmutableArray<ApiSpecAssemblyIdentity> assemblySetFramework = [
            new("System.Private.CoreLib", "7cec85d7bea7798e", ApiSpecReferenceFamily.MicrosoftNetCoreRuntime),
            new("mscorlib", "b77a5c561934e089", ApiSpecReferenceFamily.NetFrameworkReferenceAssemblies),
            new("mscorlib", "b77a5c561934e089", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("mscorlib", "b77a5c561934e089", ApiSpecReferenceFamily.NetStandardReferencePack),
            new("System.Runtime", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetFrameworkReferenceAssemblies),
            new("System.Runtime", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("System.Runtime", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetStandardReferencePack),
            new("netstandard", "cc7b13ffcd2ddd51", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("netstandard", "cc7b13ffcd2ddd51", ApiSpecReferenceFamily.NetStandardReferencePack),
            new("System.Collections", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetFrameworkReferenceAssemblies),
            new("System.Collections", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("System.Collections", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetStandardReferencePack),
            new("System.Linq", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetFrameworkReferenceAssemblies),
            new("System.Linq", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("System.Linq", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.NetStandardReferencePack),
            new("System.Linq", "b03f5f7f11d50a3a", ApiSpecReferenceFamily.MicrosoftNetCoreRuntime),
            new("System.Core", "b77a5c561934e089", ApiSpecReferenceFamily.NetFrameworkReferenceAssemblies),
            new("System.Core", "b77a5c561934e089", ApiSpecReferenceFamily.MicrosoftNetCoreReferencePack),
            new("System.Core", "b77a5c561934e089", ApiSpecReferenceFamily.NetStandardReferencePack),
        ];
        ImmutableArray<ApiSpecAssemblyIdentity> assemblySetSharpProofAttributes = [
            new("SharpProof.Attributes", "", ApiSpecReferenceFamily.SharpProofPackage),
        ];
        var evidenceContractSemantics = new SpecEvidence(SpecEvidenceKind.Documented, "sharpproof-compiler-bound-ghost-contract");
        var evidenceDocumented = new SpecEvidence(SpecEvidenceKind.Documented, "dotnet-api-contract");
        var evidenceObserved = new SpecEvidence(SpecEvidenceKind.Observed, "supported-runtime-observation");
        var evidenceTypeInitialization = new SpecEvidence(SpecEvidenceKind.Documented, "dotnet-generic-cache-type-initialization-boundary");
        return [
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.array.empty",
                    "M:System.Array.Empty``1",
                    "System.Array",
                    SpecTargetMemberKind.Method, "Empty",
                    true, 1, null, [], IrTypeKind.Sequence,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.Unknown, evidenceTypeInitialization),
                    new SpecAllocationFacet(SpecAllocationBehavior.Unknown, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceDocumented),
                    new SpecNullnessFacet(SpecNullness.NonNull, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.Empty, null, evidenceDocumented),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.enumerable.empty",
                    "M:System.Linq.Enumerable.Empty``1",
                    "System.Linq.Enumerable",
                    SpecTargetMemberKind.Method, "Empty",
                    true, 1, null, [], IrTypeKind.Sequence,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.Unknown, evidenceTypeInitialization),
                    new SpecAllocationFacet(SpecAllocationBehavior.Unknown, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NonNull, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.Empty, null, evidenceDocumented),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.exception.ctor",
                    "M:System.Exception.#ctor",
                    "System.Exception",
                    SpecTargetMemberKind.Constructor, ".ctor",
                    false, 0, IrTypeKind.Reference, [], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.WritesReceiverState, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    new SpecTerminationFacet(SpecTerminationBehavior.Terminates, evidenceObserved)),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.exception.ctor.string",
                    "M:System.Exception.#ctor(System.String)",
                    "System.Exception",
                    SpecTargetMemberKind.Constructor, ".ctor",
                    false, 0, IrTypeKind.Reference, [IrTypeKind.String], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.WritesReceiverState, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    new SpecTerminationFacet(SpecTerminationBehavior.Terminates, evidenceObserved)),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.invalid-operation-exception.ctor",
                    "M:System.InvalidOperationException.#ctor",
                    "System.InvalidOperationException",
                    SpecTargetMemberKind.Constructor, ".ctor",
                    false, 0, IrTypeKind.Reference, [], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.WritesReceiverState, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    new SpecTerminationFacet(SpecTerminationBehavior.Terminates, evidenceObserved)),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.invalid-operation-exception.ctor.string",
                    "M:System.InvalidOperationException.#ctor(System.String)",
                    "System.InvalidOperationException",
                    SpecTargetMemberKind.Constructor, ".ctor",
                    false, 0, IrTypeKind.Reference, [IrTypeKind.String], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.WritesReceiverState, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    new SpecTerminationFacet(SpecTerminationBehavior.Terminates, evidenceObserved)),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.list.add",
                    "M:System.Collections.Generic.List`1.Add(`0)",
                    "System.Collections.Generic.List`1",
                    SpecTargetMemberKind.Method, "Add",
                    false, 0, IrTypeKind.Reference, [IrTypeKind.Reference], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.WritesReceiverState, evidenceDocumented),
                    new SpecAllocationFacet(SpecAllocationBehavior.MayAllocate, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.Unknown, [], evidenceDocumented),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.math.abs.int32",
                    "M:System.Math.Abs(System.Int32)",
                    "System.Math",
                    SpecTargetMemberKind.Method, "Abs",
                    true, 0, null, [IrTypeKind.Integer], IrTypeKind.Integer,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.MayThrow, ["System.OverflowException"], evidenceDocumented),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    null),
                [
                    new SpecPostconditionDeclaration(
                        new SpecBinaryDeclaration(IrBinaryOperator.GreaterThanOrEqual, new SpecVariableDeclaration(SpecVariableRole.Result, -1, IrTypeKind.Integer), new SpecIntegerDeclaration(0), IrTypeKind.Boolean),
                        evidenceDocumented),
                ]),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.object.ctor",
                    "M:System.Object.#ctor",
                    "System.Object",
                    SpecTargetMemberKind.Constructor, ".ctor",
                    false, 0, IrTypeKind.Reference, [], null,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    new SpecTerminationFacet(SpecTerminationBehavior.Terminates, evidenceObserved)),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.string.concat.string-string",
                    "M:System.String.Concat(System.String,System.String)",
                    "System.String",
                    SpecTargetMemberKind.Method, "Concat",
                    true, 0, null, [IrTypeKind.String, IrTypeKind.String], IrTypeKind.String,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceObserved),
                    new SpecAllocationFacet(SpecAllocationBehavior.MayAllocate, evidenceDocumented),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceDocumented),
                    new SpecNullnessFacet(SpecNullness.NonNull, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "bcl.string.length",
                    "P:System.String.Length",
                    "System.String",
                    SpecTargetMemberKind.PropertyGet, "Length",
                    false, 0, IrTypeKind.String, [], IrTypeKind.Integer,
                    assemblySetFramework),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.ReadsReceiverState, evidenceDocumented),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceObserved),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceObserved),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceDocumented),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceDocumented),
                    null),
                [
                    new SpecPostconditionDeclaration(
                        new SpecBinaryDeclaration(IrBinaryOperator.Equal, new SpecVariableDeclaration(SpecVariableRole.Result, -1, IrTypeKind.Integer), new SpecLengthDeclaration(new SpecVariableDeclaration(SpecVariableRole.Receiver, -1, IrTypeKind.String)), IrTypeKind.Boolean),
                        evidenceDocumented),
                ]),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "contract.assume",
                    "M:SharpProof.Attributes.Contract.Assume(System.Boolean)",
                    "SharpProof.Attributes.Contract",
                    SpecTargetMemberKind.Method, "Assume",
                    true, 0, null, [IrTypeKind.Boolean], null,
                    assemblySetSharpProofAttributes),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceContractSemantics),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceContractSemantics),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceContractSemantics),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceContractSemantics),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceContractSemantics),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "contract.ensures",
                    "M:SharpProof.Attributes.Contract.Ensures(System.Boolean)",
                    "SharpProof.Attributes.Contract",
                    SpecTargetMemberKind.Method, "Ensures",
                    true, 0, null, [IrTypeKind.Boolean], null,
                    assemblySetSharpProofAttributes),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceContractSemantics),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceContractSemantics),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceContractSemantics),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceContractSemantics),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceContractSemantics),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "contract.old",
                    "M:SharpProof.Attributes.Contract.Old``1(``0)",
                    "SharpProof.Attributes.Contract",
                    SpecTargetMemberKind.Method, "Old",
                    true, 1, null, [IrTypeKind.Reference], IrTypeKind.Reference,
                    assemblySetSharpProofAttributes),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceContractSemantics),
                    new SpecAllocationFacet(SpecAllocationBehavior.MayAllocate, evidenceContractSemantics),
                    new SpecThrowFacet(SpecThrowBehavior.MayThrow, ["System.InvalidOperationException"], evidenceContractSemantics),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceContractSemantics),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceContractSemantics),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "contract.requires",
                    "M:SharpProof.Attributes.Contract.Requires(System.Boolean)",
                    "SharpProof.Attributes.Contract",
                    SpecTargetMemberKind.Method, "Requires",
                    true, 0, null, [IrTypeKind.Boolean], null,
                    assemblySetSharpProofAttributes),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceContractSemantics),
                    new SpecAllocationFacet(SpecAllocationBehavior.None, evidenceContractSemantics),
                    new SpecThrowFacet(SpecThrowBehavior.DoesNotThrow, [], evidenceContractSemantics),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceContractSemantics),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceContractSemantics),
                    null),
                []),
            new ApiSpecDeclaration(
                new ApiSpecTarget(
                    "contract.result",
                    "M:SharpProof.Attributes.Contract.Result``1",
                    "SharpProof.Attributes.Contract",
                    SpecTargetMemberKind.Method, "Result",
                    true, 1, null, [], IrTypeKind.Reference,
                    assemblySetSharpProofAttributes),
                new ApiSpecFacets(
                    new SpecEffectFacet(SpecEffect.None, evidenceContractSemantics),
                    new SpecAllocationFacet(SpecAllocationBehavior.MayAllocate, evidenceContractSemantics),
                    new SpecThrowFacet(SpecThrowBehavior.MayThrow, ["System.InvalidOperationException"], evidenceContractSemantics),
                    new SpecNullnessFacet(SpecNullness.NotApplicable, evidenceContractSemantics),
                    new SpecCardinalityFacet(SpecCardinality.NotApplicable, null, evidenceContractSemantics),
                    null),
                []),
        ];
    }
}
