<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RelationalSpecPackCatalog.json"
                      LogicalName="SharpProof.Specs.RelationalSpecPackCatalog.json" />
  </ItemGroup>
</Project>
