<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Polyfills\NotNullAttribute.cs" />
    <InternalsVisibleTo Include="SharpProof.CompilerCollector" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
  </ItemGroup>
</Project>
