<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Polyfills\NotNullAttribute.cs" />
    <InternalsVisibleTo Include="SharpProof.CompilerCollector" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
    <InternalsVisibleTo Include="SharpProof.Worker.Launcher" />
  </ItemGroup>
</Project>
