<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\SharpProof.Testing.props" />

  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.NUnit" Version="1.1.2" />
    <PackageReference Include="System.CodeDom" Version="10.0.9" PrivateAssets="all" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" PrivateAssets="all" />
    <PackageReference Include="System.IO.Hashing" Version="8.0.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpProof.ProofCore\SharpProof.ProofCore.csproj" />
    <ProjectReference Include="..\Tools\SharpProof.EffectSummary\SharpProof.EffectSummary.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <Target Name="CopyEffectSummaryTestDependency" AfterTargets="Build">
    <Copy SourceFiles="..\Tools\SharpProof.EffectSummary\bin\$(Configuration)\net8.0\SharpProof.EffectSummary.dll"
          DestinationFolder="$(OutDir)" />
  </Target>

  <ItemGroup>
    <Compile Remove="EffectSummaryToolTests.cs" />
    <Compile Remove="EffectSummaryToolTests.Helpers.cs" />
    <Compile Remove="ExceptionSummaryCatalogValidationTests.cs" />
    <Compile Remove="ExceptionSummaryCatalogValidationTests.Helpers.cs" />
    <Compile Remove="AnalyzerPackagingTests.cs" />
    <Compile Remove="ImpactedTestSelectionJsonSession.cs" />
    <Compile Remove="ImpactedTestSelectionScriptTests.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicCompactDomainResults.cs" Link="Imported\SymbolicCli\SymbolicCompactDomainResults.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicCompactInvariantResults.cs" Link="Imported\SymbolicCli\SymbolicCompactInvariantResults.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicInvariantProjection.cs" Link="Imported\SymbolicCli\SymbolicInvariantProjection.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicCompactProgramPointResults.cs" Link="Imported\SymbolicCli\SymbolicCompactProgramPointResults.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicCompactQueryModels.cs" Link="Imported\SymbolicCli\SymbolicCompactQueryModels.cs" />
    <Compile Include="..\Tools\SharpProof.SymbolicCli\SymbolicCliJsonProjectionExtensions.cs" Link="Imported\SymbolicCli\SymbolicCliJsonProjectionExtensions.cs" />
  </ItemGroup>

</Project>
