<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SharpProof.Testing.props" />
  <PropertyGroup>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.ProofCore\SharpProof.ProofCore.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
