using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using NUnit.Framework;
using SharpProof.Attributes;

namespace SharpProof.Analyzer.Test;

[TestFixture]
public sealed class ContractRuntimePolicyTests
{
    private const string SelectedSource =
        """
        using SharpProof.Attributes;

        internal static class Subject {
            private static int state;

            [EnforcePure]
            internal static void Write() {
                state = 1;
            }
        }
        """;

    [Test]
    public async Task ParseOptionSymbolDisablesAnalysisWithVisibleConfigurationDiagnostic()
    {
        var compilation = CreateCompilation(SelectedSource);
        var tree = compilation.SyntaxTrees.Single();
        var enabled = tree.WithRootAndOptions(
            await tree.GetRootAsync(),
            ((CSharpParseOptions)tree.Options).WithPreprocessorSymbols(
                Contract.ConditionalSymbol));

        var diagnostics = await Analyze(
            compilation.ReplaceSyntaxTree(tree, enabled));

        AssertRuntimeEvaluationRejected(diagnostics);
    }

    [Test]
    public async Task SourceAndGeneratedDefinitionsDisableAnalysis()
    {
        var baseCompilation = CreateCompilation(SelectedSource);
        var sourceDefined = CreateCompilation(
            "#define SHARPPROOF_CONTRACTS\n" + SelectedSource);
        var generatedDefinition = CSharpSyntaxTree.ParseText(
            """
            #define SHARPPROOF_CONTRACTS
            // <auto-generated />
            internal static class Generated { }
            """,
            (CSharpParseOptions)baseCompilation
                .SyntaxTrees.Single().Options,
            "Generated.RuntimeContracts.g.cs");
        var generatedDefined = baseCompilation.AddSyntaxTrees(generatedDefinition);

        var sourceDiagnostics = await Analyze(sourceDefined);
        var generatedDiagnostics = await Analyze(generatedDefined);

        AssertRuntimeEvaluationRejected(sourceDiagnostics);
        AssertRuntimeEvaluationRejected(generatedDiagnostics);
    }

    [Test]
    public async Task ActiveUndefRestoresNormalAnalysis()
    {
        var compilation = CreateCompilation(
            """
            #define SHARPPROOF_CONTRACTS
            #undef SHARPPROOF_CONTRACTS
            """ + "\n" +
            SelectedSource);

        var diagnostics = await Analyze(compilation);

        AnalyzerTestHost.AssertIds(diagnostics, "SP0002");
    }

    private static CSharpCompilation CreateCompilation(string source)
    {
        return AnalyzerTestHost.CreateCompilation(
            source,
            ["SP0002", "SP0025"]);
    }

    private static Task<ImmutableArray<Diagnostic>> Analyze(
        CSharpCompilation compilation)
    {
        return AnalyzerTestHost.AnalyzeAsync(
            compilation,
            mode: null,
            features: "effects");
    }

    private static void AssertRuntimeEvaluationRejected(
        ImmutableArray<Diagnostic> diagnostics)
    {
        using (Assert.EnterMultipleScope())
        {
            AnalyzerTestHost.AssertIds(diagnostics, "SP0025");
            Assert.That(
                diagnostics.Single().GetMessage(
                    System.Globalization.CultureInfo.InvariantCulture),
                Does.Contain(Contract.ConditionalSymbol)
                    .And.Contain("runtime evaluation"));
        }
    }
}
