using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using NUnit.Framework;
using SharpProof.CompilerArtifact;
using SharpProof.Worker.Protocol;

namespace SharpProof.Analyzer.Test;

[TestFixture]
public sealed class FinalCompilationCollectorTests
{
    private const string OutputKey =
        "build_property._SharpProofCompilerManifestPath";
    private const string TargetFrameworkKey =
        "build_property._SharpProofCompilationTargetFramework",
        ProjectDirectoryKey = "build_property._SharpProofProjectDirectory";
    private const string MaximumExpressionDepthKey =
        "build_property.SharpProofVerifyMaximumExpressionDepth";

    [Test]
    public async Task CollectorIsInactiveWithoutAPathAndForTheOffProfile()
    {
        using var workspace = new CollectorWorkspace();
        var compilation = CreateCompilation();

        var withoutPath = await AnalyzerTestHost.AnalyzeAsync(
            compilation,
            Options(path: null));
        var off = await AnalyzerTestHost.AnalyzeAsync(
            compilation,
            Options(workspace.SealPath("off"), profile: "off"));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(withoutPath, Is.Empty);
            Assert.That(off, Is.Empty);
            Assert.That(Directory.EnumerateFiles(workspace.Path), Is.Empty);
        }
    }

    [Test]
    public async Task FinalCompilationSealIsCanonicalAndIncludesGeneratedInputs()
    {
        using var workspace = new CollectorWorkspace();
        var compilation = CreateCompilation();
        var generated = CSharpSyntaxTree.ParseText(
            """
            // <auto-generated />
            using SharpProof.Attributes;
            internal static class Generated {
                internal static int Identity(int value) {
                    Contract.Ensures(Contract.Result<int>() == value);
                    Contract.Assume(value >= 0);
                    return value;
                }
            }

            """,
            ((CSharpParseOptions)compilation.SyntaxTrees.Single().Options)
                .WithPreprocessorSymbols("GENERATED"),
            "Generated.Contract.g.cs");
        compilation = compilation.AddSyntaxTrees(generated);
        var additional = ImmutableArray.Create<AdditionalText>(
            new MemoryAdditionalText("proof.inputs", "value=1"));
        var path = workspace.SealPath("canonical");

        var firstDiagnostics = await AnalyzerTestHost.AnalyzeAsync(
            compilation,
            Options(path),
            additional);
        var first = await File.ReadAllBytesAsync(path);
        var secondDiagnostics = await AnalyzerTestHost.AnalyzeAsync(
            compilation,
            Options(path),
            additional);
        var second = await File.ReadAllBytesAsync(path);
        var artifact = CompilerManifestArtifactJson.Deserialize(
            Encoding.UTF8.GetString(first));

        using (Assert.EnterMultipleScope())
        {
            Assert.That(firstDiagnostics, Is.Empty);
            Assert.That(secondDiagnostics, Is.Empty);
            Assert.That(second, Is.EqualTo(first));
            Assert.That(first.Take(3), Is.Not.EqualTo(new byte[] { 0xEF, 0xBB, 0xBF }));
            Assert.That(first, Does.Not.Contain((byte)'\r'));
            Assert.That(artifact.Schema, Is.EqualTo("SharpProof.CompilerManifest"));
            Assert.That(artifact.SchemaVersion, Is.EqualTo(6));
            Assert.That(artifact.ProtocolVersion, Is.EqualTo("8"));
            Assert.That(artifact.Compilation.TargetFramework, Is.EqualTo("net9.0"));
            Assert.That(artifact.Features, Is.EqualTo(WorkerFeatureSet.All));
            Assert.That(
                artifact.MaximumExpressionDepth,
                Is.EqualTo(64));
            Assert.That(artifact.CompilerDiagnostics, Is.Empty);
            Assert.That(artifact.Callables, Has.Length.EqualTo(1));
            Assert.That(artifact.CompilationSha256, Has.Length.EqualTo(64));
            Assert.That(artifact.Manifest.Claims, Has.Length.EqualTo(1));
            Assert.That(
                artifact.Manifest.Callables.Single().Assumptions,
                Has.Length.EqualTo(1));
        }
    }

    [Test]
    public async Task SemanticCompilerInputsInvalidateTheSeal()
    {
        using var workspace = new CollectorWorkspace();
        var baseline = CreateCompilation();
        var baselineHash = await EmitHash(
            baseline,
            workspace.SealPath("baseline"),
            additional: "value=1");
        var sourceHash = await EmitHash(
            CreateCompilation("internal static class Fixture { const int Value = 2; }"),
            workspace.SealPath("source"),
            additional: "value=1");
        var tree = baseline.SyntaxTrees.Single();
        var parseTree = tree.WithRootAndOptions(
            await tree.GetRootAsync(),
            ((CSharpParseOptions)tree.Options).WithPreprocessorSymbols("CHANGED"));
        var parseHash = await EmitHash(
            baseline.ReplaceSyntaxTree(tree, parseTree),
            workspace.SealPath("parse"),
            additional: "value=1");
        var reference = baseline.References
            .OfType<PortableExecutableReference>()
            .First();
        var aliasHash = await EmitHash(
            baseline.ReplaceReference(
                reference,
                reference.WithAliases(["ChangedAlias"])),
            workspace.SealPath("alias"),
            additional: "value=1");
        var additionalHash = await EmitHash(
            baseline,
            workspace.SealPath("additional"),
            additional: "value=2");
        var policyHash = await EmitHash(
            baseline,
            workspace.SealPath("policy"),
            additional: "value=1",
            verifyPolicy: "require-proven");
        var assumptionHash = await EmitHash(
            baseline,
            workspace.SealPath("assumption"),
            additional: "value=1",
            assumptionPolicy: "warn");
        var featuresHash = await EmitHash(
            baseline,
            workspace.SealPath("features"),
            additional: "value=1",
            features: "effects");

        using (Assert.EnterMultipleScope())
        {
            Assert.That(
                new[] {
                    baselineHash, sourceHash, parseHash, aliasHash,
                    additionalHash
                }
                    .Distinct(StringComparer.Ordinal).Count(),
                Is.EqualTo(5));
            Assert.That(
                new[] {
                    policyHash, assumptionHash, featuresHash
                },
                Is.All.EqualTo(baselineHash));
        }
    }

    [Test]
    public async Task EmissionFailureIsTypedAndDoesNotEscapeAsAd0001()
    {
        using var workspace = new CollectorWorkspace();

        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            CreateCompilation(),
            Options(workspace.Path));

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0049"]));
        Assert.That(
            diagnostics[0].DefaultSeverity,
            Is.EqualTo(DiagnosticSeverity.Error));
    }

    [TestCase("0")]
    [TestCase("257")]
    [TestCase("not-a-number")]
    public async Task InvalidExpressionDepthFailsArtifactEmission(string value)
    {
        using var workspace = new CollectorWorkspace();

        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            CreateCompilation(),
            Options(
                workspace.SealPath("invalid-depth"),
                maximumExpressionDepth: value));

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0049"]));
    }

    [Test]
    public async Task NonFileReferenceFailsWithTypedInfrastructureDiagnostic()
    {
        using var workspace = new CollectorWorkspace();
        var compilation = CreateCompilation();
        var reference = compilation.References
            .OfType<PortableExecutableReference>()
            .First();
        var image = await File.ReadAllBytesAsync(reference.FilePath!);
        var inMemory = MetadataReference.CreateFromImage(image);

        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            compilation.ReplaceReference(reference, inMemory),
            Options(workspace.SealPath("in-memory")));

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0049"]));
    }

    private static async Task<string> EmitHash(
        CSharpCompilation compilation,
        string path,
        string additional,
        string verifyPolicy = "advisory",
        string assumptionPolicy = "allow",
        string features = "all")
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            compilation,
            Options(
                path,
                features: features,
                verifyPolicy: verifyPolicy,
                assumptionPolicy: assumptionPolicy),
            [new MemoryAdditionalText("proof.inputs", additional)]);
        Assert.That(diagnostics, Is.Empty);
        var artifact = CompilerManifestArtifactJson.Deserialize(
            await File.ReadAllTextAsync(path));
        using (Assert.EnterMultipleScope())
        {
            Assert.That(artifact.Compilation.AdditionalFiles, Has.Length.EqualTo(1));
            Assert.That(
                artifact.Compilation.AdditionalFiles[0].Path,
                Does.EndWith("/proof.inputs"));
            Assert.That(
                artifact.Compilation.AdditionalFiles[0].Sha256,
                Has.Length.EqualTo(64));
        }
        return artifact.CompilationSha256;
    }

    private static CSharpCompilation CreateCompilation(
        string source = "internal static class Fixture { const int Value = 1; }")
    {
        return AnalyzerTestHost.CreateCompilation(source, []);
    }

    private static Dictionary<string, string> Options(
        string? path,
        string profile = "advisory",
        string features = "all",
        string verifyPolicy = "advisory",
        string assumptionPolicy = "allow",
        string maximumExpressionDepth = "64")
    {
        var values = new Dictionary<string, string>(
            StringComparer.OrdinalIgnoreCase)
        {
            [TargetFrameworkKey] = "net9.0",
            [ProjectDirectoryKey] = Environment.CurrentDirectory,
            [MaximumExpressionDepthKey] = maximumExpressionDepth,
            ["build_property.SharpProofProfile"] = profile,
            ["build_property.SharpProofFeatures"] = features,
            ["build_property.SharpProofVerifyPolicy"] = verifyPolicy,
            ["build_property.SharpProofAssumptionPolicy"] = assumptionPolicy
        };
        if (path != null)
        {
            values[OutputKey] = path;
        }

        return values;
    }

    private sealed class MemoryAdditionalText(
        string path,
        string content) : AdditionalText
    {
        public override string Path { get; } = path;
        public override SourceText GetText(
            CancellationToken cancellationToken = default)
        {
            return SourceText.From(content, Encoding.UTF8);
        }
    }

    private sealed class CollectorWorkspace : IDisposable
    {
        internal CollectorWorkspace()
        {
            Path = System.IO.Path.Combine(
                System.IO.Path.GetTempPath(),
                "SharpProof.FinalCompilationCollector",
                Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path);
        }

        internal string Path
        {
            get;
        }
        internal string SealPath(string name)
        {
            return System.IO.Path.Combine(Path, name + ".seal");
        }

        public void Dispose()
        {
            var resolved = System.IO.Path.GetFullPath(Path);
            var root = System.IO.Path.GetFullPath(System.IO.Path.Combine(
                System.IO.Path.GetTempPath(),
                "SharpProof.FinalCompilationCollector"));
            if (!resolved.StartsWith(
                    root + System.IO.Path.DirectorySeparatorChar,
                    StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    "Collector workspace escaped its temporary root.");
            }

            Directory.Delete(resolved, recursive: true);
        }
    }
}
