using System.Globalization;
using Microsoft.CodeAnalysis;
using NUnit.Framework;

namespace SharpProof.Analyzer.Test;

[TestFixture]
public sealed class GeneratedCodeAnalyzerTests
{
    [TestCase("advisory")]
    [TestCase("strict")]
    public async Task SelectedGeneratedMethodIsAnalyzedAndReported(
        string profile)
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            // <auto-generated />
            using SharpProof.Attributes;

            internal static class GeneratedSubject {
                private static int State;

                [EnforcePure]
                internal static void Selected() {
                    State = 1;
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0002"],
            profile: profile,
            features: "effects",
            filePath: "GeneratedSubject.g.cs");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0002"]));
        Assert.That(
            diagnostics.Single().Location.SourceTree?.FilePath,
            Is.EqualTo("GeneratedSubject.g.cs"));
    }

    [Test]
    public async Task SelectedGeneratedExceptionHandlersUseManagedReachability()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            // <auto-generated />
            using System;
            using SharpProof.Attributes;

            internal static class GeneratedSubject {
                private static int State;

                [EnforcePure]
                internal static void EmptyTry() {
                    try { }
                    catch { State = 1; }
                }

                [EnforcePure]
                internal static void ReachableCatch() {
                    try { throw new InvalidOperationException(); }
                    catch (InvalidOperationException) { State = 2; }
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0002"],
            profile: "strict",
            features: "effects",
            filePath: "GeneratedSubject.g.cs");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0002"]));
        Assert.That(
            diagnostics.Single().Location.GetLineSpan().StartLinePosition.Line,
            Is.EqualTo(14));
    }

    [Test]
    public async Task SelectedGeneratedArrayStoresUseExactRuntimeElementType()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            // <auto-generated />
            using SharpProof.Attributes;

            internal static class GeneratedSubject {
                [DoesNotThrow]
                internal static void ExactStore() {
                    object[] values = new object[1];
                    values[0] = "value";
                }

                [DoesNotThrow]
                internal static void CovariantStore() {
                    object[] values = new string[1];
                    values[0] = new object();
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0046"],
            profile: "strict",
            features: "effects",
            filePath: "GeneratedSubject.g.cs");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0046"]));
        Assert.That(
            diagnostics.Single().GetMessage(CultureInfo.InvariantCulture),
            Does.Contain("'CovariantStore'"));
    }

    [TestCase("advisory")]
    [TestCase("strict")]
    public async Task UnselectedGeneratedCallerRemainsQuiet(
        string profile)
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            // <auto-generated />
            using SharpProof.Attributes;

            internal static class GeneratedSubject {
                internal static void RequirePositive(int value) {
                    Contract.Requires(value > 0);
                }

                internal static void UnselectedCaller() {
                    RequirePositive(-1);
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0027"],
            profile: profile,
            features: "contracts",
            filePath: "GeneratedSubject.g.cs");

        Assert.That(diagnostics, Is.Empty);
    }

    [Test]
    public async Task AutoGeneratedTextInsideStringDoesNotSuppressAnalysis()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            using SharpProof.Attributes;

            internal static class Subject {
                private static int Positive(int value) {
                    Contract.Requires(value > 0);
                    return value;
                }

                internal static int Call() {
                    const string text = "<auto-generated";
                    _ = text;
                    return Positive(-1);
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0027"],
            profile: "advisory",
            features: "contracts",
            filePath: "Subject.cs");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0027"]));
    }

    [Test]
    public async Task GeneratedAssociatedPropertyAndEventAccessorsRemainQuiet()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            using System;
            using System.CodeDom.Compiler;
            using SharpProof.Attributes;

            internal static class Subject {
                private static int Positive(int value) {
                    Contract.Requires(value > 0);
                    return value;
                }

                [GeneratedCode("test", "1")]
                internal static int Value {
                    get { return Positive(-1); }
                }

                [GeneratedCode("test", "1")]
                internal static event Action Changed {
                    add { _ = Positive(-2); }
                    remove { _ = Positive(-3); }
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0027"],
            profile: "advisory",
            features: "contracts",
            filePath: "Subject.cs");

        Assert.That(diagnostics, Is.Empty);
    }

    [Test]
    public async Task AliasedEscapedContractApiNamesActivateAdvisoryAnalysis()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            using Proof = SharpProof.Attributes.Contract;

            internal static class Subject {
                internal static int RequirePositive(int value) {
                    Proof.@Requires(value > 0);
                    Proof.@Ensures(
                        Proof.@Result<int>() == Proof.@Old(value));
                    Proof.@Assume(value != int.MinValue);
                    return value;
                }

                internal static void Call() {
                    RequirePositive(-1);
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0027"],
            profile: "advisory",
            features: "contracts");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0027"]));
    }

    [Test]
    public async Task ContractCandidateActivationRunsClausePlacementValidation()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            using Proof = SharpProof.Attributes.Contract;

            internal static class Subject {
                internal static void Late(bool condition) {
                    _ = condition;
                    Proof.@Ensures(condition);
                }
            }
            """,
            mode: null,
            enabledIds: ["SP0024"],
            profile: "advisory",
            features: "contracts");

        Assert.That(
            diagnostics.Select(static diagnostic => diagnostic.Id),
            Is.EqualTo(["SP0024"]));
    }
}
