<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\eng\container\toolchain.json"
                      LogicalName="SharpProof.Host.toolchain.json" />
    <ProjectReference Include="..\SharpProof.Meta.Analyzers\SharpProof.Meta.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Package.Test" />
    <InternalsVisibleTo Include="SharpProof.BuildTasks" />
    <InternalsVisibleTo Include="SharpProof.Worker.Launcher" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
    <InternalsVisibleTo Include="SharpProof.Worker.Test" />
  </ItemGroup>
</Project>
