<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\eng\container\toolchain.json"
                      LogicalName="SharpProof.Host.toolchain.json" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Package.Test" />
    <InternalsVisibleTo Include="SharpProof.BuildTasks" />
    <InternalsVisibleTo Include="SharpProof.Worker.Launcher" />
    <InternalsVisibleTo Include="SharpProof.Worker.Test" />
  </ItemGroup>
</Project>
