using System.Diagnostics;
using System.Text;
using System.Text.Json;
using NUnit.Framework;
using SharpProof.Ir;

namespace SharpProof.Specs.Test;

[TestFixture]
public sealed class DefaultApiSpecCatalogGenerationTests
{
    private const string ExpectedContentSha256 =
        "c0f4a6b09d7efdb66ac11457ae4d80345c9a977286118058ae67750961a3342e";

    [Test]
    public void GeneratedCatalogPreservesEveryReviewedWitness()
    {
        using var document = JsonDocument.Parse(
            File.ReadAllText(CatalogPath()));
        var root = document.RootElement;
        Assert.That(
            root.GetProperty("schema").GetString(),
            Is.EqualTo("SharpProof.ApiSpecCatalog"));
        Assert.That(
            root.GetProperty("schemaVersion").GetInt32(),
            Is.EqualTo(1));
        Assert.That(
            ApiSpecTable.DefaultTableIdentity,
            Is.EqualTo(root.GetProperty("tableIdentity").GetString()));
        Assert.That(
            ApiSpecTable.DefaultTableVersion,
            Is.EqualTo(root.GetProperty("tableVersion").GetString()));

        var assemblies = ReadAssemblySets(root);
        var evidence = ReadEvidence(root);
        var reviewed = root.GetProperty("declarations")
            .EnumerateArray()
            .OrderBy(static declaration =>
                declaration.GetProperty("target")
                    .GetProperty("witnessIdentifier").GetString(),
                StringComparer.Ordinal)
            .ToArray();
        var templates = ApiSpecTable.Default.Templates;
        Assert.That(
            templates.Select(static template =>
                template.Target.WitnessIdentifier),
            Is.EqualTo(reviewed.Select(static declaration =>
                declaration.GetProperty("target")
                    .GetProperty("witnessIdentifier").GetString())));

        for (var index = 0; index < reviewed.Length; index++)
        {
            AssertDeclaration(
                reviewed[index],
                templates[index],
                assemblies,
                evidence);
        }
        Assert.That(
            ApiSpecTable.Default.ContentSha256,
            Is.EqualTo(ExpectedContentSha256));
    }

    [Test]
    public async Task CheckedInGeneratedOutputsAreCurrent()
    {
        var result = await RunGeneratorAsync("-Verify");

        Assert.That(result.ExitCode, Is.Zero, result.Output);
        Assert.That(
            result.Output,
            Does.Contain(
                "Verified deterministic API-spec catalog source and documentation."));
    }

    [Test]
    public async Task GeneratorIsDeterministicLfAndBomFree()
    {
        using var workspace = GenerationWorkspace.Create();
        var first = await RunGeneratorAsync(
            "-SourceOutputPath",
            workspace.FirstSourcePath,
            "-DocumentationOutputPath",
            workspace.FirstDocumentationPath,
            "-RuntimeWitnessOutputPath",
            workspace.FirstRuntimeWitnessPath);
        var second = await RunGeneratorAsync(
            "-SourceOutputPath",
            workspace.SecondSourcePath,
            "-DocumentationOutputPath",
            workspace.SecondDocumentationPath,
            "-RuntimeWitnessOutputPath",
            workspace.SecondRuntimeWitnessPath);

        Assert.That(first.ExitCode, Is.Zero, first.Output);
        Assert.That(second.ExitCode, Is.Zero, second.Output);
        var firstSource =
            await File.ReadAllBytesAsync(workspace.FirstSourcePath);
        var secondSource =
            await File.ReadAllBytesAsync(workspace.SecondSourcePath);
        var firstDocumentation =
            await File.ReadAllBytesAsync(
                workspace.FirstDocumentationPath);
        var secondDocumentation =
            await File.ReadAllBytesAsync(
                workspace.SecondDocumentationPath);
        var firstRuntimeWitness =
            await File.ReadAllBytesAsync(
                workspace.FirstRuntimeWitnessPath);
        var secondRuntimeWitness =
            await File.ReadAllBytesAsync(
                workspace.SecondRuntimeWitnessPath);
        Assert.That(secondSource, Is.EqualTo(firstSource));
        Assert.That(
            secondDocumentation,
            Is.EqualTo(firstDocumentation));
        Assert.That(
            secondRuntimeWitness,
            Is.EqualTo(firstRuntimeWitness));
        AssertGeneratedEncoding(
            firstSource,
            "// <auto-generated>");
        AssertGeneratedEncoding(
            firstDocumentation,
            "<!-- <auto-generated> -->");
        AssertGeneratedEncoding(
            firstRuntimeWitness,
            "// <auto-generated>");
    }

    [Test]
    public async Task VerificationRejectsStaleGeneratedOutput()
    {
        using var workspace = GenerationWorkspace.Create();
        var generated = await RunGeneratorAsync(
            "-SourceOutputPath",
            workspace.FirstSourcePath,
            "-DocumentationOutputPath",
            workspace.FirstDocumentationPath,
            "-RuntimeWitnessOutputPath",
            workspace.FirstRuntimeWitnessPath);
        Assert.That(generated.ExitCode, Is.Zero, generated.Output);
        await File.AppendAllTextAsync(
            workspace.FirstSourcePath,
            "// stale\n",
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var verification = await RunGeneratorAsync(
            "-SourceOutputPath",
            workspace.FirstSourcePath,
            "-DocumentationOutputPath",
            workspace.FirstDocumentationPath,
            "-RuntimeWitnessOutputPath",
            workspace.FirstRuntimeWitnessPath,
            "-Verify");

        Assert.That(verification.ExitCode, Is.Not.Zero);
        Assert.That(
            verification.Output,
            Does.Contain("is stale")
                .And.Contain("Generate-ApiSpecCatalog.ps1"));
    }

    [TestCase(
        "\"schemaVersion\": 1",
        "\"schemaVersion\": \"1\"")]
    [TestCase(
        "\"isStatic\": false",
        "\"isStatic\": \"false\"")]
    [TestCase(
        "\"genericArity\": 1",
        "\"genericArity\": \"1\"")]
    [TestCase(
        "\"ordinal\": -1",
        "\"ordinal\": \"-1\"")]
    [TestCase(
        "\"value\": 0",
        "\"value\": \"0\"")]
    public async Task GeneratorRejectsCoercibleScalarStrings(
        string original,
        string replacement)
    {
        using var workspace = GenerationWorkspace.Create();
        var catalog = await File.ReadAllTextAsync(CatalogPath());
        Assert.That(catalog, Does.Contain(original));
        await File.WriteAllTextAsync(
            workspace.CatalogInputPath,
            catalog.Replace(
                original,
                replacement,
                StringComparison.Ordinal),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var result = await RunGeneratorAsync(
            "-CatalogPath",
            workspace.CatalogInputPath,
            "-SourceOutputPath",
            workspace.FirstSourcePath,
            "-DocumentationOutputPath",
            workspace.FirstDocumentationPath,
            "-RuntimeWitnessOutputPath",
            workspace.FirstRuntimeWitnessPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
    }

    [Test]
    public async Task GeneratorRejectsDuplicateJsonProperties()
    {
        using var workspace = GenerationWorkspace.Create();
        var catalog = await File.ReadAllTextAsync(CatalogPath());
        var variants = new[]
        {
            catalog.Replace(
                "  \"tableVersion\": \"5\",",
                "  \"tableVersion\": \"5\",\n  \"tableVersion\": \"shadow\",",
                StringComparison.Ordinal),
            catalog.Replace(
                "        \"nullness\": {\n          \"result\": \"NonNull\",",
                "        \"nullness\": {\n          \"result\": \"NonNull\",\n          \"result\": \"Null\",",
                StringComparison.Ordinal)
        };

        foreach (var variant in variants)
        {
            await File.WriteAllTextAsync(
                workspace.CatalogInputPath,
                variant,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            var result = await RunGeneratorAsync(
                "-CatalogPath",
                workspace.CatalogInputPath,
                "-SourceOutputPath",
                workspace.FirstSourcePath,
                "-DocumentationOutputPath",
                workspace.FirstDocumentationPath,
                "-RuntimeWitnessOutputPath",
                workspace.FirstRuntimeWitnessPath);

            Assert.That(result.ExitCode, Is.Not.Zero, result.Output);

            var runtimeResult = await RunRuntimeWitnessGeneratorAsync(
                "-CatalogPath",
                workspace.CatalogInputPath,
                "-OutputPath",
                workspace.FirstRuntimeWitnessPath);
            Assert.That(runtimeResult.ExitCode, Is.Not.Zero, runtimeResult.Output);
        }
    }

    private static void AssertDeclaration(
        JsonElement declaration,
        ApiSpecTemplate template,
        Dictionary<string, ApiSpecAssemblyIdentity[]> assemblies,
        Dictionary<string, SpecEvidence> evidence)
    {
        var expected = declaration.GetProperty("target");
        var actual = template.Target;
        var witness = actual.WitnessIdentifier;
        Assert.Multiple(() =>
        {
            Assert.That(
                actual.WitnessIdentifier,
                Is.EqualTo(
                    expected.GetProperty("witnessIdentifier").GetString()),
                witness);
            Assert.That(
                actual.DocumentationCommentId,
                Is.EqualTo(
                    expected.GetProperty("documentationCommentId").GetString()),
                witness);
            Assert.That(
                actual.ContainingTypeMetadataName,
                Is.EqualTo(
                    expected.GetProperty(
                        "containingTypeMetadataName").GetString()),
                witness);
            Assert.That(
                actual.MemberKind,
                Is.EqualTo(
                    EnumValue<SpecTargetMemberKind>(
                        expected.GetProperty("memberKind"))),
                witness);
            Assert.That(
                actual.MemberName,
                Is.EqualTo(
                    expected.GetProperty("memberName").GetString()),
                witness);
            Assert.That(
                actual.IsStatic,
                Is.EqualTo(expected.GetProperty("isStatic").GetBoolean()),
                witness);
            Assert.That(
                actual.GenericArity,
                Is.EqualTo(
                    expected.GetProperty("genericArity").GetInt32()),
                witness);
            Assert.That(
                actual.ReceiverType,
                Is.EqualTo(
                    NullableEnumValue<IrTypeKind>(
                        expected.GetProperty("receiverType"))),
                witness);
            Assert.That(
                actual.ParameterTypes,
                Is.EqualTo(expected.GetProperty("parameterTypes")
                    .EnumerateArray()
                    .Select(EnumValue<IrTypeKind>)
                    .ToArray()),
                witness);
            Assert.That(
                actual.ResultType,
                Is.EqualTo(
                    NullableEnumValue<IrTypeKind>(
                        expected.GetProperty("resultType"))),
                witness);
            var assemblySet = expected
                .GetProperty("approvedAssemblySet").GetString() ??
                throw new InvalidDataException(
                    "An approved assembly set is null.");
            Assert.That(
                actual.ApprovedAssemblies,
                Is.EqualTo(assemblies[assemblySet]),
                witness);
        });

        AssertFacets(
            declaration.GetProperty("facets"),
            template.Facets,
            evidence,
            witness);
        var postconditions = declaration.GetProperty("postconditions")
            .EnumerateArray()
            .ToArray();
        Assert.That(
            template.Postconditions,
            Has.Length.EqualTo(postconditions.Length),
            witness);
        for (var index = 0;
             index < postconditions.Length;
             index++)
        {
            var expectedPostcondition = postconditions[index];
            var actualPostcondition = template.Postconditions[index];
            Assert.That(
                Describe(actualPostcondition.Condition),
                Is.EqualTo(
                    Describe(
                        expectedPostcondition.GetProperty("condition"))),
                witness + " postcondition " + index);
            Assert.That(
                actualPostcondition.Evidence,
                Is.EqualTo(
                    Evidence(
                        expectedPostcondition.GetProperty("evidence"),
                        evidence)),
                witness + " postcondition " + index);
        }
    }

    private static void AssertFacets(
        JsonElement expected,
        ApiSpecFacets actual,
        Dictionary<string, SpecEvidence> evidence,
        string witness)
    {
        var effects = expected.GetProperty("effects");
        var expectedEffects = effects.GetProperty("values")
            .EnumerateArray()
            .Aggregate(
                SpecEffect.None,
                static (value, element) =>
                    value | EnumValue<SpecEffect>(element));
        var allocation = expected.GetProperty("allocation");
        var throws = expected.GetProperty("throws");
        var nullness = expected.GetProperty("nullness");
        var cardinality = expected.GetProperty("cardinality");
        var exactCount = cardinality.GetProperty("exactCount");
        Assert.Multiple(() =>
        {
            Assert.That(
                actual.Effects.Effects,
                Is.EqualTo(expectedEffects),
                witness);
            Assert.That(
                actual.Effects.Evidence,
                Is.EqualTo(
                    Evidence(effects.GetProperty("evidence"), evidence)),
                witness);
            Assert.That(
                actual.Allocation.Behavior,
                Is.EqualTo(
                    EnumValue<SpecAllocationBehavior>(
                        allocation.GetProperty("behavior"))),
                witness);
            Assert.That(
                actual.Allocation.Evidence,
                Is.EqualTo(
                    Evidence(
                        allocation.GetProperty("evidence"),
                        evidence)),
                witness);
            Assert.That(
                actual.Throws.Behavior,
                Is.EqualTo(
                    EnumValue<SpecThrowBehavior>(
                        throws.GetProperty("behavior"))),
                witness);
            Assert.That(
                actual.Throws.ExceptionMetadataNames,
                Is.EqualTo(
                    throws.GetProperty("exceptionMetadataNames")
                        .EnumerateArray()
                        .Select(static item => item.GetString())
                        .ToArray()),
                witness);
            Assert.That(
                actual.Throws.Evidence,
                Is.EqualTo(
                    Evidence(throws.GetProperty("evidence"), evidence)),
                witness);
            Assert.That(
                actual.Nullness.Result,
                Is.EqualTo(
                    EnumValue<SpecNullness>(
                        nullness.GetProperty("result"))),
                witness);
            Assert.That(
                actual.Nullness.Evidence,
                Is.EqualTo(
                    Evidence(
                        nullness.GetProperty("evidence"),
                        evidence)),
                witness);
            Assert.That(
                actual.Cardinality.Result,
                Is.EqualTo(
                    EnumValue<SpecCardinality>(
                        cardinality.GetProperty("result"))),
                witness);
            Assert.That(
                actual.Cardinality.ExactCount,
                Is.EqualTo(
                    exactCount.ValueKind == JsonValueKind.Null
                        ? null
                        : exactCount.GetInt32()),
                witness);
            Assert.That(
                actual.Cardinality.Evidence,
                Is.EqualTo(
                    Evidence(
                        cardinality.GetProperty("evidence"),
                        evidence)),
                witness);
        });

        if (expected.TryGetProperty("termination", out var termination))
        {
            Assert.That(actual.Termination, Is.Not.Null, witness);
            Assert.Multiple(() =>
            {
                Assert.That(
                    actual.Termination!.Behavior,
                    Is.EqualTo(
                        EnumValue<SpecTerminationBehavior>(
                            termination.GetProperty("behavior"))),
                    witness);
                Assert.That(
                    actual.Termination.Evidence,
                    Is.EqualTo(
                        Evidence(
                            termination.GetProperty("evidence"),
                            evidence)),
                    witness);
            });
        }
        else
        {
            Assert.That(actual.Termination, Is.Null, witness);
        }
    }

    private static Dictionary<string, ApiSpecAssemblyIdentity[]>
        ReadAssemblySets(JsonElement root)
    {
        var result =
            new Dictionary<string, ApiSpecAssemblyIdentity[]>(
                StringComparer.Ordinal);
        foreach (var set in root.GetProperty("assemblySets")
                     .EnumerateArray())
        {
            var id = set.GetProperty("id").GetString() ??
                throw new InvalidDataException(
                    "An assembly set id is null.");
            var identities = set.GetProperty("identities").EnumerateArray()
                .SelectMany(static identity =>
                    identity.GetProperty("referenceFamilies").EnumerateArray()
                        .Select(family => new ApiSpecAssemblyIdentity(
                            identity.GetProperty("name").GetString() ??
                            throw new InvalidDataException("An assembly name is null."),
                            identity.GetProperty("publicKeyToken").GetString() ??
                            throw new InvalidDataException("A public-key token is null."),
                            Enum.Parse<ApiSpecReferenceFamily>(
                                family.GetString() ??
                                throw new InvalidDataException(
                                    "A reference family is null.")))))
                .ToArray();
            result.Add(id, identities);
        }
        return result;
    }

    private static Dictionary<string, SpecEvidence> ReadEvidence(
        JsonElement root)
    {
        return root.GetProperty("evidence")
            .EnumerateArray()
            .ToDictionary(
                static item => item.GetProperty("id").GetString() ??
                    throw new InvalidDataException(
                        "An evidence id is null."),
                static item => new SpecEvidence(
                    EnumValue<SpecEvidenceKind>(
                        item.GetProperty("kind")),
                    item.GetProperty("source").GetString() ??
                    throw new InvalidDataException(
                        "An evidence source is null.")),
                StringComparer.Ordinal);
    }

    private static SpecEvidence Evidence(
        JsonElement reference,
        Dictionary<string, SpecEvidence> evidence)
    {
        var id = reference.GetString() ??
            throw new InvalidDataException(
                "An evidence reference is null.");
        return evidence[id];
    }

    private static string Describe(JsonElement term)
    {
        var kind = term.GetProperty("kind").GetString();
        var type = term.GetProperty("type").GetString();
        return kind switch
        {
            "variable" =>
                "variable:" +
                term.GetProperty("role").GetString() + ":" +
                term.GetProperty("ordinal").GetInt32() + ":" + type,
            "boolean" =>
                "boolean:" +
                term.GetProperty("value").GetBoolean() + ":" + type,
            "integer" =>
                "integer:" +
                term.GetProperty("value").GetInt64() + ":" + type,
            "string" =>
                "string:" +
                JsonSerializer.Serialize(
                    term.GetProperty("value").GetString()) + ":" + type,
            "null" => "null:" + type,
            "unary" =>
                "unary:" +
                term.GetProperty("operator").GetString() + ":" + type +
                "(" + Describe(term.GetProperty("operand")) + ")",
            "binary" =>
                "binary:" +
                term.GetProperty("operator").GetString() + ":" + type +
                "(" + Describe(term.GetProperty("left")) + "," +
                Describe(term.GetProperty("right")) + ")",
            "conditional" =>
                "conditional:" + type +
                "(" + Describe(term.GetProperty("condition")) + "," +
                Describe(term.GetProperty("whenTrue")) + "," +
                Describe(term.GetProperty("whenFalse")) + ")",
            "length" =>
                "length:" + type +
                "(" + Describe(term.GetProperty("value")) + ")",
            _ => throw new InvalidDataException(
                "Unknown catalog term kind: " + kind)
        };
    }

    private static string Describe(SpecTermDeclaration term)
    {
        return term switch
        {
            SpecVariableDeclaration variable =>
                "variable:" + variable.Role + ":" + variable.Ordinal + ":" + variable.Type,
            SpecBooleanDeclaration boolean =>
                "boolean:" + boolean.Value + ":" + boolean.Type,
            SpecIntegerDeclaration integer =>
                "integer:" + integer.Value + ":" + integer.Type,
            SpecStringDeclaration text =>
                "string:" + JsonSerializer.Serialize(text.Value) +
                ":" + text.Type,
            SpecNullDeclaration nullTerm =>
                "null:" + nullTerm.Type,
            SpecUnaryDeclaration unary =>
                "unary:" + unary.Operator + ":" + unary.Type +
                "(" + Describe(unary.Operand) + ")",
            SpecBinaryDeclaration binary =>
                "binary:" + binary.Operator + ":" + binary.Type +
                "(" + Describe(binary.Left) + "," +
                Describe(binary.Right) + ")",
            SpecConditionalDeclaration conditional =>
                "conditional:" + conditional.Type +
                "(" + Describe(conditional.Condition) + "," +
                Describe(conditional.WhenTrue) + "," +
                Describe(conditional.WhenFalse) + ")",
            SpecLengthDeclaration length =>
                "length:" + length.Type +
                "(" + Describe(length.Value) + ")",
            _ => throw new ArgumentOutOfRangeException(nameof(term))
        };
    }

    private static T EnumValue<T>(JsonElement value)
        where T : struct, Enum
    {
        return Enum.Parse<T>(
            value.GetString() ??
            throw new InvalidDataException(
                "An enum value is null."),
            ignoreCase: false);
    }

    private static T? NullableEnumValue<T>(JsonElement value)
        where T : struct, Enum
    {
        return value.ValueKind == JsonValueKind.Null
            ? null
            : EnumValue<T>(value);
    }

    private static void AssertGeneratedEncoding(
        byte[] bytes,
        string expectedHeader)
    {
        Assert.That(bytes, Is.Not.Empty);
        Assert.That(
            bytes.Length >= 3 &&
            bytes[0] == 0xEF &&
            bytes[1] == 0xBB &&
            bytes[2] == 0xBF,
            Is.False);
        var text = Encoding.UTF8.GetString(bytes);
        Assert.That(text, Does.StartWith(expectedHeader));
        Assert.That(text, Does.Not.Contain('\r'));
        Assert.That(text, Does.EndWith("\n"));
    }

    private static async Task<GeneratorResult> RunGeneratorAsync(
        params string[] arguments)
    {
        return await RunScriptAsync(GeneratorPath(), arguments);
    }

    private static async Task<GeneratorResult> RunRuntimeWitnessGeneratorAsync(
        params string[] arguments)
    {
        return await RunScriptAsync(RuntimeGeneratorPath(), arguments);
    }

    private static async Task<GeneratorResult> RunScriptAsync(
        string scriptPath,
        params string[] arguments)
    {
        var startInfo = new ProcessStartInfo
        {
            FileName = "pwsh",
            WorkingDirectory = RepositoryRoot(),
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };
        startInfo.ArgumentList.Add("-NoLogo");
        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-File");
        startInfo.ArgumentList.Add(scriptPath);
        foreach (var argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using var process = Process.Start(startInfo) ??
            throw new InvalidOperationException(
                "Failed to start the API-spec catalog generator.");
        var output = process.StandardOutput.ReadToEndAsync();
        var error = process.StandardError.ReadToEndAsync();
        await process.WaitForExitAsync();
        return new GeneratorResult(
            process.ExitCode,
            (await output) + Environment.NewLine + (await error));
    }

    private static string CatalogPath()
    {
        return Path.Combine(
            RepositoryRoot(),
            "SharpProof.Specs",
            "DefaultApiSpecCatalog.json");
    }

    private static string GeneratorPath()
    {
        return Path.Combine(
            RepositoryRoot(),
            "scripts",
            "Generate-ApiSpecCatalog.ps1");
    }

    private static string RuntimeGeneratorPath()
    {
        return Path.Combine(
            RepositoryRoot(),
            "SharpProof.Specs.Test",
            "Generate-ApiSpecRuntimeWitnesses.ps1");
    }

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(
            TestContext.CurrentContext.TestDirectory);
        while (directory != null)
        {
            if (File.Exists(
                    Path.Combine(
                        directory.FullName,
                        "SharpProof.Release.props")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }
        throw new InvalidOperationException(
            "The repository root was not found.");
    }

    private readonly record struct GeneratorResult(
        int ExitCode,
        string Output);

    private sealed class GenerationWorkspace : IDisposable
    {
        private readonly string _root;

        private GenerationWorkspace(string root)
        {
            _root = root;
            CatalogInputPath = Path.Combine(root, "catalog.json");
            FirstSourcePath = Path.Combine(root, "first.generated.cs");
            FirstDocumentationPath =
                Path.Combine(root, "first.generated.md");
            FirstRuntimeWitnessPath =
                Path.Combine(root, "first.runtime.generated.cs");
            SecondSourcePath =
                Path.Combine(root, "second.generated.cs");
            SecondDocumentationPath =
                Path.Combine(root, "second.generated.md");
            SecondRuntimeWitnessPath =
                Path.Combine(root, "second.runtime.generated.cs");
        }

        internal string FirstSourcePath
        {
            get;
        }
        internal string CatalogInputPath
        {
            get;
        }
        internal string FirstDocumentationPath
        {
            get;
        }
        internal string FirstRuntimeWitnessPath
        {
            get;
        }
        internal string SecondSourcePath
        {
            get;
        }
        internal string SecondDocumentationPath
        {
            get;
        }
        internal string SecondRuntimeWitnessPath
        {
            get;
        }

        internal static GenerationWorkspace Create()
        {
            var root = Path.Combine(
                Path.GetTempPath(),
                "SharpProof.ApiSpecCatalog.Test",
                Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(root);
            return new GenerationWorkspace(root);
        }

        public void Dispose()
        {
            var parent = Path.GetFullPath(
                Path.Combine(
                    Path.GetTempPath(),
                    "SharpProof.ApiSpecCatalog.Test"));
            var resolved = Path.GetFullPath(_root);
            if (!resolved.StartsWith(
                    parent + Path.DirectorySeparatorChar,
                    StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Refusing to remove an unexpected generator directory.");
            }

            if (Directory.Exists(resolved))
            {
                Directory.Delete(resolved, recursive: true);
            }
        }
    }
}
