using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using NUnit.Framework;
using SharpProof.Ir;

namespace SharpProof.Specs.Test;

[TestFixture]
[Parallelizable(ParallelScope.Children)]
public sealed class DefaultApiSpecCatalogGenerationTests
{
    private const string ExpectedContentSha256 =
        "8e177ed0d36d9c78603c634aa1abe6fcc5e765e08d9607f8702277d38c0d1386";

    [Test]
    public void GeneratedCatalogPreservesEveryReviewedWitness()
    {
        using var document = JsonDocument.Parse(
            File.ReadAllText(CatalogPath()));
        var root = document.RootElement;
        Assert.That(
            root.GetProperty("schema").GetString(),
            Is.EqualTo("SharpProof.ApiSpecCatalog"));
        Assert.That(
            root.GetProperty("schemaVersion").GetInt32(),
            Is.EqualTo(2));
        Assert.That(
            ApiSpecTable.DefaultTableIdentity,
            Is.EqualTo(root.GetProperty("tableIdentity").GetString()));
        Assert.That(
            ApiSpecTable.DefaultTableVersion,
            Is.EqualTo(root.GetProperty("tableVersion").GetString()));

        var assemblies = ReadAssemblySets(root);
        var evidence = ReadEvidence(root);
        var profiles = root.GetProperty("profiles")
            .EnumerateArray()
            .ToDictionary(
                static profile => profile.GetProperty("id").GetString()!,
                static profile => profile,
                StringComparer.Ordinal);
        var reviewed = root.GetProperty("declarations")
            .EnumerateArray()
            .OrderBy(static declaration =>
                declaration.GetProperty("target")
                    .GetProperty("witnessIdentifier").GetString(),
                StringComparer.Ordinal)
            .ToArray();
        var templates = ApiSpecTable.Default.Templates;
        Assert.That(
            templates.Select(static template =>
                template.Target.WitnessIdentifier),
            Is.EqualTo(reviewed.Select(static declaration =>
                declaration.GetProperty("target")
                    .GetProperty("witnessIdentifier").GetString())));

        for (var index = 0; index < reviewed.Length; index++)
        {
            AssertDeclaration(
                reviewed[index],
                templates[index],
                assemblies,
                evidence,
                profiles);
        }
        Assert.That(
            ApiSpecTable.Default.ContentSha256,
            Is.EqualTo(ExpectedContentSha256));
    }

    [Test]
    public async Task CheckedInGeneratedOutputsAreCurrent()
    {
        var result = await RunGeneratorAsync("-Verify");

        Assert.That(result.ExitCode, Is.Zero, result.Output);
        Assert.That(
            result.Output,
            Does.Contain(
                "Verified deterministic API-spec catalog source, documentation, " +
                "runtime witnesses, and relational catalog source."));
    }

    [Test]
    public async Task GeneratorIsDeterministicLfAndBomFree()
    {
        using var workspace = GenerationWorkspace.Create();
        var first = await RunGeneratorAsync(workspace);
        var second = await RunGeneratorAsync(workspace, useSecondOutputs: true);

        Assert.That(first.ExitCode, Is.Zero, first.Output);
        Assert.That(second.ExitCode, Is.Zero, second.Output);
        var firstSource =
            await File.ReadAllBytesAsync(workspace.FirstOutputs.SourcePath);
        var secondSource =
            await File.ReadAllBytesAsync(workspace.SecondOutputs.SourcePath);
        var firstDocumentation =
            await File.ReadAllBytesAsync(
                workspace.FirstOutputs.DocumentationPath);
        var secondDocumentation =
            await File.ReadAllBytesAsync(
                workspace.SecondOutputs.DocumentationPath);
        var firstRuntimeWitness =
            await File.ReadAllBytesAsync(
                workspace.FirstOutputs.RuntimeWitnessPath);
        var secondRuntimeWitness =
            await File.ReadAllBytesAsync(
                workspace.SecondOutputs.RuntimeWitnessPath);
        var firstRelational =
            await File.ReadAllBytesAsync(workspace.FirstOutputs.RelationalPath);
        var secondRelational =
            await File.ReadAllBytesAsync(workspace.SecondOutputs.RelationalPath);
        Assert.That(secondSource, Is.EqualTo(firstSource));
        Assert.That(
            secondDocumentation,
            Is.EqualTo(firstDocumentation));
        Assert.That(
            secondRuntimeWitness,
            Is.EqualTo(firstRuntimeWitness));
        Assert.That(secondRelational, Is.EqualTo(firstRelational));
        AssertGeneratedEncoding(
            firstSource,
            "// <auto-generated>");
        AssertGeneratedEncoding(
            firstDocumentation,
            "<!-- <auto-generated> -->");
        AssertGeneratedEncoding(
            firstRuntimeWitness,
            "// <auto-generated>");
        AssertGeneratedEncoding(
            firstRelational,
            "// <auto-generated>");
    }

    [TestCase("\"operator\": \"GreaterThanOrEqual\"", "\"operator\": \"StringConcat\"")]
    [TestCase("\"ordinal\": 0", "\"ordinal\": 2")]
    [TestCase("\"type\": \"Boolean\"", "\"type\": \"String\"")]
    [TestCase("\"publicKeyToken\": \"7cec85d7bea7798e\"", "\"publicKeyToken\": \"INVALID\"")]
    [TestCase("\"documentationCommentId\": \"M:System.Math.Max", "\"documentationCommentId\": \"System.Math.Max")]
    public async Task RelationalGeneratorRejectsMalformedCatalog(
        string original,
        string replacement)
    {
        using var workspace = GenerationWorkspace.Create();
        var catalog = await File.ReadAllTextAsync(RelationalCatalogPath());
        Assert.That(catalog, Does.Contain(original));
        await File.WriteAllTextAsync(
            workspace.RelationalCatalogInputPath,
            catalog.Replace(original, replacement, StringComparison.Ordinal),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var result = await RunGeneratorAsync(
            workspace,
            "-RelationalCatalogPath",
            workspace.RelationalCatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
    }

    [Test]
    public async Task RelationalCatalogOmitsUnusedPerPackEvidence()
    {
        var catalog = await File.ReadAllTextAsync(RelationalCatalogPath());
        using var document = JsonDocument.Parse(catalog);
        Assert.That(
            document.RootElement.GetProperty("schemaVersion").GetInt32(),
            Is.EqualTo(2));
        var pack = document.RootElement.GetProperty("packs")
            .EnumerateArray()
            .Single();
        Assert.That(
            pack.EnumerateObject().Select(static property => property.Name),
            Is.EqualTo(new[] { "id", "version", "methods" }));

        using var workspace = GenerationWorkspace.Create();
        await File.WriteAllTextAsync(
            workspace.RelationalCatalogInputPath,
            catalog,
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        var result = await RunGeneratorAsync(
            workspace,
            "-RelationalCatalogPath",
            workspace.RelationalCatalogInputPath);

        Assert.That(result.ExitCode, Is.Zero, result.Output);
        var generated = await File.ReadAllTextAsync(
            workspace.FirstOutputs.RelationalPath);
        Assert.That(
            generated,
            Does.Not.Contain("dotnet-api-contract:System.Math.Max"));
        Assert.That(generated, Does.Contain("EvidenceSha256"));
    }

    [Test]
    public async Task RelationalGeneratorRejectsRemovedPerPackEvidence()
    {
        var root = JsonNode.Parse(
                await File.ReadAllTextAsync(RelationalCatalogPath()))!
            .AsObject();
        var pack = root["packs"]!.AsArray()[0]!.AsObject();
        pack.Add("evidence", "obsolete");

        using var workspace = GenerationWorkspace.Create();
        await File.WriteAllTextAsync(
            workspace.RelationalCatalogInputPath,
            root.ToJsonString(new JsonSerializerOptions { WriteIndented = true }),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        var result = await RunGeneratorAsync(
            workspace,
            "-RelationalCatalogPath",
            workspace.RelationalCatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
    }

    [Test]
    public async Task VerificationRejectsStaleGeneratedOutput()
    {
        using var workspace = GenerationWorkspace.Create();
        var generated = await RunGeneratorAsync(workspace);
        Assert.That(generated.ExitCode, Is.Zero, generated.Output);
        await File.AppendAllTextAsync(
            workspace.FirstOutputs.SourcePath,
            "// stale\n",
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var verification = await RunGeneratorAsync(workspace, "-Verify");

        Assert.That(verification.ExitCode, Is.Not.Zero);
        Assert.That(
            verification.Output,
            Does.Contain("is stale")
                .And.Contain("Generate-ApiSpecCatalog.ps1"));
    }

    [TestCase(
        "\"schemaVersion\": 2",
        "\"schemaVersion\": \"2\"")]
    [TestCase(
        "\"isStatic\": false",
        "\"isStatic\": \"false\"")]
    [TestCase(
        "\"genericArity\": 1",
        "\"genericArity\": \"1\"")]
    [TestCase(
        "\"ordinal\": -1",
        "\"ordinal\": \"-1\"")]
    [TestCase(
        "\"value\": 0",
        "\"value\": \"0\"")]
    public async Task GeneratorRejectsCoercibleScalarStrings(
        string original,
        string replacement)
    {
        using var workspace = GenerationWorkspace.Create();
        var catalog = await File.ReadAllTextAsync(CatalogPath());
        Assert.That(catalog, Does.Contain(original));
        await File.WriteAllTextAsync(
            workspace.CatalogInputPath,
            catalog.Replace(
                original,
                replacement,
                StringComparison.Ordinal),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var result = await RunGeneratorAsync(
            workspace,
            "-CatalogPath",
            workspace.CatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
    }

    [TestCase(
        "postcondition",
        "missing required property",
        "postconditions",
        false)]
    [TestCase(
        null,
        "postconditions must be a JSON array",
        "postconditions",
        false)]
    [TestCase(
        "postcondition",
        "contains unexpected property",
        "postcondition",
        true)]
    public async Task GeneratorRequiresPostconditionsArray(
        string? misspelledName,
        string expectedError,
        string expectedProperty,
        bool keepPostconditions)
    {
        using var workspace = GenerationWorkspace.Create();
        var root = JsonNode.Parse(
                await File.ReadAllTextAsync(CatalogPath()))?.AsObject() ??
            throw new InvalidDataException(
                "The API-spec catalog root is not an object.");
        var declaration = root["declarations"]?.AsArray()
            .Select(static node => node?.AsObject())
            .FirstOrDefault(static node =>
                node?["profile"] is null &&
                node?["postconditions"]?.AsArray().Count > 0) ??
            throw new InvalidDataException(
                "The API-spec catalog has no declaration with postconditions.");
        if (misspelledName == null)
        {
            declaration["postconditions"] = null;
        }
        else
        {
            var postconditions = declaration["postconditions"] ??
                throw new InvalidDataException(
                    "The API-spec declaration has no postconditions.");
            if (keepPostconditions)
            {
                declaration["postconditions"] = new JsonArray();
            }
            else
            {
                Assert.That(declaration.Remove("postconditions"), Is.True);
            }
            declaration[misspelledName] = postconditions;
        }
        await File.WriteAllTextAsync(
            workspace.CatalogInputPath,
            root.ToJsonString(new JsonSerializerOptions
            {
                WriteIndented = true
            }),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var result = await RunGeneratorAsync(
            workspace,
            "-CatalogPath",
            workspace.CatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
        Assert.That(
            result.Output,
            Does.Contain(expectedError)
                .And.Contain(expectedProperty));
    }

    [TestCase("unknown-reference", "Unknown API-spec profile 'missing-profile'.")]
    [TestCase("duplicate-profile", "Duplicate API-spec profile")]
    [TestCase("unused-profile", "Every API-spec profile must be used by a declaration.")]
    [TestCase("mixed-declaration", "contains unexpected property 'facets'.")]
    [TestCase("profile-postconditions-type", "postconditions must be a JSON array.")]
    [TestCase("missing-profile-id", "missing required property 'id'.")]
    [TestCase("missing-profile-facets", "missing required property 'facets'.")]
    [TestCase("missing-profile-postconditions", "missing required property 'postconditions'.")]
    public async Task GeneratorRejectsMalformedProfiles(string mutation, string expectedError)
    {
        using var workspace = GenerationWorkspace.Create();
        var root = JsonNode.Parse(await File.ReadAllTextAsync(CatalogPath()))!.AsObject();
        var profiles = root["profiles"]!.AsArray();
        var firstProfile = profiles[0]!.AsObject();
        var declaration = root["declarations"]!.AsArray()
            .Select(static node => node!.AsObject())
            .First(static node => node["profile"] is not null);

        switch (mutation)
        {
            case "unknown-reference":
                declaration["profile"] = "missing-profile";
                break;
            case "duplicate-profile":
                profiles.Add(firstProfile.DeepClone());
                break;
            case "unused-profile":
                var unused = firstProfile.DeepClone().AsObject();
                unused["id"] = "unused-profile";
                profiles.Add(unused);
                break;
            case "mixed-declaration":
                declaration["facets"] = new JsonObject();
                break;
            case "profile-postconditions-type":
                firstProfile["postconditions"] = new JsonObject();
                break;
            case "missing-profile-id":
                firstProfile.Remove("id");
                break;
            case "missing-profile-facets":
                firstProfile.Remove("facets");
                break;
            case "missing-profile-postconditions":
                firstProfile.Remove("postconditions");
                break;
        }

        await File.WriteAllTextAsync(
            workspace.CatalogInputPath,
            root.ToJsonString(),
            new UTF8Encoding(false));
        var result = await RunGeneratorAsync(
            workspace,
            "-CatalogPath", workspace.CatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
        Assert.That(result.Output, Does.Contain(expectedError));
    }

    [TestCase("empty", "must contain at least one declaration")]
    [TestCase("missing", "must contain at least one declaration")]
    [TestCase("factory-collision", "produce colliding factory names")]
    [TestCase("no-name-segments", "has no name segments")]
    public async Task GeneratorRejectsMalformedRuntimeWitnessInputs(
        string mutation,
        string expectedError)
    {
        using var workspace = GenerationWorkspace.Create();
        var root = JsonNode.Parse(
            await File.ReadAllTextAsync(CatalogPath()))!.AsObject();
        var declarations = root["declarations"]!.AsArray();
        switch (mutation)
        {
            case "empty":
                declarations.Clear();
                break;
            case "missing":
                root.Remove("declarations");
                break;
            case "factory-collision":
                declarations[0]!["target"]!["witnessIdentifier"] = "a-b";
                declarations[1]!["target"]!["witnessIdentifier"] = "a_b";
                break;
            case "no-name-segments":
                declarations[0]!["target"]!["witnessIdentifier"] = "---";
                break;
        }
        await File.WriteAllTextAsync(
            workspace.CatalogInputPath,
            root.ToJsonString(),
            new UTF8Encoding(false));

        var result = await RunGeneratorAsync(
            workspace,
            "-CatalogPath", workspace.CatalogInputPath);

        Assert.That(result.ExitCode, Is.Not.Zero, result.Output);
        Assert.That(result.Output, Does.Contain(expectedError));
    }

    private static void AssertDeclaration(
        JsonElement declaration,
        ApiSpecTemplate template,
        Dictionary<string, ApiSpecAssemblyIdentity[]> assemblies,
        Dictionary<string, SpecEvidence> evidence,
        Dictionary<string, JsonElement> profiles)
    {
        var expected = declaration.GetProperty("target");
        var actual = template.Target;
        var witness = actual.WitnessIdentifier;
        using (Assert.EnterMultipleScope())
        {
            Assert.That(
                actual.WitnessIdentifier,
                Is.EqualTo(
                    expected.GetProperty("witnessIdentifier").GetString()),
                witness);
            Assert.That(
                actual.DocumentationCommentId,
                Is.EqualTo(
                    expected.GetProperty("documentationCommentId").GetString()),
                witness);
            Assert.That(
                actual.ContainingTypeMetadataName,
                Is.EqualTo(
                    expected.GetProperty(
                        "containingTypeMetadataName").GetString()),
                witness);
            Assert.That(
                actual.MemberKind,
                Is.EqualTo(
                    EnumValue<SpecTargetMemberKind>(
                        expected.GetProperty("memberKind"))),
                witness);
            Assert.That(
                actual.MemberName,
                Is.EqualTo(
                    expected.GetProperty("memberName").GetString()),
                witness);
            Assert.That(
                actual.IsStatic,
                Is.EqualTo(expected.GetProperty("isStatic").GetBoolean()),
                witness);
            Assert.That(
                actual.GenericArity,
                Is.EqualTo(
                    expected.GetProperty("genericArity").GetInt32()),
                witness);
            Assert.That(
                actual.ReceiverType,
                Is.EqualTo(
                    NullableEnumValue<IrTypeKind>(
                        expected.GetProperty("receiverType"))),
                witness);
            Assert.That(
                actual.ParameterTypes,
                Is.EqualTo(expected.GetProperty("parameterTypes")
                    .EnumerateArray()
                    .Select(EnumValue<IrTypeKind>)
                    .ToArray()),
                witness);
            Assert.That(
                actual.ResultType,
                Is.EqualTo(
                    NullableEnumValue<IrTypeKind>(
                        expected.GetProperty("resultType"))),
                witness);
            var assemblySet = expected
                .GetProperty("approvedAssemblySet").GetString() ??
                throw new InvalidDataException(
                    "An approved assembly set is null.");
            Assert.That(
                actual.ApprovedAssemblies,
                Is.EqualTo(assemblies[assemblySet]),
                witness);
        }

        var profile = declaration.TryGetProperty("profile", out var reference)
            ? profiles[reference.GetString()!]
            : declaration;
        AssertFacets(
            profile.GetProperty("facets"),
            template.Facets,
            evidence,
            witness);
        var postconditions = profile.GetProperty("postconditions")
            .EnumerateArray()
            .ToArray();
        Assert.That(
            template.Postconditions,
            Has.Length.EqualTo(postconditions.Length),
            witness);
        for (var index = 0;
             index < postconditions.Length;
             index++)
        {
            var expectedPostcondition = postconditions[index];
            var actualPostcondition = template.Postconditions[index];
            Assert.That(
                Describe(actualPostcondition.Condition),
                Is.EqualTo(
                    Describe(
                        expectedPostcondition.GetProperty("condition"))),
                witness + " postcondition " + index);
            Assert.That(
                actualPostcondition.Evidence,
                Is.EqualTo(
                    Evidence(
                        expectedPostcondition.GetProperty("evidence"),
                        evidence)),
                witness + " postcondition " + index);
        }
    }

    private static void AssertFacets(
        JsonElement expected,
        ApiSpecFacets actual,
        Dictionary<string, SpecEvidence> evidence,
        string witness)
    {
        var effects = expected.GetProperty("effects");
        var expectedEffects = effects.GetProperty("values")
            .EnumerateArray()
            .Aggregate(
                SpecEffect.None,
                static (value, element) =>
                    value | EnumValue<SpecEffect>(element));
        var allocation = expected.GetProperty("allocation");
        var throws = expected.GetProperty("throws");
        var nullness = expected.GetProperty("nullness");
        var cardinality = expected.GetProperty("cardinality");
        var exactCount = cardinality.GetProperty("exactCount");
        using (Assert.EnterMultipleScope())
        {
            Assert.That(
                actual.Effects.Effects,
                Is.EqualTo(expectedEffects),
                witness);
            Assert.That(
                actual.Effects.Evidence,
                Is.EqualTo(
                    Evidence(effects.GetProperty("evidence"), evidence)),
                witness);
            Assert.That(
                actual.Allocation.Behavior,
                Is.EqualTo(
                    EnumValue<SpecAllocationBehavior>(
                        allocation.GetProperty("behavior"))),
                witness);
            Assert.That(
                actual.Allocation.Evidence,
                Is.EqualTo(
                    Evidence(
                        allocation.GetProperty("evidence"),
                        evidence)),
                witness);
            Assert.That(
                actual.Throws.Behavior,
                Is.EqualTo(
                    EnumValue<SpecThrowBehavior>(
                        throws.GetProperty("behavior"))),
                witness);
            Assert.That(
                actual.Throws.ExceptionMetadataNames,
                Is.EqualTo(
                    throws.GetProperty("exceptionMetadataNames")
                        .EnumerateArray()
                        .Select(static item => item.GetString())
                        .ToArray()),
                witness);
            Assert.That(
                actual.Throws.Evidence,
                Is.EqualTo(
                    Evidence(throws.GetProperty("evidence"), evidence)),
                witness);
            Assert.That(
                actual.Nullness.Result,
                Is.EqualTo(
                    EnumValue<SpecNullness>(
                        nullness.GetProperty("result"))),
                witness);
            Assert.That(
                actual.Nullness.Evidence,
                Is.EqualTo(
                    Evidence(
                        nullness.GetProperty("evidence"),
                        evidence)),
                witness);
            Assert.That(
                actual.Cardinality.Result,
                Is.EqualTo(
                    EnumValue<SpecCardinality>(
                        cardinality.GetProperty("result"))),
                witness);
            Assert.That(
                actual.Cardinality.ExactCount,
                Is.EqualTo(
                    exactCount.ValueKind == JsonValueKind.Null
                        ? null
                        : exactCount.GetInt32()),
                witness);
            Assert.That(
                actual.Cardinality.Evidence,
                Is.EqualTo(
                    Evidence(
                        cardinality.GetProperty("evidence"),
                        evidence)),
                witness);
        }

        if (expected.TryGetProperty("termination", out var termination))
        {
            Assert.That(actual.Termination, Is.Not.Null, witness);
            using (Assert.EnterMultipleScope())
            {
                Assert.That(
                    actual.Termination!.Behavior,
                    Is.EqualTo(
                        EnumValue<SpecTerminationBehavior>(
                            termination.GetProperty("behavior"))),
                    witness);
                Assert.That(
                    actual.Termination.Evidence,
                    Is.EqualTo(
                        Evidence(
                            termination.GetProperty("evidence"),
                            evidence)),
                    witness);
            }
        }
        else
        {
            Assert.That(actual.Termination, Is.Null, witness);
        }
    }

    private static Dictionary<string, ApiSpecAssemblyIdentity[]>
        ReadAssemblySets(JsonElement root)
    {
        var result =
            new Dictionary<string, ApiSpecAssemblyIdentity[]>(
                StringComparer.Ordinal);
        foreach (var set in root.GetProperty("assemblySets")
                     .EnumerateArray())
        {
            var id = set.GetProperty("id").GetString() ??
                throw new InvalidDataException(
                    "An assembly set id is null.");
            var identities = set.GetProperty("identities").EnumerateArray()
                .SelectMany(static identity =>
                    identity.GetProperty("referenceFamilies").EnumerateArray()
                        .Select(family => new ApiSpecAssemblyIdentity(
                            identity.GetProperty("name").GetString() ??
                            throw new InvalidDataException("An assembly name is null."),
                            identity.GetProperty("publicKeyToken").GetString() ??
                            throw new InvalidDataException("A public-key token is null."),
                            Enum.Parse<ApiSpecReferenceFamily>(
                                family.GetString() ??
                                throw new InvalidDataException(
                                    "A reference family is null.")))))
                .ToArray();
            result.Add(id, identities);
        }
        return result;
    }

    private static Dictionary<string, SpecEvidence> ReadEvidence(
        JsonElement root)
    {
        return root.GetProperty("evidence")
            .EnumerateArray()
            .ToDictionary(
                static item => item.GetProperty("id").GetString() ??
                    throw new InvalidDataException(
                        "An evidence id is null."),
                static item => new SpecEvidence(
                    EnumValue<SpecEvidenceKind>(
                        item.GetProperty("kind")),
                    item.GetProperty("source").GetString() ??
                    throw new InvalidDataException(
                        "An evidence source is null.")),
                StringComparer.Ordinal);
    }

    private static SpecEvidence Evidence(
        JsonElement reference,
        Dictionary<string, SpecEvidence> evidence)
    {
        var id = reference.GetString() ??
            throw new InvalidDataException(
                "An evidence reference is null.");
        return evidence[id];
    }

    private static string Describe(JsonElement term)
    {
        var kind = term.GetProperty("kind").GetString();
        var type = term.GetProperty("type").GetString();
        return kind switch
        {
            "variable" => FormatTerm("variable:" + term.GetProperty("role").GetString() + ":" +
                term.GetProperty("ordinal").GetInt32(), type),
            "boolean" => FormatTerm("boolean:" + term.GetProperty("value").GetBoolean(), type),
            "integer" => FormatTerm("integer:" + term.GetProperty("value").GetInt64(), type),
            "string" => FormatTerm("string:" + JsonSerializer.Serialize(term.GetProperty("value").GetString()), type),
            "null" => FormatTerm("null", type),
            "unary" => FormatTerm("unary:" + term.GetProperty("operator").GetString(), type,
                Describe(term.GetProperty("operand"))),
            "binary" => FormatTerm("binary:" + term.GetProperty("operator").GetString(), type,
                Describe(term.GetProperty("left")), Describe(term.GetProperty("right"))),
            "conditional" => FormatTerm("conditional", type,
                Describe(term.GetProperty("condition")), Describe(term.GetProperty("whenTrue")),
                Describe(term.GetProperty("whenFalse"))),
            "length" => FormatTerm("length", type, Describe(term.GetProperty("value"))),
            _ => throw new InvalidDataException(
                "Unknown catalog term kind: " + kind)
        };
    }

    private static string Describe(SpecTermDeclaration term)
    {
        return term switch
        {
            SpecVariableDeclaration variable => FormatTerm("variable:" + variable.Role + ":" + variable.Ordinal, variable.Type.ToString()),
            SpecBooleanDeclaration boolean => FormatTerm("boolean:" + boolean.Value, boolean.Type.ToString()),
            SpecIntegerDeclaration integer => FormatTerm("integer:" + integer.Value, integer.Type.ToString()),
            SpecStringDeclaration text => FormatTerm("string:" + JsonSerializer.Serialize(text.Value), text.Type.ToString()),
            SpecNullDeclaration nullTerm => FormatTerm("null", nullTerm.Type.ToString()),
            SpecUnaryDeclaration unary => FormatTerm("unary:" + unary.Operator, unary.Type.ToString(), Describe(unary.Operand)),
            SpecBinaryDeclaration binary => FormatTerm("binary:" + binary.Operator, binary.Type.ToString(),
                Describe(binary.Left), Describe(binary.Right)),
            SpecConditionalDeclaration conditional => FormatTerm("conditional", conditional.Type.ToString(),
                Describe(conditional.Condition), Describe(conditional.WhenTrue), Describe(conditional.WhenFalse)),
            SpecLengthDeclaration length => FormatTerm("length", length.Type.ToString(), Describe(length.Value)),
            _ => throw new ArgumentOutOfRangeException(nameof(term))
        };
    }

    private static string FormatTerm(string prefix, string? type, params string[] children)
    {
        return prefix + ":" + type +
            (children.Length == 0 ? string.Empty : "(" + string.Join(",", children) + ")");
    }

    private static T EnumValue<T>(JsonElement value)
        where T : struct, Enum
    {
        return Enum.Parse<T>(
            value.GetString() ??
            throw new InvalidDataException(
                "An enum value is null."),
            ignoreCase: false);
    }

    private static T? NullableEnumValue<T>(JsonElement value)
        where T : struct, Enum
    {
        return value.ValueKind == JsonValueKind.Null
            ? null
            : EnumValue<T>(value);
    }

    private static void AssertGeneratedEncoding(
        byte[] bytes,
        string expectedHeader)
    {
        Assert.That(bytes, Is.Not.Empty);
        Assert.That(
            bytes.Length >= 3 &&
            bytes[0] == 0xEF &&
            bytes[1] == 0xBB &&
            bytes[2] == 0xBF,
            Is.False);
        var text = Encoding.UTF8.GetString(bytes);
        Assert.That(text, Does.StartWith(expectedHeader));
        Assert.That(text, Does.Not.Contain('\r'));
        Assert.That(text, Does.EndWith("\n"));
    }

    private static async Task<GeneratorResult> RunGeneratorAsync(
        params string[] arguments)
    {
        var startInfo = ProcessRunner.CreateStartInfo(
            TestRepository.FindRoot(),
            "pwsh",
            ["-NoLogo", "-NoProfile", "-File", GeneratorPath(), .. arguments]);
        var result = await ProcessRunner.RunCapturedAsync(
            startInfo,
            CancellationToken.None);
        return new GeneratorResult(
            result.ExitCode,
            result.Output + Environment.NewLine + result.Error);
    }

    private static Task<GeneratorResult> RunGeneratorAsync(
        GenerationWorkspace workspace,
        params string[] arguments)
    {
        return RunGeneratorAsync(workspace, false, arguments);
    }

    private static Task<GeneratorResult> RunGeneratorAsync(
        GenerationWorkspace workspace,
        bool useSecondOutputs,
        params string[] arguments)
    {
        var outputs = useSecondOutputs
            ? workspace.SecondOutputs
            : workspace.FirstOutputs;
        return RunGeneratorAsync(
            [.. arguments,
                "-SourceOutputPath", outputs.SourcePath,
                "-DocumentationOutputPath", outputs.DocumentationPath,
                "-RuntimeWitnessOutputPath", outputs.RuntimeWitnessPath,
                "-RelationalSourceOutputPath", outputs.RelationalPath]);
    }

    private static string CatalogPath()
    {
        return Path.Combine(
            TestRepository.FindRoot(),
            "SharpProof.Specs",
            "DefaultApiSpecCatalog.json");
    }

    private static string GeneratorPath()
    {
        return Path.Combine(
            TestRepository.FindRoot(),
            "scripts",
            "Generate-ApiSpecCatalog.ps1");
    }

    private static string RelationalCatalogPath()
    {
        return Path.Combine(
            TestRepository.FindRoot(),
            "SharpProof.Specs",
            "RelationalSpecPackCatalog.json");
    }

    private readonly record struct GeneratorResult(
        int ExitCode,
        string Output);

    private readonly record struct GeneratorOutputs(
        string SourcePath,
        string DocumentationPath,
        string RuntimeWitnessPath,
        string RelationalPath);

    private sealed class GenerationWorkspace : IDisposable
    {
        private readonly TempDirectory _temporary;
        private readonly string _root;

        private GenerationWorkspace(TempDirectory temporary)
        {
            _temporary = temporary;
            _root = temporary.FullName;
            var root = _root;
            CatalogInputPath = Path.Combine(root, "catalog.json");
            RelationalCatalogInputPath = Path.Combine(
                root,
                "relational-catalog.json");
            FirstOutputs = new GeneratorOutputs(
                Path.Combine(root, "first.generated.cs"),
                Path.Combine(root, "first.generated.md"),
                Path.Combine(root, "first.runtime.generated.cs"),
                Path.Combine(root, "first.relational.generated.cs"));
            SecondOutputs = new GeneratorOutputs(
                Path.Combine(root, "second.generated.cs"),
                Path.Combine(root, "second.generated.md"),
                Path.Combine(root, "second.runtime.generated.cs"),
                Path.Combine(root, "second.relational.generated.cs"));
        }

        internal GeneratorOutputs FirstOutputs
        {
            get;
        }
        internal string CatalogInputPath
        {
            get;
        }
        internal string RelationalCatalogInputPath
        {
            get;
        }
        internal GeneratorOutputs SecondOutputs
        {
            get;
        }

        internal static GenerationWorkspace Create()
        {
            var temporary = TempDirectory.CreateOwned(
                "SharpProof.ApiSpecCatalog.Test",
                string.Empty,
                "Refusing to remove an unexpected API-spec catalog directory.");
            try
            {
                return new GenerationWorkspace(temporary);
            }
            catch
            {
                temporary.Dispose();
                throw;
            }
        }

        public void Dispose()
        {
            _temporary.Dispose();
        }
    }
}
