<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472"
                      PrivateAssets="all"
                      GeneratePathProperty="true" />
    <PackageReference Include="NETStandard.Library"
                      VersionOverride="2.0.3"
                      PrivateAssets="all"
                      GeneratePathProperty="true" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Attributes\SharpProof.Attributes.csproj" />
    <ProjectReference Include="..\SharpProof.Effects\SharpProof.Effects.csproj" />
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
    <ProjectReference Include="..\SharpProof.Specs\SharpProof.Specs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(PkgNETStandard_Library)\build\netstandard2.0\ref\*.dll"
          Link="ReferencePacks\netstandard2.0\%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="$(PkgMicrosoft_NETFramework_ReferenceAssemblies_net472)\build\.NETFramework\v4.7.2\**\*.dll"
          Link="ReferencePacks\net472\%(RecursiveDir)%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
