<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Baseline.Core\SharpProof.Baseline.Core.csproj" />
    <Compile Include="..\..\Shared\DotnetSarifBuildRunner.cs" Link="DotnetSarifBuildRunner.cs" />
  </ItemGroup>
</Project>
