using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using NUnit.Framework;
using SharpProof.CompilerProbe.TestAsset;
using SharpProof.Testing;

namespace SharpProof.Package.Test;

[TestFixture]
[Parallelizable(ParallelScope.All)]
public sealed class CompilerProbeSnapshotTests
{
    [Test]
    public async Task ProbeJsonEscapesNonAsciiProvenanceCanonically()
    {
        var compilation = CSharpCompilation.Create(
            "ProbeConsumer",
            [CSharpSyntaxTree.ParseText("class C {}", path: "café.cs")],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        var output = await CaptureSnapshotAsync(compilation);

        Assert.That(output, Does.Contain("\\u00e9.cs"));
    }

    [Test]
    public async Task SyntaxTreeGeneratedKindDoesNotClaimFilenameOrCommentProvenance()
    {
        var compilation = CSharpCompilation.Create(
            "ProbeConsumer",
            [
                CSharpSyntaxTree.ParseText(
                    "// <auto-generated/>\nclass Handwritten {}",
                    path: "Handwritten.g.cs"),
                CSharpSyntaxTree.ParseText(
                    "class AlsoHandwritten {}",
                    path: "AlsoHandwritten.cs")
            ],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)]);
        var output = await CaptureSnapshotAsync(compilation);

        using var document = JsonDocument.Parse(output);
        var kinds = document.RootElement.GetProperty("syntaxTrees")
            .EnumerateArray()
            .Select(static tree => tree.GetProperty("generatedKind").GetString())
            .ToArray();

        Assert.That(kinds, Is.EqualTo(["Unknown", "Unknown"]));
    }

    [Test]
    public async Task CompilationReferenceChangesProbeSnapshot()
    {
        using var directory = new TempDirectory(
            "sharpproof-compilation-reference-");
        var outputPath = Path.Combine(directory.FullName, "probe.json");

        var first = await CaptureSnapshotAsync(
            outputPath,
            "Referenced.First");
        var second = await CaptureSnapshotAsync(
            outputPath,
            "Referenced.Second");

        Assert.That(second, Is.Not.EqualTo(first));
    }

    [Test]
    public async Task ImageBackedPortableReferenceCarriesConsumedImageHash()
    {
        var image = await File.ReadAllBytesAsync(typeof(object).Assembly.Location);
        var compilation = CSharpCompilation.Create(
            "ProbeConsumer",
            [CSharpSyntaxTree.ParseText("class Consumer {}")],
            [MetadataReference.CreateFromImage(image)]);
        var output = await CaptureSnapshotAsync(compilation);

        using var document = JsonDocument.Parse(output);
        var reference = document.RootElement.GetProperty("portableReferences")
            .EnumerateArray()
            .Single();
        Assert.That(
            reference.GetProperty("fileSha256").GetString(),
            Does.Match("^[0-9a-f]{64}$"),
            "image-backed references must be bound to consumed PE bytes");
    }

    [Test]
    public async Task ExecutableEntryPointSelectionChangesProbeSnapshot()
    {
        using var directory = new TempDirectory(
            "sharpproof-entry-point-probe-");
        var outputPath = Path.Combine(directory.FullName, "probe.json");
        var compilation = CSharpCompilation.Create(
            "ProbeConsumer",
            [CSharpSyntaxTree.ParseText(
                    """
                    internal static class FirstEntryPoint {
                        public static void Main() { }
                    }
                    internal static class SecondEntryPoint {
                        public static void Main() { }
                    }
                    """)],
            [MetadataReference.CreateFromFile(typeof(object).Assembly.Location)],
            new CSharpCompilationOptions(OutputKind.ConsoleApplication));

        var first = await CaptureSnapshotAsync(
            outputPath,
            compilation.WithOptions(compilation.Options.WithMainTypeName(
                "FirstEntryPoint")));
        var second = await CaptureSnapshotAsync(
            outputPath,
            compilation.WithOptions(compilation.Options.WithMainTypeName(
                "SecondEntryPoint")));

        using var firstDocument = JsonDocument.Parse(first);
        using var secondDocument = JsonDocument.Parse(second);
        using (Assert.EnterMultipleScope())
        {
            Assert.That(second, Is.Not.EqualTo(first));
            Assert.That(
                firstDocument.RootElement.GetProperty("options")
                    .GetProperty("mainTypeName").GetString(),
                Is.EqualTo("FirstEntryPoint"));
            Assert.That(
                secondDocument.RootElement.GetProperty("options")
                    .GetProperty("mainTypeName").GetString(),
                Is.EqualTo("SecondEntryPoint"));
        }
    }

    private static async Task<string> CaptureSnapshotAsync(
        string outputPath,
        string referencedAssemblyName)
    {
        var referencedCompilation = CSharpCompilation.Create(
            referencedAssemblyName);
        var compilation = CSharpCompilation.Create(
            "ProbeConsumer",
            references: [referencedCompilation.ToMetadataReference()]);
        return await CaptureSnapshotAsync(outputPath, compilation);
    }

    private static async Task<string> CaptureSnapshotAsync(
        CSharpCompilation compilation)
    {
        using var directory = new TempDirectory("sharpproof-probe-snapshot-");
        return await CaptureSnapshotAsync(
            Path.Combine(directory.FullName, "probe.json"),
            compilation);
    }

    private static async Task<string> CaptureSnapshotAsync(
        string outputPath,
        CSharpCompilation compilation)
    {
        var analyzerOptions = new AnalyzerOptions(
            [],
            new DictionaryAnalyzerConfigOptionsProvider(
                new DictionaryAnalyzerConfigOptions(
                    (CompilerProbeContract.OutputPathOptionKey, outputPath))));
        var withAnalyzers = compilation.WithAnalyzers(
            [new CompilerProbeAnalyzer()],
            new CompilationWithAnalyzersOptions(
                analyzerOptions,
                onAnalyzerException: null,
                concurrentAnalysis: true,
                logAnalyzerExecutionTime: false,
                reportSuppressedDiagnostics: false));

        var diagnostics = await withAnalyzers.GetAnalyzerDiagnosticsAsync();
        Assert.That(diagnostics, Is.Empty);
        return await File.ReadAllTextAsync(outputPath);
    }

}
