<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\SharpProof.AnalyzerConsumer.props" />

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SharpProof.Smoke.Net472</RootNamespace>
    <AssemblyName>SharpProof.Smoke.Net472</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
