<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis"
               HintPath="$(RoslynTargetsPath)\bincore\Microsoft.CodeAnalysis.dll"
               Private="true" />
    <Reference Include="Microsoft.CodeAnalysis.CSharp"
               HintPath="$(RoslynTargetsPath)\bincore\Microsoft.CodeAnalysis.CSharp.dll"
               Private="true" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Gates\SharpProof.Gates.csproj" />
  </ItemGroup>
  <Target Name="_CopySharpProofCompilerRuntime"
          AfterTargets="Build">
    <Copy SourceFiles="$(RoslynTargetsPath)\bincore\Microsoft.CodeAnalysis.dll;$(RoslynTargetsPath)\bincore\Microsoft.CodeAnalysis.CSharp.dll"
          DestinationFolder="$(TargetDir)" />
  </Target>
</Project>
