using static SharpProof.CompilerProbe.TestAsset.CompilerProbeSourceHelpers;

namespace SharpProof.CompilerProbe.TestAsset;

[Generator(LanguageNames.CSharp)]
public sealed class CompilerProbeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var globalValue = context.AnalyzerConfigOptionsProvider.Select(
            static (provider, _) => GetOption(
                provider.GlobalOptions,
                CompilerProbeContract.GlobalValueOptionKey));
        var inputs = context.AdditionalTextsProvider
            .Where(static file =>
                string.Equals(
                    Path.GetFileName(file.Path),
                    CompilerProbeContract.AdditionalFileName,
                    StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, cancellationToken) =>
            {
                var text = pair.Left.GetText(cancellationToken)?.ToString() ??
                    string.Empty;
                var metadata = GetOption(
                    pair.Right.GetOptions(pair.Left),
                    CompilerProbeContract.AdditionalFileMetadataOptionKey);
                return (
                    Path: NormalizePath(pair.Left.Path),
                    Text: text,
                    Metadata: metadata);
            })
            .Collect();
        context.RegisterSourceOutput(
            globalValue.Combine(inputs),
            static (productionContext, input) =>
                Generate(productionContext, input.Left, input.Right));
    }

    private static void Generate(
        SourceProductionContext context,
        string globalValue,
        ImmutableArray<(string Path, string Text, string Metadata)> inputs)
    {
        if (inputs.IsDefaultOrEmpty)
        {
            return;
        }

        var input = inputs[0];
        for (var index = 1; index < inputs.Length; index++)
        {
            var candidate = inputs[index];
            if (StringComparer.Ordinal.Compare(candidate.Path, input.Path) < 0)
            {
                input = candidate;
            }
        }
        var fingerprint = ProbeHash.Text(
            globalValue + "\0" + input.Metadata + "\0" + input.Text);
        context.AddSource(
            CompilerProbeContract.GlobalUsingsHintName,
            SourceText.From(
                """
                // <auto-generated/>
                global using SharpProof.CompilerProbe.Generated;
                """,
                Encoding.UTF8));
        context.AddSource(
            CompilerProbeContract.ContractHintName,
            SourceText.From(
                CreateContractSource(
                    input.Path,
                    input.Text,
                    input.Metadata,
                    globalValue,
                    fingerprint),
                Encoding.UTF8));
    }

    private static string CreateContractSource(
        string path,
        string text,
        string metadata,
        string globalValue,
        string fingerprint)
    {
        var postconditionOperator = text.StartsWith(
            "refute:",
            StringComparison.Ordinal)
            ? "!="
            : "==";
        return $$"""
        // <auto-generated/>
        #nullable enable
        namespace SharpProof.CompilerProbe.Generated {
            public static class ProbeGenerated {
                public const string InputPath = {{Literal(path)}};
                public const string InputText = {{Literal(text)}};
                public const string MetadataValue = {{Literal(metadata)}};
                public const string GlobalValue = {{Literal(globalValue)}};
                public const string InputFingerprint = {{Literal(fingerprint)}};

                public static int Verify(int value) {
                    global::SharpProof.Attributes.Contract.Requires(value >= 0);
                    global::SharpProof.Attributes.Contract.Ensures(
                        global::SharpProof.Attributes.Contract.Result<int>() {{postconditionOperator}} value);
                    return value;
                }
            }
        }
        """;
    }

    private static string Literal(string value)
    {
        return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            value,
            quote: true);
    }

}
