using static SharpProof.CompilerProbe.TestAsset.CompilerProbeSourceHelpers;

namespace SharpProof.CompilerProbe.TestAsset;

[Generator(LanguageNames.CSharp)]
public sealed class CompilerProbeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var globalValue = context.AnalyzerConfigOptionsProvider.Select(
            static (provider, _) => GetOption(
                provider.GlobalOptions,
                CompilerProbeContract.GlobalValueOptionKey));
        var inputs = context.AdditionalTextsProvider
            .Where(static file =>
                string.Equals(
                    Path.GetFileName(file.Path),
                    CompilerProbeContract.AdditionalFileName,
                    StringComparison.OrdinalIgnoreCase))
            .Collect()
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, cancellationToken) =>
            {
                var files = pair.Left;
                if (files.IsDefaultOrEmpty)
                {
                    return ImmutableArray<(
                        string Path,
                        string Text,
                        string Metadata)>.Empty;
                }

                var selected = files[0];
                var selectedPath = NormalizePath(selected.Path);
                for (var index = 1; index < files.Length; index++)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var candidate = files[index];
                    var candidatePath = NormalizePath(candidate.Path);
                    if (StringComparer.Ordinal.Compare(
                            candidatePath,
                            selectedPath) < 0)
                    {
                        selected = candidate;
                        selectedPath = candidatePath;
                    }
                }

                var text = selected.GetText(cancellationToken)?.ToString() ??
                    string.Empty;
                var metadata = GetOption(
                    pair.Right.GetOptions(selected),
                    CompilerProbeContract.AdditionalFileMetadataOptionKey);
                return ImmutableArray.Create((
                    Path: selectedPath,
                    Text: text,
                    Metadata: metadata));
            });
        context.RegisterSourceOutput(
            globalValue.Combine(inputs),
            static (productionContext, input) =>
                Generate(productionContext, input.Left, input.Right));
    }

    private static void Generate(
        SourceProductionContext context,
        string globalValue,
        ImmutableArray<(string Path, string Text, string Metadata)> inputs)
    {
        if (inputs.IsDefaultOrEmpty)
        {
            return;
        }

        var input = inputs[0];
        var fingerprint = ProbeHash.Text(
            globalValue + "\0" + input.Metadata + "\0" + input.Text);
        context.AddSource(
            CompilerProbeContract.GlobalUsingsHintName,
            SourceText.From(
                """
                // <auto-generated/>
                global using SharpProof.CompilerProbe.Generated;
                """,
                Encoding.UTF8));
        context.AddSource(
            CompilerProbeContract.ContractHintName,
            SourceText.From(
                CreateContractSource(
                    input.Path,
                    input.Text,
                    input.Metadata,
                    globalValue,
                    fingerprint),
                Encoding.UTF8));
    }

    private static string CreateContractSource(
        string path,
        string text,
        string metadata,
        string globalValue,
        string fingerprint)
    {
        var postconditionOperator = text.StartsWith(
            "refute:",
            StringComparison.Ordinal)
            ? "!="
            : "==";
        return $$"""
        // <auto-generated/>
        #nullable enable
        namespace SharpProof.CompilerProbe.Generated {
            public static class ProbeGenerated {
                public const string InputPath = {{Literal(path)}};
                public const string InputText = {{Literal(text)}};
                public const string MetadataValue = {{Literal(metadata)}};
                public const string GlobalValue = {{Literal(globalValue)}};
                public const string InputFingerprint = {{Literal(fingerprint)}};

                public static int Verify(int value) {
                    global::SharpProof.Attributes.Contract.Requires(value >= 0);
                    global::SharpProof.Attributes.Contract.Ensures(
                        global::SharpProof.Attributes.Contract.Result<int>() {{postconditionOperator}} value);
                    return value;
                }
            }
        }
        """;
    }

    private static string Literal(string value)
    {
        return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(
            value,
            quote: true);
    }

}
