<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);RS1035;RS2008</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\SharpProof.Ir\HashEncoding.cs"
             Link="HashEncoding.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
</Project>
