// <auto-generated>
// Generated by scripts/Generate-DiagnosticDescriptors.ps1 from
// eng/diagnostics/diagnostic-descriptors.v1.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.ContractForGenerator;

internal static class GeneratedDiagnosticDescriptors
{

    internal static readonly DiagnosticDescriptor InvalidTarget = new(
        id: "SPCF0001",
        title: "Invalid ContractFor target",
        messageFormat: "Contract companion '{0}' does not identify one resolvable named target type",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor DuplicateCompanion = new(
        id: "SPCF0002",
        title: "Duplicate ContractFor companion",
        messageFormat: "Target type '{0}' has multiple ContractFor companions; exactly one is required",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidCompanionType = new(
        id: "SPCF0003",
        title: "Invalid ContractFor companion type",
        messageFormat: "Contract companion '{0}' must be a static class whose generic arity and constraints exactly match target '{1}'",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor MissingMember = new(
        id: "SPCF0004",
        title: "Missing ContractFor member",
        messageFormat: "Target method '{0}' has no exact ordinary companion member in '{1}'",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor SignatureMismatch = new(
        id: "SPCF0005",
        title: "ContractFor member signature mismatch",
        messageFormat: "Companion method '{0}' does not exactly match a target overload, including receiver, generic constraints, ref kinds, nullability, and return type",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor AmbiguousMember = new(
        id: "SPCF0006",
        title: "Ambiguous ContractFor member",
        messageFormat: "Companion mapping for method '{0}' is ambiguous",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor BodyRequired = new(
        id: "SPCF0007",
        title: "ContractFor member body required",
        messageFormat: "Companion method '{0}' must have a compiler-bound source body",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidClausePlacement = new(
        id: "SPCF0008",
        title: "Invalid ContractFor clause placement",
        messageFormat: "Contract.{0} in companion method '{1}' has invalid placement: {2}",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "",
        customTags: []);
}
