<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
    <NoWarn>$(NoWarn);RS2008</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Analyzer.Core\SharpProof.Analyzer.Core.csproj" />
    <ProjectReference Include="..\SharpProof.Contracts\SharpProof.Contracts.csproj" />
  </ItemGroup>
</Project>
