namespace SharpProof.Analyzer;

internal static class AnalyzerGeneratedCodePolicy
{
    private static readonly string[] GeneratedPathSuffixes = [
        ".g.cs",
        ".g.i.cs",
        ".generated.cs",
        ".designer.cs"];
    private static readonly string[] GeneratedHeaderMarkers = [
        "<auto-generated",
        "<autogenerated"];

    internal static bool IsGenerated(
        IMethodSymbol method,
        SyntaxTree tree,
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        var generated = compilation.Options.SyntaxTreeOptionsProvider?
            .IsGenerated(tree, cancellationToken) ?? GeneratedKind.Unknown;
        if (generated == GeneratedKind.MarkedGenerated)
        {
            return true;
        }

        if (generated == GeneratedKind.NotGenerated)
        {
            return false;
        }

        return HasGeneratedPath(tree.FilePath) ||
            HasGeneratedHeader(tree, cancellationToken) ||
            HasGeneratedCodeAttribute(method, compilation);
    }

    private static bool HasGeneratedPath(string path)
    {
        return GeneratedPathSuffixes.Any(suffix =>
            path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool HasGeneratedHeader(
        SyntaxTree tree,
        CancellationToken cancellationToken)
    {
        var text = tree.GetText(cancellationToken);
        var length = Math.Min(text.Length, 2048);
        if (length == 0)
        {
            return false;
        }

        var prefix = text.ToString(new TextSpan(0, length));
        return GeneratedHeaderMarkers.Any(marker =>
            prefix.IndexOf(marker, StringComparison.OrdinalIgnoreCase) >= 0);
    }

    private static bool HasGeneratedCodeAttribute(
        IMethodSymbol method,
        Compilation compilation)
    {
        var generatedCode = compilation.GetTypeByMetadataName(
            FrameworkTypeMetadataNames.GeneratedCodeAttribute);
        if (generatedCode == null)
        {
            return false;
        }

        for (ISymbol? symbol = method;
             symbol is IMethodSymbol or INamedTypeSymbol;
             symbol = symbol.ContainingType)
        {
            if (symbol.GetAttributes().Any(attribute =>
                    SymbolEqualityComparer.Default.Equals(
                        attribute.AttributeClass?.OriginalDefinition,
                        generatedCode.OriginalDefinition)))
            {
                return true;
            }
        }

        return false;
    }
}
