[assembly: InternalsVisibleTo("SharpProof.Test")]
[assembly: InternalsVisibleTo("SharpProof.ToolingTest")]
[assembly: InternalsVisibleTo("SharpProof.Testing")]
[assembly: InternalsVisibleTo("SharpProof.Fuzz.Core")]
[assembly: InternalsVisibleTo("SharpProof.SymbolicCli")]
