// <auto-generated>
// Generated by scripts/Generate-DiagnosticDescriptors.ps1 from
// eng/diagnostics/diagnostic-descriptors.v1.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.Analyzer;

internal static class GeneratedDiagnosticDescriptors {

    internal static readonly DiagnosticDescriptor PurityNotVerifiedRule = new(
        id: "SP0002",
        title: "Purity Not Proven",
        messageFormat: "Method '{0}' is marked [EnforcePure], but its effects do not prove observable purity",
        category: "Purity",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Unknown or observable effects prevent an [EnforcePure] success verdict.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0002",
        customTags: []);

    internal static readonly DiagnosticDescriptor AllocationInZeroAllocationMethodRule = new(
        id: "SP0013",
        title: "Allocation In [ZeroAllocations] Method",
        messageFormat: "Method '{1}' is marked [ZeroAllocations], but operation '{0}' allocates",
        category: "Allocation",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports a known allocation in a [ZeroAllocations] method.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0013",
        customTags: []);

    internal static readonly DiagnosticDescriptor CapabilityViolationRule = new(
        id: "SP0015",
        title: "Disallowed Capability Use",
        messageFormat: "Method '{1}' is marked [AllowedCapabilities], but operation '{0}' requires capabilities: {2}",
        category: "Capabilities",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports known capabilities outside the declared set.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0015",
        customTags: []);

    internal static readonly DiagnosticDescriptor CapabilityUnknownRule = new(
        id: "SP0016",
        title: "Capability Contract Not Proven",
        messageFormat: "Method '{1}' is marked [AllowedCapabilities], but operation '{0}' could not be capability-verified: {2}",
        category: "Capabilities",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports capability contracts whose rich effect summary remains unknown.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0016",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidContractArgumentRule = new(
        id: "SP0024",
        title: "Invalid SharpProof Contract Argument",
        messageFormat: "SharpProof contract '{0}' has invalid argument '{1}': {2}",
        category: "Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Reports malformed SharpProof contract or control arguments.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0024",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidAnalyzerConfigurationRule = new(
        id: "SP0025",
        title: "Invalid SharpProof Analyzer Configuration",
        messageFormat: "SharpProof analyzer option '{0}' has invalid value '{1}': {2}",
        category: "Configuration",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Reports invalid compilation-global SharpProof analyzer options.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0025",
        customTags: []);

    internal static readonly DiagnosticDescriptor RequiresNotProvenRule = new(
        id: "SP0027",
        title: "Precondition Violated",
        messageFormat: "Call to '{0}' violates precondition '{1}'",
        category: "Contracts",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Reports only compiler-bound preconditions that concretely replay as false.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0027",
        customTags: []);

    internal static readonly DiagnosticDescriptor ExceptionContractViolationRule = new(
        id: "SP0030",
        title: "Exception Contract Violated",
        messageFormat: "Method '{0}' is marked {1}, but operation '{2}' can throw disallowed exceptions: {3}",
        category: "ExceptionFlow",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports known escaping exceptions outside the declared exception contract.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0030",
        customTags: []);

    internal static readonly DiagnosticDescriptor ZeroAllocationsNotVerifiedRule = new(
        id: "SP0045",
        title: "Zero-allocation Contract Not Proven",
        messageFormat: "Method '{0}' is marked [ZeroAllocations], but allocation freedom could not be verified: {1}",
        category: "Allocation",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports [ZeroAllocations] methods whose rich effect summary remains unknown.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0045",
        customTags: []);

    internal static readonly DiagnosticDescriptor ExceptionContractNotVerifiedRule = new(
        id: "SP0046",
        title: "Exception Contract Not Proven",
        messageFormat: "Method '{0}' is marked {1}, but its exception behavior could not be verified: {2}",
        category: "ExceptionFlow",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports exception contracts whose rich effect summary remains unknown.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0046",
        customTags: []);

    internal static readonly DiagnosticDescriptor SelectedAnalysisIncompleteRule = new(
        id: "SP0047",
        title: "Selected Analysis Incomplete",
        messageFormat: "SharpProof could not completely analyze selected method '{0}': {1}",
        category: "Verification",
        defaultSeverity: DiagnosticSeverity.Info,
        isEnabledByDefault: true,
        description: "Reports selected methods outside the supported analyzer subset.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0047",
        customTags: []);

    internal static readonly DiagnosticDescriptor CompilerManifestFailureRule = new(
        id: "SP0049",
        title: "Compiler Manifest Emission Failed",
        messageFormat: "SharpProof could not emit the final compiler manifest: {0}",
        category: "Infrastructure",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Reports a fatal failure to attest the compiler's final compilation.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#sp0049",
        customTags: []);

    internal static readonly ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics = [
        PurityNotVerifiedRule,
        AllocationInZeroAllocationMethodRule,
        CapabilityViolationRule,
        CapabilityUnknownRule,
        InvalidContractArgumentRule,
        InvalidAnalyzerConfigurationRule,
        RequiresNotProvenRule,
        ExceptionContractViolationRule,
        ZeroAllocationsNotVerifiedRule,
        ExceptionContractNotVerifiedRule,
        SelectedAnalysisIncompleteRule,
        CompilerManifestFailureRule
    ];
}
