global using System.Collections.Immutable;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Globalization;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.FlowAnalysis;
global using Microsoft.CodeAnalysis.Operations;
global using Microsoft.CodeAnalysis.Text;
global using SharpProof.Analyzer.Configuration;
global using SharpProof.Analyzer.Engine;
global using SharpProof.Analyzer.Engine.Analysis;
global using SharpProof.Identity;
global using SharpProof.ProofCore.Smt;
global using SharpProof.Schema;
global using SharpProof.Symbolic;
global using SharpProof.Symbolic.Ir;
global using SharpProof.Symbolic.Smt;
global using ExceptionCategories = SharpProof.Symbolic.SymbolicRuntimeExceptionFacts.ExceptionCategories;
global using ExceptionTypes = SharpProof.Symbolic.SymbolicRuntimeExceptionFacts.ExceptionTypes;
