<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <ProjectReference Include="..\..\SharpProof.Attributes\SharpProof.Attributes.csproj" />
    <ProjectReference Include="..\..\SharpProof.Symbolic\SharpProof.Symbolic.csproj" />
  </ItemGroup>
</Project>
