[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Analyzer")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Contracts")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Ir.Test")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Smt")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Verify")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Worker")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("SharpProof.Worker.Launcher")]
