// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable

namespace SharpProof.Ir;

public enum IrTypeKind
{
    Boolean = 0,
    Integer = 1,
    String = 2,
    Reference = 3,
    Sequence = 4
}

public enum IrUnaryOperator
{
    Not = 0,
    Negate = 1
}

public enum IrBinaryOperator
{
    Add = 0,
    Subtract = 1,
    Multiply = 2,
    Divide = 3,
    Remainder = 4,
    AndAlso = 5,
    OrElse = 6,
    Equal = 7,
    NotEqual = 8,
    LessThan = 9,
    LessThanOrEqual = 10,
    GreaterThan = 11,
    GreaterThanOrEqual = 12,
    StringConcat = 13,
    // C# string ==: null-aware ordinal comparison of UTF-16 code units.
    // Equal on strings is reference identity.
    StringEquals = 14,
    BitwiseAnd = 15,
    // CLR shl/shr/shr.un on 32- or 64-bit operands of one type. The count
    // operand has the shifted type and only its low five (32-bit) or six
    // (64-bit) bits are used. ShiftRight is arithmetic for signed types and
    // logical for unsigned types. Other widths are unsupported.
    ShiftLeft = 16,
    ShiftRight = 17,
    // Bitwise or and exclusive or on integer operands of one type.
    BitwiseOr = 18,
    BitwiseXor = 19
}

internal static class IrOperatorCatalog
{
    internal static (int Key, IrTypeKind Operand, string Token) Get(
        IrUnaryOperator @operator)
    {
        return @operator switch
        {
            IrUnaryOperator.Not => (0, IrTypeKind.Boolean, "!"),
            IrUnaryOperator.Negate => (1, IrTypeKind.Integer, "-"),
            _ => throw new ArgumentOutOfRangeException(nameof(@operator))
        };
    }

    internal static IrTypeId GetBuiltInType(
        IrFactory factory, IrTypeKind kind)
    {
        return kind switch
        {
            IrTypeKind.Boolean => factory.BooleanType,
            IrTypeKind.Integer => factory.IntegerType,
            IrTypeKind.String => factory.StringType,
            _ => throw new ArgumentOutOfRangeException(nameof(kind))
        };
    }

    internal static bool IsNullable(IrTypeKind kind)
    {
        return kind is
            IrTypeKind.String or
            IrTypeKind.Reference or
            IrTypeKind.Sequence;
    }


    internal static int GetPurityKey(IrOpaquePurity purity)
    {
        return purity switch
        {
            IrOpaquePurity.Pure => 0,
            IrOpaquePurity.Impure => 1,
            _ => throw new ArgumentOutOfRangeException(nameof(purity))
        };
    }

    internal static (
        int Key,
        IrTypeKind? Operand,
        IrTypeKind Result,
        string Token) Get(IrBinaryOperator @operator)
    {
        return @operator switch
        {
            IrBinaryOperator.Add => (0, IrTypeKind.Integer, IrTypeKind.Integer, "+"),
            IrBinaryOperator.Subtract => (1, IrTypeKind.Integer, IrTypeKind.Integer, "-"),
            IrBinaryOperator.Multiply => (2, IrTypeKind.Integer, IrTypeKind.Integer, "*"),
            IrBinaryOperator.Divide => (3, IrTypeKind.Integer, IrTypeKind.Integer, "/"),
            IrBinaryOperator.Remainder => (4, IrTypeKind.Integer, IrTypeKind.Integer, "%"),
            IrBinaryOperator.AndAlso => (5, IrTypeKind.Boolean, IrTypeKind.Boolean, "&&"),
            IrBinaryOperator.OrElse => (6, IrTypeKind.Boolean, IrTypeKind.Boolean, "||"),
            IrBinaryOperator.Equal => (7, null, IrTypeKind.Boolean, "=="),
            IrBinaryOperator.NotEqual => (8, null, IrTypeKind.Boolean, "!="),
            IrBinaryOperator.LessThan => (9, IrTypeKind.Integer, IrTypeKind.Boolean, "<"),
            IrBinaryOperator.LessThanOrEqual => (10, IrTypeKind.Integer, IrTypeKind.Boolean, "<="),
            IrBinaryOperator.GreaterThan => (11, IrTypeKind.Integer, IrTypeKind.Boolean, ">"),
            IrBinaryOperator.GreaterThanOrEqual => (12, IrTypeKind.Integer, IrTypeKind.Boolean, ">="),
            IrBinaryOperator.StringConcat => (13, IrTypeKind.String, IrTypeKind.String, "++"),
            IrBinaryOperator.StringEquals => (14, IrTypeKind.String, IrTypeKind.Boolean, "string=="),
            IrBinaryOperator.BitwiseAnd => (15, IrTypeKind.Integer, IrTypeKind.Integer, "&"),
            IrBinaryOperator.ShiftLeft => (16, IrTypeKind.Integer, IrTypeKind.Integer, "<<"),
            IrBinaryOperator.ShiftRight => (17, IrTypeKind.Integer, IrTypeKind.Integer, ">>"),
            IrBinaryOperator.BitwiseOr => (18, IrTypeKind.Integer, IrTypeKind.Integer, "|"),
            IrBinaryOperator.BitwiseXor => (19, IrTypeKind.Integer, IrTypeKind.Integer, "^"),
            _ => throw new ArgumentOutOfRangeException(nameof(@operator))
        };
    }
}
