// <auto-generated>
// Generated by scripts/Generate-ProjectionCatalog.ps1 from
// SharpProof.Projection.catalog.json.
// Declarative projection tables only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Ir;

public sealed partial class IrPrinter
{
    private string Format(
        IrTerm term
    )
    {
        return term switch
        {
            IrBooleanTerm value => value.Value ? "true" : "false",
            IrIntegerTerm value => value.Value.ToString(CultureInfo.InvariantCulture),
            IrStringTerm value => Quote(_factory.GetString(value.Value)),
            IrNullTerm => "((" + TypeName(term.Type) + ")null)",
            IrVariableTerm value => "v" + value.Variable.Value.ToString(CultureInfo.InvariantCulture),
            IrOpaqueTerm value => FormatOpaque(value),
            IrUnaryTerm value => "(" + IrOperatorCatalog.Get(value.Operator).Token + FormatChild(value.Operand) + ")",
            IrBinaryTerm value => "(" + FormatChild(value.Left) + " " + IrOperatorCatalog.Get(value.Operator).Token + " " + FormatChild(value.Right) + ")",
            IrConditionalTerm value => "(" + FormatChild(value.Condition) + " ? " + FormatChild(value.WhenTrue) + " : " + FormatChild(value.WhenFalse) + ")",
            IrCastTerm value => "((" + TypeName(value.Type) + ")" + FormatChild(value.Operand) + ")",
            IrLengthTerm value => "len(" + FormatChild(value.Value) + ")",
            IrSequenceAccessTerm value => FormatChild(value.Sequence) + "[" + FormatChild(value.Index) + "]",
            _ => throw new InvalidOperationException("Unknown IR term kind: " + term.Kind + ".")
        };
    }
}
