// <auto-generated>
// Generated by scripts/Generate-LauncherArguments.ps1 from
// SharpProof.Worker.Launcher/LauncherArguments.catalog.json.
// Declarative option inventories and request projections only.
// Parsing, validation, manifest I/O, and hashing remain handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

using SharpProof.Worker.Protocol;

namespace SharpProof.Worker.Launcher;

internal sealed partial class LauncherArguments
{
    private static readonly string[] s_required = [
        "worker",
        "request",
        "result",
        "compiler-manifest",
        "verify-policy",
        "assumption-policy",
    ];
    private static readonly string[] s_publication = [
        "publish-request",
        "publish-result",
        "publish-compiler-manifest",
    ];
    private static readonly HashSet<string> s_allowed = [
        "worker",
        "request",
        "result",
        "compiler-manifest",
        "verify-policy",
        "assumption-policy",
        "publish-request",
        "publish-result",
        "publish-compiler-manifest",
        "publish-sarif",
        "termination-grace-ms",
        "query-rlimit",
        "method-rlimit",
        "method-wall-ms",
        "project-wall-ms",
        "max-parallelism",
        "max-expression-depth",
        "process-memory-bytes",
        "max-worker-processes",
        "cache-enabled",
        "cache-directory",
        "cache-maximum-bytes",
    ];

    internal static string[] LauncherRuntimePaths
    {
        get
        {
            var path = typeof(LauncherArguments).Assembly.Location;
            return [
                path,
                System.IO.Path.ChangeExtension(path, ".deps.json"),
                System.IO.Path.ChangeExtension(path, ".runtimeconfig.json"),
                System.IO.Path.Combine(System.IO.Path.GetDirectoryName(path)!, "SharpProof.Worker.Protocol.dll")
            ];
        }
    }

    internal string WorkerPath => FullPath("worker");
    internal string RequestPath => FullPath("request");
    internal string ResultPath => FullPath("result");
    internal string CompilerManifestPath => FullPath("compiler-manifest");
    internal string? PublishRequestPath => OptionalFullPath("publish-request");
    internal string? PublishResultPath => OptionalFullPath("publish-result");
    internal string? PublishCompilerManifestPath => OptionalFullPath("publish-compiler-manifest");
    internal string? PublishSarifPath => OptionalFullPath("publish-sarif");
    internal int TerminationGraceMilliseconds => Number("termination-grace-ms", WorkerLauncherDefaults.TerminationGraceMilliseconds);

    internal WorkerVerifyRequest ProjectRequest(
        WorkerFileReference compilerManifest)
    {
        return new()
        {
            CompilerManifest = compilerManifest,
            VerifyPolicy = LauncherPresentation.ParseVerifyPolicy(
                Required("verify-policy")),
            AssumptionPolicy = LauncherPresentation.ParseAssumptionPolicy(
                Required("assumption-policy")),
            Budgets = CreateBudgets(),
            Cache = CreateCache()
        };
    }

    private WorkerBudgets CreateBudgets()
    {
        return new()
        {
            QueryRlimit = Number("query-rlimit", WorkerBudgets.DefaultQueryRlimit),
            MethodRlimit = Number("method-rlimit", WorkerBudgets.DefaultMethodRlimit),
            MethodWallTimeMilliseconds = Number("method-wall-ms", WorkerBudgets.DefaultMethodWallTimeMilliseconds),
            ProjectWallTimeMilliseconds = Number("project-wall-ms", WorkerBudgets.DefaultProjectWallTimeMilliseconds),
            MaxParallelism = Number("max-parallelism", WorkerBudgets.MaximumParallelism),
            MaximumExpressionDepth = Number("max-expression-depth", WorkerBudgets.DefaultMaximumExpressionDepth),
            ProcessMemoryLimitBytes = Number("process-memory-bytes", WorkerBudgets.DefaultProcessMemoryLimitBytes),
            MaxWorkerProcesses = Number("max-worker-processes", WorkerBudgets.MaximumParallelism)
        };
    }

    private WorkerCacheOptions CreateCache()
    {
        return new()
        {
            Enabled = Boolean("cache-enabled", true),
            Directory = Optional("cache-directory"),
            MaximumBytes = Number("cache-maximum-bytes", WorkerCacheOptions.DefaultMaximumBytes)
        };
    }
}
