<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <SharpProofFeatures>contracts</SharpProofFeatures>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpProof.Verifier"
                      Version="$(SharpProofSamplePackageVersion)"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
