// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable
namespace SharpProof.Contracts;

internal static class ContractProjections
{
    internal static string ClosedAttributeName(
        ClosedContractAttributeKind kind
    )
    {
        return kind switch
        {
            ClosedContractAttributeKind.NotNull => "[NotNull]",
            ClosedContractAttributeKind.Positive => "[Positive]",
            ClosedContractAttributeKind.InRange => "[InRange]",
            _ => throw new InvalidOperationException("The attribute is not a closed contract.")
        };
    }
}
