// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable
namespace SharpProof.Contracts;

internal sealed partial class EffectiveContractSourceResolution
{
    internal EffectiveContractSourceResolution(
        IMethodSymbol source,
        ContractClauseInventory directInventory,
        ContractClauseInventory inventory,
        bool usesCompanion,
        ContractBindingFailure failure
    )
    {
        Source = source;
        DirectInventory = directInventory;
        Inventory = inventory;
        UsesCompanion = usesCompanion;
        Failure = failure;
    }
    internal IMethodSymbol Source { get; }
    internal ContractClauseInventory DirectInventory { get; }
    internal ContractClauseInventory Inventory { get; }
    internal bool UsesCompanion { get; }
    internal ContractBindingFailure Failure { get; }
}
