// <auto-generated>
// Generated by scripts/Generate-DeclarativeModels.ps1 from
// SharpProof.DeclarativeModels.catalog.json.
// Declarative record storage only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Contracts;

internal sealed partial class EffectiveContractSourceResolution
{
    internal EffectiveContractSourceResolution(
        IMethodSymbol source,
        ContractClauseInventory directInventory,
        ContractClauseInventory inventory,
        bool usesCompanion,
        ContractBindingFailure failure
    )
    {
        Source = source;
        DirectInventory = directInventory;
        Inventory = inventory;
        UsesCompanion = usesCompanion;
        Failure = failure;
    }

    internal IMethodSymbol Source
    {
        get;
    }

    internal ContractClauseInventory DirectInventory
    {
        get;
    }

    internal ContractClauseInventory Inventory
    {
        get;
    }

    internal bool UsesCompanion
    {
        get;
    }

    internal ContractBindingFailure Failure
    {
        get;
    }
}
