<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DefineConstants>$(DefineConstants);SHARPPROOF_DATAFLOW_ARGUMENT_GUARD</DefineConstants>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharpProof.Ir\ArgumentNullGuard.cs"
             Link="ArgumentNullGuard.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Dataflow.Test" />
    <InternalsVisibleTo Include="SharpProof.Analyzer.Core" />
  </ItemGroup>
</Project>
