<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);SHARPPROOF_DATAFLOW_ARGUMENT_GUARD</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharpProof.Ir\ArgumentNullGuard.cs"
             Link="ArgumentNullGuard.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Meta.Analyzers\SharpProof.Meta.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Dataflow.Test" />
    <InternalsVisibleTo Include="SharpProof.Analyzer.Core" />
  </ItemGroup>
</Project>
