// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable
namespace SharpProof.Worker;

internal sealed partial record WorkerInputSnapshot(
    CompilerManifestArtifact CompilerManifest,
    ImmutableArray<CompilerCallablePreparation> Callables,
    string ArtifactDigest,
    string InputHash);

internal sealed partial record CallableEntryFeasibility(
    CallableEntryFeasibilityKind Kind,
    WorkerClaimReason Reason,
    ImmutableArray<string> ProofCore,
    ImmutableHashSet<string> UsedAssumptionIds
);

internal sealed partial record CallableVerificationResult(
    WorkerCallableResult Callable,
    ImmutableArray<WorkerClaimResult> Claims
);

internal readonly partial record struct SpecResultProjection(IrVarId? NonNullVariable, IrVarId? LengthVariable);

internal sealed partial class VerificationCache
{
    private sealed partial record CacheEntry(
        int SchemaVersion,
        string InputHash,
        string ManifestHash,
        WorkerCallableResult[] CallableResults,
        WorkerClaimResult[] ClaimResults
    );
}
