using System.Collections.Immutable;

namespace PurelySharp.Analyzer.Engine;

public static class Constants
{

    public static readonly ImmutableHashSet<string> KnownImpureNamespaces = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "System.IO",
        "System.Net",
        "System.Data",
        "System.Threading",
        "System.Diagnostics",
        "System.Security.Cryptography",
        "System.Runtime.InteropServices",
        "System.Reflection"
    );

    public static readonly ImmutableHashSet<string> KnownImpureTypeNames = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "System.Random",
        "System.DateTime",
        "System.Console",
        "System.Environment",
        "System.Timers.Timer"


    );

    public static readonly HashSet<string> KnownImpureMethods = new HashSet<string>(StringComparer.Ordinal)
    {

        "System.Activator.CreateInstance<T>()",
        "System.Activator.CreateInstance(System.Type)",
        "System.Activator.CreateInstance(System.Type, params object[])",
        "System.AppDomain.BaseDirectory.get",
        "System.AppDomain.CurrentDomain.get",
        "System.AppDomain.FriendlyName.get",
        "System.AppDomain.Id.get",
        "System.AppContext.BaseDirectory.get",
        "System.AppContext.GetData(string)",
        "System.AppContext.SetData(string, object?)",
        "System.AppContext.TargetFrameworkName.get",
        "System.AppContext.TryGetSwitch(string, out bool)",
        "System.Array.AsReadOnly<T>(T[])",
        "System.Array.ConvertAll<TInput, TOutput>(TInput[], System.Converter<TInput, TOutput>)",
        "System.Array.Reverse(System.Array)",
        "System.Array.Sort(System.Array)",
        "System.Buffer.BlockCopy(System.Array, int, System.Array, int, int)",
        "System.Collections.ArrayList.Adapter(System.Collections.IList)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey, TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.IDictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.IDictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.List<T>.AsReadOnly()",
        "System.Collections.Queue.Synchronized(System.Collections.Queue)",
        "System.Collections.Generic.HashSet<T>.UnionWith(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.Add(T)",
        "System.Collections.Generic.List<T>.Clear()",
        "System.Collections.Generic.List<T>.ConvertAll<TOutput>(System.Converter<T, TOutput>)",
        "System.Collections.Generic.List<T>.ForEach(System.Action<T>)",
        "System.Collections.Generic.List<T>.FindAll(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.Insert(int, T)",
        "System.Collections.Generic.List<T>.Remove(T)",
        "System.Collections.Generic.List<T>.ToArray()",
        "System.Collections.Generic.Queue<T>.ToArray()",
        "System.Collections.Generic.Queue<T>.Dequeue()",
        "System.Collections.Generic.Queue<T>.Enqueue(T)",
        "System.ReadOnlySpan<T>.ToArray()",
        "System.Runtime.InteropServices.CollectionsMarshal.AsSpan<T>(System.Collections.Generic.List<T>)",
        "System.Collections.Generic.Stack<T>.ToArray()",
        "System.Collections.Generic.Stack<T>.Pop()",
        "System.Collections.Generic.Stack<T>.Push(T)",
        "System.Text.RegularExpressions.Regex.Split(string, string)",
        "System.Text.RegularExpressions.Regex.Split(string)",
        "System.Console.Clear()",
        "System.Console.ReadKey()",
        "System.Console.ReadLine()",
        "System.Console.SetCursorPosition(int, int)",
        "System.Console.Write(string)",
        "System.Console.WriteLine(string)",
        "System.Console.Write(object)",
        "System.Console.WriteLine(object)",
        "System.Console.Write()",
        "System.Console.WriteLine()",
        "System.Console.Error.get",
        "System.Console.In.get",
        "System.Console.Out.get",
        "System.ComponentModel.TypeDescriptor.GetConverter(System.Type)",
        "System.ComponentModel.TypeDescriptor.GetProperties(object)",
        "System.Convert.ToByte(object?)",
        "System.Convert.ToByte(string?)",
        "System.Convert.ToDateTime(object?)",
        "System.Convert.ToDateTime(string?)",
        "System.Convert.ToDecimal(object?)",
        "System.Convert.ToDecimal(string?)",
        "System.Convert.ToDouble(object?)",
        "System.Convert.ToDouble(string?)",
        "System.Convert.ToInt16(object?)",
        "System.Convert.ToInt16(string?)",
        "System.Convert.ToInt32(object?)",
        "System.Convert.ToInt32(string?)",
        "System.Convert.ToInt64(object?)",
        "System.Convert.ToInt64(string?)",
        "System.Convert.ToSByte(object?)",
        "System.Convert.ToSByte(string?)",
        "System.Convert.ToSingle(object?)",
        "System.Convert.ToSingle(string?)",
        "System.Convert.ToString(object?)",
        "System.Convert.ToUInt16(object?)",
        "System.Convert.ToUInt16(string?)",
        "System.Convert.ToUInt32(object?)",
        "System.Convert.ToUInt32(string?)",
        "System.Convert.ToUInt64(object?)",
        "System.Convert.ToUInt64(string?)",
        "object.Equals(object)",
        "object.GetHashCode()",
        "System.DateTime.Now.get",
        "System.DateTime.Today.get",
        "System.DateTime.UtcNow.get",
        "System.DateTimeOffset.Now.get",
        "System.DateTimeOffset.UtcNow.get",
        "System.Diagnostics.ActivitySource.StartActivity(string)",
        "System.Diagnostics.Debug.Assert(bool)",
        "System.Diagnostics.Debug.WriteLine(string)",
        "System.Diagnostics.Debugger.Break()",
        "System.Diagnostics.DiagnosticListener.DiagnosticListener(string)",
        "System.Diagnostics.FileVersionInfo.FileVersion.get",
        "System.Diagnostics.Process.GetCurrentProcess()",
        "System.Diagnostics.Process.Id.get",
        "System.Diagnostics.Process.StartInfo.get",
        "System.Diagnostics.Process.Start(string)",
        "System.Diagnostics.StackFrame.GetMethod()",
        "System.Diagnostics.Stopwatch.Stopwatch()",
        "System.Diagnostics.Stopwatch.IsRunning.get",
        "System.Diagnostics.Stopwatch.IsHighResolution",
        "System.OperatingSystem.IsAndroid()",
        "System.OperatingSystem.IsAndroidVersionAtLeast(int, int, int, int)",
        "System.OperatingSystem.IsBrowser()",
        "System.OperatingSystem.IsFreeBSD()",
        "System.OperatingSystem.IsFreeBSDVersionAtLeast(int, int, int, int)",
        "System.OperatingSystem.IsIOS()",
        "System.OperatingSystem.IsIOSVersionAtLeast(int, int, int)",
        "System.OperatingSystem.IsLinux()",
        "System.OperatingSystem.IsMacCatalyst()",
        "System.OperatingSystem.IsMacCatalystVersionAtLeast(int, int, int)",
        "System.OperatingSystem.IsMacOS()",
        "System.OperatingSystem.IsMacOSVersionAtLeast(int, int, int)",
        "System.OperatingSystem.IsOSPlatform(string)",
        "System.OperatingSystem.IsOSPlatformVersionAtLeast(string, int, int, int, int)",
        "System.OperatingSystem.Platform.get",
        "System.OperatingSystem.IsTvOS()",
        "System.OperatingSystem.IsTvOSVersionAtLeast(int, int, int)",
        "System.OperatingSystem.IsWasi()",
        "System.OperatingSystem.IsWatchOS()",
        "System.OperatingSystem.IsWatchOSVersionAtLeast(int, int, int)",
        "System.OperatingSystem.IsWindows()",
        "System.OperatingSystem.IsWindowsVersionAtLeast(int, int, int, int)",
        "System.Type.GetConstructor(System.Type[])",
        "System.Type.GetTypeFromHandle(System.RuntimeTypeHandle)",
        "System.Type.GetConstructors()",
        "System.Type.GetConstructors(System.Reflection.BindingFlags)",
        "System.Type.GetEvent(string)",
        "System.Type.GetEvent(string, System.Reflection.BindingFlags)",
        "System.Type.GetEvents()",
        "System.Type.GetEvents(System.Reflection.BindingFlags)",
        "System.Type.GetField(string)",
        "System.Type.GetField(string, System.Reflection.BindingFlags)",
        "System.Type.GetFields()",
        "System.Type.GetFields(System.Reflection.BindingFlags)",
        "System.Type.AssemblyQualifiedName.get",
        "System.Type.Attributes.get",
        "System.Type.BaseType.get",
        "System.Type.ContainsGenericParameters.get",
        "System.Type.DefaultBinder.get",
        "System.Type.DeclaringType.get",
        "System.Type.DeclaringMethod.get",
        "System.Type.FullName.get",
        "System.Type.GenericParameterAttributes.get",
        "System.Type.GenericTypeArguments.get",
        "System.Type.GenericParameterPosition.get",
        "System.Type.GUID.get",
        "System.Type.HasElementType.get",
        "System.Type.IsCOMObject.get",
        "System.Type.IsConstructedGenericType.get",
        "System.Type.IsContextful.get",
        "System.Type.IsAbstract.get",
        "System.Type.IsAnsiClass.get",
        "System.Type.IsArray.get",
        "System.Type.IsAutoClass.get",
        "System.Type.IsAutoLayout.get",
        "System.Type.IsByRef.get",
        "System.Type.IsByRefLike.get",
        "System.Type.IsClass.get",
        "System.Type.IsEnum.get",
        "System.Type.IsExplicitLayout.get",
        "System.Type.IsGenericType.get",
        "System.Type.IsGenericTypeDefinition.get",
        "System.Type.IsGenericParameter.get",
        "System.Type.IsImport.get",
        "System.Type.IsInterface.get",
        "System.Type.IsNestedAssembly.get",
        "System.Type.IsNestedFamANDAssem.get",
        "System.Type.IsNestedFamORAssem.get",
        "System.Type.IsNestedFamily.get",
        "System.Type.IsNested.get",
        "System.Type.IsNestedPrivate.get",
        "System.Type.IsNestedPublic.get",
        "System.Type.IsNotPublic.get",
        "System.Type.IsPointer.get",
        "System.Type.IsPrimitive.get",
        "System.Type.IsPublic.get",
        "System.Type.IsLayoutSequential.get",
        "System.Type.IsMarshalByRef.get",
        "System.Type.IsSecurityCritical.get",
        "System.Type.IsSecuritySafeCritical.get",
        "System.Type.IsSecurityTransparent.get",
        "System.Type.IsSealed.get",
        "System.Type.IsSerializable.get",
        "System.Type.IsSZArray.get",
        "System.Type.IsSpecialName.get",
        "System.Type.IsTypeDefinition.get",
        "System.Type.IsUnicodeClass.get",
        "System.Type.IsValueType.get",
        "System.Type.IsVariableBoundArray.get",
        "System.Type.IsVisible.get",
        "System.Type.StructLayoutAttribute.get",
        "System.Type.GetInterface(string)",
        "System.Type.GetInterface(string, bool)",
        "System.Type.GetInterfaces()",
        "System.Type.GetMember(string)",
        "System.Type.GetMember(string, System.Reflection.BindingFlags)",
        "System.Type.GetMember(string, System.Reflection.MemberTypes, System.Reflection.BindingFlags)",
        "System.Type.GetMembers()",
        "System.Type.GetMembers(System.Reflection.BindingFlags)",
        "System.Type.GetMethod(string)",
        "System.Type.GetMethod(string, System.Type[])",
        "System.Type.GetMethod(string, System.Reflection.BindingFlags)",
        "System.Type.GetMethods()",
        "System.Type.GetMethods(System.Reflection.BindingFlags)",
        "System.Type.Assembly.get",
        "System.Type.MemberType.get",
        "System.Type.Module.get",
        "System.Type.Namespace.get",
        "System.Type.ReflectedType.get",
        "System.Type.ToString()",
        "System.Type.GetNestedType(string)",
        "System.Type.GetNestedType(string, System.Reflection.BindingFlags)",
        "System.Type.GetNestedTypes()",
        "System.Type.GetNestedTypes(System.Reflection.BindingFlags)",
        "System.Type.GetProperty(string)",
        "System.Type.GetProperty(string, System.Reflection.BindingFlags)",
        "System.Type.GetProperties(System.Reflection.BindingFlags)",
        "System.Type.GetProperties()",
        "System.Type.TypeHandle.get",
        "System.Type.TypeInitializer.get",
        "System.Type.UnderlyingSystemType.get",
        "System.Reflection.Assembly.CodeBase.get",
        "System.Reflection.Assembly.CustomAttributes.get",
        "System.Reflection.Assembly.DefinedTypes.get",
        "System.Reflection.Assembly.EntryPoint.get",
        "System.Reflection.Assembly.EscapedCodeBase.get",
        "System.Reflection.Assembly.ExportedTypes.get",
        "System.Reflection.Assembly.GetTypes()",
        "System.Reflection.Assembly.GetExecutingAssembly()",
        "System.Reflection.Assembly.GlobalAssemblyCache.get",
        "System.Reflection.Assembly.HostContext.get",
        "System.Reflection.Assembly.IsDynamic.get",
        "System.Reflection.Assembly.IsFullyTrusted.get",
        "System.Reflection.Assembly.Location.get",
        "System.Reflection.Assembly.ManifestModule.get",
        "System.Reflection.Assembly.Modules.get",
        "System.Reflection.Assembly.ReflectionOnly.get",
        "System.Reflection.Assembly.SecurityRuleSet.get",
        "System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo, System.Type)",
        "System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)",
        "System.Attribute.IsDefined(System.Reflection.MemberInfo, System.Type)",
        "System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)",
        "System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.MemberInfo)",
        "System.Reflection.MethodBase.IsStatic.get",
        "System.Reflection.MemberInfo.GetCustomAttributes(bool)",
        "System.Reflection.Module.Assembly.get",
        "System.Reflection.Module.FullyQualifiedName.get",
        "System.Reflection.PropertyInfo.PropertyType.get",
        "System.Reflection.Module.ModuleVersionId.get",
        "System.Reflection.Module.Name.get",
        "System.Reflection.Module.ScopeName.get",
        "System.Diagnostics.Stopwatch.Elapsed.get",
        "System.Diagnostics.Stopwatch.ElapsedMilliseconds.get",
        "System.Diagnostics.Stopwatch.ElapsedTicks.get",
        "System.Diagnostics.Stopwatch.Frequency",
        "System.Diagnostics.Stopwatch.GetTimestamp()",
        "System.Diagnostics.Stopwatch.Start()",
        "System.Diagnostics.Stopwatch.Stop()",
        "System.Diagnostics.Trace.WriteLine(string)",
        "System.Globalization.CultureInfo.GetCultureInfo(string)",
        "System.Enum.GetName(System.Type, object)",
        "System.Enum.IsDefined(System.Type, object)",
        "System.Enum.GetValues(System.Type)",
        "System.IO.MemoryStream.ToArray()",
        "System.IO.StringReader.StringReader(string)",
        "System.Environment.CurrentDirectory.get",
        "object.GetType()",
        "object.ToString()",
        "System.Environment.CurrentDirectory.set",
        "System.Environment.CurrentManagedThreadId.get",
        "System.Environment.ExitCode.get",
        "System.Environment.Exit(int)",
        "System.Environment.GetEnvironmentVariable(string)",
        "System.Environment.GetEnvironmentVariable(string, System.EnvironmentVariableTarget)",
        "System.Environment.GetFolderPath(System.Environment.SpecialFolder)",
        "System.Environment.GetFolderPath(System.Environment.SpecialFolder, System.Environment.SpecialFolderOption)",
        "System.Environment.HasShutdownStarted.get",
        "System.Environment.Is64BitProcess.get",
        "System.Environment.Is64BitOperatingSystem.get",
        "System.Environment.MachineName.get",
        "System.Environment.ProcessorCount.get",
        "System.Environment.ProcessPath.get",
        "System.Environment.SetEnvironmentVariable(string, string)",
        "System.Environment.SetEnvironmentVariable(string, string, System.EnvironmentVariableTarget)",
        "System.Environment.SystemPageSize.get",
        "System.Environment.TickCount.get",
        "System.Environment.TickCount64.get",
        "System.Environment.UserDomainName.get",
        "System.Environment.UserInteractive.get",
        "System.Environment.UserName.get",
        "System.Environment.Version.get",
        "System.Environment.NewLine.get",
        "System.Environment.WorkingSet.get",
        "System.GC.Collect()",
        "System.GC.GetTotalMemory(bool)",
        "System.Globalization.CultureInfo.CurrentCulture.get",
        "System.Globalization.CultureInfo.CurrentUICulture.get",
        "System.Globalization.CultureInfo.DefaultThreadCurrentCulture.get",
        "System.Globalization.CultureInfo.DefaultThreadCurrentUICulture.get",
        "System.Globalization.CultureInfo.InstalledUICulture.get",
        "System.Globalization.RegionInfo.CurrentRegion.get",
        "System.Guid.NewGuid()",
        "System.TimeProvider.LocalTimeZone.get",
        "System.TimeProvider.System.get",
        "System.TimeProvider.TimestampFrequency.get",
        "System.TimeZoneInfo.Local.get",
        "System.IO.Directory.CreateDirectory(string)",
        "System.IO.Directory.Exists(string)",
        "System.IO.DriveInfo.TotalSize.get",
        "System.IO.DriveInfo.GetDrives()",
        "System.IO.File.AppendAllText(string, string)",
        "System.IO.File.Delete(string)",
        "System.IO.File.Exists(string)",
        "System.IO.File.ReadAllBytes(string)",
        "System.IO.File.ReadAllText(string)",
        "System.IO.File.WriteAllText(string, string)",
        "System.IO.File.WriteAllBytes(string, byte[])",
        "System.IO.MemoryStream.Write(byte[], int, int)",
        "System.IO.Path.GetRandomFileName()",
        "System.IO.Path.GetTempFileName()",
        "System.IO.Path.GetTempPath()",
        "System.IO.Stream.Flush()",
        "System.IO.Stream.Read(byte[], int, int)",
        "System.IO.Stream.Seek(long, System.IO.SeekOrigin)",
        "System.IO.Stream.Write(byte[], int, int)",
        "System.IO.StreamReader.ReadLine()",
        "System.IO.StreamReader.StreamReader(System.IO.Stream)",
        "System.IO.StreamWriter.WriteLine(string)",
        "System.IO.StreamWriter.StreamWriter(System.IO.Stream)",
        "System.IO.StringReader.ReadToEnd()",
        "System.IO.StringWriter.Write(string)",
        "System.Lazy<T>.Lazy(System.Func<T>)",
        "System.Lazy<T>.Value.get",
        "System.Linq.Enumerable.ToArray<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.ToDictionary<TSource, TKey>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TKey>)",
        "System.Linq.Enumerable.ToHashSet<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.ToList<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Net.Dns.GetHostEntry(string)",
        "System.Net.Http.HttpClient.GetAsync(string)",
        "System.Net.Http.HttpClient.GetStringAsync(string)",
        "System.Net.Http.HttpClient.PostAsync(string, System.Net.Http.HttpContent)",
        "System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()",
        "System.Net.Sockets.Socket.Connect(System.Net.EndPoint)",
        "System.Net.Sockets.Socket.ConnectAsync(System.Net.EndPoint)",
        "System.Net.Sockets.Socket.Receive(byte[])",
        "System.Net.Sockets.Socket.Send(byte[])",
        "System.Net.WebClient.DownloadString(string)",
        "System.Random.Next()",
        "System.Random.Next(int)",
        "System.Random.NextDouble()",
        "System.Random.NextInt64()",
        "System.Random.NextInt64(long)",
        "System.Random.NextInt64(long, long)",
        "System.Reflection.Assembly.Load(string)",
        "System.Reflection.Assembly.LoadFrom(string)",
        "System.Reflection.FieldInfo.SetValue(object, object)",
        "System.Reflection.MethodBase.GetCurrentMethod()",
        "System.Reflection.MethodInfo.Invoke(object, object[])",
        "System.Reflection.PropertyInfo.SetValue(object, object)",
        "System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)",
        "System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(System.RuntimeTypeHandle)",
        "System.Runtime.GCSettings.IsServerGC.get",
        "System.Runtime.InteropServices.Marshal.AllocHGlobal(System.IntPtr)",
        "System.Runtime.InteropServices.Marshal.FreeHGlobal(System.IntPtr)",
        "System.Runtime.InteropServices.Marshal.StructureToPtr(object, System.IntPtr, bool)",

        "System.Random.Shared.get",
        "System.Security.Cryptography.RandomNumberGenerator.GetBytes(byte[])",
        "System.CodeDom.Compiler.CodeDomProvider.CreateProvider(string)",
        "System.CodeDom.Compiler.CompilerResults.Errors.get",
        "byte.Parse(string)",
        "byte.TryParse(System.ReadOnlySpan<char>, out byte)",
        "byte.ToString(string?)",
        "byte.ToString()",
        "System.DateOnly.Parse(string)",
        "System.DateOnly.Parse(string, System.IFormatProvider?)",
        "System.DateOnly.Parse(string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateOnly.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?)",
        "System.DateOnly.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateOnly.ParseExact(string, string)",
        "System.DateOnly.ParseExact(string, string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateOnly.ParseExact(string, string[])",
        "System.DateOnly.ParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateOnly.ParseExact(System.ReadOnlySpan<char>, string[])",
        "System.DateOnly.ToLongDateString()",
        "System.DateOnly.ToShortDateString()",
        "System.DateOnly.TryParse(string, out System.DateOnly)",
        "System.DateOnly.TryParse(System.ReadOnlySpan<char>, out System.DateOnly)",
        "System.DateOnly.TryParseExact(string, string, out System.DateOnly)",
        "System.DateOnly.TryParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, out System.DateOnly)",
        "System.DateOnly.TryParseExact(string, string[], out System.DateOnly)",
        "System.DateOnly.TryParseExact(System.ReadOnlySpan<char>, string?[]?, out System.DateOnly)",
        "System.DateOnly.ToString(string?)",
        "System.DateOnly.ToString()",
        "System.DateTime.Parse(string)",
        "System.DateTime.ToLongDateString()",
        "System.DateTime.ToLongTimeString()",
        "System.DateTime.ToShortDateString()",
        "System.DateTime.ToShortTimeString()",
        "System.DateTime.ToString(string)",
        "System.DateTime.TryParse(string, out System.DateTime)",
        "System.DateTime.TryParseExact(string, string, System.IFormatProvider, System.Globalization.DateTimeStyles, out System.DateTime)",
        "System.DateTime.TryParseExact(string, string[], System.IFormatProvider, System.Globalization.DateTimeStyles, out System.DateTime)",
        "System.DateTime.TryParse(System.ReadOnlySpan<char>, out System.DateTime)",
        "System.DateTime.ToString()",
        "System.DateTimeOffset.Parse(string)",
        "System.DateTimeOffset.Parse(string, System.IFormatProvider?)",
        "System.DateTimeOffset.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?)",
        "System.DateTimeOffset.Parse(string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.ParseExact(string, string, System.IFormatProvider?)",
        "System.DateTimeOffset.ParseExact(string, string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.ParseExact(string, string[], System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.ParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.ParseExact(System.ReadOnlySpan<char>, string[], System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.DateTimeOffset.TryParse(string, out System.DateTimeOffset)",
        "System.DateTimeOffset.TryParseExact(string, string, System.IFormatProvider, System.Globalization.DateTimeStyles, out System.DateTimeOffset)",
        "System.DateTimeOffset.TryParseExact(string?, string?[]?, System.IFormatProvider?, System.Globalization.DateTimeStyles, out System.DateTimeOffset)",
        "System.DateTimeOffset.TryParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles, out System.DateTimeOffset)",
        "System.DateTimeOffset.TryParseExact(System.ReadOnlySpan<char>, string?[]?, System.IFormatProvider?, System.Globalization.DateTimeStyles, out System.DateTimeOffset)",
        "System.DateTimeOffset.TryParse(System.ReadOnlySpan<char>, out System.DateTimeOffset)",
        "System.DateTimeOffset.ToString(string?)",
        "System.DateTimeOffset.ToString()",
        "System.Exception.ToString()",
        "decimal.Parse(string)",
        "decimal.TryParse(System.ReadOnlySpan<char>, out decimal)",
        "decimal.ToString(string?)",
        "decimal.ToString()",
        "double.Parse(string)",
        "double.TryParse(string, out double)",
        "double.TryParse(System.ReadOnlySpan<char>, out double)",
        "double.ToString(string?)",
        "double.ToString()",
        "float.Parse(string)",
        "float.ToString(string?)",
        "float.ToString()",
        "float.TryParse(string, out float)",
        "float.TryParse(System.ReadOnlySpan<char>, out float)",
        "int.Parse(string)",
        "int.TryParse(string, out int)",
        "int.TryParse(System.ReadOnlySpan<char>, out int)",
        "int.ToString(string?)",
        "int.ToString()",
        "long.Parse(string)",
        "long.TryParse(System.ReadOnlySpan<char>, out long)",
        "long.ToString(string?)",
        "long.ToString()",
        "short.Parse(string)",
        "short.ToString(string?)",
        "short.ToString()",
        "short.TryParse(string, out short)",
        "short.TryParse(System.ReadOnlySpan<char>, out short)",
        "sbyte.Parse(string)",
        "sbyte.ToString(string?)",
        "sbyte.ToString()",
        "sbyte.TryParse(string, out sbyte)",
        "sbyte.TryParse(System.ReadOnlySpan<char>, out sbyte)",
        "ushort.Parse(string)",
        "ushort.ToString(string?)",
        "ushort.ToString()",
        "ushort.TryParse(string, out ushort)",
        "ushort.TryParse(System.ReadOnlySpan<char>, out ushort)",
        "uint.Parse(string)",
        "uint.ToString(string?)",
        "uint.ToString()",
        "uint.TryParse(string, out uint)",
        "uint.TryParse(System.ReadOnlySpan<char>, out uint)",
        "ulong.Parse(string)",
        "ulong.ToString(string?)",
        "ulong.ToString()",
        "ulong.TryParse(string, out ulong)",
        "ulong.TryParse(System.ReadOnlySpan<char>, out ulong)",
        "System.Half.Parse(string)",
        "System.Half.ToString(string?)",
        "System.Half.ToString()",
        "System.Half.TryParse(string, out System.Half)",
        "System.Half.TryParse(System.ReadOnlySpan<char>, out System.Half)",
        "System.Numerics.BigInteger.Parse(string)",
        "System.Numerics.BigInteger.TryParse(string, out System.Numerics.BigInteger)",
        "System.Numerics.BigInteger.TryParse(System.ReadOnlySpan<char>, out System.Numerics.BigInteger)",
        "System.TimeOnly.Parse(string)",
        "System.TimeOnly.Parse(string, System.IFormatProvider?)",
        "System.TimeOnly.Parse(string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.TimeOnly.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?)",
        "System.TimeOnly.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.TimeOnly.ParseExact(string, string)",
        "System.TimeOnly.ParseExact(string, string, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.TimeOnly.ParseExact(string, string[])",
        "System.TimeOnly.ParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.DateTimeStyles)",
        "System.TimeOnly.ParseExact(System.ReadOnlySpan<char>, string[])",
        "System.TimeOnly.ToLongTimeString()",
        "System.TimeOnly.ToShortTimeString()",
        "System.TimeOnly.ToString(string?)",
        "System.TimeOnly.ToString()",
        "System.TimeOnly.TryParse(string, out System.TimeOnly)",
        "System.TimeOnly.TryParse(System.ReadOnlySpan<char>, out System.TimeOnly)",
        "System.TimeOnly.TryParseExact(string, string, out System.TimeOnly)",
        "System.TimeOnly.TryParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, out System.TimeOnly)",
        "System.TimeOnly.TryParseExact(string, string[], out System.TimeOnly)",
        "System.TimeOnly.TryParseExact(System.ReadOnlySpan<char>, string?[]?, out System.TimeOnly)",
        "System.TimeSpan.Parse(string)",
        "System.TimeSpan.Parse(string, System.IFormatProvider?)",
        "System.TimeSpan.Parse(System.ReadOnlySpan<char>, System.IFormatProvider?)",
        "System.TimeSpan.ParseExact(string, string, System.IFormatProvider?)",
        "System.TimeSpan.ParseExact(string, string, System.IFormatProvider?, System.Globalization.TimeSpanStyles)",
        "System.TimeSpan.ParseExact(System.ReadOnlySpan<char>, System.ReadOnlySpan<char>, System.IFormatProvider?, System.Globalization.TimeSpanStyles)",
        "System.TimeSpan.ToString()",
        "System.TimeSpan.TryParse(string, out System.TimeSpan)",
        "System.TimeSpan.TryParse(System.ReadOnlySpan<char>, out System.TimeSpan)",

        "System.Text.Json.JsonSerializer.Deserialize",
        "JsonSerializer.Deserialize",
        "System.Text.Json.JsonSerializer.Deserialize<TValue>(string, System.Text.Json.JsonSerializerOptions?)",
        "System.Text.Json.JsonSerializer.Deserialize<TValue>(System.ReadOnlySpan<byte>, System.Text.Json.JsonSerializerOptions?)",

        "System.Text.Json.JsonSerializer.DeserializeAsync",
        "System.Text.Json.JsonSerializer.SerializeAsync",
        "System.Text.StringBuilder.Append(string?)",
        "System.Text.StringBuilder.Append(char)",
        "System.Text.StringBuilder.Append(object)",
        "System.Text.StringBuilder.AppendLine(string)",
        "System.Text.StringBuilder.Clear()",
        "System.Text.StringBuilder.EnsureCapacity(int)",
        "System.Text.StringBuilder.Insert(int, string)",
        "System.Text.StringBuilder.Remove(int, int)",
        "System.Text.StringBuilder.Replace(string, string)",
        "System.Threading.Interlocked.CompareExchange(ref int, int, int)",
        "System.Threading.Interlocked.CompareExchange(ref long, long, long)",
        "System.Threading.Interlocked.CompareExchange(ref object, object, object)",
        "System.Threading.Interlocked.Increment(ref int)",
        "System.Threading.Interlocked.Increment(ref long)",
        "System.Threading.Interlocked.Decrement(ref int)",
        "System.Threading.Interlocked.Decrement(ref long)",
        "System.Threading.Interlocked.Add(ref int, int)",
        "System.Threading.Interlocked.Add(ref long, long)",
        "System.Threading.Interlocked.Exchange(ref int, int)",
        "System.Threading.Interlocked.Exchange(ref long, long)",
        "System.Threading.Interlocked.Exchange(ref object, object)",
        "System.Threading.Monitor.Enter(object)",
        "System.Threading.Monitor.Exit(object)",
        "System.Threading.Monitor.Pulse(object)",
        "System.Threading.Monitor.Wait(object)",
        "System.Threading.Mutex.ReleaseMutex()",
        "System.Threading.Mutex.WaitOne()",
        "System.Threading.SemaphoreSlim.Release()",
        "System.Threading.SemaphoreSlim.Wait()",
        "System.Threading.Tasks.Task.Delay(int)",
        "System.Threading.Tasks.Task.Delay(System.TimeSpan)",
        "System.Threading.Tasks.Task.IsCompleted.get",
        "System.Threading.Tasks.Task.Run(System.Action)",


        "System.Threading.Tasks.Task.Yield()",
        "System.Threading.Thread.CurrentThread.get",
        "System.Threading.Thread.ManagedThreadId.get",
        "System.Threading.Thread.Sleep(int)",
        "System.Threading.Thread.Sleep(System.TimeSpan)",
        "System.Threading.Volatile.Write",
        "System.TimeZoneInfo.FindSystemTimeZoneById(string)",
        "System.Type.GetType(string)",
        "System.Type.GetType(string, bool)",
        "System.Type.GetType(string, bool, bool)",
        "System.Xml.Linq.XElement.Add(object)",
        "XElement.Add",
        "System.Xml.Linq.XElement.Load(System.IO.Stream)",
        "System.Xml.Linq.XElement.Save(System.IO.Stream)",
        "System.Xml.Linq.XNode.Remove()",
        "System.Xml.XmlReader.Create(System.IO.Stream)",
        "System.Xml.XmlReader.Read()",
        "System.Xml.XmlWriter.Create(System.IO.Stream)",
        "System.Xml.XmlWriter.WriteStartElement(string)",
        "System.Xml.XmlWriter.WriteString(string)",
        "System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.TryAdd(TKey, TValue)",
        "System.Collections.Concurrent.ConcurrentQueue<T>.Enqueue(T)",
        "System.Collections.Concurrent.ConcurrentQueue<T>.TryDequeue(out T)",
        "System.Collections.Concurrent.BlockingCollection<T>.Add(T)",
        "System.Collections.Concurrent.BlockingCollection<T>.Take()",
        "System.Collections.ObjectModel.ObservableCollection<T>.Add(T)",
        "System.ComponentModel.BackgroundWorker.RunWorkerAsync()",
        "System.Diagnostics.EventLog.WriteEntry(string)",
        "System.Diagnostics.PerformanceCounter.NextValue()",
        "System.Diagnostics.TraceSource.TraceEvent(System.Diagnostics.TraceEventType, int)",
        "System.Diagnostics.FileVersionInfo.GetVersionInfo(string)",
        "System.Globalization.NumberFormatInfo.CurrentInfo.get",
        "System.IO.Compression.ZipFile.CreateFromDirectory(string, string)",
        "System.IO.Compression.ZipFile.ExtractToDirectory(string, string)",
        "System.IO.Pipes.NamedPipeServerStream.WaitForConnection()",
        "System.Net.Mail.SmtpClient.Send(System.Net.Mail.MailMessage)",
        "System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()",
        "System.Net.NetworkInformation.Ping.Send(string)",
        "System.Reflection.Emit.DynamicMethod.DynamicMethod(string, System.Type, System.Type[])",
        "System.Reflection.Emit.ILGenerator.Emit(System.Reflection.Emit.OpCode)",
        "System.Runtime.Caching.MemoryCache.Default.get",
        "System.Runtime.Caching.MemoryCache.Add(string, object, System.DateTimeOffset)",
        "System.Runtime.Caching.MemoryCache.Get(string)",
        "System.Runtime.Loader.AssemblyLoadContext.All.get",
        "System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext.get",
        "System.Runtime.Loader.AssemblyLoadContext.Default.get",
        "System.Runtime.Loader.AssemblyLoadContext.EnterContextualReflection()",
        "System.Runtime.Loader.AssemblyLoadContext.EnterContextualReflection(System.Reflection.Assembly?)",
        "System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(System.Reflection.Assembly)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(System.Reflection.AssemblyName)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(string)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromNativeImagePath(string, string?)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(System.IO.Stream)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(System.IO.Stream, System.IO.Stream?)",
        "System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(System.IO.Stream)",
        "System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(System.IO.Stream, object)",
        "System.Security.Principal.WindowsIdentity.GetCurrent()",
        "System.Security.SecureString.AppendChar(char)",
        "System.Security.SecureString.Dispose()",
        "System.Threading.CancellationToken.IsCancellationRequested.get",
        "System.Threading.CancellationToken.Register(System.Action)",
        "System.Threading.CancellationToken.ThrowIfCancellationRequested()",
        "System.Threading.CancellationTokenSource.Cancel()",
        "System.Threading.ReaderWriterLockSlim.EnterReadLock()",
        "System.Threading.ReaderWriterLockSlim.ExitReadLock()",
        "System.Threading.SpinWait.SpinOnce()",
        "System.Threading.Timer.Timer(System.Threading.TimerCallback)",
        "System.Threading.Timer.Change(int, int)",
        "System.Timers.Timer.Start()",
        "System.Timers.Timer.Stop()",
        "System.Xml.Xsl.XslCompiledTransform.Load(string)",
        "System.Xml.Xsl.XslCompiledTransform.Transform(string, string)",
        "System.Collections.BitArray.Set(int, bool)",
        "System.Collections.Specialized.NameValueCollection.Add(string, string)",
        "System.Diagnostics.Process.GetProcessesByName(string)",
        "System.IO.DirectoryInfo.Exists.get",
        "System.IO.DirectoryInfo.EnumerateFiles()",
        "System.IO.FileInfo.Length.get",
        "System.IO.FileSystemWatcher.EnableRaisingEvents.set",
        "System.Net.HttpListener.Start()",
        "System.Net.HttpListener.GetContext()",
        "System.Net.Sockets.UdpClient.Receive(ref System.Net.IPEndPoint)",
        "System.Reflection.AssemblyName.GetAssemblyName(string)",
        "System.Security.Cryptography.X509Certificates.X509Store.Open(System.Security.Cryptography.X509Certificates.OpenFlags)",
        "System.Threading.Barrier.SignalAndWait()",
        "System.Threading.CountdownEvent.Signal()",
        "System.Threading.CountdownEvent.Wait()",
        "System.Threading.Tasks.Dataflow.ActionBlock<TInput>.Post(TInput)",
        "System.Threading.Tasks.Parallel.ForEach",
        "System.Threading.Tasks.Parallel.Invoke",
        "System.Windows.Input.ICommand.Execute(object)",
        "Microsoft.Extensions.Logging.ILogger.LogInformation(string)",
        "Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type)",
        "System.IO.BufferedStream.BufferedStream(System.IO.Stream)",
        "System.IO.BufferedStream.Flush()",


        "string.Format(string, object?)",
        "string.Format(string, object?, object?)",
        "string.Format(string, object?, object?, object?)",
        "string.Format(string, params object?[])",












        "Microsoft.Extensions.Configuration.IConfiguration.GetConnectionString(string)",
        "Microsoft.Extensions.Configuration.IConfigurationRoot.Reload()",
        "System.Buffers.ArrayPool<T>.Shared.Rent(int)",
        "System.Buffers.ArrayPool<T>.Shared.Return(T[], bool)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt16BigEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.WriteSingleBigEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.WriteDoubleBigEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.WriteDoubleLittleEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.WriteHalfBigEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.WriteHalfLittleEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt16BigEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt16LittleEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt32BigEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt32LittleEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt64BigEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt64LittleEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteSingleBigEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteSingleLittleEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteDoubleBigEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteDoubleLittleEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteHalfBigEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteHalfLittleEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16BigEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16LittleEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32BigEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32LittleEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64BigEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64LittleEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(System.Span<byte>, ulong)",
        "System.Buffers.Text.Base64.EncodeToUtf8(System.ReadOnlySpan<byte>, System.Span<byte>, out int, out int)",
        "System.Collections.Generic.LinkedList<T>.AddFirst(T)",
        "System.Collections.Generic.LinkedListNode<T>.Value.set",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Add(TKey, TValue)",








        "System.Collections.ObjectModel.KeyedCollection<TKey, TItem>.Remove(TKey)",
        "System.ComponentModel.AddingNewEventArgs.AddingNewEventArgs()",
        "System.ComponentModel.CancelEventArgs.Cancel.get",
        "System.ComponentModel.CancelEventArgs.Cancel.set",
        "System.ComponentModel.INotifyPropertyChanged.PropertyChanged",
        "System.Data.DataTable.NewRow()",
        "System.Data.DataRow.AcceptChanges()",
        "System.Diagnostics.Activity.Current.get",
        "System.Diagnostics.Activity.Current.set",
        "System.Diagnostics.Activity.SetTag(string, object)",
        "System.Diagnostics.DiagnosticListener.Write(string, object)",
        "System.Drawing.Bitmap.Bitmap(int, int)",
        "System.IO.Compression.BrotliStream.BrotliStream(System.IO.Stream, System.IO.Compression.CompressionMode)",
        "System.IO.Compression.DeflateStream.Read(byte[], int, int)",
        "System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(string)",
        "System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.ReadByte(long)",
        "System.Linq.Queryable.Count<TSource>(System.Linq.IQueryable<TSource>)",
        "System.Linq.Queryable.ToList<TSource>(System.Linq.IQueryable<TSource>)",
        "System.Net.Http.Headers.HttpRequestHeaders.Add(string, string)",
        "System.Net.Security.SslStream.AuthenticateAsClientAsync(string)",
        "System.Net.Sockets.Socket.Accept()",
        "System.Net.Sockets.SocketAsyncEventArgs.AcceptSocket.get",
        "System.Net.Sockets.SocketAsyncEventArgs.AcceptSocket.set",
        "System.Reflection.AssemblyName.AssemblyName(string)",
        "System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(string)",
        "System.Resources.ResourceManager.GetString(string)",
        "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine)",
        "System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>.Add(TKey, TValue)",
        "System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr, System.Runtime.InteropServices.CreateObjectFlags)",
        "System.Runtime.InteropServices.GCHandle.Alloc(object)",
        "System.Runtime.InteropServices.GCHandle.Free()",
        "System.Security.AccessControl.DirectorySecurity.AddAccessRule(System.Security.AccessControl.FileSystemAccessRule)",
        "System.Security.Cryptography.Pkcs.SignedCms.Sign()",
        "System.Security.Cryptography.Xml.SignedXml.ComputeSignature()",
        "System.Security.Cryptography.X509Certificates.X509Certificate2.X509Certificate2(string)",
        "System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase)",
        "System.Speech.Synthesis.SpeechSynthesizer.SpeakAsync(string)",
        "System.Text.Json.Utf8JsonWriter.WriteString(string, string)",
        "System.Threading.AsyncLocal<T>.Value.get",
        "System.Threading.AsyncLocal<T>.Value.set",
        "System.Threading.Channels.Channel.CreateUnbounded<T>()",
        "System.Threading.Channels.ChannelReader<T>.ReadAsync(System.Threading.CancellationToken)",
        "System.Threading.Channels.ChannelWriter<T>.WriteAsync(T, System.Threading.CancellationToken)",
        "System.Threading.LazyInitializer.EnsureInitialized<T>(ref T, System.Func<T>)",
        "System.Transactions.TransactionScope.TransactionScope()",
        "System.Transactions.Transaction.Current.get",
        "Microsoft.Win32.RegistryKey.OpenSubKey(string)",
        "Microsoft.Win32.RegistryKey.GetValue(string)",
        "Microsoft.Win32.RegistryKey.SetValue(string, object)",
        "System.Net.Http.Headers.HttpContentHeaders.ContentLength.get",
        "System.Net.Http.Headers.HttpContentHeaders.ContentLength.set",
        "System.Runtime.InteropServices.SafeHandle.Dispose()",
        "System.Runtime.InteropServices.SafeHandle.IsInvalid.get",
        "System.Text.Unicode.Utf8.ToUtf16(System.ReadOnlySpan<byte>, System.Span<char>, out int, out int)",
        "System.Threading.Semaphore.Semaphore(int, int)",
        "System.TimeZoneInfo.ClearCachedData()",
        "System.Xml.XmlDocument.LoadXml(string)",
        "System.Xml.XmlNode.SelectSingleNode(string)",
        "System.Xml.Schema.XmlSchemaSet.Compile()",
        "System.Xml.Linq.XDocument.Parse(string)",
        "System.Xml.Linq.XElement.Value.get",
        "System.Xml.Linq.XAttribute.Value.get",
        "System.Xml.Linq.XElement.Attribute(System.Xml.Linq.XName)",
        "System.Xml.Linq.XContainer.Elements()",
        "System.Xml.Linq.XContainer.Descendants()",
        "System.Text.Json.JsonDocument.Parse(string, System.Text.Json.JsonDocumentOptions)",
        "System.Text.Json.JsonElement.GetString()",
        "System.Runtime.Versioning.FrameworkName.FrameworkName(string)",
        "System.AppContext.SetSwitch(string, bool)",
        "System.Collections.Generic.PriorityQueue<TElement, TPriority>.Enqueue(TElement, TPriority)",
        "System.Collections.Generic.PriorityQueue<TElement, TPriority>.Dequeue()",
        "System.Diagnostics.Metrics.Counter<T>.Add(T, System.Collections.Generic.KeyValuePair<string, object?>)",
        "System.Runtime.InteropServices.MemoryMarshal.Write<T>(System.Span<byte>, ref T)",
        "System.ComponentModel.Component.Dispose()",
        "System.ComponentModel.LicenseManager.Validate(System.Type, object)",
        "System.Configuration.ConfigurationManager.AppSettings.get",
        "System.Configuration.ConfigurationManager.ConnectionStrings.get",
        "System.Console.Beep()",
        "System.Console.BackgroundColor.get",
        "System.Console.BufferHeight.get",
        "System.Console.BufferHeight.set",
        "System.Console.BufferWidth.get",
        "System.Console.CursorLeft.get",
        "System.Console.CursorSize.get",
        "System.Console.CursorTop.get",
        "System.Console.CursorVisible.get",
        "System.Console.ForegroundColor.get",
        "System.Console.CapsLock.get",
        "System.Console.IsErrorRedirected.get",
        "System.Console.IsInputRedirected.get",
        "System.Console.InputEncoding.get",
        "System.Console.IsOutputRedirected.get",
        "System.Console.KeyAvailable.get",
        "System.Console.LargestWindowHeight.get",
        "System.Console.LargestWindowWidth.get",
        "System.Console.NumberLock.get",
        "System.Console.OutputEncoding.get",
        "System.Console.TreatControlCAsInput.get",
        "System.Console.Title.get",
        "System.Console.Title.set",
        "System.Console.WindowHeight.get",
        "System.Console.WindowLeft.get",
        "System.Console.WindowTop.get",
        "System.Console.WindowWidth.get",
        "System.Data.DataSet.Clear()",
        "System.Diagnostics.Debugger.IsAttached.get",
        "System.Diagnostics.Debugger.Launch()",
        "System.Diagnostics.StackTrace.StackTrace()",
        "System.Diagnostics.Switch.Level.get",
        "System.DirectoryServices.DirectoryEntry.DirectoryEntry(string)",
        "System.GC.GetGeneration(object)",
        "System.GC.KeepAlive(object)",
        "System.GC.KeepAlive(object?)",
        "System.Globalization.DateTimeFormatInfo.CurrentInfo.get",
        "System.IO.BinaryReader.ReadBoolean()",
        "System.IO.BinaryWriter.Write(string)",
        "System.IO.Directory.EnumerateDirectories(string)",
        "System.IO.Directory.GetCurrentDirectory()",
        "System.IO.Directory.SetCurrentDirectory(string)",
        "System.IO.FileStream.FileStream(string, System.IO.FileMode)",
        "System.IO.Pipelines.PipeReader.ReadAsync(System.Threading.CancellationToken)",
        "System.IO.Pipelines.PipeWriter.WriteAsync(System.ReadOnlyMemory<byte>, System.Threading.CancellationToken)",
        "System.Linq.ParallelEnumerable.ForAll<TSource>(System.Linq.ParallelQuery<TSource>, System.Action<TSource>)",
        "System.Linq.ParallelQuery<TSource>.ToList()",
        "System.Management.ManagementObjectSearcher.ManagementObjectSearcher(string)",
        "System.Net.CredentialCache.DefaultCredentials.get",
        "System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)",
        "System.Net.ServicePointManager.SecurityProtocol.get",
        "System.Net.ServicePointManager.SecurityProtocol.set",
        "System.Runtime.InteropServices.Marshal.GetLastWin32Error()",
        "System.Runtime.Serialization.FormatterServices.GetUninitializedObject(System.Type)",
        "System.Threading.ThreadLocal<T>.ThreadLocal(System.Func<T>)",
        "System.Threading.ThreadLocal<T>.Value.get",


        "System.Collections.Generic.IEnumerator<T>.MoveNext()",
        "System.Collections.ObjectModel.Collection<T>.InsertItem(int, T)",
        "System.Collections.ObjectModel.Collection<T>.SetItem(int, T)",
        "System.ComponentModel.INotifyCollectionChanged.CollectionChanged",
        "System.DateTime.ToLocalTime()",
        "System.Delegate.DynamicInvoke(object[])",
        "System.Environment.OSVersion.get",

        "System.GC.SuppressFinalize(object)",

        "System.IDisposable.Dispose()",
        "System.IServiceProvider.GetService(System.Type)",
        "System.IO.File.Copy(string, string)",
        "System.IO.File.Move(string, string)",
        "System.IO.File.OpenRead(string)",
        "System.IO.File.OpenWrite(string)",
        "System.IO.File.ReadAllLines(string)",
        "System.IO.Stream.Close()",
        "System.IO.Stream.CopyToAsync(System.IO.Stream)",
        "System.IO.TextReader.Peek()",
        "System.IO.TextReader.ReadToEnd()",
        "System.IO.TextWriter.Flush()",
        "System.IO.TextWriter.Write(char)",
        "System.Net.Http.HttpContent.ReadAsStringAsync()",
        "System.Net.Http.HttpContent.ReadAsByteArrayAsync()",
        "System.Text.Encoding.Default.get",
        "System.Threading.Tasks.Task.ContinueWith(System.Action<System.Threading.Tasks.Task>)",
        "System.Threading.Tasks.Task.Wait()",
        "System.Threading.Tasks.Task<TResult>.Result.get",


        "System.Array.Clear(System.Array, int, int)",
        "System.Array.ConstrainedCopy(System.Array, int, System.Array, int, int)",
        "System.Array.Copy(System.Array, System.Array, int)",
        "System.Array.Copy(System.Array, int, System.Array, int, int)",
        "System.Array.CopyTo(System.Array, int)",
        "System.Array.Clear(System.Array)",
        "System.Array.Fill<T>(T[], T)",
        "System.Array.Fill<T>(T[], T, int, int)",
        "System.Span<T>.Clear()",
        "System.Span<T>.CopyTo(System.Span<T>)",
        "System.Span<T>.Fill(T)",
        "System.Span<T>.TryCopyTo(System.Span<T>)",
        "System.MemoryExtensions.Reverse<T>(System.Span<T>)",
        "System.Array.Resize<T>(ref T[], int)",
        "System.Array.Reverse<T>(T[])",
        "System.Array.Reverse<T>(T[], int, int)",
        "System.Array.Sort<T>(T[], System.Collections.Generic.IComparer<T>?)",
        "System.Array.Sort<T>(T[], int, int, System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Clear()",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Remove(TKey)",
        "System.Collections.Generic.HashSet<T>.Add(T)",
        "System.Collections.Generic.HashSet<T>.Clear()",
        "System.Collections.Generic.HashSet<T>.Remove(T)",
        "System.Collections.Generic.List<T>.AddRange(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.Capacity.set",
        "System.Collections.Generic.List<T>.InsertRange(int, System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.RemoveAll(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.RemoveAt(int)",
        "System.Collections.Generic.List<T>.RemoveRange(int, int)",
        "System.Collections.Generic.List<T>.Reverse()",
        "System.Collections.Generic.List<T>.Sort()",
        "System.Collections.Generic.List<T>.Sort(System.Comparison<T>)",
        "System.Collections.Generic.List<T>.Sort(System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.List<T>.Sort(int, int, System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.Queue<T>.Clear()",
        "System.Collections.Generic.Stack<T>.Clear()",
        "System.Exception.Source.set",
        "System.IO.Path.GetFullPath(string)",


        "System.Activator.CreateInstanceFrom(string, string)",
        "System.Array.Sort<T>(T[], System.Comparison<T>)",
        "System.Collections.Concurrent.ConcurrentBag<T>.Add(T)",
        "System.Collections.Concurrent.ConcurrentBag<T>.TryTake(out T)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.TryAdd(TKey, TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Values.CopyTo(TValue[], int)",
        "System.Collections.Generic.ICollection<T>.Add(T)",
        "System.Collections.Generic.ICollection<T>.Clear()",
        "System.Collections.Generic.ICollection<T>.Remove(T)",
        "System.Collections.Generic.IList<T>.Insert(int, T)",
        "System.Collections.Generic.IList<T>.RemoveAt(int)",
        "System.Collections.Generic.SortedSet<T>.Add(T)",
        "System.ComponentModel.EventHandlerList.AddHandler(object, System.Delegate)",
        "System.Console.OpenStandardError()",
        "System.Console.OpenStandardInput()",
        "System.Console.OpenStandardOutput()",
        "System.Console.SetError(System.IO.TextWriter)",
        "System.Console.SetIn(System.IO.TextReader)",
        "System.Console.SetOut(System.IO.TextWriter)",
        "System.Diagnostics.Process.ExitCode.get",
        "System.Environment.CommandLine.get",
        "System.Environment.ProcessId.get",
        "System.Environment.StackTrace.get",
        "System.Environment.SystemDirectory.get",
        "System.HashCode.Add<T>(T)",
        "System.IO.DirectoryInfo.Create()",
        "System.IO.DirectoryInfo.Delete()",
        "System.IO.FileInfo.CopyTo(string)",
        "System.IO.FileInfo.Delete()",
        "System.IO.Stream.ReadAsync(byte[], int, int, System.Threading.CancellationToken)",
        "System.IO.Stream.WriteAsync(byte[], int, int, System.Threading.CancellationToken)",
        "System.IO.StreamReader.StreamReader(string)",
        "System.IO.StreamWriter.StreamWriter(string)",
        "System.Linq.Enumerable.ToLookup",
        "System.Text.StringBuilder.AppendJoin(string, object[])",
        "System.Threading.Monitor.TryEnter(object)",


        "System.Xml.Linq.XContainer.Add(object)",
        "XContainer.Add",


        "System.IO.MemoryStream.MemoryStream()",

        "System.Text.Json.JsonSerializer.Serialize",

        "System.Security.Cryptography.RandomNumberGenerator.Fill(byte[])",



























        "System.Convert.ChangeType(object, System.Type)",
    };

    public static readonly HashSet<string> KnownFreshOwnedArrayReturningMembers = new HashSet<string>(StringComparer.Ordinal)
    {
        "System.Security.Cryptography.SHA1.HashData(byte[])",
        "System.Security.Cryptography.SHA1.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.MD5.HashData(byte[])",
        "System.Security.Cryptography.MD5.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.SHA256.HashData(byte[])",
        "System.Security.Cryptography.SHA256.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.SHA384.HashData(byte[])",
        "System.Security.Cryptography.SHA384.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.SHA512.HashData(byte[])",
        "System.Security.Cryptography.SHA512.HashData(System.ReadOnlySpan<byte>)",
    };

    public static readonly HashSet<string> KnownPureBCLMembers = new HashSet<string>(StringComparer.Ordinal)
    {
        "System.Array.Exists<T>(T[], System.Predicate<T>)",
        "System.Array.IndexOf(System.Array, object)",
        "System.Array.TrueForAll<T>(T[], System.Predicate<T>)",
        "System.Array.Length.get",


        "System.BitConverter.ToInt32(byte[], int)",
        "System.BitConverter.ToDouble(byte[], int)",


        "bool.Parse(string)",
        "bool.ToString()",


        "char.IsDigit(char)",
        "char.IsLetter(char)",
        "char.IsWhiteSpace(char)",
        "char.ToLowerInvariant(char)",
        "char.ToUpperInvariant(char)",
        "char.ToString()",


        "System.Collections.Generic.Dictionary<TKey, TValue>.ContainsKey(TKey)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.ContainsValue(TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.TryGetValue(TKey, out TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Count.get",
        "System.Collections.Generic.Comparer<T>.Default.get",
        "System.Collections.Generic.EqualityComparer<T>.Default.get",
        "System.Collections.Generic.HashSet<T>.IsSubsetOf(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.Contains(T)",
        "System.Collections.Generic.List<T>.Count.get",
        "System.Collections.Generic.List<T>.Find(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.Exists(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.TrueForAll(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.this[int].get",
        "System.Collections.Generic.Queue<T>.Peek()",
        "System.Collections.Generic.Stack<T>.Peek()",


        "System.Collections.Immutable.ImmutableList<T>.Add(T)",
        "System.Collections.Immutable.ImmutableList<T>.Contains(T)",
        "System.Collections.Immutable.ImmutableList<T>.Count.get",
        "System.Collections.Immutable.ImmutableList<T>.Remove(T)",
        "System.Collections.Immutable.ImmutableList<T>.SetItem(int, T)",

        "System.Collections.Immutable.ImmutableList<T>.this[int].get",
        "System.Collections.Immutable.ImmutableList.Create<T>()",
        "System.Collections.Immutable.ImmutableList.Create<T>(params T[])",
        "System.Collections.Immutable.ImmutableArray.Create<T>()",
        "System.Collections.Immutable.ImmutableArray.Create<T>(params T[])",
        "System.Collections.Immutable.ImmutableDictionary.Create<TKey, TValue>()",
        "System.Collections.Immutable.ImmutableHashSet.Create<T>()",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Immutable.ImmutableArray<T>, System.Func<T, TResult>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Immutable.ImmutableArray<T>, System.Func<T, TState, TResult>, TState)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Immutable.ImmutableArray<T>, int, int, System.Func<T, TResult>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Immutable.ImmutableArray<T>, int, int, System.Func<T, TState, TResult>, TState)",
        "System.Collections.Immutable.ImmutableList.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEqualityComparer<TKey>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEqualityComparer<TKey>, System.Collections.Generic.IEqualityComparer<TValue>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableHashSet.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableHashSet.CreateRange<T>(System.Collections.Generic.IEqualityComparer<T>, System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableHashSet<T>.Add(T)",
        "System.Collections.Immutable.ImmutableHashSet<T>.Contains(T)",
        "System.Collections.Immutable.ImmutableHashSet<T>.Remove(T)",
        "System.Collections.Immutable.ImmutableHashSet<T>.Count.get",
        "System.Collections.Immutable.ImmutableHashSet<T>.IsEmpty.get",
        "System.Collections.Immutable.ImmutableHashSet<T>.KeyComparer.get",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Add(T)",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Clear()",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Remove(T)",
        "System.Collections.Immutable.ImmutableQueue<T>.Clear()",
        "System.Collections.Immutable.ImmutableQueue<T>.Enqueue(T)",
        "System.Collections.Immutable.ImmutableQueue<T>.Dequeue()",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Clear()",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Dequeue()",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Enqueue(T)",
        "System.Collections.Immutable.ImmutableStack<T>.Clear()",
        "System.Collections.Immutable.ImmutableStack<T>.Push(T)",
        "System.Collections.Immutable.ImmutableStack<T>.Pop()",
        "System.Collections.Immutable.ImmutableStack<T>.IsEmpty.get",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Clear()",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Pop()",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Push(T)",




        "System.DateTime.DateTime(long)",
        "System.DateTime.DateTime(int, int, int)",
        "System.DateTime.Add(System.TimeSpan)",
        "System.DateTime.AddDays(double)",
        "System.DateTime.AddHours(double)",
        "System.DateTime.AddMilliseconds(double)",
        "System.DateTime.AddMinutes(double)",
        "System.DateTime.AddMonths(int)",
        "System.DateTime.AddSeconds(double)",
        "System.DateTime.AddTicks(long)",
        "System.DateTime.AddYears(int)",
        "System.DateTime.IsLeapYear(int)",
        "System.DateTimeOffset.DateTimeOffset(long, System.TimeSpan)",
        "System.DateTimeOffset.Add(System.TimeSpan)",
        "System.DateTimeOffset.AddDays(double)",
        "System.DateTimeOffset.AddHours(double)",
        "System.DateTimeOffset.AddMilliseconds(double)",
        "System.DateTimeOffset.AddMinutes(double)",
        "System.DateTimeOffset.AddMonths(int)",
        "System.DateTimeOffset.AddSeconds(double)",
        "System.DateTimeOffset.AddTicks(long)",
        "System.DateTimeOffset.AddYears(int)",
        "System.DateTimeOffset.FromUnixTimeMilliseconds(long)",
        "System.DateTimeOffset.FromUnixTimeSeconds(long)",
        "System.DateTimeOffset.ToUnixTimeMilliseconds()",
        "System.DateTimeOffset.ToUnixTimeSeconds()",
        "System.DateTimeOffset.DateTime.get",
        "System.DateTimeOffset.Day.get",
        "System.DateTimeOffset.DayOfWeek.get",
        "System.DateTimeOffset.DayOfYear.get",
        "System.DateTimeOffset.Hour.get",
        "System.DateTimeOffset.Millisecond.get",
        "System.DateTimeOffset.Minute.get",
        "System.DateTimeOffset.Month.get",
        "System.DateTimeOffset.Offset.get",
        "System.DateTimeOffset.Second.get",
        "System.DateTimeOffset.Ticks.get",
        "System.DateTimeOffset.UtcDateTime.get",
        "System.DateTimeOffset.UtcTicks.get",
        "System.DateTimeOffset.Year.get",


        "System.DBNull.Value.get",


        "System.Diagnostics.Contracts.Contract.Ensures(bool)",
        "System.Diagnostics.Contracts.Contract.Requires(bool)",


        "System.Globalization.CultureInfo.InvariantCulture.get",
        "System.Globalization.CultureInfo.Name.get",


        "System.Guid.CompareTo(System.Guid)",
        "System.Guid.Empty.get",
        "System.Guid.Equals(System.Guid)",

        "System.IO.Path.Combine(string, string)",
        "System.IO.Path.GetDirectoryName(string)",
        "System.IO.Path.GetDirectoryName(string?)",
        "System.IO.Path.GetExtension(string)",
        "System.IO.Path.GetExtension(string?)",
        "System.IO.Path.GetFileName(string)",
        "System.IO.Path.GetFileName(string?)",
        "System.IO.Path.GetFileNameWithoutExtension(string)",
        "System.IO.Path.GetFileNameWithoutExtension(string?)",


        "System.Linq.Enumerable.Aggregate",
        "System.Linq.Enumerable.All<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)",
        "System.Linq.Enumerable.Any<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Cast<TResult>(System.Collections.IEnumerable)",
        "System.Linq.Enumerable.Count<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Empty<TResult>()",
        "System.Linq.Enumerable.FirstOrDefault<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.GroupBy",
        "System.Linq.Enumerable.OfType<TResult>(System.Collections.IEnumerable)",
        "System.Linq.Enumerable.OrderBy",
        "System.Linq.Enumerable.Range(int, int)",
        "System.Linq.Enumerable.Repeat<TResult>(TResult, int)",
        "System.Linq.Enumerable.Select<TSource, TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TResult>)",
        "System.Linq.Enumerable.SequenceEqual<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Sum",
        "System.Linq.Enumerable.Where<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)",





        "System.Linq.Enumerable.Contains<TSource>(System.Collections.Generic.IEnumerable<TSource>, TSource)",



        "System.Math.E",
        "System.Math.PI",
        "System.Math.Tau",
        "System.Math.Ceiling(double)",
        "System.Math.Floor(double)",
        "System.Math.Sin(double)",
        "System.Math.Sqrt(double)",


        "System.Net.WebUtility.HtmlDecode(string)",
        "System.Net.WebUtility.HtmlEncode(string)",
        "System.Net.WebUtility.UrlDecode(string)",
        "System.Net.WebUtility.UrlEncode(string)",
        "System.Net.WebUtility.UrlDecodeToBytes(byte[], int, int)",
        "System.Net.WebUtility.UrlEncodeToBytes(byte[], int, int)",


        "System.Nullable.Compare<T>(T?, T?)",
        "System.Nullable.Equals<T>(T?, T?)",


        "System.Numerics.BigInteger.Add(System.Numerics.BigInteger, System.Numerics.BigInteger)",
        "System.Numerics.Complex.Complex(double, double)",
        "System.Numerics.Complex.Abs(System.Numerics.Complex)",

        "object.ReferenceEquals(object, object)",


        "System.Reflection.FieldInfo.GetValue(object)",
        "System.Reflection.PropertyInfo.GetValue(object)",
        "System.Runtime.InteropServices.Marshal.PtrToStructure<T>(System.IntPtr)",


        "System.Security.Claims.ClaimsPrincipal.IsInRole(string)",


        "System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(System.ReadOnlySpan<byte>, System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.Aes.DecryptCbc(byte[], byte[], byte[], System.Security.Cryptography.PaddingMode)",
        "System.Security.Cryptography.Aes.EncryptCbc(byte[], byte[], byte[], System.Security.Cryptography.PaddingMode)",
        "System.Security.Cryptography.SHA1.HashData(byte[])",
        "System.Security.Cryptography.SHA1.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.MD5.HashData(byte[])",
        "System.Security.Cryptography.MD5.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.MD5.ComputeHash(byte[])",
        "System.Security.Cryptography.SHA256.HashData(byte[])",
        "System.Security.Cryptography.SHA256.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.SHA256.ComputeHash(byte[])",
        "System.Security.Cryptography.SHA384.HashData(byte[])",
        "System.Security.Cryptography.SHA384.HashData(System.ReadOnlySpan<byte>)",
        "System.Security.Cryptography.SHA512.HashData(byte[])",
        "System.Security.Cryptography.SHA512.HashData(System.ReadOnlySpan<byte>)",


        "string.Concat(string, string)",
        "string.Concat(params string[])",
        "string.IsNullOrEmpty(string)",
        "string.IsNullOrWhiteSpace(string)",
        "string.Replace(string, string)",
        "string.Substring(int, int)",
        "string.ToLower()",
        "string.ToUpper()",
        "string.Trim()",
        "string.Length.get",
        "string.Equals(string)",
        "string.Equals(object)",
        "string.GetHashCode()",
        "string.ToLowerInvariant()",
        "string.ToUpperInvariant()",

        "System.String.Split(char)",
        "System.String.Split(params char[])",
        "System.String.Split(char[])",
        "System.String.Split(char[], System.StringSplitOptions)",
        "System.String.Split(string[], System.StringSplitOptions)",
        "System.String.Split(char[], int, System.StringSplitOptions)",
        "System.String.Split(string[], int, System.StringSplitOptions)",

        "System.String.Join(string, string[])",
        "System.String.Join(string, params string[])",
        "System.String.Join(string, System.Collections.Generic.IEnumerable<string>)",
        "System.String.Join<T>(string, System.Collections.Generic.IEnumerable<T>)",


        "string.String(System.ReadOnlySpan<char>)",



        "System.StringComparer.InvariantCultureIgnoreCase.Compare(string, string)",
        "System.StringComparer.Ordinal.Equals(string, string)",


        "System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, System.Text.Json.JsonSerializerOptions?)",
        "System.Text.RegularExpressions.Regex.Regex(string)",
        "System.Text.RegularExpressions.Regex.IsMatch(string, string)",
        "System.Text.RegularExpressions.Regex.Match(string, string)",
        "System.Text.RegularExpressions.Regex.Replace(string, string, string)",
        "System.Text.RegularExpressions.Regex.IsMatch(string)",
        "System.Text.RegularExpressions.Regex.Match(string)",
        "System.Text.RegularExpressions.Regex.Replace(string, string)",
        "System.Text.StringBuilder.ToString()",




        "System.Threading.Tasks.Task.CompletedTask.get",
        "System.Threading.Tasks.Task.FromResult<TResult>(TResult)",


        "System.TimeSpan.TimeSpan(long)",
        "System.TimeSpan.Add(System.TimeSpan)",


        "System.TimeZoneInfo.ConvertTime(System.DateTimeOffset, System.TimeZoneInfo)",


        "System.Tuple.Create",
        "System.ValueTuple.Create",


        "System.Type.Equals(object)",
        "System.Type.Equals(System.Type)",
        "System.Type.GetHashCode()",



        "System.Buffers.Text.Utf8Parser.TryParse(System.ReadOnlySpan<byte>, out int, out int)",
        "System.Collections.Generic.LinkedListNode<T>.Value.get",
        "System.Collections.Generic.SortedList<TKey, TValue>.IndexOfKey(TKey)",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.ContainsKey(TKey)",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.ContainsValue(TValue)",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.TryGetValue(TKey, out TValue)",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Count.get",
        "System.Collections.ObjectModel.KeyedCollection<TKey, TItem>.Contains(TKey)",
        "System.Drawing.Color.FromArgb(int, int, int, int)",
        "System.Drawing.Point.Point(int, int)",
        "System.Globalization.StringInfo.ParseCombiningCharacters(string)",
        "System.Linq.IQueryable<T>.Expression.get",
        "System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)",
        "System.Memory<T>.Span.get",
        "System.Memory<T>.Slice(int, int)",
        "System.Numerics.Matrix4x4.CreateRotationX(float)",
        "System.Numerics.Vector3.Normalize(System.Numerics.Vector3)",
        "System.Reflection.Metadata.MetadataReader.GetString(System.Reflection.Metadata.StringHandle)",
        "System.Runtime.Intrinsics.X86.Sse.Add(System.Runtime.Intrinsics.Vector128<float>, System.Runtime.Intrinsics.Vector128<float>)",
        "System.Runtime.Intrinsics.X86.Avx2.Multiply(System.Runtime.Intrinsics.Vector256<double>, System.Runtime.Intrinsics.Vector256<double>)",
        "System.Diagnostics.CounterSample.Calculate(System.Diagnostics.CounterSample, System.Diagnostics.CounterSample)",
        "System.Numerics.Plane.Normalize(System.Numerics.Plane)",
        "System.Reflection.Emit.Label.Equals(object)",
        "System.Threading.Tasks.ValueTask<TResult>.ValueTask(TResult)",
        "System.Threading.Tasks.ValueTask.AsTask()",
        "System.Buffers.ReadOnlySequence<T>.Slice(long)",
        "System.IO.Hashing.Crc32.Hash(System.ReadOnlySpan<byte>)",
        "System.Linq.Enumerable.Chunk<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Runtime.InteropServices.MemoryMarshal.Read<T>(System.ReadOnlySpan<byte>)",
        "System.ArgumentOutOfRangeException.ArgumentOutOfRangeException(string)",
        "System.ArraySegment<T>.ArraySegment(T[], int, int)",
        "System.AttributeUsageAttribute.AttributeUsageAttribute(System.AttributeTargets)",
        "System.BadImageFormatException.BadImageFormatException(string)",
        "System.Collections.Hashtable.ContainsKey(object)",
        "System.Collections.SortedList.GetKey(int)",
        "System.ComponentModel.BrowsableAttribute.BrowsableAttribute(bool)",
        "System.ComponentModel.DataAnnotations.RangeAttribute.RangeAttribute(double, double)",
        "System.ComponentModel.DescriptionAttribute.DescriptionAttribute(string)",
        "System.Diagnostics.ConditionalAttribute.ConditionalAttribute(string)",
        "System.DivideByZeroException.DivideByZeroException()",
        "System.EventArgs.Empty.get",
        "System.Exception.HResult.get",
        "System.Exception.InnerException.get",
        "System.FlagsAttribute.FlagsAttribute()",
        "System.FormatException.FormatException(string)",
        "System.Globalization.CompareInfo.Compare(string, string)",
        "System.HashCode.Combine<T1, T2>(T1, T2)",
        "System.Index.Index(int, bool)",
        "System.IO.EndOfStreamException.EndOfStreamException()",
        "System.IO.Path.ChangeExtension(string, string)",
        "System.IO.Path.ChangeExtension(string?, string?)",
        "System.IO.Path.HasExtension(string)",
        "System.IO.Path.HasExtension(string?)",
        "System.IO.Pipelines.Pipe.Pipe(System.IO.Pipelines.PipeOptions)",
        "System.Linq.Expressions.Expression.Constant(object)",
        "System.Linq.Expressions.Expression.Call(System.Reflection.MethodInfo, System.Linq.Expressions.Expression[])",
        "System.Linq.ParallelEnumerable.AsParallel<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.MemoryExtensions.AsSpan<T>(T[])",
        "System.MemoryExtensions.BinarySearch<T>(System.ReadOnlySpan<T>, T)",
        "System.Net.HttpVersion.Version11.get",
        "System.NotImplementedException.NotImplementedException()",
        "System.Nullable<T>.GetValueOrDefault()",
        "System.Numerics.Quaternion.Quaternion(float, float, float, float)",
        "System.ObsoleteAttribute.ObsoleteAttribute(string)",
        "System.OverflowException.OverflowException()",
        "System.PlatformNotSupportedException.PlatformNotSupportedException()",
        "System.Range.Range(System.Index, System.Index)",
        "System.Reflection.Emit.OpCodes.Ldarg_0.get",
        "System.Reflection.MemberInfo.Name.get",
        "System.Reflection.Missing.Value.get",
        "System.Runtime.CompilerServices.CallerArgumentExpressionAttribute.CallerArgumentExpressionAttribute(string)",
        "System.Runtime.CompilerServices.IsExternalInit",
        "System.Runtime.CompilerServices.MethodImplAttribute.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions)",
        "System.Runtime.Serialization.DataContractAttribute.DataContractAttribute()",
        "System.Security.AllowPartiallyTrustedCallersAttribute.AllowPartiallyTrustedCallersAttribute()",

        "System.SerializableAttribute.SerializableAttribute()",
        "System.UIntPtr.UIntPtr(uint)",


        "System.Collections.Generic.ICollection<T>.Count.get",
        "System.Array.GetEnumerator()",
        "System.Collections.Generic.IEnumerable<T>.GetEnumerator()",
        "System.Collections.Generic.IEnumerator<T>.Current.get",
        "System.Collections.Generic.KeyValuePair<TKey, TValue>.KeyValuePair(TKey, TValue)",
        "System.Collections.Generic.KeyValuePair<TKey, TValue>.Key.get",
        "System.Collections.Generic.KeyValuePair<TKey, TValue>.Value.get",
        "System.ComponentModel.DataAnnotations.RequiredAttribute.RequiredAttribute()",
        "System.ComponentModel.DataAnnotations.StringLengthAttribute.StringLengthAttribute(int)",
        "System.DateTime.CompareTo(System.DateTime)",
        "System.DateTime.Compare(System.DateTime, System.DateTime)",
        "System.DateTime.Equals(System.DateTime)",
        "System.DateTime.Equals(System.DateTime, System.DateTime)",
        "System.DateTime.DaysInMonth(int, int)",
        "System.DateTime.FromBinary(long)",
        "System.DateTime.FromOADate(double)",
        "System.DateTime.Subtract(System.DateTime)",
        "System.DateTime.ToBinary()",
        "System.DateTime.ToFileTime()",
        "System.DateTime.ToOADate()",
        "System.DateTimeOffset.Compare(System.DateTimeOffset, System.DateTimeOffset)",
        "System.DateTimeOffset.CompareTo(System.DateTimeOffset)",
        "System.DateTimeOffset.Equals(System.DateTimeOffset)",
        "System.DateTimeOffset.Equals(System.DateTimeOffset, System.DateTimeOffset)",
        "System.DateTimeOffset.Subtract(System.DateTimeOffset)",
        "System.Decimal.Compare(decimal, decimal)",
        "System.Decimal.ToDouble(decimal)",
        "System.Decimal.ToInt32(decimal)",
        "System.Delegate.Combine(System.Delegate, System.Delegate)",
        "System.Delegate.Remove(System.Delegate, System.Delegate)",
        "System.Enum.Parse(System.Type, string)",
        "System.Enum.TryParse<TEnum>(string, out TEnum)",
        "System.Enum.TryParse<TEnum>(string, bool, out TEnum)",
        "System.Enum.TryParse<TEnum>(string?, out TEnum)",
        "System.Enum.TryParse<TEnum>(string?, bool, out TEnum)",
        "System.Linq.Enumerable.Average",
        "System.Linq.Enumerable.Distinct<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.ElementAt<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Linq.Enumerable.First<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Last<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Max",
        "System.Linq.Enumerable.Min",
        "System.Linq.Enumerable.OrderByDescending",
        "System.Linq.Enumerable.Reverse<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Single<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Skip<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Linq.Enumerable.Take<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Linq.Enumerable.ThenBy",
        "System.Linq.Enumerable.Zip",
        "System.Math.Sign(decimal)",
        "System.Math.Truncate(double)",
        "System.Net.IPEndPoint.IPEndPoint(System.Net.IPAddress, int)",
        "System.ObjectDisposedException.ObjectDisposedException(string)",
        "System.Runtime.InteropServices.Marshal.SizeOf<T>()",
        "string.Contains(string)",
        "string.EndsWith(string)",
        "string.IndexOf(char)",
        "string.Insert(int, string)",
        "string.Join(string, System.Collections.Generic.IEnumerable<string>)",
        "string.PadLeft(int)",
        "string.Remove(int)",
        "string.StartsWith(string)",
        "System.Net.Http.HttpResponseMessage.IsSuccessStatusCode.get",
        "System.Text.Encoding.ASCII.get",
        "System.Text.StringBuilder.Length.get",
        "System.Threading.CancellationToken.None.get",
        "System.TimeSpan.CompareTo(System.TimeSpan)",
        "System.TimeSpan.FromDays(double)",
        "System.Uri.IsWellFormedUriString(string, System.UriKind)",
        "System.Uri.ToString()",


        "System.AggregateException.AggregateException(System.Collections.Generic.IEnumerable<System.Exception>)",
        "System.AggregateException.Flatten()",
        "System.ArgumentException.ArgumentException(string, string)",
        "System.Array.BinarySearch(System.Array, object)",
        "System.Array.Find<T>(T[], System.Predicate<T>)",
        "System.Array.FindIndex<T>(T[], System.Predicate<T>)",
        "bool.CompareTo(bool)",
        "bool.TryParse(string, out bool)",
        "bool.TryParse(string?, out bool)",
        "char.GetNumericValue(char)",
        "char.IsControl(char)",
        "char.IsLower(char)",
        "char.IsNumber(char)",
        "char.IsPunctuation(char)",
        "char.IsSeparator(char)",
        "char.IsSymbol(char)",
        "char.IsUpper(char)",
        "char.ToString(char)",
        "System.Collections.Generic.HashSet<T>.Contains(T)",
        "System.Collections.Generic.List<T>.BinarySearch(T)",
        "System.Collections.Generic.List<T>.Capacity.get",

        "System.Collections.Generic.List<T>.FindIndex(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.FindLast(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.IndexOf(T)",
        "System.Collections.Generic.List<T>.LastIndexOf(T)",
        "System.Collections.Generic.Queue<T>.Contains(T)",
        "System.Collections.Generic.Stack<T>.Contains(T)",
        "System.DateTime.Day.get",
        "System.DateTime.DayOfWeek.get",
        "System.DateTime.DayOfYear.get",
        "System.DateTime.Hour.get",
        "System.DateTime.Kind.get",
        "System.DateTime.Millisecond.get",
        "System.DateTime.Minute.get",
        "System.DateTime.Month.get",
        "System.DateTime.Second.get",
        "System.DateTime.Ticks.get",
        "System.DateTime.TimeOfDay.get",


        "System.Array.GetLength(int)",
        "System.Array.IndexOf<T>(T[], T)",
        "System.Array.LastIndexOf<T>(T[], T)",
        "System.Buffers.ReadOnlySequence<T>.End.get",
        "System.Buffers.ReadOnlySequence<T>.IsEmpty.get",
        "System.Buffers.ReadOnlySequence<T>.Length.get",
        "System.Buffers.ReadOnlySequence<T>.Start.get",
        "char.ConvertFromUtf32(int)",
        "char.ConvertToUtf32(char, char)",
        "System.Collections.Generic.ICollection<T>.Contains(T)",
        "System.Collections.Generic.IList<T>.IndexOf(T)",
        "System.Collections.Generic.List<T>.Contains(T)",
        "System.Collections.Generic.Queue<T>.TryPeek(out T)",
        "System.Collections.Generic.SortedSet<T>.GetViewBetween(T, T)",
        "System.ComponentModel.DataAnnotations.EmailAddressAttribute.EmailAddressAttribute()",
        "System.ComponentModel.DataAnnotations.RegularExpressionAttribute.RegularExpressionAttribute(string)",
        "decimal.Negate(decimal)",
        "double.PositiveInfinity.get",
        "System.IO.FileNotFoundException.FileNotFoundException(string?)",
        "System.FormattableString.Format.get",
        "System.FormattableString.Invariant(System.FormattableString)",
        "System.FormattableString.ToString(System.IFormatProvider)",
        "System.HashCode.HashCode()",
        "System.HashCode.ToHashCode()",
        "System.Index.End.get",
        "System.Index.Start.get",
        "System.InvalidOperationException.InvalidOperationException(string)",
        "System.IO.DirectoryInfo.Name.get",
        "System.IO.DirectoryInfo.Parent.get",
        "System.IO.FileInfo.DirectoryName.get",
        "System.IO.FileInfo.Extension.get",
        "System.IO.FileInfo.Name.get",

        "System.Linq.Enumerable.TakeWhile<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)",
        "System.Math.Ceiling(decimal)",
        "System.Net.IPAddress.Any.get",
        "System.Net.IPAddress.Loopback.get",
        "System.Net.IPAddress.IsLoopback(System.Net.IPAddress)",
        "System.Net.IPAddress.Parse(string)",
        "System.Net.IPAddress.Parse(System.ReadOnlySpan<char>)",
        "System.NotSupportedException.NotSupportedException(string)",
        "object.MemberwiseClone()",
        "System.Runtime.InteropServices.MemoryMarshal.AsBytes<T>(System.Span<T>)",
        "string.IsNullOrWhiteSpace(System.ReadOnlySpan<char>)",
        "System.TimeSpan.Zero.get",
        "System.Text.RegularExpressions.Regex.IsMatch(string, string)",
        "System.Collections.Generic.List<T>.Find(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.get_Count()",

















        "object.ReferenceEquals(object, object)",


        "System.ReadOnlySpan<T>.Length.get",
        "System.ReadOnlySpan<T>.IsEmpty.get",
        "System.ReadOnlySpan<T>.Slice(int, int)",
        "System.Span<T>.Length.get",
        "System.Span<T>.IsEmpty.get",


        "string.Clone()",
        "string.CompareTo(string)",
        "string.Contains(char)",
        "string.Contains(char, System.StringComparison)",
        "string.Contains(string)",
        "string.Contains(string, System.StringComparison)",
        "string.EndsWith(string)",
        "string.Equals(string)",
        "string.Equals(string, string)",
        "string.Equals(string, System.StringComparison)",
        "string.GetHashCode()",
        "string.IndexOf(char)",
        "string.IndexOf(string)",
        "string.IsNullOrEmpty(string)",
        "string.IsNullOrWhiteSpace(string)",
        "string.Length.get",
        "string.StartsWith(string)",
        "string.Substring(int)",
        "string.Substring(int, int)",
        "string.ToLower()",
        "string.ToLowerInvariant()",
        "string.ToString()",
        "string.ToUpper()",
        "string.ToUpperInvariant()",
        "string.Trim()",
        "string.TrimEnd()",
        "string.TrimStart()",




        // Exception guard helpers considered pure (diverging without side effects)
        "System.Exception.Message.get",
        "System.ArgumentNullException.ArgumentNullException(string)",
        "System.ArgumentNullException.ThrowIfNull(object)",
        "System.ArgumentNullException.ThrowIfNull(object, string)",
        "System.ArgumentException.ThrowIfNullOrEmpty(string)",
        "System.ArgumentException.ThrowIfNullOrWhiteSpace(string)",
        "System.ArgumentOutOfRangeException.ThrowIfNegative<T>(T)",
        "System.ArgumentOutOfRangeException.ThrowIfZero<T>(T)",
        "System.ArgumentOutOfRangeException.ThrowIfNegativeOrZero<T>(T)",
        "System.ArgumentOutOfRangeException.ThrowIfLessThan<T>(T, T)",
        "System.ArgumentOutOfRangeException.ThrowIfLessThanOrEqual<T>(T, T)",
        "System.ArgumentOutOfRangeException.ThrowIfGreaterThan<T>(T, T)",
        "System.ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual<T>(T, T)",
    };
}
