using System.Collections.Immutable;

namespace PurelySharp.Analyzer.Engine;

public static class Constants
{

    public static readonly ImmutableHashSet<string> KnownImpureNamespaces = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "System.IO",
        "System.Net",
        "System.Data",
        "System.Threading",
        "System.Diagnostics",
        "System.Security.Cryptography",
        "System.Runtime.InteropServices",
        "System.Reflection"
    );

    public static readonly ImmutableHashSet<string> KnownImpureTypeNames = ImmutableHashSet.Create(
        StringComparer.Ordinal,
        "System.Random",
        "System.Timers.Timer"


    );

    public static readonly HashSet<string> KnownImpureMethods = new HashSet<string>(StringComparer.Ordinal)
    {

        "System.Activator.CreateInstance<T>()",
        "System.Activator.CreateInstance(System.Type)",
        "System.Activator.CreateInstance(System.Type, params object[])",
        "System.Array.AsReadOnly<T>(T[])",
        "System.Array.ConvertAll<TInput, TOutput>(TInput[], System.Converter<TInput, TOutput>)",
        "System.Array.Reverse(System.Array)",
        "System.Array.Sort(System.Array)",
        "System.Buffer.BlockCopy(System.Array, int, System.Array, int, int)",
        "System.Collections.ArrayList.Adapter(System.Collections.IList)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey, TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.IDictionary<TKey, TValue>.Keys.get",
        "System.Collections.Generic.IDictionary<TKey, TValue>.Values.get",
        "System.Collections.Generic.List<T>.AsReadOnly()",
        "System.Collections.Queue.Synchronized(System.Collections.Queue)",
        "System.Collections.Generic.HashSet<T>.UnionWith(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.Add(T)",
        "System.Collections.Generic.List<T>.Clear()",
        "System.Collections.Generic.List<T>.ForEach(System.Action<T>)",
        "System.Collections.Generic.List<T>.Insert(int, T)",
        "System.Collections.Generic.List<T>.Remove(T)",
        "System.Collections.Generic.Queue<T>.ToArray()",
        "System.Collections.Generic.Queue<T>.Dequeue()",
        "System.Collections.Generic.Queue<T>.Enqueue(T)",
        "System.ReadOnlySpan<T>.ToArray()",
        "System.Runtime.InteropServices.CollectionsMarshal.AsSpan<T>(System.Collections.Generic.List<T>)",
        "System.Collections.Generic.Stack<T>.ToArray()",
        "System.Collections.Generic.Stack<T>.Pop()",
        "System.Collections.Generic.Stack<T>.Push(T)",
        "System.Text.RegularExpressions.Regex.Split(string, string)",
        "System.Text.RegularExpressions.Regex.Split(string)",
        "System.ComponentModel.TypeDescriptor.GetConverter(System.Type)",
        "System.ComponentModel.TypeDescriptor.GetProperties(object)",
        "object.Equals(object)",
        "object.GetHashCode()",
        "System.Diagnostics.ActivitySource.StartActivity(string)",
        "System.Diagnostics.Debug.Assert(bool)",
        "System.Diagnostics.Debugger.Break()",
        "System.Diagnostics.DiagnosticListener.DiagnosticListener(string)",
        "System.Diagnostics.FileVersionInfo.FileVersion.get",
        "System.Diagnostics.StackFrame.GetMethod()",
        "System.Type.GetConstructor(System.Type[])",
        "System.Type.GetConstructors()",
        "System.Type.GetConstructors(System.Reflection.BindingFlags)",
        "System.Type.GetEvent(string)",
        "System.Type.GetEvent(string, System.Reflection.BindingFlags)",
        "System.Type.GetEvents()",
        "System.Type.GetEvents(System.Reflection.BindingFlags)",
        "System.Type.GetField(string)",
        "System.Type.GetField(string, System.Reflection.BindingFlags)",
        "System.Type.GetFields()",
        "System.Type.GetFields(System.Reflection.BindingFlags)",
        "System.Type.AssemblyQualifiedName.get",
        "System.Type.Attributes.get",
        "System.Type.BaseType.get",
        "System.Type.ContainsGenericParameters.get",
        "System.Type.DefaultBinder.get",
        "System.Type.FullName.get",
        "System.Type.GenericParameterAttributes.get",
        "System.Type.GenericTypeArguments.get",
        "System.Type.GenericParameterPosition.get",
        "System.Type.GUID.get",
        "System.Type.HasElementType.get",
        "System.Type.IsCOMObject.get",
        "System.Type.IsConstructedGenericType.get",
        "System.Type.IsAbstract.get",
        "System.Type.IsAnsiClass.get",
        "System.Type.IsArray.get",
        "System.Type.IsAutoClass.get",
        "System.Type.IsAutoLayout.get",
        "System.Type.IsByRef.get",
        "System.Type.IsByRefLike.get",
        "System.Type.IsClass.get",
        "System.Type.IsEnum.get",
        "System.Type.IsExplicitLayout.get",
        "System.Type.IsImport.get",
        "System.Type.IsInterface.get",
        "System.Type.IsNestedAssembly.get",
        "System.Type.IsNestedFamANDAssem.get",
        "System.Type.IsNestedFamORAssem.get",
        "System.Type.IsNestedFamily.get",
        "System.Type.IsNested.get",
        "System.Type.IsNestedPrivate.get",
        "System.Type.IsNestedPublic.get",
        "System.Type.IsNotPublic.get",
        "System.Type.IsPointer.get",
        "System.Type.IsPrimitive.get",
        "System.Type.IsPublic.get",
        "System.Type.IsLayoutSequential.get",
        "System.Type.IsSecurityCritical.get",
        "System.Type.IsSecuritySafeCritical.get",
        "System.Type.IsSecurityTransparent.get",
        "System.Type.IsSealed.get",
        "System.Type.IsSerializable.get",
        "System.Type.IsSZArray.get",
        "System.Type.IsSpecialName.get",
        "System.Type.IsTypeDefinition.get",
        "System.Type.IsUnicodeClass.get",
        "System.Type.IsValueType.get",
        "System.Type.IsVariableBoundArray.get",
        "System.Type.IsVisible.get",
        "System.Type.StructLayoutAttribute.get",
        "System.Type.GetInterface(string)",
        "System.Type.GetInterface(string, bool)",
        "System.Type.GetInterfaces()",
        "System.Type.GetMember(string)",
        "System.Type.GetMember(string, System.Reflection.BindingFlags)",
        "System.Type.GetMember(string, System.Reflection.MemberTypes, System.Reflection.BindingFlags)",
        "System.Type.GetMembers()",
        "System.Type.GetMembers(System.Reflection.BindingFlags)",
        "System.Type.GetMethod(string)",
        "System.Type.GetMethod(string, System.Type[])",
        "System.Type.GetMethod(string, System.Reflection.BindingFlags)",
        "System.Type.GetMethods()",
        "System.Type.GetMethods(System.Reflection.BindingFlags)",
        "System.Type.Module.get",
        "System.Type.Namespace.get",
        "System.Type.GetNestedType(string)",
        "System.Type.GetNestedType(string, System.Reflection.BindingFlags)",
        "System.Type.GetNestedTypes()",
        "System.Type.GetNestedTypes(System.Reflection.BindingFlags)",
        "System.Type.GetProperty(string)",
        "System.Type.GetProperty(string, System.Reflection.BindingFlags)",
        "System.Type.GetProperties(System.Reflection.BindingFlags)",
        "System.Type.GetProperties()",
        "System.Type.TypeHandle.get",
        "System.Type.TypeInitializer.get",
        "System.Type.UnderlyingSystemType.get",
        "System.Reflection.Assembly.CodeBase.get",
        "System.Reflection.Assembly.CustomAttributes.get",
        "System.Reflection.Assembly.DefinedTypes.get",
        "System.Reflection.Assembly.EntryPoint.get",
        "System.Reflection.Assembly.EscapedCodeBase.get",
        "System.Reflection.Assembly.ExportedTypes.get",
        "System.Reflection.Assembly.GetTypes()",
        "System.Reflection.Assembly.GetExecutingAssembly()",
        "System.Reflection.Assembly.GlobalAssemblyCache.get",
        "System.Reflection.Assembly.HostContext.get",
        "System.Reflection.Assembly.IsDynamic.get",
        "System.Reflection.Assembly.IsFullyTrusted.get",
        "System.Reflection.Assembly.Location.get",
        "System.Reflection.Assembly.ManifestModule.get",
        "System.Reflection.Assembly.Modules.get",
        "System.Reflection.Assembly.ReflectionOnly.get",
        "System.Reflection.Assembly.SecurityRuleSet.get",
        "System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo, System.Type)",
        "System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo)",
        "System.Attribute.IsDefined(System.Reflection.MemberInfo, System.Type)",
        "System.Reflection.IntrospectionExtensions.GetTypeInfo(System.Type)",
        "System.Reflection.CustomAttributeData.GetCustomAttributes(System.Reflection.MemberInfo)",
        "System.Reflection.MethodBase.IsStatic.get",
        "System.Reflection.MemberInfo.GetCustomAttributes(bool)",
        "System.Reflection.Module.Assembly.get",
        "System.Reflection.Module.FullyQualifiedName.get",
        "System.Reflection.PropertyInfo.PropertyType.get",
        "System.Reflection.Module.ModuleVersionId.get",
        "System.Reflection.Module.Name.get",
        "System.Reflection.Module.ScopeName.get",
        "System.Diagnostics.Trace.WriteLine(string)",
        "System.Enum.GetName(System.Type, object)",
        "System.Enum.IsDefined(System.Type, object)",
        "System.Enum.GetValues(System.Type)",
        "System.IO.MemoryStream.ToArray()",
        "System.IO.StringReader.StringReader(string)",
        "System.GC.Collect()",
        "System.GC.GetTotalMemory(bool)",
        "System.IO.DriveInfo.TotalSize.get",
        "System.IO.DriveInfo.GetDrives()",
        "System.IO.File.AppendAllText(string, string)",
        "System.IO.File.Delete(string)",
        "System.IO.File.ReadAllBytes(string)",
        "System.IO.File.ReadAllText(string)",
        "System.IO.File.WriteAllText(string, string)",
        "System.IO.File.WriteAllBytes(string, byte[])",
        "System.IO.MemoryStream.Write(byte[], int, int)",
        "System.IO.Stream.Flush()",
        "System.IO.Stream.Read(byte[], int, int)",
        "System.IO.Stream.Seek(long, System.IO.SeekOrigin)",
        "System.IO.Stream.Write(byte[], int, int)",
        "System.IO.StreamReader.ReadLine()",
        "System.IO.StreamReader.StreamReader(System.IO.Stream)",
        "System.IO.StreamWriter.WriteLine(string)",
        "System.IO.StreamWriter.StreamWriter(System.IO.Stream)",
        "System.IO.StringReader.ReadToEnd()",
        "System.IO.StringWriter.Write(string)",
        "System.Lazy<T>.Lazy(System.Func<T>)",
        "System.Lazy<T>.Value.get",
        "System.Linq.Enumerable.ToArray<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Net.Dns.GetHostEntry(string)",
        "System.Net.Http.HttpClient.GetAsync(string)",
        "System.Net.Http.HttpClient.GetStringAsync(string)",
        "System.Net.Http.HttpClient.PostAsync(string, System.Net.Http.HttpContent)",
        "System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()",
        "System.Net.Sockets.Socket.Connect(System.Net.EndPoint)",
        "System.Net.Sockets.Socket.ConnectAsync(System.Net.EndPoint)",
        "System.Net.Sockets.Socket.Receive(byte[])",
        "System.Net.Sockets.Socket.Send(byte[])",
        "System.Net.WebClient.DownloadString(string)",
        "System.Random.Next()",
        "System.Random.Next(int)",
        "System.Random.NextDouble()",
        "System.Random.NextInt64()",
        "System.Random.NextInt64(long)",
        "System.Random.NextInt64(long, long)",
        "System.Reflection.Assembly.Load(string)",
        "System.Reflection.Assembly.LoadFrom(string)",
        "System.Reflection.FieldInfo.SetValue(object, object)",
        "System.Reflection.MethodBase.GetCurrentMethod()",
        "System.Reflection.MethodInfo.Invoke(object, object[])",
        "System.Reflection.PropertyInfo.SetValue(object, object)",
        "System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(object)",
        "System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(System.RuntimeTypeHandle)",
        "System.Runtime.GCSettings.IsServerGC.get",
        "System.Runtime.InteropServices.Marshal.AllocHGlobal(System.IntPtr)",
        "System.Runtime.InteropServices.Marshal.FreeHGlobal(System.IntPtr)",
        "System.Runtime.InteropServices.Marshal.StructureToPtr(object, System.IntPtr, bool)",

        "System.Random.Shared.get",
        "System.Security.Cryptography.RandomNumberGenerator.GetBytes(byte[])",
        "System.CodeDom.Compiler.CodeDomProvider.CreateProvider(string)",
        "System.CodeDom.Compiler.CompilerResults.Errors.get",
        "System.Exception.ToString()",

        "System.Text.Json.JsonSerializer.Deserialize",
        "JsonSerializer.Deserialize",
        "System.Text.Json.JsonSerializer.Deserialize<TValue>(string, System.Text.Json.JsonSerializerOptions?)",
        "System.Text.Json.JsonSerializer.Deserialize<TValue>(System.ReadOnlySpan<byte>, System.Text.Json.JsonSerializerOptions?)",

        "System.Text.Json.JsonSerializer.DeserializeAsync",
        "System.Text.Json.JsonSerializer.SerializeAsync",
        "System.Text.StringBuilder.Append(string?)",
        "System.Text.StringBuilder.Append(char)",
        "System.Text.StringBuilder.Append(object)",
        "System.Text.StringBuilder.AppendLine(string)",
        "System.Text.StringBuilder.Clear()",
        "System.Text.StringBuilder.EnsureCapacity(int)",
        "System.Text.StringBuilder.Insert(int, string)",
        "System.Text.StringBuilder.Remove(int, int)",
        "System.Text.StringBuilder.Replace(string, string)",
        "System.Threading.Interlocked.CompareExchange(ref int, int, int)",
        "System.Threading.Interlocked.CompareExchange(ref long, long, long)",
        "System.Threading.Interlocked.CompareExchange(ref object, object, object)",
        "System.Threading.Interlocked.Increment(ref int)",
        "System.Threading.Interlocked.Increment(ref long)",
        "System.Threading.Interlocked.Decrement(ref int)",
        "System.Threading.Interlocked.Decrement(ref long)",
        "System.Threading.Interlocked.Add(ref int, int)",
        "System.Threading.Interlocked.Add(ref long, long)",
        "System.Threading.Interlocked.Exchange(ref int, int)",
        "System.Threading.Interlocked.Exchange(ref long, long)",
        "System.Threading.Interlocked.Exchange(ref object, object)",
        "System.Threading.Monitor.Enter(object)",
        "System.Threading.Monitor.Pulse(object)",
        "System.Threading.Monitor.Wait(object)",
        "System.Threading.Mutex.ReleaseMutex()",
        "System.Threading.Mutex.WaitOne()",
        "System.Threading.SemaphoreSlim.Release()",
        "System.Threading.SemaphoreSlim.Wait()",
        "System.Threading.Tasks.Task.Delay(int)",
        "System.Threading.Tasks.Task.Delay(System.TimeSpan)",
        "System.Threading.Tasks.Task.IsCompleted.get",
        "System.Threading.Tasks.Task.Run(System.Action)",


        "System.Threading.Tasks.Task.Yield()",
        "System.Threading.Thread.CurrentThread.get",
        "System.Threading.Thread.ManagedThreadId.get",
        "System.Threading.Thread.Sleep(int)",
        "System.Threading.Thread.Sleep(System.TimeSpan)",
        "System.Threading.Volatile.Write",
        "System.Type.GetType(string)",
        "System.Type.GetType(string, bool)",
        "System.Type.GetType(string, bool, bool)",
        "System.Xml.Linq.XElement.Add(object)",
        "XElement.Add",
        "System.Xml.Linq.XElement.Load(System.IO.Stream)",
        "System.Xml.Linq.XElement.Save(System.IO.Stream)",
        "System.Xml.Linq.XNode.Remove()",
        "System.Xml.XmlReader.Create(System.IO.Stream)",
        "System.Xml.XmlReader.Read()",
        "System.Xml.XmlWriter.Create(System.IO.Stream)",
        "System.Xml.XmlWriter.WriteStartElement(string)",
        "System.Xml.XmlWriter.WriteString(string)",
        "System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.TryAdd(TKey, TValue)",
        "System.Collections.Concurrent.ConcurrentQueue<T>.Enqueue(T)",
        "System.Collections.Concurrent.ConcurrentQueue<T>.TryDequeue(out T)",
        "System.Collections.Concurrent.BlockingCollection<T>.Add(T)",
        "System.Collections.Concurrent.BlockingCollection<T>.Take()",
        "System.Collections.ObjectModel.ObservableCollection<T>.Add(T)",
        "System.ComponentModel.BackgroundWorker.RunWorkerAsync()",
        "System.Diagnostics.EventLog.WriteEntry(string)",
        "System.Diagnostics.PerformanceCounter.NextValue()",
        "System.Diagnostics.TraceSource.TraceEvent(System.Diagnostics.TraceEventType, int)",
        "System.Diagnostics.FileVersionInfo.GetVersionInfo(string)",
        "System.IO.Compression.ZipFile.CreateFromDirectory(string, string)",
        "System.IO.Compression.ZipFile.ExtractToDirectory(string, string)",
        "System.IO.Pipes.NamedPipeServerStream.WaitForConnection()",
        "System.Net.Mail.SmtpClient.Send(System.Net.Mail.MailMessage)",
        "System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()",
        "System.Net.NetworkInformation.Ping.Send(string)",
        "System.Reflection.Emit.DynamicMethod.DynamicMethod(string, System.Type, System.Type[])",
        "System.Reflection.Emit.ILGenerator.Emit(System.Reflection.Emit.OpCode)",
        "System.Runtime.Caching.MemoryCache.Default.get",
        "System.Runtime.Caching.MemoryCache.Add(string, object, System.DateTimeOffset)",
        "System.Runtime.Caching.MemoryCache.Get(string)",
        "System.Runtime.Loader.AssemblyLoadContext.All.get",
        "System.Runtime.Loader.AssemblyLoadContext.CurrentContextualReflectionContext.get",
        "System.Runtime.Loader.AssemblyLoadContext.Default.get",
        "System.Runtime.Loader.AssemblyLoadContext.EnterContextualReflection()",
        "System.Runtime.Loader.AssemblyLoadContext.EnterContextualReflection(System.Reflection.Assembly?)",
        "System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(System.Reflection.Assembly)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(System.Reflection.AssemblyName)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(string)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromNativeImagePath(string, string?)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(System.IO.Stream)",
        "System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(System.IO.Stream, System.IO.Stream?)",
        "System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(System.IO.Stream)",
        "System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(System.IO.Stream, object)",
        "System.Security.Principal.WindowsIdentity.GetCurrent()",
        "System.Security.SecureString.AppendChar(char)",
        "System.Security.SecureString.Dispose()",
        "System.Threading.CancellationToken.IsCancellationRequested.get",
        "System.Threading.CancellationToken.Register(System.Action)",
        "System.Threading.CancellationToken.ThrowIfCancellationRequested()",
        "System.Threading.CancellationTokenSource.Cancel()",
        "System.Threading.ReaderWriterLockSlim.EnterReadLock()",
        "System.Threading.ReaderWriterLockSlim.ExitReadLock()",
        "System.Threading.SpinWait.SpinOnce()",
        "System.Threading.Timer.Timer(System.Threading.TimerCallback)",
        "System.Threading.Timer.Change(int, int)",
        "System.Timers.Timer.Start()",
        "System.Timers.Timer.Stop()",
        "System.Xml.Xsl.XslCompiledTransform.Load(string)",
        "System.Xml.Xsl.XslCompiledTransform.Transform(string, string)",
        "System.Collections.BitArray.Set(int, bool)",
        "System.Collections.Specialized.NameValueCollection.Add(string, string)",
        "System.IO.DirectoryInfo.Exists.get",
        "System.IO.DirectoryInfo.EnumerateFiles()",
        "System.IO.FileInfo.Length.get",
        "System.IO.FileSystemWatcher.EnableRaisingEvents.set",
        "System.Net.HttpListener.Start()",
        "System.Net.HttpListener.GetContext()",
        "System.Net.Sockets.UdpClient.Receive(ref System.Net.IPEndPoint)",
        "System.Reflection.AssemblyName.GetAssemblyName(string)",
        "System.Security.Cryptography.X509Certificates.X509Store.Open(System.Security.Cryptography.X509Certificates.OpenFlags)",
        "System.Threading.Barrier.SignalAndWait()",
        "System.Threading.CountdownEvent.Signal()",
        "System.Threading.CountdownEvent.Wait()",
        "System.Threading.Tasks.Dataflow.ActionBlock<TInput>.Post(TInput)",
        "System.Threading.Tasks.Parallel.ForEach",
        "System.Threading.Tasks.Parallel.Invoke",
        "System.Windows.Input.ICommand.Execute(object)",
        "Microsoft.Extensions.Logging.ILogger.LogInformation(string)",
        "Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type)",
        "System.IO.BufferedStream.BufferedStream(System.IO.Stream)",
        "System.IO.BufferedStream.Flush()",


        "string.Format(string, object?)",
        "string.Format(string, object?, object?)",
        "string.Format(string, object?, object?, object?)",
        "string.Format(string, params object?[])",












        "Microsoft.Extensions.Configuration.IConfiguration.GetConnectionString(string)",
        "Microsoft.Extensions.Configuration.IConfigurationRoot.Reload()",
        "System.Buffers.ArrayPool<T>.Shared.Rent(int)",
        "System.Buffers.ArrayPool<T>.Shared.Return(T[], bool)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt16BigEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt64BigEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.WriteSingleBigEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.WriteDoubleBigEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.WriteDoubleLittleEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.WriteHalfBigEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.WriteHalfLittleEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt16BigEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt16LittleEndian(System.Span<byte>, short)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt32BigEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt32LittleEndian(System.Span<byte>, int)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt64BigEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteInt64LittleEndian(System.Span<byte>, long)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteSingleBigEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteSingleLittleEndian(System.Span<byte>, float)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteDoubleBigEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteDoubleLittleEndian(System.Span<byte>, double)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteHalfBigEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteHalfLittleEndian(System.Span<byte>, System.Half)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16BigEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt16LittleEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32BigEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32LittleEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64BigEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.TryWriteUInt64LittleEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(System.Span<byte>, ushort)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian(System.Span<byte>, uint)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt64BigEndian(System.Span<byte>, ulong)",
        "System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian(System.Span<byte>, ulong)",
        "System.Buffers.Text.Base64.EncodeToUtf8(System.ReadOnlySpan<byte>, System.Span<byte>, out int, out int)",
        "System.Collections.Generic.LinkedList<T>.AddFirst(T)",
        "System.Collections.Generic.LinkedListNode<T>.Value.set",
        "System.Collections.Generic.SortedDictionary<TKey, TValue>.Add(TKey, TValue)",








        "System.Collections.ObjectModel.KeyedCollection<TKey, TItem>.Remove(TKey)",
        "System.ComponentModel.AddingNewEventArgs.AddingNewEventArgs()",
        "System.ComponentModel.CancelEventArgs.Cancel.get",
        "System.ComponentModel.CancelEventArgs.Cancel.set",
        "System.ComponentModel.INotifyPropertyChanged.PropertyChanged",
        "System.Data.DataTable.NewRow()",
        "System.Data.DataRow.AcceptChanges()",
        "System.Diagnostics.Activity.Current.get",
        "System.Diagnostics.Activity.Current.set",
        "System.Diagnostics.Activity.SetTag(string, object)",
        "System.Diagnostics.DiagnosticListener.Write(string, object)",
        "System.Drawing.Bitmap.Bitmap(int, int)",
        "System.IO.Compression.BrotliStream.BrotliStream(System.IO.Stream, System.IO.Compression.CompressionMode)",
        "System.IO.Compression.DeflateStream.Read(byte[], int, int)",
        "System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(string)",
        "System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.ReadByte(long)",
        "System.Linq.Queryable.Count<TSource>(System.Linq.IQueryable<TSource>)",
        "System.Linq.Queryable.ToList<TSource>(System.Linq.IQueryable<TSource>)",
        "System.Net.Http.Headers.HttpRequestHeaders.Add(string, string)",
        "System.Net.Security.SslStream.AuthenticateAsClientAsync(string)",
        "System.Net.Sockets.Socket.Accept()",
        "System.Net.Sockets.SocketAsyncEventArgs.AcceptSocket.get",
        "System.Net.Sockets.SocketAsyncEventArgs.AcceptSocket.set",
        "System.Reflection.AssemblyName.AssemblyName(string)",
        "System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(string)",
        "System.Resources.ResourceManager.GetString(string)",
        "System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine)",
        "System.Runtime.CompilerServices.ConditionalWeakTable<TKey, TValue>.Add(TKey, TValue)",
        "System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr, System.Runtime.InteropServices.CreateObjectFlags)",
        "System.Runtime.InteropServices.GCHandle.Alloc(object)",
        "System.Runtime.InteropServices.GCHandle.Free()",
        "System.Security.AccessControl.DirectorySecurity.AddAccessRule(System.Security.AccessControl.FileSystemAccessRule)",
        "System.Security.Cryptography.Pkcs.SignedCms.Sign()",
        "System.Security.Cryptography.Xml.SignedXml.ComputeSignature()",
        "System.Security.Cryptography.X509Certificates.X509Certificate2.X509Certificate2(string)",
        "System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase)",
        "System.Speech.Synthesis.SpeechSynthesizer.SpeakAsync(string)",
        "System.Text.Json.Utf8JsonWriter.WriteString(string, string)",
        "System.Threading.AsyncLocal<T>.Value.get",
        "System.Threading.AsyncLocal<T>.Value.set",
        "System.Threading.Channels.Channel.CreateUnbounded<T>()",
        "System.Threading.Channels.ChannelReader<T>.ReadAsync(System.Threading.CancellationToken)",
        "System.Threading.Channels.ChannelWriter<T>.WriteAsync(T, System.Threading.CancellationToken)",
        "System.Threading.LazyInitializer.EnsureInitialized<T>(ref T, System.Func<T>)",
        "System.Transactions.TransactionScope.TransactionScope()",
        "System.Transactions.Transaction.Current.get",
        "Microsoft.Win32.RegistryKey.OpenSubKey(string)",
        "Microsoft.Win32.RegistryKey.GetValue(string)",
        "Microsoft.Win32.RegistryKey.SetValue(string, object)",
        "System.Net.Http.Headers.HttpContentHeaders.ContentLength.get",
        "System.Net.Http.Headers.HttpContentHeaders.ContentLength.set",
        "System.Runtime.InteropServices.SafeHandle.IsInvalid.get",
        "System.Text.Unicode.Utf8.ToUtf16(System.ReadOnlySpan<byte>, System.Span<char>, out int, out int)",
        "System.Threading.Semaphore.Semaphore(int, int)",
        "System.Xml.XmlDocument.LoadXml(string)",
        "System.Xml.XmlNode.SelectSingleNode(string)",
        "System.Xml.Schema.XmlSchemaSet.Compile()",
        "System.Xml.Linq.XDocument.Parse(string)",
        "System.Xml.Linq.XElement.Value.get",
        "System.Xml.Linq.XAttribute.Value.get",
        "System.Xml.Linq.XElement.Attribute(System.Xml.Linq.XName)",
        "System.Xml.Linq.XContainer.Elements()",
        "System.Xml.Linq.XContainer.Descendants()",
        "System.Text.Json.JsonDocument.Parse(string, System.Text.Json.JsonDocumentOptions)",
        "System.Text.Json.JsonElement.GetString()",
        "System.Runtime.Versioning.FrameworkName.FrameworkName(string)",
        "System.Collections.Generic.PriorityQueue<TElement, TPriority>.Enqueue(TElement, TPriority)",
        "System.Collections.Generic.PriorityQueue<TElement, TPriority>.Dequeue()",
        "System.Diagnostics.Metrics.Counter<T>.Add(T, System.Collections.Generic.KeyValuePair<string, object?>)",
        "System.Runtime.InteropServices.MemoryMarshal.Write<T>(System.Span<byte>, ref T)",
        "System.ComponentModel.Component.Dispose()",
        "System.ComponentModel.LicenseManager.Validate(System.Type, object)",
        "System.Configuration.ConfigurationManager.ConnectionStrings.get",
        "System.Data.DataSet.Clear()",
        "System.Diagnostics.Debugger.IsAttached.get",
        "System.Diagnostics.Debugger.Launch()",
        "System.Diagnostics.StackTrace.StackTrace()",
        "System.Diagnostics.Switch.Level.get",
        "System.DirectoryServices.DirectoryEntry.DirectoryEntry(string)",
        "System.GC.GetGeneration(object)",
        "System.GC.KeepAlive(object)",
        "System.GC.KeepAlive(object?)",
        "System.IO.BinaryReader.ReadBoolean()",
        "System.IO.BinaryWriter.Write(string)",
        "System.IO.Directory.EnumerateDirectories(string)",
        "System.IO.FileStream.FileStream(string, System.IO.FileMode)",
        "System.IO.Pipelines.PipeReader.ReadAsync(System.Threading.CancellationToken)",
        "System.IO.Pipelines.PipeWriter.WriteAsync(System.ReadOnlyMemory<byte>, System.Threading.CancellationToken)",
        "System.Linq.ParallelEnumerable.ForAll<TSource>(System.Linq.ParallelQuery<TSource>, System.Action<TSource>)",
        "System.Linq.ParallelQuery<TSource>.ToList()",
        "System.Management.ManagementObjectSearcher.ManagementObjectSearcher(string)",
        "System.Net.CredentialCache.DefaultCredentials.get",
        "System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)",
        "System.Net.ServicePointManager.SecurityProtocol.get",
        "System.Net.ServicePointManager.SecurityProtocol.set",
        "System.Runtime.InteropServices.Marshal.GetLastWin32Error()",
        "System.Runtime.Serialization.FormatterServices.GetUninitializedObject(System.Type)",
        "System.Threading.ThreadLocal<T>.ThreadLocal(System.Func<T>)",
        "System.Threading.ThreadLocal<T>.Value.get",


        "System.Collections.Generic.IEnumerator<T>.MoveNext()",
        "System.Collections.ObjectModel.Collection<T>.InsertItem(int, T)",
        "System.Collections.ObjectModel.Collection<T>.SetItem(int, T)",
        "System.ComponentModel.INotifyCollectionChanged.CollectionChanged",
        "System.Delegate.DynamicInvoke(object[])",

        "System.GC.SuppressFinalize(object)",

        "System.IServiceProvider.GetService(System.Type)",
        "System.IO.File.Copy(string, string)",
        "System.IO.File.Move(string, string)",
        "System.IO.File.OpenRead(string)",
        "System.IO.File.OpenWrite(string)",
        "System.IO.File.ReadAllLines(string)",
        "System.IO.Stream.Close()",
        "System.IO.Stream.CopyToAsync(System.IO.Stream)",
        "System.IO.TextReader.Peek()",
        "System.IO.TextReader.ReadToEnd()",
        "System.IO.TextWriter.Flush()",
        "System.IO.TextWriter.Write(char)",
        "System.Net.Http.HttpContent.ReadAsStringAsync()",
        "System.Net.Http.HttpContent.ReadAsByteArrayAsync()",
        "System.Text.Encoding.Default.get",
        "System.Threading.Tasks.Task.ContinueWith(System.Action<System.Threading.Tasks.Task>)",
        "System.Threading.Tasks.Task.Wait()",
        "System.Threading.Tasks.Task<TResult>.Result.get",


        "System.Array.Clear(System.Array, int, int)",
        "System.Array.ConstrainedCopy(System.Array, int, System.Array, int, int)",
        "System.Array.Copy(System.Array, System.Array, int)",
        "System.Array.Copy(System.Array, int, System.Array, int, int)",
        "System.Array.CopyTo(System.Array, int)",
        "System.Array.Clear(System.Array)",
        "System.Array.Fill<T>(T[], T)",
        "System.Array.Fill<T>(T[], T, int, int)",
        "System.Span<T>.Clear()",
        "System.Span<T>.CopyTo(System.Span<T>)",
        "System.Span<T>.Fill(T)",
        "System.Span<T>.TryCopyTo(System.Span<T>)",
        "System.MemoryExtensions.Reverse<T>(System.Span<T>)",
        "System.Array.Resize<T>(ref T[], int)",
        "System.Array.Reverse<T>(T[])",
        "System.Array.Reverse<T>(T[], int, int)",
        "System.Array.Sort<T>(T[], System.Collections.Generic.IComparer<T>?)",
        "System.Array.Sort<T>(T[], int, int, System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Clear()",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Remove(TKey)",
        "System.Collections.Generic.HashSet<T>.Add(T)",
        "System.Collections.Generic.HashSet<T>.Clear()",
        "System.Collections.Generic.HashSet<T>.Remove(T)",
        "System.Collections.Generic.List<T>.AddRange(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.InsertRange(int, System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Generic.List<T>.RemoveAll(System.Predicate<T>)",
        "System.Collections.Generic.List<T>.RemoveAt(int)",
        "System.Collections.Generic.List<T>.RemoveRange(int, int)",
        "System.Collections.Generic.List<T>.Reverse()",
        "System.Collections.Generic.List<T>.Sort()",
        "System.Collections.Generic.List<T>.Sort(System.Comparison<T>)",
        "System.Collections.Generic.List<T>.Sort(System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.List<T>.Sort(int, int, System.Collections.Generic.IComparer<T>?)",
        "System.Collections.Generic.Queue<T>.Clear()",
        "System.Collections.Generic.Stack<T>.Clear()",
        "System.Exception.Source.set",


        "System.Activator.CreateInstanceFrom(string, string)",
        "System.Array.Sort<T>(T[], System.Comparison<T>)",
        "System.Collections.Concurrent.ConcurrentBag<T>.Add(T)",
        "System.Collections.Concurrent.ConcurrentBag<T>.TryTake(out T)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.TryAdd(TKey, TValue)",
        "System.Collections.Generic.Dictionary<TKey, TValue>.Values.CopyTo(TValue[], int)",
        "System.Collections.Generic.ICollection<T>.Add(T)",
        "System.Collections.Generic.ICollection<T>.Clear()",
        "System.Collections.Generic.ICollection<T>.Remove(T)",
        "System.Collections.Generic.IList<T>.Insert(int, T)",
        "System.Collections.Generic.IList<T>.RemoveAt(int)",
        "System.Collections.Generic.SortedSet<T>.Add(T)",
        "System.ComponentModel.EventHandlerList.AddHandler(object, System.Delegate)",
        "System.HashCode.Add<T>(T)",
        "System.IO.DirectoryInfo.Create()",
        "System.IO.DirectoryInfo.Delete()",
        "System.IO.FileInfo.CopyTo(string)",
        "System.IO.FileInfo.Delete()",
        "System.IO.Stream.ReadAsync(byte[], int, int, System.Threading.CancellationToken)",
        "System.IO.Stream.WriteAsync(byte[], int, int, System.Threading.CancellationToken)",
        "System.IO.StreamReader.StreamReader(string)",
        "System.IO.StreamWriter.StreamWriter(string)",
        "System.Text.StringBuilder.AppendJoin(string, object[])",
        "System.Threading.Monitor.TryEnter(object)",


        "System.Xml.Linq.XContainer.Add(object)",
        "XContainer.Add",


        "System.IO.MemoryStream.MemoryStream()",

        "System.Text.Json.JsonSerializer.Serialize",

        "System.Security.Cryptography.RandomNumberGenerator.Fill(byte[])",



























    };

    public static readonly HashSet<string> KnownFreshOwnedArrayReturningMembers = new HashSet<string>(StringComparer.Ordinal)
    {
    };

    public static readonly HashSet<string> KnownPureBCLMembers = new HashSet<string>(StringComparer.Ordinal)
    {
        "System.Collections.Generic.HashSet<T>.IsSubsetOf(System.Collections.Generic.IEnumerable<T>)",


        "System.Collections.Immutable.ImmutableList<T>.Add(T)",
        "System.Collections.Immutable.ImmutableList<T>.Count.get",
        "System.Collections.Immutable.ImmutableList<T>.SetItem(int, T)",
        "System.Collections.Immutable.ImmutableList<T>.this[int].get",
        "System.Collections.Immutable.ImmutableList.Create<T>(params T[])",
        "System.Collections.Immutable.ImmutableArray.Create<T>()",
        "System.Collections.Immutable.ImmutableArray.Create<T>(params T[])",
        "System.Collections.Immutable.ImmutableArray.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<TSource, TResult>(System.Collections.Immutable.ImmutableArray<TSource>, System.Func<TSource, TResult>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<TSource, TArg, TResult>(System.Collections.Immutable.ImmutableArray<TSource>, System.Func<TSource, TArg, TResult>, TArg)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<TSource, TResult>(System.Collections.Immutable.ImmutableArray<TSource>, int, int, System.Func<TSource, TResult>)",
        "System.Collections.Immutable.ImmutableArray.CreateRange<TSource, TArg, TResult>(System.Collections.Immutable.ImmutableArray<TSource>, int, int, System.Func<TSource, TArg, TResult>, TArg)",
        "System.Collections.Immutable.ImmutableList.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEqualityComparer<TKey>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableDictionary.CreateRange<TKey, TValue>(System.Collections.Generic.IEqualityComparer<TKey>, System.Collections.Generic.IEqualityComparer<TValue>, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<TKey, TValue>>)",
        "System.Collections.Immutable.ImmutableHashSet.CreateRange<T>(System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableHashSet.CreateRange<T>(System.Collections.Generic.IEqualityComparer<T>, System.Collections.Generic.IEnumerable<T>)",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Add(T)",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Clear()",
        "System.Collections.Immutable.ImmutableHashSet<T>.System.Collections.Immutable.IImmutableSet<T>.Remove(T)",
        "System.Collections.Immutable.ImmutableQueue<T>.Enqueue(T)",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Clear()",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Dequeue()",
        "System.Collections.Immutable.ImmutableQueue<T>.System.Collections.Immutable.IImmutableQueue<T>.Enqueue(T)",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Clear()",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Pop()",
        "System.Collections.Immutable.ImmutableStack<T>.System.Collections.Immutable.IImmutableStack<T>.Push(T)",





        "System.Linq.Enumerable.All<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)",
        "System.Linq.Enumerable.Any<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Count<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.FirstOrDefault<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Select<TSource, TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TResult>)",
        "System.Linq.Enumerable.SequenceEqual<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Where<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)",





        "System.Linq.Enumerable.Contains<TSource>(System.Collections.Generic.IEnumerable<TSource>, TSource)",

        "System.Numerics.BigInteger.Add(System.Numerics.BigInteger, System.Numerics.BigInteger)",
        "System.Numerics.Complex.Complex(double, double)",
        "System.Numerics.Complex.Abs(System.Numerics.Complex)",

        "System.Security.Cryptography.Aes.DecryptCbc(byte[], byte[], byte[], System.Security.Cryptography.PaddingMode)",
        "System.Security.Cryptography.Aes.EncryptCbc(byte[], byte[], byte[], System.Security.Cryptography.PaddingMode)",
        "System.Security.Cryptography.MD5.ComputeHash(byte[])",
        "System.Security.Cryptography.SHA256.ComputeHash(byte[])",

        "System.StringComparer.InvariantCultureIgnoreCase.Compare(string, string)",
        "System.StringComparer.Ordinal.Equals(string, string)",


        "System.Type.Equals(object)",
        "System.Type.Equals(System.Type)",
        "System.Type.GetHashCode()",



        "System.Buffers.Text.Utf8Parser.TryParse(System.ReadOnlySpan<byte>, out int, out int)",
        "System.Drawing.Color.FromArgb(int, int, int, int)",
        "System.Drawing.Point.Point(int, int)",
        "System.Globalization.StringInfo.ParseCombiningCharacters(string)",
        "System.Linq.IQueryable<T>.Expression.get",
        "System.Linq.Queryable.Where<TSource>(System.Linq.IQueryable<TSource>, System.Linq.Expressions.Expression<System.Func<TSource, bool>>)",
        "System.Memory<T>.Span.get",
        "System.Numerics.Matrix4x4.CreateRotationX(float)",
        "System.Numerics.Vector3.Normalize(System.Numerics.Vector3)",
        "System.Reflection.Metadata.MetadataReader.GetString(System.Reflection.Metadata.StringHandle)",
        "System.Runtime.Intrinsics.X86.Sse.Add(System.Runtime.Intrinsics.Vector128<float>, System.Runtime.Intrinsics.Vector128<float>)",
        "System.Runtime.Intrinsics.X86.Avx2.Multiply(System.Runtime.Intrinsics.Vector256<double>, System.Runtime.Intrinsics.Vector256<double>)",
        "System.Diagnostics.CounterSample.Calculate(System.Diagnostics.CounterSample, System.Diagnostics.CounterSample)",
        "System.Numerics.Plane.Normalize(System.Numerics.Plane)",
        "System.Reflection.Emit.Label.Equals(object)",
        "System.IO.Hashing.Crc32.Hash(System.ReadOnlySpan<byte>)",
        "System.Runtime.InteropServices.MemoryMarshal.Read<T>(System.ReadOnlySpan<byte>)",
        "System.HashCode.Combine<T1, T2>(T1, T2)",
        "System.IO.Pipelines.Pipe.Pipe(System.IO.Pipelines.PipeOptions)",
        "System.Linq.Expressions.Expression.Constant(object)",
        "System.Linq.Expressions.Expression.Call(System.Reflection.MethodInfo, System.Linq.Expressions.Expression[])",
        "System.Linq.ParallelEnumerable.AsParallel<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.MemoryExtensions.BinarySearch<T>(System.ReadOnlySpan<T>, T)",
        "System.Numerics.Quaternion.Quaternion(float, float, float, float)",
        "System.Reflection.Emit.OpCodes.Ldarg_0.get",
        "System.Runtime.CompilerServices.IsExternalInit",
        "System.Runtime.Serialization.DataContractAttribute.DataContractAttribute()",
        "System.Security.AllowPartiallyTrustedCallersAttribute.AllowPartiallyTrustedCallersAttribute()",
        "System.Delegate.Combine(System.Delegate, System.Delegate)",
        "System.Delegate.Remove(System.Delegate, System.Delegate)",
        "System.Linq.Enumerable.ElementAt<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Linq.Enumerable.First<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Last<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Single<TSource>(System.Collections.Generic.IEnumerable<TSource>)",
        "System.Linq.Enumerable.Skip<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Linq.Enumerable.Take<TSource>(System.Collections.Generic.IEnumerable<TSource>, int)",
        "System.Runtime.InteropServices.Marshal.SizeOf<T>()",
        "System.FormattableString.Format.get",
        "System.FormattableString.Invariant(System.FormattableString)",
        "System.FormattableString.ToString(System.IFormatProvider)",

    };
}
