using System.Collections.Immutable;

namespace SharpProof.Analyzer;

internal static class AnalyzerGeneratedCodePolicy
{
    private static readonly ImmutableArray<string> GeneratedPathSuffixes = [
        ".g.cs",
        ".g.i.cs",
        ".generated.cs",
        ".designer.cs"];
    private static readonly ImmutableArray<string> GeneratedHeaderTokens = [
        "<auto-generated/>",
        "<auto-generated />",
        "<autogenerated/>",
        "<autogenerated />"];

    internal static bool IsGenerated(
        ISymbol symbol,
        SyntaxTree tree,
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        var generated = GetGeneratedKind(
            tree,
            compilation,
            cancellationToken);
        if (generated == GeneratedKind.MarkedGenerated)
        {
            return true;
        }

        if (generated == GeneratedKind.NotGenerated)
        {
            return false;
        }

        return HasGeneratedPath(tree.FilePath) ||
            HasGeneratedHeader(tree, cancellationToken) ||
            HasGeneratedCodeAttribute(symbol, compilation);
    }

    internal static bool IsGenerated(
        SyntaxTree tree,
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        var generated = GetGeneratedKind(tree, compilation, cancellationToken);
        if (generated == GeneratedKind.MarkedGenerated)
        {
            return true;
        }

        if (generated == GeneratedKind.NotGenerated)
        {
            return false;
        }

        return HasGeneratedPath(tree.FilePath) ||
            HasGeneratedHeader(tree, cancellationToken);
    }

    private static GeneratedKind GetGeneratedKind(
        SyntaxTree tree,
        Compilation compilation,
        CancellationToken cancellationToken)
    {
        return compilation.Options.SyntaxTreeOptionsProvider?
            .IsGenerated(tree, cancellationToken) ?? GeneratedKind.Unknown;
    }

    private static bool HasGeneratedPath(string path)
    {
        return GeneratedPathSuffixes.Any(suffix =>
            path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool HasGeneratedHeader(
        SyntaxTree tree,
        CancellationToken cancellationToken)
    {
        foreach (var trivia in tree.GetRoot(cancellationToken)
                     .GetLeadingTrivia())
        {
            if (trivia.IsKind(SyntaxKind.WhitespaceTrivia) ||
                trivia.IsKind(SyntaxKind.EndOfLineTrivia))
            {
                continue;
            }

            return trivia.IsKind(SyntaxKind.SingleLineCommentTrivia) ||
                trivia.IsKind(SyntaxKind.MultiLineCommentTrivia)
                    ? IsExactGeneratedHeader(trivia.ToString())
                    : false;
        }
        return false;
    }

    private static bool IsExactGeneratedHeader(string comment)
    {
        var body = comment.StartsWith("//", StringComparison.Ordinal)
            ? comment.Substring(2)
            : comment.StartsWith("/*", StringComparison.Ordinal) &&
              comment.EndsWith("*/", StringComparison.Ordinal)
                ? comment.Substring(2, comment.Length - 4)
                : string.Empty;
        body = body.Trim();
        return GeneratedHeaderTokens.Any(token => string.Equals(
            body,
            token,
            StringComparison.OrdinalIgnoreCase));
    }

    private static bool HasGeneratedCodeAttribute(
        ISymbol symbol,
        Compilation compilation)
    {
        var generatedCode = compilation.GetTypeByMetadataName(
            FrameworkTypeMetadataNames.GeneratedCodeAttribute);
        if (generatedCode == null)
        {
            return false;
        }

        var scopes = new List<ISymbol> { symbol };
        if (symbol is IMethodSymbol { AssociatedSymbol: { } associated })
        {
            scopes.Add(associated);
        }
        for (var type = symbol.ContainingType;
             type != null;
             type = type.ContainingType)
        {
            scopes.Add(type);
        }

        foreach (var scope in scopes)
        {
            if (scope.GetAttributes().Any(attribute =>
                    SymbolEqualityComparer.Default.Equals(
                        attribute.AttributeClass?.OriginalDefinition,
                        generatedCode.OriginalDefinition)))
            {
                return true;
            }
        }

        return false;
    }
}
