// <auto-generated>
// Generated by scripts/Generate-AnalyzerDiagnosticCatalog.ps1 from
// SharpProof.Analyzer.Core/AnalyzerDiagnostic.catalog.json.
// Declarative diagnostic projections only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.Analyzer;

internal static class AnalyzerDiagnosticCatalog
{
    internal static (string Argument, string Reason) DescribeIntrinsicViolation(
        ContractBindingFailure failure, bool isOld)
    {
        return (failure, isOld) switch
        {
            (ContractBindingFailure.NestedOld, true) => (
                "<nesting>",
                "Contract.Old cannot be nested inside Contract.Old"),
            (ContractBindingFailure.NestedOld, false) => (
                "<nesting>",
                "Contract.Result cannot be nested inside Contract.Old"),
            (ContractBindingFailure.InvalidIntrinsicSignature, true) => (
                "<signature>",
                "expected exactly one value argument"),
            (ContractBindingFailure.InvalidIntrinsicSignature, false) => (
                "<signature>",
                "expected a result type matching the callable return type"),
            _ => ("<placement>",
                "expected use inside Contract.Ensures")
        };
    }

    internal static string DescribePlacement(ContractClausePlacement placement)
    {
        return placement switch
        {
            ContractClausePlacement.Conditional =>
                "expected an unconditional prologue statement",
            ContractClausePlacement.Unreachable =>
                "expected a reachable prologue statement",
            ContractClausePlacement.Late =>
                "expected the clause before every non-contract statement",
            _ => "expected a direct prologue statement"
        };
    }
}
