// <auto-generated>
// Generated by scripts/Generate-DeclarativeModels.ps1 from
// SharpProof.DeclarativeModels.catalog.json.
// Declarative record storage only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Analyzer;

internal sealed partial record EffectClaimEvaluation(
    EffectEvaluationContractKind Kind,
    ImmutableArray<AttributeData> Attributes,
    EffectEvaluationOutcome Outcome,
    EffectEvaluationReason Reason,
    EffectEvaluationCertainty Certainty,
    string Evidence,
    EffectDirectWitness? Witness,
    EffectClaimConstraint Constraint,
    DiagnosticDescriptor? Diagnostic,
    Location DiagnosticLocation,
    object[] DiagnosticArguments
);

internal sealed partial record EffectClaimConstraint(
    EffectContractKind Effects,
    EffectContractCapabilityKind Capabilities,
    ImmutableArray<INamedTypeSymbol> ExceptionTypes
);

internal readonly partial record struct LanguageSubsetDecision(
    bool IsSupported,
    LanguageSubsetAbstentionReason Reason,
    OperationKind? OperationKind
);

internal readonly partial record struct RequiresCallSiteCandidate(
    IOperation Operation,
    IMethodSymbol TargetMethod,
    IOperation? Instance,
    ImmutableArray<IArgumentOperation> Arguments,
    ImmutableDictionary<int, IOperation> ExplicitArguments,
    bool CanReplay,
    ManagedFlowResult? Flow,
    ManagedFlowStatus FlowStatus
);

internal sealed partial class SharpProofAnalyzerEngine
{
    private readonly partial record struct AdvisoryActivation(
        bool RequiresSymbolAnalysis,
        bool RequiresOperationAnalysis,
        bool RequiresFullOperationAnalysis
    );
}

internal static partial class AnalyzerFeaturePipeline
{
    private readonly partial record struct MethodSelection(
        ContractSelectionFeatures Features,
        bool IsSuppressed
    );
}

internal static partial class RequiresCallSiteAnalyzer
{
    private readonly partial record struct ClauseEvaluation(
        bool? Value,
        IrTerm Condition
    );
}

internal sealed partial class RequiresCallSiteDiscovery
{
    private readonly partial record struct RequiresCallTarget(
        IMethodSymbol TargetMethod,
        IOperation? Instance,
        ImmutableArray<IArgumentOperation> Arguments,
        ImmutableDictionary<int, IOperation> ExplicitArguments,
        bool CanReplay
    );
}

internal static partial class RequiresCallSiteTreeAnalyzer
{
    private readonly partial record struct NestedCallable(
        IMethodSymbol Method,
        SyntaxNode Declaration,
        IFlowAnonymousFunctionOperation? AnonymousFunction,
        bool IsExpressionTree
    );
}
