// <auto-generated>
// Generated by scripts/Generate-ProjectionCatalog.ps1 from
// SharpProof.Projection.catalog.json.
// Declarative projection tables only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Analyzer;

internal static class EffectEvaluationProjections
{
    internal static (EffectEvaluationOutcome Outcome, EffectEvaluationReason Reason, EffectEvaluationCertainty Certainty) Classify(
        bool established,
        bool violated,
        bool valid,
        bool complete,
        bool trusted,
        EffectEvaluationReason incompleteReason
    )
    {
        return (established, violated, valid, complete, trusted) switch
        {
            (true, _, _, _, true) => (EffectEvaluationOutcome.Proven, EffectEvaluationReason.None, EffectEvaluationCertainty.TrustedCompleteBoundary),
            (true, _, _, _, _) => (EffectEvaluationOutcome.Proven, EffectEvaluationReason.None, EffectEvaluationCertainty.CompleteMayEffectSummary),
            (_, true, _, _, _) => (EffectEvaluationOutcome.Refuted, EffectEvaluationReason.None, EffectEvaluationCertainty.DefiniteViolation),
            (_, _, false, _, _) => (EffectEvaluationOutcome.Unknown, EffectEvaluationReason.UnsupportedContract, EffectEvaluationCertainty.Unavailable),
            (_, _, _, _, true) => (EffectEvaluationOutcome.Unknown, complete ? EffectEvaluationReason.EffectContractNotEstablished : incompleteReason, EffectEvaluationCertainty.TrustedCompleteBoundary),
            (_, _, _, false, _) => (EffectEvaluationOutcome.Unknown, incompleteReason, EffectEvaluationCertainty.IncompleteMayEffectSummary),
            _ => (EffectEvaluationOutcome.Unknown, EffectEvaluationReason.EffectContractNotEstablished, EffectEvaluationCertainty.CompleteMayEffectSummary)
        };
    }

    internal static EffectEvaluationReason MapIncompleteReason(
        EffectAnalysisIncompleteReason reason
    )
    {
        return ((reason & (EffectAnalysisIncompleteReason.BlockBudgetExceeded | EffectAnalysisIncompleteReason.OperationBudgetExceeded)) != 0, (reason & EffectAnalysisIncompleteReason.CyclicControlFlow) != 0) switch
        {
            (true, _) => EffectEvaluationReason.ResourceLimit,
            (_, true) => EffectEvaluationReason.UnsupportedBody,
            _ => EffectEvaluationReason.EffectSummaryIncomplete
        };
    }
}
