// <auto-generated>
// Generated by scripts/Generate-DiagnosticDescriptors.ps1 from
// eng/diagnostics/diagnostic-descriptors.v1.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.ContractForValidation;

internal static class ContractForDiagnosticDescriptors
{

    internal static readonly DiagnosticDescriptor InvalidTarget = new(
        id: "SPCF0001",
        title: "Invalid ContractFor target",
        messageFormat: "Contract companion '{0}' does not identify one resolvable named target type",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0001",
        customTags: []);

    internal static readonly DiagnosticDescriptor DuplicateCompanion = new(
        id: "SPCF0002",
        title: "Duplicate ContractFor companion",
        messageFormat: "Target type '{0}' has multiple ContractFor companions; exactly one is required",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0002",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidCompanionType = new(
        id: "SPCF0003",
        title: "Invalid ContractFor companion type",
        messageFormat: "Contract companion '{0}' must be a static class whose generic arity and constraints exactly match target '{1}'",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0003",
        customTags: []);

    internal static readonly DiagnosticDescriptor MissingMember = new(
        id: "SPCF0004",
        title: "Missing ContractFor member",
        messageFormat: "Target method '{0}' has no exact ordinary companion member in '{1}'",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0004",
        customTags: []);

    internal static readonly DiagnosticDescriptor SignatureMismatch = new(
        id: "SPCF0005",
        title: "ContractFor member signature mismatch",
        messageFormat: "Companion method '{0}' does not exactly match a target overload, including receiver, generic constraints, ref kinds, nullability, and return type",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0005",
        customTags: []);

    internal static readonly DiagnosticDescriptor AmbiguousMember = new(
        id: "SPCF0006",
        title: "Ambiguous ContractFor member",
        messageFormat: "Companion mapping for method '{0}' is ambiguous",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0006",
        customTags: []);

    internal static readonly DiagnosticDescriptor BodyRequired = new(
        id: "SPCF0007",
        title: "ContractFor member body required",
        messageFormat: "Companion method '{0}' must have a compiler-bound source body",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0007",
        customTags: []);

    internal static readonly DiagnosticDescriptor InvalidClausePlacement = new(
        id: "SPCF0008",
        title: "Invalid ContractFor clause placement",
        messageFormat: "Contract.{0} in companion method '{1}' has invalid placement: {2}",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Validates compiler-bound ContractFor companion declarations without textual signature reconstruction.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0008",
        customTags: []);

    internal static readonly DiagnosticDescriptor SelfTarget = new(
        id: "SPCF0009",
        title: "ContractFor companion targets itself",
        messageFormat: "Contract companion '{0}' cannot target itself",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Rejects ContractFor relationships whose companion and target are the same type.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0009",
        customTags: []);

    internal static readonly DiagnosticDescriptor CyclicRelationship = new(
        id: "SPCF0010",
        title: "Cyclic ContractFor relationship",
        messageFormat: "Contract companion '{0}' targets '{1}' in a ContractFor cycle",
        category: "SharpProof.ContractFor.Usage",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "Rejects ContractFor relationships that participate in a cycle of companion and target types.",
        helpLinkUri: "https://github.com/alexyorke/SharpProof/blob/master/docs/diagnostic-examples.md#spcf0010",
        customTags: []);

    internal static readonly ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics = [
        InvalidTarget,
        DuplicateCompanion,
        InvalidCompanionType,
        MissingMember,
        SignatureMismatch,
        AmbiguousMember,
        BodyRequired,
        InvalidClausePlacement,
        SelfTarget,
        CyclicRelationship
    ];
}
