global using System.Collections.Immutable;
global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.RegularExpressions;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using Microsoft.CodeAnalysis.FlowAnalysis;
global using Microsoft.CodeAnalysis.Operations;
global using Microsoft.CodeAnalysis.Text;
global using SharpProof.ProofCore.Collections;
global using SharpProof.Identity;
global using SharpProof.ProofCore.Purity;
global using SharpProof.ProofCore.Smt;
global using SharpProof.Symbolic.Ir;
global using SharpProof.Symbolic.Smt;
global using ExceptionCategories = SharpProof.Symbolic.SymbolicRuntimeExceptionFacts.ExceptionCategories;
global using ExceptionTypes = SharpProof.Symbolic.SymbolicRuntimeExceptionFacts.ExceptionTypes;
