<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\SharpProof.PackageMetadata.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NuspecFile>SharpProof.nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>SharpProof</PackageId>
    <NoPackageAnalysis>true</NoPackageAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Attributes\SharpProof.Attributes.csproj"
                      PrivateAssets="all"
                      TreatAsPackageReference="false" />
    <ProjectReference Include="..\SharpProof.CompilerCollector\SharpProof.CompilerCollector.csproj"
                      ReferenceOutputAssembly="false"
                      SkipGetTargetFrameworkProperties="true"
                      PrivateAssets="all"
                      TreatAsPackageReference="false" />
    <ProjectReference Include="..\SharpProof.Analyzer\SharpProof.Analyzer.csproj"
                      ReferenceOutputAssembly="false"
                      SkipGetTargetFrameworkProperties="true"
                      PrivateAssets="all"
                      TreatAsPackageReference="false" />
    <ProjectReference Include="..\SharpProof.ContractForGenerator\SharpProof.ContractForGenerator.csproj"
                      ReferenceOutputAssembly="false"
                      SkipGetTargetFrameworkProperties="true"
                      PrivateAssets="all"
                      TreatAsPackageReference="false" />
  </ItemGroup>
  <Target Name="_SharpProofPrepareNuspecProperties"
          BeforeTargets="GenerateNuspec">
    <PropertyGroup>
      <NuspecProperties>version=$(SharpProofPackageVersion);configuration=$(Configuration);repositorycommit=$(RepositoryCommit);authors=$(Authors);license=$(PackageLicenseExpression);readme=$(PackageReadmeFile);copyright=$(PackageCopyright);projecturl=$(PackageProjectUrl);repositorytype=$(RepositoryType);repositoryurl=$(RepositoryUrl)</NuspecProperties>
    </PropertyGroup>
  </Target>
</Project>
