// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable
namespace SharpProof.CompilerArtifact;

internal static class CompilerCallableProjections
{
    internal static ITypeSymbol? GetVariableSource(
        BoundContractVariable variable,
        BoundMethodContracts contracts
    )
    {
        return variable.Role switch
        {
            BoundContractVariableRole.Parameter when variable.Symbol is IParameterSymbol parameter => parameter.Type,
            BoundContractVariableRole.Receiver => variable.Symbol as ITypeSymbol,
            BoundContractVariableRole.Result => contracts.Target.ReturnType,
            _ => null
        };
    }

    internal static string GetModelLabel(
        BoundContractVariable variable
    )
    {
        return variable.Role switch
        {
            BoundContractVariableRole.Parameter => "parameter:" + variable.Ordinal.ToString(CultureInfo.InvariantCulture),
            BoundContractVariableRole.Receiver => "receiver",
            BoundContractVariableRole.Result => "result",
            BoundContractVariableRole.PreState => "pre:" + (variable.CurrentStateVariable?.Value ?? -1).ToString(CultureInfo.InvariantCulture),
            _ => "variable:" + variable.Variable.Value.ToString(CultureInfo.InvariantCulture)
        };
    }
}
