// <auto-generated>
// Generated by scripts/Generate-CompilerArtifactModel.ps1 from
// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.
// Output: CompilerWireMappings.generated.cs.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.CompilerArtifact;

internal static partial class CompilerOptionWireMappings
{
    internal static CompilerOutputKind Map(OutputKind value)
    {
        return value switch
        {
            OutputKind.ConsoleApplication => CompilerOutputKind.ConsoleApplication,
            OutputKind.WindowsApplication => CompilerOutputKind.WindowsApplication,
            OutputKind.DynamicallyLinkedLibrary => CompilerOutputKind.DynamicallyLinkedLibrary,
            OutputKind.NetModule => CompilerOutputKind.NetModule,
            OutputKind.WindowsRuntimeMetadata => CompilerOutputKind.WindowsRuntimeMetadata,
            OutputKind.WindowsRuntimeApplication => CompilerOutputKind.WindowsRuntimeApplication,
            _ => throw Unsupported(nameof(OutputKind), value)
        };
    }

    internal static CompilerOptimizationLevel Map(OptimizationLevel value)
    {
        return value switch
        {
            OptimizationLevel.Debug => CompilerOptimizationLevel.Debug,
            OptimizationLevel.Release => CompilerOptimizationLevel.Release,
            _ => throw Unsupported(nameof(OptimizationLevel), value)
        };
    }

    internal static CompilerPlatform Map(Platform value)
    {
        return value switch
        {
            Platform.AnyCpu => CompilerPlatform.AnyCpu,
            Platform.AnyCpu32BitPreferred => CompilerPlatform.AnyCpu32BitPreferred,
            Platform.Arm => CompilerPlatform.Arm,
            Platform.Arm64 => CompilerPlatform.Arm64,
            Platform.Itanium => CompilerPlatform.Itanium,
            Platform.X64 => CompilerPlatform.X64,
            Platform.X86 => CompilerPlatform.X86,
            _ => throw Unsupported(nameof(Platform), value)
        };
    }

    internal static CompilerNullableContext Map(NullableContextOptions value)
    {
        return value switch
        {
            NullableContextOptions.Disable => CompilerNullableContext.Disable,
            NullableContextOptions.Warnings => CompilerNullableContext.Warnings,
            NullableContextOptions.Annotations => CompilerNullableContext.Annotations,
            NullableContextOptions.Enable => CompilerNullableContext.Enable,
            _ => throw Unsupported(nameof(NullableContextOptions), value)
        };
    }

    internal static CompilerMetadataImportOptions Map(MetadataImportOptions value)
    {
        return value switch
        {
            MetadataImportOptions.Public => CompilerMetadataImportOptions.Public,
            MetadataImportOptions.Internal => CompilerMetadataImportOptions.Internal,
            MetadataImportOptions.All => CompilerMetadataImportOptions.All,
            _ => throw Unsupported(nameof(MetadataImportOptions), value)
        };
    }

    internal static CompilerReportDiagnostic Map(ReportDiagnostic value)
    {
        return value switch
        {
            ReportDiagnostic.Default => CompilerReportDiagnostic.Default,
            ReportDiagnostic.Error => CompilerReportDiagnostic.Error,
            ReportDiagnostic.Warn => CompilerReportDiagnostic.Warn,
            ReportDiagnostic.Info => CompilerReportDiagnostic.Info,
            ReportDiagnostic.Hidden => CompilerReportDiagnostic.Hidden,
            ReportDiagnostic.Suppress => CompilerReportDiagnostic.Suppress,
            _ => throw Unsupported(nameof(ReportDiagnostic), value)
        };
    }

    internal static CompilerAssemblyIdentityComparer Map(AssemblyIdentityComparer value)
    {
        if (ReferenceEquals(value, AssemblyIdentityComparer.Default))
            return CompilerAssemblyIdentityComparer.Default;
        if (ReferenceEquals(value, DesktopAssemblyIdentityComparer.Default))
            return CompilerAssemblyIdentityComparer.Desktop;
        throw new InvalidOperationException(
            "A custom assembly identity comparer is unsupported.");
    }

    private static InvalidOperationException Unsupported<T>(
        string name,
        T value)
        where T : struct
    {
        return new($"The compiler option '{name}' has unsupported value '{value}'.");
    }
}

internal static partial class CompilerEffectEvaluationWireMappings
{
    internal static WorkerEffectContractKind ToWorker(EffectEvaluationContractKind value)
    {
        return value switch
        {
            EffectEvaluationContractKind.EnforcePure => WorkerEffectContractKind.EnforcePure,
            EffectEvaluationContractKind.ZeroAllocations => WorkerEffectContractKind.ZeroAllocations,
            EffectEvaluationContractKind.AllowedCapabilities => WorkerEffectContractKind.AllowedCapabilities,
            EffectEvaluationContractKind.DoesNotThrow => WorkerEffectContractKind.DoesNotThrow,
            EffectEvaluationContractKind.AllowedExceptions => WorkerEffectContractKind.AllowedExceptions,
            EffectEvaluationContractKind.EffectContract => WorkerEffectContractKind.EffectContract,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static WorkerClaimOutcome ToWorker(EffectEvaluationOutcome value)
    {
        return value switch
        {
            EffectEvaluationOutcome.Proven => WorkerClaimOutcome.Proven,
            EffectEvaluationOutcome.Refuted => WorkerClaimOutcome.Refuted,
            EffectEvaluationOutcome.Unknown => WorkerClaimOutcome.Unknown,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static WorkerClaimReason ToWorker(EffectEvaluationReason value)
    {
        return value switch
        {
            EffectEvaluationReason.None => WorkerClaimReason.None,
            EffectEvaluationReason.UnsupportedContract => WorkerClaimReason.UnsupportedContract,
            EffectEvaluationReason.EffectContractNotEstablished => WorkerClaimReason.EffectContractNotEstablished,
            EffectEvaluationReason.EffectSummaryIncomplete => WorkerClaimReason.EffectSummaryIncomplete,
            EffectEvaluationReason.ResourceLimit => WorkerClaimReason.ResourceLimit,
            EffectEvaluationReason.UnsupportedBody => WorkerClaimReason.UnsupportedBody,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static WorkerEffectEvidenceCertainty ToWorker(EffectEvaluationCertainty value)
    {
        return value switch
        {
            EffectEvaluationCertainty.IncompleteMayEffectSummary => WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary,
            EffectEvaluationCertainty.CompleteMayEffectSummary => WorkerEffectEvidenceCertainty.CompleteMayEffectSummary,
            EffectEvaluationCertainty.TrustedCompleteBoundary => WorkerEffectEvidenceCertainty.TrustedCompleteBoundary,
            EffectEvaluationCertainty.DefiniteViolation => WorkerEffectEvidenceCertainty.DefiniteViolation,
            EffectEvaluationCertainty.Unavailable => WorkerEffectEvidenceCertainty.Unavailable,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }
}

internal sealed partial class ClaimManifestBuilder
{
    internal static WorkerEffectSet ToWorkerEffects(EffectContractKind source)
    {
        if ((source & ~EffectContractMetadata.AllEffects) != 0)
            throw new ArgumentOutOfRangeException(nameof(source));
        var result = WorkerEffectSet.None;
        if ((source & EffectContractKind.ReadsReceiverState) != 0)
            result |= WorkerEffectSet.ReadsReceiverState;
        if ((source & EffectContractKind.ReadsArgumentState) != 0)
            result |= WorkerEffectSet.ReadsArgumentState;
        if ((source & EffectContractKind.ReadsCapturedState) != 0)
            result |= WorkerEffectSet.ReadsCapturedState;
        if ((source & EffectContractKind.ReadsStaticState) != 0)
            result |= WorkerEffectSet.ReadsStaticState;
        if ((source & EffectContractKind.ReadsAmbientState) != 0)
            result |= WorkerEffectSet.ReadsAmbientState;
        if ((source & EffectContractKind.WritesReceiverState) != 0)
            result |= WorkerEffectSet.WritesReceiverState;
        if ((source & EffectContractKind.WritesArgumentState) != 0)
            result |= WorkerEffectSet.WritesArgumentState;
        if ((source & EffectContractKind.WritesCapturedState) != 0)
            result |= WorkerEffectSet.WritesCapturedState;
        if ((source & EffectContractKind.WritesStaticState) != 0)
            result |= WorkerEffectSet.WritesStaticState;
        if ((source & EffectContractKind.WritesAmbientState) != 0)
            result |= WorkerEffectSet.WritesAmbientState;
        if ((source & EffectContractKind.Allocates) != 0)
            result |= WorkerEffectSet.Allocates;
        if ((source & EffectContractKind.Throws) != 0)
            result |= WorkerEffectSet.Throws;
        if ((source & EffectContractKind.Synchronizes) != 0)
            result |= WorkerEffectSet.Synchronizes;
        if ((source & EffectContractKind.UsesNondeterminism) != 0)
            result |= WorkerEffectSet.UsesNondeterminism;
        if ((source & EffectContractKind.UsesNativeCode) != 0)
            result |= WorkerEffectSet.UsesNativeCode;
        if ((source & EffectContractKind.UsesReflection) != 0)
            result |= WorkerEffectSet.UsesReflection;
        return result;
    }

    internal static WorkerEffectCapabilitySet ToWorkerCapabilities(EffectContractCapabilityKind source)
    {
        if ((source & ~EffectContractMetadata.AllCapabilities) != 0)
            throw new ArgumentOutOfRangeException(nameof(source));
        var result = WorkerEffectCapabilitySet.None;
        if ((source & EffectContractCapabilityKind.IO) != 0)
            result |= WorkerEffectCapabilitySet.IO;
        if ((source & EffectContractCapabilityKind.FileRead) != 0)
            result |= WorkerEffectCapabilitySet.FileRead;
        if ((source & EffectContractCapabilityKind.FileWrite) != 0)
            result |= WorkerEffectCapabilitySet.FileWrite;
        if ((source & EffectContractCapabilityKind.Network) != 0)
            result |= WorkerEffectCapabilitySet.Network;
        if ((source & EffectContractCapabilityKind.Console) != 0)
            result |= WorkerEffectCapabilitySet.Console;
        if ((source & EffectContractCapabilityKind.Process) != 0)
            result |= WorkerEffectCapabilitySet.Process;
        if ((source & EffectContractCapabilityKind.Environment) != 0)
            result |= WorkerEffectCapabilitySet.Environment;
        if ((source & EffectContractCapabilityKind.Registry) != 0)
            result |= WorkerEffectCapabilitySet.Registry;
        if ((source & EffectContractCapabilityKind.Clock) != 0)
            result |= WorkerEffectCapabilitySet.Clock;
        if ((source & EffectContractCapabilityKind.Randomness) != 0)
            result |= WorkerEffectCapabilitySet.Randomness;
        if ((source & EffectContractCapabilityKind.Reflection) != 0)
            result |= WorkerEffectCapabilitySet.Reflection;
        if ((source & EffectContractCapabilityKind.Synchronization) != 0)
            result |= WorkerEffectCapabilitySet.Synchronization;
        if ((source & EffectContractCapabilityKind.NativeInterop) != 0)
            result |= WorkerEffectCapabilitySet.NativeInterop;
        return result;
    }
}

internal static partial class CompilerLoweringWireMappings
{
    internal static CompilerContractKind ToCompiler(BoundContractKind value)
    {
        return value switch
        {
            BoundContractKind.Requires => CompilerContractKind.Requires,
            BoundContractKind.Ensures => CompilerContractKind.Ensures,
            BoundContractKind.Assume => CompilerContractKind.Assume,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static CompilerContractEvidence ToCompiler(BoundContractEvidence value)
    {
        return value switch
        {
            BoundContractEvidence.CompilerBoundInvocation => CompilerContractEvidence.CompilerBoundInvocation,
            BoundContractEvidence.ClosedAttribute => CompilerContractEvidence.ClosedAttribute,
            BoundContractEvidence.Companion => CompilerContractEvidence.Companion,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static CompilerVariableRole ToCompiler(BoundContractVariableRole value)
    {
        return value switch
        {
            BoundContractVariableRole.Receiver => CompilerVariableRole.Receiver,
            BoundContractVariableRole.Parameter => CompilerVariableRole.Parameter,
            BoundContractVariableRole.Result => CompilerVariableRole.Result,
            BoundContractVariableRole.PreState => CompilerVariableRole.PreState,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static WorkerClaimEvidence ToWorkerEvidence(BoundContractEvidence value)
    {
        return value switch
        {
            BoundContractEvidence.CompilerBoundInvocation => WorkerClaimEvidence.DirectClause,
            BoundContractEvidence.ClosedAttribute => WorkerClaimEvidence.ReturnAttribute,
            BoundContractEvidence.Companion => WorkerClaimEvidence.CompanionClause,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }

    internal static WorkerClaimReason ToWorkerFailure(ContractBindingFailure value)
    {
        return value switch
        {
            ContractBindingFailure.None => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.ContractApiUnavailable => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.UnsupportedExpression => WorkerClaimReason.UnsupportedExpression,
            ContractBindingFailure.NonBooleanCondition => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.ResultOutsideEnsures => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.OldOutsideEnsures => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.NestedOld => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.InvalidIntrinsicSignature => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.MissingCompanion => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.AmbiguousCompanion => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.CompanionSignatureMismatch => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.CompanionBodyUnavailable => WorkerClaimReason.UnsupportedCallable,
            ContractBindingFailure.InvalidClosedAttribute => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.InvalidClausePlacement => WorkerClaimReason.UnsupportedContract,
            ContractBindingFailure.UnsupportedTarget => WorkerClaimReason.UnsupportedCallable,
            _ => throw new ArgumentOutOfRangeException(nameof(value))
        };
    }
}

internal static class CompilerCallableProducerReasonCatalog
{
    internal const WorkerClaimReason SuccessReason = WorkerClaimReason.None;
    internal const WorkerClaimReason DiagnosticFailureReason = WorkerClaimReason.UnsupportedCallable;
    internal static readonly WorkerClaimReason[] FailureReasons = [
        WorkerClaimReason.UnsupportedCallable,
        WorkerClaimReason.UnsupportedContract,
        WorkerClaimReason.UnsupportedBody,
        WorkerClaimReason.UnsupportedExpression,
    ];
    internal static bool IsFailureReason(WorkerClaimReason reason) =>
        Array.IndexOf(FailureReasons, reason) >= 0;
}
