// <auto-generated>
// Generated by scripts/Generate-DeclarativeModels.ps1 from
// SharpProof.DeclarativeModels.catalog.json.
// Declarative record storage only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.CompilerArtifact;

internal sealed partial record ClaimManifestBuildResult(
    WorkerClaimManifest Manifest,
    ImmutableDictionary<IMethodSymbol, ManifestCallableTarget> Targets
);

internal sealed partial record ManifestCallableTarget(
    IMethodSymbol Method,
    SyntaxNode? Declaration,
    SemanticModel? SemanticModel,
    WorkerCallableManifestEntry Entry,
    ImmutableArray<ManifestClaim> Claims,
    ImmutableArray<ManifestEffectClaim> EffectClaims,
    bool IsVerifierSupported
);

internal sealed partial record ManifestClaim(
    WorkerClaimManifestEntry Entry,
    IInvocationOperation? SourceOperation,
    AttributeData? SourceAttribute,
    ContractClausePlacement? Placement
);

internal sealed partial record ManifestEffectClaim(
    WorkerClaimManifestEntry Entry,
    CompilerEffectClaimArtifact Evidence
);

internal sealed partial class ClaimManifestBuilder
{
    private readonly partial record struct ClaimCandidate(
        string Fingerprint,
        Location Location,
        WorkerClaimEvidence Evidence,
        IInvocationOperation? Operation,
        AttributeData? Attribute,
        ContractClausePlacement? Placement
    );
    private readonly partial record struct AssumptionCandidate(
        WorkerAssumptionKind Kind,
        string Fingerprint
    );
    private readonly partial record struct CallableSeed(
        IMethodSymbol Method,
        SyntaxNode? Declaration,
        SemanticModel? Model
    );
}

internal static partial class SemanticClaimIdentity
{
    private readonly partial record struct ClaimIdentityContext(
        IMethodSymbol Target,
        IMethodSymbol Source,
        bool UsesCompanion
    );
}
