<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
    <NoWarn>$(NoWarn);RS2008</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\eng\RoslynSymbolFacts.cs"
             Link="RoslynSymbolFacts.cs" />
    <Compile Include="..\eng\RoslynCfgFactory.cs"
             Link="RoslynCfgFactory.cs" />
    <Compile Include="..\eng\RoslynCfgThrowFacts.cs"
             Link="RoslynCfgThrowFacts.cs" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
</Project>
