// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable
namespace SharpProof.Frontend;

internal static class CompilerIdentityProjections
{
}
