namespace SharpProof.Frontend;

internal enum OperationSupportStage { ContractExpressionLowering, EffectDiscovery }

internal readonly struct CSharpOperationDecision(TotalOperationAdmission admission,
    bool contractExpression = false, bool effectDiscovery = false)
{
    internal TotalOperationAdmission Admission { get; } = admission;
    internal bool ContractExpression { get; } = contractExpression;
    internal bool EffectDiscovery { get; } = effectDiscovery;
}

internal static partial class CSharpOperationSemantics
{
    // Frozen decisions for the distinct Roslyn 4.14 operation values. Aliases share a row.
    internal static readonly ImmutableDictionary<OperationKind, CSharpOperationDecision> Operations =
        new Dictionary<OperationKind, CSharpOperationDecision>
        {
            [OperationKind.None] = new(TotalOperationAdmission.Invalid),
            [OperationKind.Invalid] = new(TotalOperationAdmission.Invalid),
            [OperationKind.Block] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.VariableDeclarationGroup] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Switch] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Loop] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Labeled] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Branch] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Empty] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Return] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.YieldBreak] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Lock] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Try] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Using] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.YieldReturn] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ExpressionStatement] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.LocalFunction] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Stop] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.End] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.RaiseEvent] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Literal] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.Conversion] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.Invocation] = new(TotalOperationAdmission.Intrinsic, effectDiscovery: true),
            [OperationKind.ArrayElementReference] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.LocalReference] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.ParameterReference] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.FieldReference] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.MethodReference] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.PropertyReference] = new(TotalOperationAdmission.Incomplete, contractExpression: true, effectDiscovery: true),
            [OperationKind.EventReference] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Unary] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.Binary] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.Conditional] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.Coalesce] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.AnonymousFunction] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ObjectCreation] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.TypeParameterObjectCreation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ArrayCreation] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.InstanceReference] = new(TotalOperationAdmission.Incomplete, contractExpression: true, effectDiscovery: true),
            [OperationKind.IsType] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Await] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.SimpleAssignment] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.CompoundAssignment] = new(TotalOperationAdmission.Scalar, effectDiscovery: true),
            [OperationKind.Parenthesized] = new(TotalOperationAdmission.Scalar, effectDiscovery: true),
            [OperationKind.EventAssignment] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ConditionalAccess] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.ConditionalAccessInstance] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.InterpolatedString] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.AnonymousObjectCreation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ObjectOrCollectionInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.MemberInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [(OperationKind)52] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.NameOf] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Tuple] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DynamicObjectCreation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DynamicMemberReference] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DynamicInvocation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DynamicIndexerAccess] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.TranslatedQuery] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DelegateCreation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DefaultValue] = new(TotalOperationAdmission.Scalar, contractExpression: true, effectDiscovery: true),
            [OperationKind.TypeOf] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.SizeOf] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.AddressOf] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.IsPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Increment] = new(TotalOperationAdmission.Scalar, effectDiscovery: true),
            [OperationKind.Throw] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Decrement] = new(TotalOperationAdmission.Scalar, effectDiscovery: true),
            [OperationKind.DeconstructionAssignment] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DeclarationExpression] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.OmittedArgument] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.FieldInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.VariableInitializer] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.PropertyInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.ParameterInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.ArrayInitializer] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.VariableDeclarator] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.VariableDeclaration] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.Argument] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.CatchClause] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.SwitchCase] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.CaseClause] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.InterpolatedStringText] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Interpolation] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.ConstantPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DeclarationPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.TupleBinary] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.MethodBodyOperation] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.ConstructorBodyOperation] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Discard] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.FlowCapture] = new(TotalOperationAdmission.Structure, effectDiscovery: true),
            [OperationKind.FlowCaptureReference] = new(TotalOperationAdmission.Scalar, effectDiscovery: true),
            [OperationKind.IsNull] = new(TotalOperationAdmission.Incomplete, contractExpression: true, effectDiscovery: true),
            [OperationKind.CaughtException] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.StaticLocalInitializationSemaphore] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.FlowAnonymousFunction] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.CoalesceAssignment] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.Range] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ReDim] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ReDimClause] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.RecursivePattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.DiscardPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.SwitchExpression] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.SwitchExpressionArm] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.PropertySubpattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.UsingDeclaration] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.NegatedPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.BinaryPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.TypePattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.RelationalPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.With] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringHandlerCreation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringAddition] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringAppendLiteral] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringAppendFormatted] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringAppendInvalid] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.InterpolatedStringHandlerArgumentPlaceholder] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.FunctionPointerInvocation] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ListPattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.SlicePattern] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.ImplicitIndexerReference] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Utf8String] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Attribute] = new(TotalOperationAdmission.Incomplete, effectDiscovery: true),
            [OperationKind.InlineArrayAccess] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.CollectionExpression] = new(TotalOperationAdmission.Incomplete),
            [OperationKind.Spread] = new(TotalOperationAdmission.Incomplete),
        }.ToImmutableDictionary();
    internal static bool IsSupported(OperationSupportStage stage, OperationKind kind)
    {
        Operations.TryGetValue(kind, out var decision);
        return stage switch
        {
            OperationSupportStage.ContractExpressionLowering => decision.ContractExpression,
            OperationSupportStage.EffectDiscovery => decision.EffectDiscovery,
            _ => throw new ArgumentOutOfRangeException(nameof(stage), stage, "Unknown operation support stage.")
        };
    }
}
