// <auto-generated>
// Generated by scripts/Generate-ProjectionCatalog.ps1 from
// SharpProof.Projection.catalog.json.
// Declarative projection tables only; analysis remains handwritten.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
namespace SharpProof.Frontend;

internal static class OperationSupportProjections
{
    internal static OperationKind[] GetSupported(
        OperationSupportStage stage
    )
    {
        return stage switch
        {
            OperationSupportStage.ContractExpressionLowering => OperationSupportCatalogData.ContractExpression,
            OperationSupportStage.EffectDiscovery => OperationSupportCatalogData.EffectDiscovery,
            _ => throw new ArgumentOutOfRangeException(nameof(stage), stage, "Unknown operation support stage.")
        };
    }
}
