<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\SharpProof.Testing.props" />

  <ItemGroup>
    <ProjectReference Include="..\Tools\SharpProof.Baseline.Core\SharpProof.Baseline.Core.csproj" />
    <ProjectReference Include="..\Tools\SharpProof.CorpusReport.Core\SharpProof.CorpusReport.Core.csproj" />
    <ProjectReference Include="..\Tools\SharpProof.Fuzz.Core\SharpProof.Fuzz.Core.csproj" />
    <ProjectReference Include="..\SharpProof.Testing\SharpProof.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
