<Project>
  <PropertyGroup>
    <_SharpProofPortablePackagePresent>true</_SharpProofPortablePackagePresent>
    <SharpProofAnalyzerDirectory Condition="'$(SharpProofAnalyzerDirectory)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/analyzers/dotnet/cs'))</SharpProofAnalyzerDirectory>
    <_SharpProofAnalyzerDirectory>$([System.IO.Path]::GetFullPath('$(SharpProofAnalyzerDirectory)'))</_SharpProofAnalyzerDirectory>
    <_SharpProofAnalyzerPath Condition="'$(_SharpProofAnalyzerPath)' == ''">$(_SharpProofAnalyzerDirectory)/SharpProof.Analyzer.dll</_SharpProofAnalyzerPath>
    <_SharpProofContractForGeneratorPath Condition="'$(_SharpProofContractForGeneratorPath)' == ''">$(_SharpProofAnalyzerDirectory)/SharpProof.ContractForGenerator.dll</_SharpProofContractForGeneratorPath>
    <_SharpProofSharedDirectory Condition="'$(_SharpProofSharedDirectory)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/shared/netstandard2.0'))</_SharpProofSharedDirectory>
    <SharpProofCollectorDirectory Condition="'$(SharpProofCollectorDirectory)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/collector'))</SharpProofCollectorDirectory>
    <_SharpProofCollectorDirectory>$([System.IO.Path]::GetFullPath('$(SharpProofCollectorDirectory)'))</_SharpProofCollectorDirectory>
    <SharpProofCompilerCollectorPath Condition="'$(SharpProofCompilerCollectorPath)' == ''">$(_SharpProofCollectorDirectory)/SharpProof.CompilerCollector.dll</SharpProofCompilerCollectorPath>
    <SharpProofSpecificationPacks Condition="'$(SharpProofSpecificationPacks)' == ''"></SharpProofSpecificationPacks>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="SharpProofProfile" />
    <CompilerVisibleProperty Include="SharpProofFeatures" />
    <CompilerVisibleProperty Include="SharpProofSpecificationPacks" />
  </ItemGroup>
</Project>
