<Project>
  <Target Name="_SharpProofExcludeNativeAnalyzerAssets"
          BeforeTargets="CoreCompile">
    <ItemGroup>
      <_SharpProofNativeAnalyzer Include="@(Analyzer)"
                                 Condition="'%(Analyzer.Filename)' == 'libz3' AND ('%(Analyzer.Extension)' == '.dll' OR '%(Analyzer.Extension)' == '.dylib' OR '%(Analyzer.Extension)' == '.so')" />
      <Analyzer Remove="@(_SharpProofNativeAnalyzer)" />
      <_SharpProofNativeSmtLocator
          Include="$(MSBuildThisFileDirectory)../analyzers/dotnet/cs/SharpProof.NativeSmtLocator.txt"
          Condition="Exists('$(MSBuildThisFileDirectory)../analyzers/dotnet/cs/SharpProof.NativeSmtLocator.txt')" />
      <AdditionalFiles Include="@(_SharpProofNativeSmtLocator)" />
    </ItemGroup>
  </Target>
</Project>
