<Project>
  <PropertyGroup>
    <_SharpProofPortablePackagePresent>true</_SharpProofPortablePackagePresent>
    <SharpProofAnalyzerDirectory Condition="'$(SharpProofAnalyzerDirectory)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/analyzers/dotnet/cs'))</SharpProofAnalyzerDirectory>
    <_SharpProofAnalyzerDirectory>$([System.IO.Path]::GetFullPath('$(SharpProofAnalyzerDirectory)'))</_SharpProofAnalyzerDirectory>
    <SharpProofPortableAnalyzerPath Condition="'$(SharpProofPortableAnalyzerPath)' == ''">$(_SharpProofAnalyzerDirectory)/SharpProof.PortableAnalyzer.dll</SharpProofPortableAnalyzerPath>
    <SharpProofCollectorDirectory Condition="'$(SharpProofCollectorDirectory)' == ''">$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../tools/collector'))</SharpProofCollectorDirectory>
    <_SharpProofCollectorDirectory>$([System.IO.Path]::GetFullPath('$(SharpProofCollectorDirectory)'))</_SharpProofCollectorDirectory>
    <SharpProofCompilerCollectorPath Condition="'$(SharpProofCompilerCollectorPath)' == ''">$(_SharpProofCollectorDirectory)/SharpProof.CompilerCollector.dll</SharpProofCompilerCollectorPath>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="SharpProofProfile" />
    <CompilerVisibleProperty Include="SharpProofFeatures" />
    <CompilerVisibleProperty Include="SharpProofMode" />
  </ItemGroup>
</Project>
