[CmdletBinding()]
param(
    [Parameter()][string]$SchemaPath,
    [Parameter()][Alias('OutputPath')][string]$ModelOutputPath,
    [Parameter()][string]$PortableOutputPath,
    [Parameter()][string]$CompilationOutputPath,
    [Parameter()][Alias('Check')][switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'GeneratedFileHelpers.ps1')

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($SchemaPath)) {
    $SchemaPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerArtifactModel.schema.json'
}
if ([string]::IsNullOrWhiteSpace($ModelOutputPath)) {
    $ModelOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerArtifactModel.generated.cs'
}
if ([string]::IsNullOrWhiteSpace($PortableOutputPath)) {
    $PortableOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\PortableIrModel.generated.cs'
}
if ([string]::IsNullOrWhiteSpace($CompilationOutputPath)) {
    $CompilationOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerCompilationModel.generated.cs'
}
$SchemaPath = [IO.Path]::GetFullPath($SchemaPath)
$ModelOutputPath = [IO.Path]::GetFullPath($ModelOutputPath)
$PortableOutputPath = [IO.Path]::GetFullPath($PortableOutputPath)
$CompilationOutputPath = [IO.Path]::GetFullPath($CompilationOutputPath)
if (-not [IO.File]::Exists($SchemaPath)) {
    throw "Compiler-artifact schema not found: $SchemaPath"
}

function Get-RequiredMember {
    param([object]$Object, [string]$Name, [string]$Context)

    $member = $Object.PSObject.Properties[$Name]
    if ($null -eq $member -or $null -eq $member.Value) {
        throw "$Context must define '$Name'."
    }
    return $member.Value
}

function Get-MemberArray {
    param([object]$Object, [string]$Name)

    $member = $Object.PSObject.Properties[$Name]
    if ($null -eq $member -or $null -eq $member.Value) {
        return @()
    }
    return @($member.Value)
}

function Assert-Identifier {
    param([string]$Value, [string]$Context)

    if ($Value -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "$Context is not a C# identifier: '$Value'."
    }
}

function Assert-TypeName {
    param([string]$Value, [string]$Context)

    if ($Value -notmatch '^[A-Za-z_][A-Za-z0-9_?.<>, \[\]]*$') {
        throw "$Context is not a supported C# type: '$Value'."
    }
}

function ConvertTo-CSharpString {
    param([string]$Value)

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function New-GeneratedOutput {
    param([string]$OutputName)

    $result = [Collections.Generic.List[string]]::new()
    $result.Add('// <auto-generated>')
    $result.Add('// Generated by scripts/Generate-CompilerArtifactModel.ps1 from')
    $result.Add('// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.')
    $result.Add("// Output: $OutputName.")
    $result.Add('// Do not edit this file directly.')
    $result.Add('// </auto-generated>')
    $result.Add('#nullable enable')
    $result.Add('')
    $result.Add('namespace SharpProof.CompilerArtifact;')
    return ,$result
}

function Get-ParameterSource {
    param([object[]]$Parameters, [string]$Context)

    $sources = @()
    $names = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($parameter in $Parameters) {
        $name = [string](Get-RequiredMember $parameter 'name' $Context)
        $type = [string](Get-RequiredMember $parameter 'type' $Context)
        Assert-Identifier $name "$Context parameter"
        Assert-TypeName $type "$Context parameter '$name'"
        if (-not $names.Add($name)) {
            throw "$Context repeats parameter '$name'."
        }
        $defaultMember = $parameter.PSObject.Properties['default']
        $default = if ($null -eq $defaultMember) {
            ''
        }
        else {
            $value = [string]$defaultMember.Value
            if ($value -notmatch '^(default|null|false|true|-?[0-9]+)$') {
                throw "$Context parameter '$name' has an invalid default."
            }
            " = $value"
        }
        $sources += "$type $name$default"
    }
    return $sources
}

function Add-ParameterList {
    param(
        [Collections.Generic.List[string]]$Lines,
        [string]$Prefix,
        [object[]]$Parameters,
        [string]$Suffix,
        [string]$Context
    )

    $sources = @(Get-ParameterSource $Parameters $Context)
    if ($sources.Count -eq 0) {
        $Lines.Add("$Prefix$Suffix")
        return
    }
    $Lines.Add("$Prefix(")
    for ($index = 0; $index -lt $sources.Count; $index++) {
        $comma = if ($index -lt $sources.Count - 1) { ',' } else { '' }
        $Lines.Add("    $($sources[$index])$comma")
    }
    $Lines.Add(")$Suffix")
}

function Get-InitializerSource {
    param(
        [object]$Default,
        [Collections.Generic.HashSet[string]]$ConstructorParameters,
        [string]$Context
    )

    $kind = [string](Get-RequiredMember $Default 'kind' $Context)
    switch ($kind) {
        'implicit' { return '' }
        'stringEmpty' { return ' = string.Empty' }
        'new' { return ' = new()' }
        'emptyArray' { return ' = []' }
        'literal' {
            $value = [string](Get-RequiredMember $Default 'value' $Context)
            if ($value -notmatch '^-?[0-9]+$') {
                throw "$Context has an invalid literal initializer."
            }
            return " = $value"
        }
        'member' {
            $value = [string](Get-RequiredMember $Default 'value' $Context)
            if ($value -notmatch '^[A-Za-z_][A-Za-z0-9_.]*$') {
                throw "$Context has an invalid member initializer."
            }
            return " = $value"
        }
        { $_ -in 'parameter', 'parameterOrStringEmpty', 'parameterOrEmptyArray' } {
            $name = [string](Get-RequiredMember $Default 'name' $Context)
            if (-not $ConstructorParameters.Contains($name)) {
                throw "$Context references unknown constructor parameter '$name'."
            }
            $expression = switch ($kind) {
                'parameter' { $name }
                'parameterOrStringEmpty' { "$name ?? string.Empty" }
                'parameterOrEmptyArray' { "$name ?? []" }
            }
            return " = $expression"
        }
        default { throw "$Context has unsupported default kind '$kind'." }
    }
}

function Add-Properties {
    param(
        [Collections.Generic.List[string]]$Lines,
        [object[]]$Properties,
        [Collections.Generic.HashSet[string]]$ConstructorParameters,
        [string]$TypeName,
        [string]$JsonNamingPolicy
    )

    $names = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    $jsonNames = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($property in $Properties) {
        $name = [string](
            Get-RequiredMember $property 'name' "type '$TypeName' property")
        $type = [string](
            Get-RequiredMember $property 'type' "property '$TypeName.$name'")
        $accessibility = [string](
            Get-RequiredMember $property 'accessibility' "property '$TypeName.$name'")
        $setter = [string](
            Get-RequiredMember $property 'set' "property '$TypeName.$name'")
        Assert-Identifier $name "Type '$TypeName' property"
        Assert-TypeName $type "Property '$TypeName.$name'"
        if (-not $names.Add($name)) {
            throw "Type '$TypeName' repeats property '$name'."
        }
        if ($accessibility -notin 'public', 'internal') {
            throw "Property '$TypeName.$name' has invalid accessibility."
        }
        if ($setter -notin 'set', 'init', 'none') {
            throw "Property '$TypeName.$name' has invalid setter."
        }
        $jsonMember = $property.PSObject.Properties['jsonName']
        if ($accessibility -eq 'public') {
            if ($null -eq $jsonMember -or [string]::IsNullOrWhiteSpace(
                    [string]$jsonMember.Value)) {
                throw "Public property '$TypeName.$name' must define its JSON name."
            }
            $jsonName = [string]$jsonMember.Value
            $expected = $name.Substring(0, 1).ToLowerInvariant() +
                $name.Substring(1)
            if ($JsonNamingPolicy -ne 'camelCase' -or
                $jsonName -ne $expected -or
                -not $jsonNames.Add($jsonName)) {
                throw "Property '$TypeName.$name' has an invalid JSON name."
            }
        }
        elseif ($null -ne $jsonMember) {
            throw "Internal property '$TypeName.$name' cannot define a JSON name."
        }
        $default = Get-RequiredMember $property 'default' "property '$TypeName.$name'"
        $initializer = Get-InitializerSource `
            $default $ConstructorParameters "property '$TypeName.$name'"
        $accessors = switch ($setter) {
            'set' { '{ get; set; }' }
            'init' { '{ get; init; }' }
            'none' { '{ get; }' }
        }
        $terminator = if ($initializer.Length -eq 0) { '' } else { ';' }
        $Lines.Add(
            "    $accessibility $type $name $accessors$initializer$terminator")
    }
}

function Add-RecordMembers {
    param(
        [Collections.Generic.List[string]]$Lines,
        [object[]]$Members,
        [string]$TypeName
    )

    foreach ($member in $Members) {
        $kind = [string](
            Get-RequiredMember $member 'kind' "record '$TypeName' member")
        $name = [string](
            Get-RequiredMember $member 'name' "record '$TypeName' member")
        $type = [string](
            Get-RequiredMember $member 'type' "record '$TypeName.$name'")
        $accessibility = [string](
            Get-RequiredMember $member 'accessibility' "record '$TypeName.$name'")
        Assert-Identifier $name "Record '$TypeName' member"
        Assert-TypeName $type "Record '$TypeName.$name'"
        if ($accessibility -notin 'public', 'internal') {
            throw "Record '$TypeName.$name' has invalid accessibility."
        }
        if ($kind -eq 'computedProperty') {
            $operation = [string](
                Get-RequiredMember $member 'operation' "record '$TypeName.$name'")
            $source = [string](
                Get-RequiredMember $member 'source' "record '$TypeName.$name'")
            $value = [string](
                Get-RequiredMember $member 'value' "record '$TypeName.$name'")
            if ($operation -ne 'equals' -or
                $source -notmatch '^[A-Za-z_][A-Za-z0-9_]*$' -or
                $value -notmatch '^[A-Za-z_][A-Za-z0-9_.]*$') {
                throw "Record '$TypeName.$name' has invalid computed semantics."
            }
            $Lines.Add("    $accessibility $type $name => $source == $value;")
        }
        elseif ($kind -eq 'property') {
            $setter = [string](
                Get-RequiredMember $member 'set' "record '$TypeName.$name'")
            if ($setter -notin 'set', 'init') {
                throw "Record '$TypeName.$name' has invalid setter."
            }
            $default = Get-RequiredMember `
                $member 'default' "record '$TypeName.$name'"
            $empty = [Collections.Generic.HashSet[string]]::new(
                [StringComparer]::Ordinal)
            $initializer = Get-InitializerSource `
                $default $empty "record '$TypeName.$name'"
            $Lines.Add(
                "    $accessibility $type $name { get; $setter; }$initializer;")
        }
        else {
            throw "Record '$TypeName.$name' has unsupported kind '$kind'."
        }
    }
}

$schema = Get-Content -LiteralPath $SchemaPath -Raw |
    ConvertFrom-Json -Depth 100
if ([int](Get-RequiredMember $schema 'schemaVersion' 'schema') -ne 1) {
    throw 'Only compiler-artifact model schema version 1 is supported.'
}
$namespace = [string](Get-RequiredMember $schema 'namespace' 'schema')
$jsonNamingPolicy = [string](
    Get-RequiredMember $schema 'jsonNamingPolicy' 'schema')
if ($jsonNamingPolicy -ne 'camelCase') {
    throw "Unsupported JSON naming policy '$jsonNamingPolicy'."
}
$declarations = @(Get-RequiredMember $schema 'declarations' 'schema')
$declarationNames = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
if ($namespace -ne 'SharpProof.CompilerArtifact') {
    throw "Unsupported compiler-artifact namespace '$namespace'."
}
$modelLines = New-GeneratedOutput 'CompilerArtifactModel.generated.cs'
$portableLines = New-GeneratedOutput 'PortableIrModel.generated.cs'
$compilationLines = New-GeneratedOutput 'CompilerCompilationModel.generated.cs'

foreach ($declaration in $declarations) {
    $kind = [string](Get-RequiredMember $declaration 'kind' 'declaration')
    $name = [string](Get-RequiredMember $declaration 'name' 'declaration')
    Assert-Identifier $name 'Declaration name'
    if (-not $declarationNames.Add($name)) {
        throw "Duplicate compiler-artifact declaration '$name'."
    }
    $lines = if ($name -match '^PortableIr' -or
        $name -in 'DecodedPortableIrGraph', 'EncodedPortableIrGraph') {
        ,$portableLines
    }
    elseif ($name -in @(
            'CompilerCompilationSnapshot',
            'CompilerCompilationOptionsSnapshot',
            'CompilerSyntaxTreeSnapshot',
            'CompilerReferenceSnapshot',
            'CompilerAdditionalFileSnapshot',
            'CompilerFeatureSnapshot')) {
        ,$compilationLines
    }
    else {
        ,$modelLines
    }
    $lines.Add('')
    if ($kind -eq 'staticClass') {
        $lines.Add("internal static class $name {")
        foreach ($constant in @(Get-RequiredMember `
                $declaration 'constants' "static class '$name'")) {
            $constantName = [string](
                Get-RequiredMember $constant 'name' "static class '$name'")
            $type = [string](
                Get-RequiredMember $constant 'type' "constant '$name.$constantName'")
            $accessibility = [string](
                Get-RequiredMember $constant 'accessibility' "constant '$name.$constantName'")
            Assert-Identifier $constantName "Constant '$name'"
            if ($accessibility -ne 'internal' -or $type -notin 'string', 'int') {
                throw "Constant '$name.$constantName' has unsupported shape."
            }
            $value = Get-RequiredMember `
                $constant 'value' "constant '$name.$constantName'"
            $source = if ($type -eq 'string') {
                ConvertTo-CSharpString ([string]$value)
            }
            else {
                ([Convert]::ToInt32(
                    $value,
                    [Globalization.CultureInfo]::InvariantCulture)
                ).ToString([Globalization.CultureInfo]::InvariantCulture)
            }
            $lines.Add("    internal const $type $constantName = $source;")
        }
        $lines.Add('}')
        continue
    }
    if ($kind -eq 'enum') {
        $members = @(Get-RequiredMember $declaration 'members' "enum '$name'")
        $memberNames = [Collections.Generic.HashSet[string]]::new(
            [StringComparer]::Ordinal)
        $lines.Add("internal enum $name {")
        for ($index = 0; $index -lt $members.Count; $index++) {
            $member = $members[$index]
            $memberName = [string](
                Get-RequiredMember $member 'name' "enum '$name' member")
            Assert-Identifier $memberName "Enum '$name' member"
            if (-not $memberNames.Add($memberName)) {
                throw "Enum '$name' repeats member '$memberName'."
            }
            $value = [int](
                Get-RequiredMember $member 'value' "enum '$name.$memberName'")
            if ($value -ne $index) {
                throw "Enum '$name.$memberName' must use its declared wire ordinal."
            }
            $comma = if ($index -lt $members.Count - 1) { ',' } else { '' }
            $lines.Add("    $memberName = $value$comma")
        }
        $lines.Add('}')
        continue
    }
    if ($kind -in 'record', 'recordStruct', 'preparedBodyRecord') {
        $parameters = @(
            Get-RequiredMember $declaration 'parameters' "record '$name'")
        $prefix = if ($kind -eq 'recordStruct') {
            $readonly = [bool](
                Get-RequiredMember $declaration 'readonly' "record '$name'")
            if (-not $readonly) {
                throw "Record struct '$name' must be readonly."
            }
            "internal readonly record struct $name"
        }
        else {
            "internal sealed record $name"
        }
        $members = @(Get-MemberArray $declaration 'members')
        $hasBody = $members.Count -ne 0 -or $kind -eq 'preparedBodyRecord'
        Add-ParameterList `
            $lines $prefix $parameters $(if ($hasBody) { ' {' } else { ';' }) `
            "record '$name'"
        if (-not $hasBody) {
            continue
        }
        if ($kind -eq 'preparedBodyRecord') {
            $maximumInstructions = [int](
                Get-RequiredMember `
                    $declaration 'maximumInstructions' "record '$name'")
            if ($maximumInstructions -ne 4096) {
                throw "Record '$name' must preserve its replay instruction bound."
            }
            $lines.Add(
                "    internal const int MaximumInstructions = $maximumInstructions;")
            $lines.Add('')
            $lines.Add('    internal static CompilerPreparedBody Trivial() =>')
            $lines.Add('        new(')
            $lines.Add('            CompilerPreparedBodyKind.Trivial,')
            $lines.Add('            null,')
            $lines.Add('            ImmutableDictionary<IrVarId, IrVarId>.Empty,')
            $lines.Add(
                '            ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall>.Empty);')
            $lines.Add('')
            $lines.Add('    internal static CompilerPreparedBody ProgramBody(')
            $lines.Add('        IrProgram program,')
            $lines.Add(
                '        ImmutableDictionary<IrVarId, IrVarId> parameterBindings,')
            $lines.Add(
                '        ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> specCalls) =>')
            $lines.Add('        new(')
            $lines.Add('            CompilerPreparedBodyKind.Program,')
            $lines.Add(
                '            program ?? throw new ArgumentNullException(nameof(program)),')
            $lines.Add('            parameterBindings,')
            $lines.Add('            specCalls);')
        }
        else {
            Add-RecordMembers $lines $members $name
        }
        $lines.Add('}')
        continue
    }
    if ($kind -ne 'class') {
        throw "Unsupported compiler-artifact declaration kind '$kind'."
    }
    $parameters = @(Get-MemberArray $declaration 'constructor')
    $parameterNames = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($parameter in $parameters) {
        [void]$parameterNames.Add([string](
            Get-RequiredMember $parameter 'name' "class '$name' constructor"))
    }
    if ($parameters.Count -eq 0) {
        $lines.Add("internal sealed class $name {")
    }
    else {
        Add-ParameterList `
            $lines "internal sealed class $name" $parameters ' {' "class '$name'"
    }
    Add-Properties `
        $lines @(Get-RequiredMember $declaration 'properties' "class '$name'") `
        $parameterNames $name $jsonNamingPolicy
    $lines.Add('}')
}

$envelope = Get-RequiredMember $schema 'artifactEnvelope' 'schema'
if ([string](Get-RequiredMember $envelope 'schema' 'artifact envelope') -ne
        'SharpProof.CompilerManifest' -or
    [int](Get-RequiredMember $envelope 'version' 'artifact envelope') -ne 9) {
    throw 'The compiler-artifact envelope must remain schema version 9.'
}

$catalogs = @(Get-RequiredMember $schema 'wireEnumCatalogs' 'schema')
$catalogFields = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
$portableLines.Add('')
$portableLines.Add('internal static partial class PortableIrGraphCodec {')
foreach ($catalog in $catalogs) {
    $field = [string](Get-RequiredMember $catalog 'field' 'wire enum catalog')
    $type = [string](Get-RequiredMember $catalog 'type' "wire catalog '$field'")
    Assert-Identifier $field 'Wire catalog field'
    Assert-TypeName $type "Wire catalog '$field'"
    if (-not $catalogFields.Add($field)) {
        throw "Duplicate wire catalog '$field'."
    }
    $members = @(Get-RequiredMember $catalog 'members' "wire catalog '$field'")
    if ($members.Count -eq 0) {
        throw "Wire catalog '$field' cannot be empty."
    }
    $portableLines.Add("    private static readonly $type[] $field = [")
    for ($index = 0; $index -lt $members.Count; $index++) {
        $member = [string]$members[$index]
        Assert-Identifier $member "Wire catalog '$field' member"
        $comma = if ($index -lt $members.Count - 1) { ',' } else { '' }
        $portableLines.Add("        $type.$member$comma")
    }
    $portableLines.Add('    ];')
}
$portableLines.Add('')
$portableLines.Add('    internal static bool HasCompleteWireEnumCatalogs =>')
for ($index = 0; $index -lt $catalogs.Count; $index++) {
    $field = [string]$catalogs[$index].field
    $ending = if ($index -lt $catalogs.Count - 1) { ' &&' } else { ';' }
    $portableLines.Add("        IsComplete($field)$ending")
}
$portableLines.Add('')
$portableLines.Add(
    '    private static bool IsComplete<T>(T[] values) where T : struct, Enum =>')
$portableLines.Add(
    '        values.SequenceEqual(Enum.GetValues(typeof(T)).Cast<T>());')
$portableLines.Add('}')

$evidence = Get-RequiredMember $schema 'effectEvidence' 'schema'
$domain = [string](Get-RequiredMember $evidence 'domain' 'effect evidence')
$evidenceVersion = [int](Get-RequiredMember $evidence 'version' 'effect evidence')
if ($domain -ne 'SharpProof.CompilerEffectClaimEvidence' -or
    $evidenceVersion -ne 8) {
    throw 'Compiler effect evidence must preserve domain version 8.'
}
$unknownReasons = @(Get-RequiredMember `
    $evidence 'unknownReasons' 'effect evidence')
if ($unknownReasons.Count -eq 0) {
    throw 'Compiler effect evidence must define typed unknown reasons.'
}
foreach ($reason in $unknownReasons) {
    Assert-Identifier ([string]$reason) 'Effect evidence unknown reason'
}
$constraintKinds = Get-RequiredMember `
    $evidence 'constraintKinds' 'effect evidence'
$capabilitiesKind = [string](
    Get-RequiredMember $constraintKinds 'capabilities' 'effect evidence constraints')
$exceptionsKind = [string](
    Get-RequiredMember $constraintKinds 'exceptions' 'effect evidence constraints')
$combinedKind = [string](
    Get-RequiredMember $constraintKinds 'combined' 'effect evidence constraints')
foreach ($kind in $capabilitiesKind, $exceptionsKind, $combinedKind) {
    Assert-Identifier $kind 'Effect evidence constraint kind'
}
$replay = Get-RequiredMember $evidence 'replay' 'effect evidence'
$replayPathKind = [string](
    Get-RequiredMember $replay 'pathKind' 'effect replay')
Assert-Identifier $replayPathKind 'Effect replay path kind'
$maximumReplayEvents = [int](
    Get-RequiredMember $replay 'maximumEvents' 'effect replay')
if ($maximumReplayEvents -ne 256) {
    throw 'Compiler effect replay must preserve its 256-event bound.'
}
$supportedReplayEventKinds = @(
    Get-RequiredMember $replay 'supportedEventKinds' 'effect replay')
if ($supportedReplayEventKinds.Count -eq 0) {
    throw 'Compiler effect replay must define supported event kinds.'
}
foreach ($kind in $supportedReplayEventKinds) {
    Assert-Identifier ([string]$kind) 'Supported effect replay event kind'
}
if (-not [bool](Get-RequiredMember `
        $evidence 'sortAllowedExceptionTypes' 'effect evidence') -or
    -not [bool](Get-RequiredMember `
        $evidence 'sortWitnessExceptionHierarchy' 'effect evidence')) {
    throw 'Compiler effect evidence must use canonical exception ordering.'
}

$modelLines.Add('')
$modelLines.Add('internal static class CompilerEffectClaimArtifactCodec {')
$modelLines.Add('    internal static void Seal(CompilerEffectClaimArtifact value) {')
$modelLines.Add('        if (value.Replay is { } replay) {')
$modelLines.Add(
    '            replay.ConstraintSha256 = ComputeConstraintSha256(value.ContractKind, value.Constraint);')
$modelLines.Add('            foreach (var effectEvent in replay.Events ?? [])')
$modelLines.Add(
    '                effectEvent.OperationIdentitySha256 = ComputeReplayOperationSha256(effectEvent);')
$modelLines.Add('        }')
$modelLines.Add('        value.EvidenceSha256 = ComputeSha256(value);')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add('    internal static void Validate(CompilerEffectClaimArtifact value) {')
$modelLines.Add('        if (value == null || string.IsNullOrWhiteSpace(value.ClaimId) ||')
$modelLines.Add('            string.IsNullOrWhiteSpace(value.Evidence) ||')
$modelLines.Add(
    '            !WorkerProtocolJson.IsDefined(value.ContractKind, WorkerEffectContractKind.Unspecified) ||')
$modelLines.Add(
    '            !Enum.IsDefined(typeof(WorkerClaimReason), value.Reason) ||')
$modelLines.Add(
    '            !WorkerProtocolJson.IsDefined(value.Certainty, WorkerEffectEvidenceCertainty.Unspecified) ||')
$modelLines.Add(
    '            !HasValidConstraint(value.ContractKind, value.Constraint) ||')
$modelLines.Add('            !HasValidReplay(value) ||')
$modelLines.Add('            !HasValidOutcome(value) ||')
$modelLines.Add('            value.EvidenceSha256 != ComputeSha256(value))')
$modelLines.Add(
    '            throw new InvalidDataException("Compiler effect-claim evidence is invalid.");')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add('    private static bool HasValidOutcome(CompilerEffectClaimArtifact value) =>')
$modelLines.Add(
    '        WorkerProtocolJson.HasValidEffectCertainty(value.Outcome, value.Reason, value.Certainty) &&')
$modelLines.Add(
    '        (value.Outcome, value.Reason, value.Certainty, value.Witness, value.Replay) switch {')
$modelLines.Add(
    '            (WorkerClaimOutcome.Proven, WorkerClaimReason.None, _, null, null) => true,')
$modelLines.Add('            (WorkerClaimOutcome.Refuted, WorkerClaimReason.None,')
$modelLines.Add(
    '                _, { } witness, { }) => WorkerProtocolJson.HasValidEffectWitness(witness) &&')
$modelLines.Add(
    '                    WorkerProtocolJson.HasValidLocation(witness.Location),')
$modelLines.Add('            (WorkerClaimOutcome.Unknown,')
for ($index = 0; $index -lt $unknownReasons.Count; $index++) {
    $reason = [string]$unknownReasons[$index]
    $suffix = if ($index -lt $unknownReasons.Count - 1) { ' or' } else { ',' }
    $modelLines.Add("                WorkerClaimReason.$reason$suffix")
}
$modelLines.Add('                _, null, null) => true,')
$modelLines.Add('            _ => false')
$modelLines.Add('        };')
$modelLines.Add('')
$modelLines.Add('    private static bool HasValidConstraint(')
$modelLines.Add('        WorkerEffectContractKind kind,')
$modelLines.Add('        CompilerEffectConstraintArtifact? constraint) {')
$modelLines.Add('        if (constraint == null ||')
$modelLines.Add('            !WorkerProtocolJson.HasKnownEffects(')
$modelLines.Add(
    '                constraint.AllowedEffects, constraint.AllowedCapabilities) ||')
$modelLines.Add(
    '            !WorkerProtocolJson.AreDistinctNonblank(constraint.AllowedExceptionTypes))')
$modelLines.Add('            return false;')
$modelLines.Add('        return kind switch {')
$modelLines.Add("            WorkerEffectContractKind.$capabilitiesKind =>")
$modelLines.Add(
    '                constraint.AllowedEffects == WorkerEffectSet.None &&')
$modelLines.Add('                constraint.AllowedExceptionTypes.Length == 0,')
$modelLines.Add("            WorkerEffectContractKind.$exceptionsKind =>")
$modelLines.Add(
    '                constraint.AllowedEffects == WorkerEffectSet.None &&')
$modelLines.Add(
    '                constraint.AllowedCapabilities == WorkerEffectCapabilitySet.None,')
$modelLines.Add("            WorkerEffectContractKind.$combinedKind => true,")
$modelLines.Add('            _ => constraint.AllowedEffects == WorkerEffectSet.None &&')
$modelLines.Add(
    '                constraint.AllowedCapabilities == WorkerEffectCapabilitySet.None &&')
$modelLines.Add('                constraint.AllowedExceptionTypes.Length == 0')
$modelLines.Add('        };')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add(
    '    private static bool HasValidReplay(CompilerEffectClaimArtifact value) {')
$modelLines.Add('        var replay = value.Replay;')
$modelLines.Add('        if (replay == null)')
$modelLines.Add('            return value.Outcome != WorkerClaimOutcome.Refuted;')
$modelLines.Add('        if (value.Outcome != WorkerClaimOutcome.Refuted ||')
$modelLines.Add(
    "            replay.PathKind != CompilerEffectReplayPathKind.$replayPathKind ||")
$modelLines.Add(
    "            replay.Events is not { Length: > 0 and <= $maximumReplayEvents } ||")
$modelLines.Add(
    '            replay.ConstraintSha256 != ComputeConstraintSha256(value.ContractKind, value.Constraint))')
$modelLines.Add('            return false;')
$modelLines.Add('        return replay.Events.Select((item, index) =>')
$modelLines.Add('                HasValidReplayEvent(item, index)).All(static valid => valid);')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add(
    '    private static bool HasValidReplayEvent(CompilerEffectReplayEventArtifact? value, int ordinal) {')
$supportedKindExpression = ($supportedReplayEventKinds |
    ForEach-Object { "CompilerEffectReplayEventKind.$_" }) -join ' or '
$modelLines.Add('        if (value == null || value.Ordinal != ordinal ||')
$modelLines.Add("            value.Kind is not ($supportedKindExpression) ||")
$modelLines.Add('            value.SyntaxTreeOrdinal < 0 ||')
$modelLines.Add(
    '            !WorkerProtocolJson.IsSha256(value.SyntaxTreeSha256) ||')
$modelLines.Add('            value.SyntaxStart < 0 || value.SyntaxLength <= 0 ||')
$modelLines.Add(
    '            value.SyntaxStart > int.MaxValue - value.SyntaxLength ||')
$modelLines.Add(
    '            value.OperationIdentitySha256 != ComputeReplayOperationSha256(value) ||')
$modelLines.Add('            string.IsNullOrWhiteSpace(value.TypeIdentity) ||')
$modelLines.Add(
    '            !HasOptionalText(value.MemberDocumentationId) ||')
$modelLines.Add(
    '            !HasOptionalText(value.TypeDocumentationId) ||')
$modelLines.Add(
    '            !HasOptionalText(value.SpecWitnessIdentifier) ||')
$modelLines.Add('            value.ScalarOperands is not { Length: 0 } ||')
$modelLines.Add(
    '            value.ExactExceptionTypeHierarchy is not { Length: 0 } ||')
$modelLines.Add(
    '            !WorkerProtocolJson.HasValidLocation(value.Location) ||')
$modelLines.Add('            value.Location.Start != value.SyntaxStart ||')
$modelLines.Add('            value.Location.Length != value.SyntaxLength)')
$modelLines.Add('            return false;')
$modelLines.Add('        return value.Kind switch {')
$modelLines.Add(
    '            CompilerEffectReplayEventKind.ManagedObjectAllocation =>')
$modelLines.Add('                !string.IsNullOrWhiteSpace(value.MemberIdentity) &&')
$modelLines.Add('                value.SpecWitnessIdentifier == null,')
$modelLines.Add(
    '            CompilerEffectReplayEventKind.ManagedArrayAllocation =>')
$modelLines.Add('                string.IsNullOrEmpty(value.MemberIdentity) &&')
$modelLines.Add('                value.MemberDocumentationId == null &&')
$modelLines.Add('                value.SpecWitnessIdentifier == null,')
$modelLines.Add('            _ => false')
$modelLines.Add('        };')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add('    private static bool HasOptionalText(string? value) =>')
$modelLines.Add('        value == null || !string.IsNullOrWhiteSpace(value);')
$modelLines.Add('')
$modelLines.Add('    internal static string ComputeConstraintSha256(')
$modelLines.Add('        WorkerEffectContractKind kind,')
$modelLines.Add('        CompilerEffectConstraintArtifact constraint) {')
$modelLines.Add('        if (constraint == null)')
$modelLines.Add('            throw new ArgumentNullException(nameof(constraint));')
$modelLines.Add('        using var hash = new CanonicalHashWriter();')
$modelLines.Add(
    '        hash.Add("SharpProof.CompilerEffectReplayConstraint", 1, kind,')
$modelLines.Add(
    '            constraint.AllowedEffects, constraint.AllowedCapabilities);')
$modelLines.Add('        foreach (var type in (constraint.AllowedExceptionTypes ?? [])')
$modelLines.Add(
    '                     .OrderBy(static item => item, StringComparer.Ordinal))')
$modelLines.Add('            hash.Add(type);')
$modelLines.Add('        return hash.Finish();')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add('    internal static string ComputeReplayOperationSha256(')
$modelLines.Add('        CompilerEffectReplayEventArtifact value) {')
$modelLines.Add('        if (value == null)')
$modelLines.Add('            throw new ArgumentNullException(nameof(value));')
$modelLines.Add('        var location = value.Location;')
$modelLines.Add('        using var hash = new CanonicalHashWriter();')
$modelLines.Add(
    '        hash.Add("SharpProof.CompilerEffectReplayOperation", 1, value.Kind,')
$modelLines.Add(
    '            value.SyntaxTreeOrdinal, value.SyntaxTreeSha256, value.SyntaxStart,')
$modelLines.Add(
    '            value.SyntaxLength, value.MemberIdentity, value.MemberDocumentationId,')
$modelLines.Add(
    '            value.TypeIdentity, value.TypeDocumentationId, value.SpecWitnessIdentifier);')
$modelLines.Add('        hash.Add((value.ScalarOperands ?? []).Length);')
$modelLines.Add('        foreach (var operand in value.ScalarOperands ?? [])')
$modelLines.Add('            hash.Add(operand);')
$modelLines.Add('        hash.Add((value.ExactExceptionTypeHierarchy ?? []).Length);')
$modelLines.Add('        foreach (var type in value.ExactExceptionTypeHierarchy ?? [])')
$modelLines.Add('            hash.Add(type);')
$modelLines.Add('        return hash.Add(location?.Path, location?.Start ?? -1,')
$modelLines.Add('            location?.Length ?? -1, location?.Line ?? -1,')
$modelLines.Add('            location?.Column ?? -1).Finish();')
$modelLines.Add('    }')
$modelLines.Add('')
$modelLines.Add(
    '    private static string ComputeSha256(CompilerEffectClaimArtifact value) {')
$modelLines.Add('        var witness = value.Witness;')
$modelLines.Add('        var constraint = value.Constraint;')
$modelLines.Add('        using var hash = new CanonicalHashWriter();')
$modelLines.Add(
    "        hash.Add($(ConvertTo-CSharpString $domain), $evidenceVersion, value.ClaimId,")
$modelLines.Add(
    '            value.ContractKind, value.Outcome, value.Reason, value.Certainty,')
$modelLines.Add(
    '            constraint.AllowedEffects, constraint.AllowedCapabilities);')
$modelLines.Add(
    '        foreach (var type in constraint.AllowedExceptionTypes')
$modelLines.Add(
    '                     .OrderBy(static item => item, StringComparer.Ordinal))')
$modelLines.Add('            hash.Add(type);')
$modelLines.Add(
    '        hash.Add(witness?.Kind, witness?.Detail, witness?.Effects ?? WorkerEffectSet.None,')
$modelLines.Add(
    '            witness?.Capabilities ?? WorkerEffectCapabilitySet.None);')
$modelLines.Add(
    '        foreach (var type in (witness?.ExactExceptionTypeHierarchy ?? [])')
$modelLines.Add(
    '                     .OrderBy(static item => item, StringComparer.Ordinal))')
$modelLines.Add('            hash.Add(type);')
$modelLines.Add('        var replay = value.Replay;')
$modelLines.Add('        hash.Add(replay != null,')
$modelLines.Add(
    '            replay?.PathKind ?? CompilerEffectReplayPathKind.Unspecified,')
$modelLines.Add('            replay?.ConstraintSha256, replay?.Events?.Length ?? -1);')
$modelLines.Add('        foreach (var effectEvent in replay?.Events ?? []) {')
$modelLines.Add('            hash.Add(effectEvent.Ordinal, effectEvent.Kind,')
$modelLines.Add(
    '                effectEvent.SyntaxTreeOrdinal, effectEvent.SyntaxTreeSha256,')
$modelLines.Add(
    '                effectEvent.SyntaxStart, effectEvent.SyntaxLength,')
$modelLines.Add(
    '                effectEvent.OperationIdentitySha256, effectEvent.MemberIdentity,')
$modelLines.Add(
    '                effectEvent.MemberDocumentationId, effectEvent.TypeIdentity,')
$modelLines.Add(
    '                effectEvent.TypeDocumentationId, effectEvent.SpecWitnessIdentifier);')
$modelLines.Add('            hash.Add((effectEvent.ScalarOperands ?? []).Length);')
$modelLines.Add('            foreach (var operand in effectEvent.ScalarOperands ?? [])')
$modelLines.Add('                hash.Add(operand);')
$modelLines.Add(
    '            hash.Add((effectEvent.ExactExceptionTypeHierarchy ?? []).Length);')
$modelLines.Add(
    '            foreach (var type in effectEvent.ExactExceptionTypeHierarchy ?? [])')
$modelLines.Add('                hash.Add(type);')
$modelLines.Add('            hash.Add(effectEvent.Location?.Path,')
$modelLines.Add('                effectEvent.Location?.Start ?? -1,')
$modelLines.Add('                effectEvent.Location?.Length ?? -1,')
$modelLines.Add('                effectEvent.Location?.Line ?? -1,')
$modelLines.Add('                effectEvent.Location?.Column ?? -1);')
$modelLines.Add('        }')
$modelLines.Add(
    '        return hash.Add(witness?.Location.Path, witness?.Location.Start ?? -1,')
$modelLines.Add(
    '            witness?.Location.Length ?? -1, witness?.Location.Line ?? -1,')
$modelLines.Add(
    '            witness?.Location.Column ?? -1, value.Evidence).Finish();')
$modelLines.Add('    }')
$modelLines.Add('}')

$outputs = [ordered]@{
    $ModelOutputPath = $modelLines
    $PortableOutputPath = $portableLines
    $CompilationOutputPath = $compilationLines
}
foreach ($output in $outputs.GetEnumerator()) {
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($output.Key)) |
        Out-Null
    Update-SharpProofGeneratedFile `
        -Path $output.Key `
        -Content ($output.Value -join "`n") `
        -DisplayPath $output.Key `
        -GeneratorCommand '.\scripts\Generate-CompilerArtifactModel.ps1' `
        -Verify:$Verify
}
$verb = if ($Verify) { 'Verified' } else { 'Generated' }
Write-Host "$verb deterministic compiler-artifact model."
