[CmdletBinding()]
param(
    [Parameter()][string]$SchemaPath,
    [Parameter()][string]$OutputPath,
    [Parameter()][Alias('Check')][switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'GeneratedFileHelpers.ps1')

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($SchemaPath)) {
    $SchemaPath = Join-Path $repositoryRoot 'SharpProof.Contracts\BoundContractModel.schema.json'
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $repositoryRoot 'SharpProof.Contracts\BoundContractModel.generated.cs'
}
$SchemaPath = [IO.Path]::GetFullPath($SchemaPath)
$OutputPath = [IO.Path]::GetFullPath($OutputPath)
$schema = Get-Content -LiteralPath $SchemaPath -Raw | ConvertFrom-Json

function Get-RequiredProperty([object]$Object, [string]$Name, [string]$Context) {
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property -or $null -eq $property.Value) {
        throw "$Context must define '$Name'."
    }
    return $property.Value
}

if ([int](Get-RequiredProperty $schema 'schemaVersion' 'Bound contract model') -ne 1) {
    throw 'Bound contract model schema version must be 1.'
}
if ([string](Get-RequiredProperty $schema 'namespace' 'Bound contract model') -ne
    'SharpProof.Contracts') {
    throw 'Bound contract model namespace must be SharpProof.Contracts.'
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated>')
$lines.Add('// Generated by scripts/Generate-BoundContractModel.ps1 from')
$lines.Add('// SharpProof.Contracts/BoundContractModel.schema.json.')
$lines.Add('// Declarative bound-contract vocabulary and storage only.')
$lines.Add('// Do not edit this file directly.')
$lines.Add('// </auto-generated>')
$lines.Add('#nullable enable')
$lines.Add('')
$lines.Add('namespace SharpProof.Contracts;')

foreach ($enum in @($schema.enums)) {
    $name = [string](Get-RequiredProperty $enum 'name' 'Bound contract enum')
    Assert-Identifier $name 'Bound contract enum name'
    $members = @(Get-RequiredProperty $enum 'members' "enum '$name'")
    if ($members.Count -eq 0) {
        throw "enum '$name' must define members."
    }
    $lines.Add('')
    $lines.Add("public enum $name")
    $lines.Add('{')
    for ($index = 0; $index -lt $members.Count; $index++) {
        $member = [string]$members[$index]
        Assert-Identifier $member "enum '$name' member"
        $suffix = if ($index -lt $members.Count - 1) { ',' } else { '' }
        $lines.Add("    $member$suffix")
    }
    $lines.Add('}')
}

foreach ($class in @($schema.classes)) {
    $name = [string](Get-RequiredProperty $class 'name' 'Bound contract class')
    Assert-Identifier $name 'Bound contract class name'
    $constructor = Get-RequiredProperty $class 'constructor' "class '$name'"
    $access = [string](Get-RequiredProperty $constructor 'access' "class '$name' constructor")
    if ($access -notin @('internal', 'public')) {
        throw "class '$name' has unsupported constructor access '$access'."
    }
    $parameters = @(Get-RequiredProperty $constructor 'parameters' "class '$name' constructor")
    $assignments = @(Get-RequiredProperty $constructor 'assignments' "class '$name' constructor")
    if ($parameters.Count -ne $assignments.Count) {
        throw "class '$name' constructor assignments must match parameters."
    }
    $lines.Add('')
    $lines.Add("public sealed class $name")
    $lines.Add('{')
    $lines.Add("    $access $name(")
    for ($index = 0; $index -lt $parameters.Count; $index++) {
        $parameter = $parameters[$index]
        $type = [string](Get-RequiredProperty $parameter 'type' "class '$name' parameter")
        $parameterName = [string](Get-RequiredProperty $parameter 'name' "class '$name' parameter")
        Assert-TypeName $type "class '$name' parameter type"
        Assert-Identifier $parameterName "class '$name' parameter name"
        $comma = if ($index -lt $parameters.Count - 1) { ',' } else { '' }
        $lines.Add("        $type $parameterName$comma")
    }
    $lines.Add('    )')
    $lines.Add('    {')
    foreach ($assignment in $assignments) {
        $propertyName = [string]$assignment
        Assert-Identifier $propertyName "class '$name' assignment"
        $parameter = @($parameters | Where-Object {
            [string]$_.name -eq ($propertyName.Substring(0, 1).ToLowerInvariant() + $propertyName.Substring(1))
        })
        if ($parameter.Count -ne 1) {
            throw "class '$name' assignment '$propertyName' has no matching parameter."
        }
        $lines.Add("        $propertyName = $($parameter[0].name);")
    }
    $lines.Add('    }')
    foreach ($property in @(Get-RequiredProperty $class 'properties' "class '$name'")) {
        $propertyName = [string](Get-RequiredProperty $property 'name' "class '$name' property")
        $type = [string](Get-RequiredProperty $property 'type' "class '$name' property")
        Assert-Identifier $propertyName "class '$name' property name"
        Assert-TypeName $type "class '$name' property type"
        $lines.Add("    public $type $propertyName { get; }")
    }
    $projectionProperty = $class.PSObject.Properties['projections']
    $projections = if ($null -eq $projectionProperty) {
        @()
    }
    else {
        @($projectionProperty.Value)
    }
    foreach ($projection in $projections) {
        $propertyName = [string](Get-RequiredProperty $projection 'name' "class '$name' projection")
        $type = [string](Get-RequiredProperty $projection 'type' "class '$name' projection")
        $expression = [string](Get-RequiredProperty $projection 'expression' "class '$name' projection")
        Assert-Identifier $propertyName "class '$name' projection name"
        Assert-TypeName $type "class '$name' projection type"
        if ($expression -notmatch '^[A-Za-z_][A-Za-z0-9_ .?=<>|&!()]+$') {
            throw "class '$name' projection expression is not approved."
        }
        $lines.Add("    public $type $propertyName => $expression;")
    }
    $lines.Add('}')
}

Update-SharpProofGeneratedFile `
    -Path $OutputPath `
    -Content ($lines -join "`n") `
    -DisplayPath 'SharpProof.Contracts/BoundContractModel.generated.cs' `
    -GeneratorCommand '.\scripts\Generate-BoundContractModel.ps1' `
    -Verify:$Verify
$verb = if ($Verify) { 'Verified' } else { 'Generated' }
Write-Host "$verb deterministic bound-contract model."
