[CmdletBinding()]
param(
    [Parameter()][string]$SchemaPath,
    [Parameter()][Alias('OutputPath')][string]$ModelOutputPath,
    [Parameter()][string]$PortableOutputPath,
    [Parameter()][string]$CompilationOutputPath,
    [Parameter()][string]$CollectorOutputPath,
    [Parameter()][Alias('Check')][switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'GeneratedFileHelpers.ps1')

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ([string]::IsNullOrWhiteSpace($SchemaPath)) {
    $SchemaPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerArtifactModel.schema.json'
}
if ([string]::IsNullOrWhiteSpace($ModelOutputPath)) {
    $ModelOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerArtifactModel.generated.cs'
}
if ([string]::IsNullOrWhiteSpace($PortableOutputPath)) {
    $PortableOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\PortableIrModel.generated.cs'
}
if ([string]::IsNullOrWhiteSpace($CompilationOutputPath)) {
    $CompilationOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerArtifact\CompilerCompilationModel.generated.cs'
}
if ([string]::IsNullOrWhiteSpace($CollectorOutputPath)) {
    $CollectorOutputPath = Join-Path $repositoryRoot `
        'SharpProof.CompilerCollector\CompilerArtifact\CompilerWireMappings.generated.cs'
}
$SchemaPath = [IO.Path]::GetFullPath($SchemaPath)
$ModelOutputPath = [IO.Path]::GetFullPath($ModelOutputPath)
$PortableOutputPath = [IO.Path]::GetFullPath($PortableOutputPath)
$CompilationOutputPath = [IO.Path]::GetFullPath($CompilationOutputPath)
$CollectorOutputPath = [IO.Path]::GetFullPath($CollectorOutputPath)
if (-not [IO.File]::Exists($SchemaPath)) {
    throw "Compiler-artifact schema not found: $SchemaPath"
}

function Get-RequiredMember {
    param([object]$Object, [string]$Name, [string]$Context)

    $member = $Object.PSObject.Properties[$Name]
    if ($null -eq $member -or $null -eq $member.Value) {
        throw "$Context must define '$Name'."
    }
    return $member.Value
}

function Get-MemberArray {
    param([object]$Object, [string]$Name)

    $member = $Object.PSObject.Properties[$Name]
    if ($null -eq $member -or $null -eq $member.Value) {
        return @()
    }
    return @($member.Value)
}

function Assert-Properties {
    param(
        [object]$Object,
        [string[]]$Allowed,
        [string]$Context)

    $actual = @($Object.PSObject.Properties.Name)
    foreach ($name in $actual) {
        if ($name -notin $Allowed) {
            throw "$Context contains unsupported property '$name'."
        }
    }
    foreach ($name in $Allowed) {
        if ($name -notin $actual) {
            throw "$Context is missing required property '$name'."
        }
    }
}

function Assert-Identifier {
    param([string]$Value, [string]$Context)

    if ($Value -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
        throw "$Context is not a C# identifier: '$Value'."
    }
}

function Assert-TypeName {
    param([string]$Value, [string]$Context)

    if ($Value -notmatch '^[A-Za-z_][A-Za-z0-9_?.<>, \[\]]*$') {
        throw "$Context is not a supported C# type: '$Value'."
    }
}

function ConvertTo-CSharpString {
    param([string]$Value)

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function New-GeneratedOutput {
    param([string]$OutputName)

    $result = [Collections.Generic.List[string]]::new()
    $result.Add('// <auto-generated>')
    $result.Add('// Generated by scripts/Generate-CompilerArtifactModel.ps1 from')
    $result.Add('// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.')
    $result.Add("// Output: $OutputName.")
    $result.Add('// Do not edit this file directly.')
    $result.Add('// </auto-generated>')
    $result.Add('#nullable enable')
    $result.Add('')
    $result.Add('namespace SharpProof.CompilerArtifact;')
    return ,$result
}

function Get-ParameterSource {
    param([object[]]$Parameters, [string]$Context)

    $sources = @()
    $names = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($parameter in $Parameters) {
        $name = [string](Get-RequiredMember $parameter 'name' $Context)
        $type = [string](Get-RequiredMember $parameter 'type' $Context)
        Assert-Identifier $name "$Context parameter"
        Assert-TypeName $type "$Context parameter '$name'"
        if (-not $names.Add($name)) {
            throw "$Context repeats parameter '$name'."
        }
        $defaultMember = $parameter.PSObject.Properties['default']
        $default = if ($null -eq $defaultMember) {
            ''
        }
        else {
            $value = [string]$defaultMember.Value
            if ($value -notmatch '^(default|null|false|true|-?[0-9]+)$') {
                throw "$Context parameter '$name' has an invalid default."
            }
            " = $value"
        }
        $sources += "$type $name$default"
    }
    return $sources
}

function Add-ParameterList {
    param(
        [Collections.Generic.List[string]]$Lines,
        [string]$Prefix,
        [object[]]$Parameters,
        [string]$Suffix,
        [string]$Context
    )

    $sources = @(Get-ParameterSource $Parameters $Context)
    if ($sources.Count -eq 0) {
        $Lines.Add("$Prefix$Suffix")
        return
    }
    $Lines.Add("$Prefix(")
    for ($index = 0; $index -lt $sources.Count; $index++) {
        $comma = if ($index -lt $sources.Count - 1) { ',' } else { '' }
        $Lines.Add("    $($sources[$index])$comma")
    }
    $Lines.Add(")$Suffix")
}

function Get-InitializerSource {
    param(
        [object]$Default,
        [Collections.Generic.HashSet[string]]$ConstructorParameters,
        [string]$Context
    )

    $kind = [string](Get-RequiredMember $Default 'kind' $Context)
    switch ($kind) {
        'implicit' { return '' }
        'stringEmpty' { return ' = string.Empty' }
        'new' { return ' = new()' }
        'emptyArray' { return ' = []' }
        'literal' {
            $value = [string](Get-RequiredMember $Default 'value' $Context)
            if ($value -notmatch '^-?[0-9]+$') {
                throw "$Context has an invalid literal initializer."
            }
            return " = $value"
        }
        'member' {
            $value = [string](Get-RequiredMember $Default 'value' $Context)
            if ($value -notmatch '^[A-Za-z_][A-Za-z0-9_.]*$') {
                throw "$Context has an invalid member initializer."
            }
            return " = $value"
        }
        { $_ -in 'parameter', 'parameterOrStringEmpty', 'parameterOrEmptyArray' } {
            $name = [string](Get-RequiredMember $Default 'name' $Context)
            if (-not $ConstructorParameters.Contains($name)) {
                throw "$Context references unknown constructor parameter '$name'."
            }
            $expression = switch ($kind) {
                'parameter' { $name }
                'parameterOrStringEmpty' { "$name ?? string.Empty" }
                'parameterOrEmptyArray' { "$name ?? []" }
            }
            return " = $expression"
        }
        default { throw "$Context has unsupported default kind '$kind'." }
    }
}

function Add-Properties {
    param(
        [Collections.Generic.List[string]]$Lines,
        [object[]]$Properties,
        [Collections.Generic.HashSet[string]]$ConstructorParameters,
        [string]$TypeName,
        [string]$JsonNamingPolicy
    )

    $names = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    $jsonNames = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($property in $Properties) {
        $name = [string](
            Get-RequiredMember $property 'name' "type '$TypeName' property")
        $type = [string](
            Get-RequiredMember $property 'type' "property '$TypeName.$name'")
        $accessibility = [string](
            Get-RequiredMember $property 'accessibility' "property '$TypeName.$name'")
        $setter = [string](
            Get-RequiredMember $property 'set' "property '$TypeName.$name'")
        Assert-Identifier $name "Type '$TypeName' property"
        Assert-TypeName $type "Property '$TypeName.$name'"
        if (-not $names.Add($name)) {
            throw "Type '$TypeName' repeats property '$name'."
        }
        if ($accessibility -notin 'public', 'internal') {
            throw "Property '$TypeName.$name' has invalid accessibility."
        }
        if ($setter -notin 'set', 'init', 'none') {
            throw "Property '$TypeName.$name' has invalid setter."
        }
        $jsonMember = $property.PSObject.Properties['jsonName']
        if ($accessibility -eq 'public') {
            if ($null -eq $jsonMember -or [string]::IsNullOrWhiteSpace(
                    [string]$jsonMember.Value)) {
                throw "Public property '$TypeName.$name' must define its JSON name."
            }
            $jsonName = [string]$jsonMember.Value
            $expected = $name.Substring(0, 1).ToLowerInvariant() +
                $name.Substring(1)
            if ($JsonNamingPolicy -ne 'camelCase' -or
                $jsonName -ne $expected -or
                -not $jsonNames.Add($jsonName)) {
                throw "Property '$TypeName.$name' has an invalid JSON name."
            }
        }
        elseif ($null -ne $jsonMember) {
            throw "Internal property '$TypeName.$name' cannot define a JSON name."
        }
        $default = Get-RequiredMember $property 'default' "property '$TypeName.$name'"
        $initializer = Get-InitializerSource `
            $default $ConstructorParameters "property '$TypeName.$name'"
        $accessors = switch ($setter) {
            'set' { '{ get; set; }' }
            'init' { '{ get; init; }' }
            'none' { '{ get; }' }
        }
        $terminator = if ($initializer.Length -eq 0) { '' } else { ';' }
        $Lines.Add(
            "    $accessibility $type $name $accessors$initializer$terminator")
    }
}

function Add-RecordMembers {
    param(
        [Collections.Generic.List[string]]$Lines,
        [object[]]$Members,
        [string]$TypeName
    )

    foreach ($member in $Members) {
        $kind = [string](
            Get-RequiredMember $member 'kind' "record '$TypeName' member")
        $name = [string](
            Get-RequiredMember $member 'name' "record '$TypeName' member")
        $type = [string](
            Get-RequiredMember $member 'type' "record '$TypeName.$name'")
        $accessibility = [string](
            Get-RequiredMember $member 'accessibility' "record '$TypeName.$name'")
        Assert-Identifier $name "Record '$TypeName' member"
        Assert-TypeName $type "Record '$TypeName.$name'"
        if ($accessibility -notin 'public', 'internal') {
            throw "Record '$TypeName.$name' has invalid accessibility."
        }
        if ($kind -eq 'computedProperty') {
            $operation = [string](
                Get-RequiredMember $member 'operation' "record '$TypeName.$name'")
            $source = [string](
                Get-RequiredMember $member 'source' "record '$TypeName.$name'")
            $value = [string](
                Get-RequiredMember $member 'value' "record '$TypeName.$name'")
            if ($operation -ne 'equals' -or
                $source -notmatch '^[A-Za-z_][A-Za-z0-9_]*$' -or
                $value -notmatch '^[A-Za-z_][A-Za-z0-9_.]*$') {
                throw "Record '$TypeName.$name' has invalid computed semantics."
            }
            $Lines.Add("    $accessibility $type $name => $source == $value;")
        }
        elseif ($kind -eq 'property') {
            $setter = [string](
                Get-RequiredMember $member 'set' "record '$TypeName.$name'")
            if ($setter -notin 'set', 'init') {
                throw "Record '$TypeName.$name' has invalid setter."
            }
            $default = Get-RequiredMember `
                $member 'default' "record '$TypeName.$name'"
            $empty = [Collections.Generic.HashSet[string]]::new(
                [StringComparer]::Ordinal)
            $initializer = Get-InitializerSource `
                $default $empty "record '$TypeName.$name'"
            $Lines.Add(
                "    $accessibility $type $name { get; $setter; }$initializer;")
        }
        else {
            throw "Record '$TypeName.$name' has unsupported kind '$kind'."
        }
    }
}

$schema = Get-Content -LiteralPath $SchemaPath -Raw |
    ConvertFrom-Json -Depth 100
if ([int](Get-RequiredMember $schema 'schemaVersion' 'schema') -ne 1) {
    throw 'Only compiler-artifact model schema version 1 is supported.'
}
$namespace = [string](Get-RequiredMember $schema 'namespace' 'schema')
$jsonNamingPolicy = [string](
    Get-RequiredMember $schema 'jsonNamingPolicy' 'schema')
if ($jsonNamingPolicy -ne 'camelCase') {
    throw "Unsupported JSON naming policy '$jsonNamingPolicy'."
}
$declarations = @(Get-RequiredMember $schema 'declarations' 'schema')
$declarationNames = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
if ($namespace -ne 'SharpProof.CompilerArtifact') {
    throw "Unsupported compiler-artifact namespace '$namespace'."
}
$modelLines = New-GeneratedOutput 'CompilerArtifactModel.generated.cs'
$portableLines = New-GeneratedOutput 'PortableIrModel.generated.cs'
$compilationLines = New-GeneratedOutput 'CompilerCompilationModel.generated.cs'
$collectorLines = New-GeneratedOutput 'CompilerWireMappings.generated.cs'

foreach ($declaration in $declarations) {
    $kind = [string](Get-RequiredMember $declaration 'kind' 'declaration')
    $name = [string](Get-RequiredMember $declaration 'name' 'declaration')
    Assert-Identifier $name 'Declaration name'
    if (-not $declarationNames.Add($name)) {
        throw "Duplicate compiler-artifact declaration '$name'."
    }
    $lines = if ($name -match '^PortableIr' -or
        $name -in 'DecodedPortableIrGraph', 'EncodedPortableIrGraph') {
        ,$portableLines
    }
    elseif ($name -in @(
            'CompilerCompilationSnapshot',
            'CompilerCompilationOptionsSnapshot',
            'CompilerSyntaxTreeSnapshot',
            'CompilerReferenceSnapshot',
            'CompilerAdditionalFileSnapshot',
            'CompilerFeatureSnapshot')) {
        ,$compilationLines
    }
    else {
        ,$modelLines
    }
    $lines.Add('')
    if ($kind -eq 'staticClass') {
        $lines.Add("internal static class $name {")
        foreach ($constant in @(Get-RequiredMember `
                $declaration 'constants' "static class '$name'")) {
            $constantName = [string](
                Get-RequiredMember $constant 'name' "static class '$name'")
            $type = [string](
                Get-RequiredMember $constant 'type' "constant '$name.$constantName'")
            $accessibility = [string](
                Get-RequiredMember $constant 'accessibility' "constant '$name.$constantName'")
            Assert-Identifier $constantName "Constant '$name'"
            if ($accessibility -ne 'internal' -or $type -notin 'string', 'int') {
                throw "Constant '$name.$constantName' has unsupported shape."
            }
            $value = Get-RequiredMember `
                $constant 'value' "constant '$name.$constantName'"
            $source = if ($type -eq 'string') {
                ConvertTo-CSharpString ([string]$value)
            }
            else {
                ([Convert]::ToInt32(
                    $value,
                    [Globalization.CultureInfo]::InvariantCulture)
                ).ToString([Globalization.CultureInfo]::InvariantCulture)
            }
            $lines.Add("    internal const $type $constantName = $source;")
        }
        $lines.Add('}')
        continue
    }
    if ($kind -eq 'enum') {
        $members = @(Get-RequiredMember $declaration 'members' "enum '$name'")
        $memberNames = [Collections.Generic.HashSet[string]]::new(
            [StringComparer]::Ordinal)
        $lines.Add("internal enum $name {")
        for ($index = 0; $index -lt $members.Count; $index++) {
            $member = $members[$index]
            $memberName = [string](
                Get-RequiredMember $member 'name' "enum '$name' member")
            Assert-Identifier $memberName "Enum '$name' member"
            if (-not $memberNames.Add($memberName)) {
                throw "Enum '$name' repeats member '$memberName'."
            }
            $value = [int](
                Get-RequiredMember $member 'value' "enum '$name.$memberName'")
            if ($value -ne $index) {
                throw "Enum '$name.$memberName' must use its declared wire ordinal."
            }
            $comma = if ($index -lt $members.Count - 1) { ',' } else { '' }
            $lines.Add("    $memberName = $value$comma")
        }
        $lines.Add('}')
        continue
    }
    if ($kind -in 'record', 'recordStruct', 'preparedBodyRecord') {
        $parameters = @(
            Get-RequiredMember $declaration 'parameters' "record '$name'")
        $prefix = if ($kind -eq 'recordStruct') {
            $readonly = [bool](
                Get-RequiredMember $declaration 'readonly' "record '$name'")
            if (-not $readonly) {
                throw "Record struct '$name' must be readonly."
            }
            "internal readonly record struct $name"
        }
        else {
            "internal sealed record $name"
        }
        $members = @(Get-MemberArray $declaration 'members')
        $hasBody = $members.Count -ne 0 -or $kind -eq 'preparedBodyRecord'
        Add-ParameterList `
            $lines $prefix $parameters $(if ($hasBody) { ' {' } else { ';' }) `
            "record '$name'"
        if (-not $hasBody) {
            continue
        }
        if ($kind -eq 'preparedBodyRecord') {
            $maximumInstructions = [int](
                Get-RequiredMember `
                    $declaration 'maximumInstructions' "record '$name'")
            if ($maximumInstructions -ne 4096) {
                throw "Record '$name' must preserve its replay instruction bound."
            }
            $lines.Add(
                "    internal const int MaximumInstructions = $maximumInstructions;")
            $lines.Add('')
            $lines.Add('    internal static CompilerPreparedBody Trivial() =>')
            $lines.Add('        new(')
            $lines.Add('            CompilerPreparedBodyKind.Trivial,')
            $lines.Add('            null,')
            $lines.Add('            ImmutableDictionary<IrVarId, IrVarId>.Empty,')
            $lines.Add(
                '            ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall>.Empty);')
            $lines.Add('')
            $lines.Add('    internal static CompilerPreparedBody ProgramBody(')
            $lines.Add('        IrProgram program,')
            $lines.Add(
                '        ImmutableDictionary<IrVarId, IrVarId> parameterBindings,')
            $lines.Add(
                '        ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> specCalls) =>')
            $lines.Add('        new(')
            $lines.Add('            CompilerPreparedBodyKind.Program,')
            $lines.Add(
                '            program ?? throw new ArgumentNullException(nameof(program)),')
            $lines.Add('            parameterBindings,')
            $lines.Add('            specCalls);')
        }
        else {
            Add-RecordMembers $lines $members $name
        }
        $lines.Add('}')
        continue
    }
    if ($kind -ne 'class') {
        throw "Unsupported compiler-artifact declaration kind '$kind'."
    }
    $parameters = @(Get-MemberArray $declaration 'constructor')
    $parameterNames = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    foreach ($parameter in $parameters) {
        [void]$parameterNames.Add([string](
            Get-RequiredMember $parameter 'name' "class '$name' constructor"))
    }
    if ($parameters.Count -eq 0) {
        $lines.Add("internal sealed class $name {")
    }
    else {
        Add-ParameterList `
            $lines "internal sealed class $name" $parameters ' {' "class '$name'"
    }
    Add-Properties `
        $lines @(Get-RequiredMember $declaration 'properties' "class '$name'") `
        $parameterNames $name $jsonNamingPolicy
    $lines.Add('}')
}

$envelope = Get-RequiredMember $schema 'artifactEnvelope' 'schema'
if ([string](Get-RequiredMember $envelope 'schema' 'artifact envelope') -ne
        'SharpProof.CompilerManifest' -or
    [int](Get-RequiredMember $envelope 'version' 'artifact envelope') -ne 9) {
    throw 'The compiler-artifact envelope must remain schema version 9.'
}

$catalogs = @(Get-RequiredMember $schema 'wireEnumCatalogs' 'schema')
$catalogFields = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
$portableLines.Add('')
$portableLines.Add('internal static class PortableIrWireCatalog {')
foreach ($catalog in $catalogs) {
    $field = [string](Get-RequiredMember $catalog 'field' 'wire enum catalog')
    $type = [string](Get-RequiredMember $catalog 'type' "wire catalog '$field'")
    Assert-Identifier $field 'Wire catalog field'
    Assert-TypeName $type "Wire catalog '$field'"
    if (-not $catalogFields.Add($field)) {
        throw "Duplicate wire catalog '$field'."
    }
    $members = @(Get-RequiredMember $catalog 'members' "wire catalog '$field'")
    if ($members.Count -eq 0) {
        throw "Wire catalog '$field' cannot be empty."
    }
    $portableLines.Add("    internal static readonly $type[] $field = [")
    for ($index = 0; $index -lt $members.Count; $index++) {
        $member = [string]$members[$index]
        Assert-Identifier $member "Wire catalog '$field' member"
        $comma = if ($index -lt $members.Count - 1) { ',' } else { '' }
        $portableLines.Add("        $type.$member$comma")
    }
    $portableLines.Add('    ];')
}
$portableLines.Add('}')

$slotMappings = Get-RequiredMember $schema `
    'portableIrSlotMappings' 'schema'
$portableLines.Add('')
$portableLines.Add('internal readonly struct PortableIrSlotMapping(')
$portableLines.Add('    string kind,')
$portableLines.Add('    string[] slots)')
$portableLines.Add('{')
$portableLines.Add('    internal string Kind { get; } = kind;')
$portableLines.Add('    internal string[] Slots { get; } = slots;')
$portableLines.Add('}')
$slotDomains = @(
    [pscustomobject]@{
        Key = 'terms'
        Name = 'Terms'
        Enum = 'IrTermKind'
        Kinds = @(
            'Boolean', 'Integer', 'String', 'Null', 'Variable', 'Opaque',
            'Unary', 'Binary', 'Conditional', 'Cast', 'Length', 'SequenceAccess')
        Slots = @('a', 'b', 'c', 'd', 'number', 'text', 'items')
    },
    [pscustomobject]@{
        Key = 'locations'
        Name = 'Locations'
        Enum = 'IrLocationKind'
        Kinds = @('Member', 'Sequence')
        Slots = @('a', 'b', 'c', 'd', 'items')
    },
    [pscustomobject]@{
        Key = 'instructions'
        Name = 'Instructions'
        Enum = 'IrInstructionKind'
        Kinds = @(
            'Assign', 'Load', 'Store', 'Call', 'Assume', 'Assert', 'Havoc',
            'Branch', 'Goto', 'Return')
        Slots = @('a', 'b', 'c', 'd', 'items', 'location')
    })
$allowedSlotRoles = @(
    'unused',
    'empty',
    'booleanValue',
    'integerValue',
    'stringValue',
    'variableIndex',
    'variableIndices',
    'optionalVariableIndex',
    'memberIndex',
    'optionalTermIndex',
    'termIndex',
    'termIndices',
    'operationWhenImpure',
    'blockIndex',
    'location',
    'wire:OpaquePurities',
    'wire:UnaryOperators',
    'wire:BinaryOperators',
    'wire:HavocKinds')
$actualSlotDomains = @($slotMappings.PSObject.Properties.Name)
foreach ($domainName in $actualSlotDomains) {
    if ($domainName -notin $slotDomains.Key) {
        throw "Portable IR slot mappings contain unsupported domain '$domainName'."
    }
}
$slotDomainNames = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
$portableLines.Add('internal static class PortableIrSlotCatalog {')
foreach ($domain in $slotDomains) {
    if (-not $slotDomainNames.Add($domain.Key)) {
        throw "Duplicate portable IR slot domain '$($domain.Key)'."
    }
    $rows = @(Get-RequiredMember $slotMappings $domain.Key `
        "portable IR slot domain '$($domain.Key)'")
    if ($rows.Count -ne $domain.Kinds.Count) {
        throw (
            "Portable IR slot domain '$($domain.Key)' must contain " +
            "$($domain.Kinds.Count) rows.")
    }
    $portableLines.Add('')
    $portableLines.Add(
        "    internal static readonly PortableIrSlotMapping[] $($domain.Name) = [")
    for ($index = 0; $index -lt $rows.Count; $index++) {
        $row = $rows[$index]
        Assert-Properties `
            -Object $row `
            -Allowed @('kind', 'slots') `
            -Context "portable IR slot mapping '$($domain.Key)'"
        $kind = [string](Get-RequiredMember $row 'kind' `
            "portable IR slot mapping '$($domain.Key)'")
        if ($kind -ne $domain.Kinds[$index]) {
            throw (
                "Portable IR slot domain '$($domain.Key)' row $index " +
                "must describe '$($domain.Kinds[$index])'.")
        }
        $slots = @($row.slots | ForEach-Object { [string]$_ })
        if ($slots.Count -ne $domain.Slots.Count) {
            throw (
                "Portable IR slot mapping '$($domain.Key).$kind' must " +
                "define $($domain.Slots.Count) slots.")
        }
        for ($slotIndex = 0; $slotIndex -lt $slots.Count; $slotIndex++) {
            $role = $slots[$slotIndex]
            if ($role -notin $allowedSlotRoles) {
                throw (
                    "Portable IR slot mapping '$($domain.Key).$kind' " +
                    "has unsupported role '$role'.")
            }
            if ($role.StartsWith('wire:', [StringComparison]::Ordinal) -and
                -not $catalogFields.Contains($role.Substring(5))) {
                throw (
                    "Portable IR slot mapping '$($domain.Key).$kind' " +
                    "references missing wire catalog '$($role.Substring(5))'.")
            }
        }
        $slotLiterals = $slots | ForEach-Object {
            ConvertTo-CSharpString ([string]$_)
        }
        $portableLines.Add(
            '    new(' +
            (ConvertTo-CSharpString $kind) +
            ', [' +
            ($slotLiterals -join ', ') +
            ']),')
    }
    $portableLines.Add('    ];')
}
$portableLines.Add('}')

$portableProjectionSource = @'

internal static class PortableIrGraphCodecProjections
{
    internal static PortableIrTerm EncodeTerm(
        IrTerm term,
        Func<IrTypeId, int> typeIndex,
        Func<IrStringId, string> stringValue,
        Func<IrVarId, int> variableIndex,
        Func<IrTerm, int> termIndex,
        Func<IrMemberId, int> memberIndex,
        Func<OperationId, int> operationIndex,
        Func<IrTerm?, int> optionalTermIndex,
        Func<IEnumerable<IrTerm>, int[]> termIndices,
        Func<IrOpaquePurity, int> opaquePurity,
        Func<IrUnaryOperator, int> unaryOperator,
        Func<IrBinaryOperator, int> binaryOperator,
        Func<IrTerm, int, int, int, int, long, string?, int[]?, PortableIrTerm> row,
        Func<Exception> invalid)
    {
        return term switch
        {
            IrBooleanTerm value => row(term, value.Value ? 1 : 0, -1, -1, -1, 0, null, null),
            IrIntegerTerm value => row(term, -1, -1, -1, -1, value.Value, null, null),
            IrStringTerm value => row(term, -1, -1, -1, -1, 0, stringValue(value.Value), null),
            IrNullTerm => row(term, -1, -1, -1, -1, 0, null, null),
            IrVariableTerm value => row(term, variableIndex(value.Variable), -1, -1, -1, 0, null, null),
            IrOpaqueTerm value => row(
                term,
                memberIndex(value.Member),
                optionalTermIndex(value.Receiver),
                opaquePurity(value.Purity),
                value.Purity == IrOpaquePurity.Pure ? -1 : operationIndex(value.Operation),
                0,
                null,
                termIndices(value.Arguments)),
            IrUnaryTerm value => row(
                term,
                unaryOperator(value.Operator),
                termIndex(value.Operand),
                -1,
                -1,
                0,
                null,
                null),
            IrBinaryTerm value => row(
                term,
                binaryOperator(value.Operator),
                termIndex(value.Left),
                termIndex(value.Right),
                -1,
                0,
                null,
                null),
            IrConditionalTerm value => row(
                term,
                termIndex(value.Condition),
                termIndex(value.WhenTrue),
                termIndex(value.WhenFalse),
                -1,
                0,
                null,
                null),
            IrCastTerm value => row(term, termIndex(value.Operand), -1, -1, -1, 0, null, null),
            IrLengthTerm value => row(term, termIndex(value.Value), -1, -1, -1, 0, null, null),
            IrSequenceAccessTerm value => row(
                term,
                termIndex(value.Sequence),
                termIndex(value.Index),
                -1,
                -1,
                0,
                null,
                null),
            _ => throw invalid()
        };
    }

    internal static PortableIrLocation EncodeLocation(
        IrLocation location,
        Func<IrTypeId, int> typeIndex,
        Func<IrMemberId, int> memberIndex,
        Func<IrTerm?, int> optionalTermIndex,
        Func<IrTerm, int> termIndex,
        Func<IEnumerable<IrTerm>, int[]> termIndices,
        Func<IrLocation, int, int, int[]?, PortableIrLocation> row,
        Func<Exception> invalid)
    {
        return location switch
        {
            IrMemberLocation value => row(
                location,
                memberIndex(value.Member),
                optionalTermIndex(value.Receiver),
                termIndices(value.Arguments)),
            IrSequenceLocation value => row(
                location,
                termIndex(value.Sequence),
                termIndex(value.Index),
                null),
            _ => throw invalid()
        };
    }

    internal static PortableIrInstruction EncodeInstruction(
        IrInstruction instruction,
        Func<OperationId, int> operationIndex,
        Func<IrVarId, int> variableIndex,
        Func<IrTerm, int> termIndex,
        Func<IrVarId?, int> optionalVariableIndex,
        Func<IrMemberId, int> memberIndex,
        Func<IrTerm?, int> optionalTermIndex,
        Func<IrHavocKind, int> havocKind,
        Func<IrBlockId, int> blockIndex,
        Func<IEnumerable<IrTerm>, int[]> termIndices,
        Func<IEnumerable<IrVarId>, int[]> variableIndices,
        Func<IrLocation, PortableIrLocation> location,
        Func<IrInstruction, int, int, int, int, int[]?, PortableIrLocation?, PortableIrInstruction> row,
        Func<Exception> invalid)
    {
        return instruction switch
        {
            IrAssignInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                variableIndex(value.Target),
                termIndex(value.Value),
                -1,
                null,
                null),
            IrLoadInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                variableIndex(value.Target),
                -1,
                -1,
                null,
                location(value.Location)),
            IrStoreInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                termIndex(value.Value),
                -1,
                -1,
                null,
                location(value.Location)),
            IrCallInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                optionalVariableIndex(value.Target),
                memberIndex(value.Member),
                optionalTermIndex(value.Receiver),
                termIndices(value.Arguments),
                null),
            IrAssumeInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                termIndex(value.Condition),
                -1,
                -1,
                null,
                null),
            IrAssertInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                termIndex(value.Condition),
                -1,
                -1,
                null,
                null),
            IrHavocInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                havocKind(value.HavocKind),
                -1,
                -1,
                variableIndices(value.Variables),
                null),
            IrBranchInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                termIndex(value.Condition),
                blockIndex(value.WhenTrue),
                blockIndex(value.WhenFalse),
                null,
                null),
            IrGotoInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                blockIndex(value.Target),
                -1,
                -1,
                null,
                null),
            IrReturnInstruction value => row(
                instruction,
                operationIndex(instruction.Operation),
                optionalTermIndex(value.Value),
                -1,
                -1,
                null,
                null),
            _ => throw invalid()
        };
    }

    internal static IrTerm DecodeTerm(
        PortableIrTerm row,
        IrFactory factory,
        int depth,
        Func<int, IrTypeId> type,
        Func<int, int, IrTerm> term,
        Func<int, int, IrTerm?> optionalTerm,
        Func<int, IrVarId> variable,
        Func<int, IrMemberId> member,
        Func<int, OperationId> operation,
        Func<int[], int, IrTerm[]> terms,
        Func<int, IrOpaquePurity> opaquePurity,
        Func<int, IrUnaryOperator> unaryOperator,
        Func<int, IrBinaryOperator> binaryOperator,
        Func<Exception> invalid)
    {
        return row.Kind switch
        {
            IrTermKind.Boolean when row.A is 0 or 1 => factory.Boolean(row.A == 1),
            IrTermKind.Integer => factory.Integer(row.Number),
            IrTermKind.String when row.Text != null => factory.String(row.Text),
            IrTermKind.Null => factory.Null(type(row.Type)),
            IrTermKind.Variable => factory.Variable(variable(row.A)),
            IrTermKind.Opaque => DecodeOpaque(
                row,
                factory,
                depth,
                optionalTerm,
                member,
                operation,
                terms,
                opaquePurity,
                invalid),
            IrTermKind.Unary => factory.Unary(
                unaryOperator(row.A),
                term(row.B, depth + 1)),
            IrTermKind.Binary => factory.Binary(
                binaryOperator(row.A),
                term(row.B, depth + 1),
                term(row.C, depth + 1)),
            IrTermKind.Conditional => factory.Conditional(
                term(row.A, depth + 1),
                term(row.B, depth + 1),
                term(row.C, depth + 1)),
            IrTermKind.Cast => factory.Cast(type(row.Type), term(row.A, depth + 1)),
            IrTermKind.Length => factory.Length(term(row.A, depth + 1)),
            IrTermKind.SequenceAccess => factory.SequenceAccess(
                term(row.A, depth + 1),
                term(row.B, depth + 1)),
            _ => throw invalid()
        };
    }

    private static IrTerm DecodeOpaque(
        PortableIrTerm row,
        IrFactory factory,
        int depth,
        Func<int, int, IrTerm?> optionalTerm,
        Func<int, IrMemberId> member,
        Func<int, OperationId> operation,
        Func<int[], int, IrTerm[]> terms,
        Func<int, IrOpaquePurity> opaquePurity,
        Func<Exception> invalid)
    {
        var purity = opaquePurity(row.C);
        var receiver = optionalTerm(row.B, depth);
        var arguments = terms(row.Items, depth);
        return purity switch
        {
            IrOpaquePurity.Pure when row.D == -1 =>
                factory.PureOpaque(member(row.A), receiver, arguments),
            IrOpaquePurity.Impure =>
                factory.ImpureOpaque(operation(row.D), member(row.A), receiver, arguments),
            _ => throw invalid()
        };
    }

    internal static IrLocation DecodeLocation(
        IrProgramBuilder builder,
        PortableIrLocation row,
        Func<int, IrMemberId> member,
        Func<int, IrTerm?> optionalTerm,
        Func<int, IrTerm> term,
        Func<int[], IrTerm[]> terms,
        Func<Exception> invalid)
    {
        return row.Kind switch
        {
            IrLocationKind.Member => builder.MemberLocation(
                member(row.A),
                optionalTerm(row.B),
                terms(row.Items)),
            IrLocationKind.Sequence => builder.SequenceLocation(
                term(row.A),
                term(row.B)),
            _ => throw invalid()
        };
    }

    internal static IrInstruction DecodeInstruction(
        IrProgramBuilder builder,
        IrBlockId block,
        PortableIrInstruction row,
        Func<int, OperationId> operation,
        Func<int, IrVarId> variable,
        Func<int, IrMemberId> member,
        Func<int, IrTerm?> optionalTerm,
        Func<int, IrTerm> term,
        Func<int, IrVarId?> optionalVariable,
        Func<int, IrHavocKind> havocKind,
        Func<int, IrBlockId> blockAt,
        Func<PortableIrLocation?, IrLocation> location,
        Func<int[], IrTerm[]> terms,
        Func<int[], IrVarId[]> variables,
        Func<Exception> invalid)
    {
        return row.Kind switch
        {
            IrInstructionKind.Assign => builder.Assign(
                block,
                operation(row.Operation),
                variable(row.A),
                term(row.B)),
            IrInstructionKind.Load => builder.Load(
                block,
                operation(row.Operation),
                variable(row.A),
                location(row.Location)),
            IrInstructionKind.Store => builder.Store(
                block,
                operation(row.Operation),
                location(row.Location),
                term(row.A)),
            IrInstructionKind.Call => builder.Call(
                block,
                operation(row.Operation),
                optionalVariable(row.A),
                member(row.B),
                optionalTerm(row.C),
                terms(row.Items)),
            IrInstructionKind.Assume => builder.Assume(
                block,
                operation(row.Operation),
                term(row.A)),
            IrInstructionKind.Assert => builder.Assert(
                block,
                operation(row.Operation),
                term(row.A)),
            IrInstructionKind.Havoc => builder.Havoc(
                block,
                operation(row.Operation),
                havocKind(row.A),
                variables(row.Items)),
            IrInstructionKind.Branch => builder.Branch(
                block,
                operation(row.Operation),
                term(row.A),
                blockAt(row.B),
                blockAt(row.C)),
            IrInstructionKind.Goto => builder.Goto(
                block,
                operation(row.Operation),
                blockAt(row.A)),
            IrInstructionKind.Return => builder.Return(
                block,
                operation(row.Operation),
                optionalTerm(row.A)),
            _ => throw invalid()
        };
    }
}
'@
foreach ($line in ($portableProjectionSource -split "`r?`n")) {
    $portableLines.Add($line)
}

$collectorMappings = @(
    Get-RequiredMember $schema 'collectorWireMappings' 'schema')
if ($collectorMappings.Count -eq 0) {
    throw 'Collector wire catalog cannot be empty.'
}
$collectorMappingNames = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
$collectorMappingOverloads = [Collections.Generic.HashSet[string]]::new(
    [StringComparer]::Ordinal)
foreach ($mapping in $collectorMappings) {
    $name = [string](
        Get-RequiredMember $mapping 'name' 'collector wire mapping')
    $owner = [string](
        Get-RequiredMember $mapping 'owner' "collector mapping '$name'")
    $method = [string](
        Get-RequiredMember $mapping 'method' "collector mapping '$name'")
    $kind = [string](
        Get-RequiredMember $mapping 'kind' "collector mapping '$name'")
    $sourceType = [string](
        Get-RequiredMember $mapping 'sourceType' "collector mapping '$name'")
    $targetType = [string](
        Get-RequiredMember $mapping 'targetType' "collector mapping '$name'")
    $unknownException = [string](
        Get-RequiredMember $mapping 'unknownException' "collector mapping '$name'")
    foreach ($identifier in @(
            $name,
            $owner,
            $method,
            $sourceType,
            $targetType,
            $unknownException)) {
        Assert-Identifier $identifier "Collector mapping '$name'"
    }
    if (-not $collectorMappingNames.Add($name)) {
        throw "Duplicate collector wire mapping '$name'."
    }
    if (-not $collectorMappingOverloads.Add(
            "$owner.$method($sourceType)")) {
        throw (
            "Duplicate collector wire overload '$owner.$method($sourceType)'.")
    }
    $validShape = switch ($owner) {
        'CompilerOptionWireMappings' {
            $method -eq 'Map' -and
            $kind -in 'enum', 'referenceIdentity' -and
            $unknownException -eq 'InvalidOperationException'
        }
        'CompilerEffectEvaluationWireMappings' {
            $method -eq 'ToWorker' -and
            $kind -eq 'enum' -and
            $unknownException -eq 'ArgumentOutOfRangeException'
        }
        'CompilerLoweringWireMappings' {
            $method -in 'ToCompiler', 'ToWorkerEvidence', 'ToWorkerFailure' -and
            $kind -eq 'enum' -and
            $unknownException -eq 'ArgumentOutOfRangeException'
        }
        'ClaimManifestBuilder' {
            $method -in 'ToWorkerEffects', 'ToWorkerCapabilities' -and
            $kind -eq 'flags' -and
            $unknownException -eq 'ArgumentOutOfRangeException'
        }
        default { $false }
    }
    if (-not $validShape) {
        throw "Collector mapping '$name' has an unsupported owner or shape."
    }
    $rows = @(Get-RequiredMember $mapping 'rows' "collector mapping '$name'")
    if ($rows.Count -eq 0) {
        throw "Collector mapping '$name' cannot be empty."
    }
    $sources = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    $targets = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal)
    $allowTargetAliases = $false
    if ($mapping.PSObject.Properties['allowTargetAliases']) {
        $allowTargetAliases = [bool]$mapping.allowTargetAliases
        if (-not $allowTargetAliases -or $kind -ne 'enum') {
            throw "Collector mapping '$name' has an invalid target-alias setting."
        }
    }
    foreach ($row in $rows) {
        $source = [string](
            Get-RequiredMember $row 'source' "collector mapping '$name' row")
        $target = [string](
            Get-RequiredMember $row 'target' "collector mapping '$name' row")
        if ($kind -eq 'referenceIdentity') {
            if ($source -notmatch
                '^[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*$') {
                throw (
                    "Collector mapping '$name' has invalid source '$source'.")
            }
        }
        else {
            Assert-Identifier $source "Collector mapping '$name' source"
        }
        Assert-Identifier $target "Collector mapping '$name' target"
        if (-not $sources.Add($source)) {
            throw "Collector mapping '$name' repeats source '$source'."
        }
        if (-not $allowTargetAliases -and -not $targets.Add($target)) {
            throw "Collector mapping '$name' repeats target '$target'."
        }
    }
    if ($kind -eq 'flags') {
        $sourceMask = [string](
            Get-RequiredMember $mapping 'sourceMask' "collector mapping '$name'")
        if ($sourceMask -notmatch
            '^[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*$') {
            throw "Collector mapping '$name' has an invalid source mask."
        }
        if ([string]$rows[0].source -ne 'None' -or
            [string]$rows[0].target -ne 'None') {
            throw "Collector flags mapping '$name' must begin with None -> None."
        }
    }
    elseif ($mapping.PSObject.Properties['sourceMask']) {
        throw "Non-flags collector mapping '$name' cannot define sourceMask."
    }
}

$collectorOwners = @(
    $collectorMappings |
        ForEach-Object { [string]$_.owner } |
        Select-Object -Unique)
foreach ($owner in $collectorOwners) {
    $ownerMappings = @(
        $collectorMappings |
            Where-Object { [string]$_.owner -eq $owner })
    $collectorLines.Add('')
    $declaration = if ($owner -eq 'ClaimManifestBuilder') {
        'internal sealed partial class'
    }
    else {
        'internal static partial class'
    }
    $collectorLines.Add("$declaration $owner {")
    foreach ($mapping in $ownerMappings) {
        $method = [string]$mapping.method
        $kind = [string]$mapping.kind
        $sourceType = [string]$mapping.sourceType
        $targetType = [string]$mapping.targetType
        $rows = @($mapping.rows)
        $parameterName = if ($kind -eq 'flags') { 'source' } else { 'value' }
        $collectorLines.Add(
            "    internal static $targetType $method($sourceType $parameterName) {")
        if ($kind -eq 'enum') {
            $collectorLines.Add("        return $parameterName switch {")
            foreach ($row in $rows) {
                $collectorLines.Add(
                    "            $sourceType.$($row.source) => " +
                    "$targetType.$($row.target),")
            }
            $throw = if ([string]$mapping.unknownException -eq
                'InvalidOperationException') {
                "throw Unsupported(nameof($sourceType), $parameterName)"
            }
            else {
                "throw new ArgumentOutOfRangeException(nameof($parameterName))"
            }
            $collectorLines.Add("            _ => $throw")
            $collectorLines.Add('        };')
        }
        elseif ($kind -eq 'referenceIdentity') {
            foreach ($row in $rows) {
                $collectorLines.Add(
                    "        if (ReferenceEquals($parameterName, $($row.source)))")
                $collectorLines.Add(
                    "            return $targetType.$($row.target);")
            }
            $collectorLines.Add('        throw new InvalidOperationException(')
            $collectorLines.Add(
                '            "A custom assembly identity comparer is unsupported.");')
        }
        elseif ($kind -eq 'flags') {
            $collectorLines.Add(
                "        if (($parameterName & ~$($mapping.sourceMask)) != 0)")
            $collectorLines.Add(
                "            throw new ArgumentOutOfRangeException(nameof($parameterName));")
            $collectorLines.Add(
                "        var result = $targetType.$($rows[0].target);")
            for ($rowIndex = 1; $rowIndex -lt $rows.Count; $rowIndex++) {
                $row = $rows[$rowIndex]
                $collectorLines.Add(
                    "        if (($parameterName & $sourceType.$($row.source)) != 0)")
                $collectorLines.Add(
                    "            result |= $targetType.$($row.target);")
            }
            $collectorLines.Add('        return result;')
        }
        else {
            throw "Collector mapping '$($mapping.name)' has unsupported kind '$kind'."
        }
        $collectorLines.Add('    }')
        $collectorLines.Add('')
    }
    if ($owner -eq 'CompilerOptionWireMappings') {
        $collectorLines.Add('    private static InvalidOperationException Unsupported<T>(')
        $collectorLines.Add('        string name,')
        $collectorLines.Add('        T value)')
        $collectorLines.Add('        where T : struct {')
        $collectorLines.Add(
            '        return new($"The compiler option ''{name}'' has unsupported value ''{value}''.");')
        $collectorLines.Add('    }')
    }
    elseif ($collectorLines[$collectorLines.Count - 1] -eq '') {
        $collectorLines.RemoveAt($collectorLines.Count - 1)
    }
    $collectorLines.Add('}')
}

$evidence = Get-RequiredMember $schema 'effectEvidence' 'schema'
$domain = [string](Get-RequiredMember $evidence 'domain' 'effect evidence')
$evidenceVersion = [int](Get-RequiredMember $evidence 'version' 'effect evidence')
if ($domain -ne 'SharpProof.CompilerEffectClaimEvidence' -or
    $evidenceVersion -ne 8) {
    throw 'Compiler effect evidence must preserve domain version 8.'
}
$unknownReasons = @(Get-RequiredMember `
    $evidence 'unknownReasons' 'effect evidence')
if ($unknownReasons.Count -eq 0) {
    throw 'Compiler effect evidence must define typed unknown reasons.'
}
foreach ($reason in $unknownReasons) {
    Assert-Identifier ([string]$reason) 'Effect evidence unknown reason'
}
$constraintKinds = Get-RequiredMember `
    $evidence 'constraintKinds' 'effect evidence'
$capabilitiesKind = [string](
    Get-RequiredMember $constraintKinds 'capabilities' 'effect evidence constraints')
$exceptionsKind = [string](
    Get-RequiredMember $constraintKinds 'exceptions' 'effect evidence constraints')
$combinedKind = [string](
    Get-RequiredMember $constraintKinds 'combined' 'effect evidence constraints')
foreach ($kind in $capabilitiesKind, $exceptionsKind, $combinedKind) {
    Assert-Identifier $kind 'Effect evidence constraint kind'
}
$replay = Get-RequiredMember $evidence 'replay' 'effect evidence'
$replayPathKind = [string](
    Get-RequiredMember $replay 'pathKind' 'effect replay')
Assert-Identifier $replayPathKind 'Effect replay path kind'
$maximumReplayEvents = [int](
    Get-RequiredMember $replay 'maximumEvents' 'effect replay')
if ($maximumReplayEvents -ne 256) {
    throw 'Compiler effect replay must preserve its 256-event bound.'
}
$supportedReplayEventKinds = @(
    Get-RequiredMember $replay 'supportedEventKinds' 'effect replay')
if ($supportedReplayEventKinds.Count -eq 0) {
    throw 'Compiler effect replay must define supported event kinds.'
}
foreach ($kind in $supportedReplayEventKinds) {
    Assert-Identifier ([string]$kind) 'Supported effect replay event kind'
}
if (-not [bool](Get-RequiredMember `
        $evidence 'sortAllowedExceptionTypes' 'effect evidence') -or
    -not [bool](Get-RequiredMember `
        $evidence 'sortWitnessExceptionHierarchy' 'effect evidence')) {
    throw 'Compiler effect evidence must use canonical exception ordering.'
}

$constraintRuleKinds = @(
    'EnforcePure',
    'ZeroAllocations',
    'AllowedCapabilities',
    'DoesNotThrow',
    'AllowedExceptions',
    'EffectContract')
$modelLines.Add('')
$modelLines.Add('internal readonly struct CompilerEffectConstraintRule(')
$modelLines.Add('    WorkerEffectContractKind kind,')
$modelLines.Add('    bool effectsMustBeEmpty,')
$modelLines.Add('    bool capabilitiesMustBeEmpty,')
$modelLines.Add('    bool exceptionsMustBeEmpty)')
$modelLines.Add('{')
$modelLines.Add('    internal WorkerEffectContractKind Kind { get; } = kind;')
$modelLines.Add('    internal bool EffectsMustBeEmpty { get; } = effectsMustBeEmpty;')
$modelLines.Add('    internal bool CapabilitiesMustBeEmpty { get; } = capabilitiesMustBeEmpty;')
$modelLines.Add('    internal bool ExceptionsMustBeEmpty { get; } = exceptionsMustBeEmpty;')
$modelLines.Add('}')
$modelLines.Add('')
$modelLines.Add('internal static class CompilerEffectEvidenceCatalog {')
$modelLines.Add('    internal const string ConstraintDomain = "SharpProof.CompilerEffectReplayConstraint";')
$modelLines.Add('    internal const int ConstraintVersion = 1;')
$modelLines.Add('    internal const string OperationDomain = "SharpProof.CompilerEffectReplayOperation";')
$modelLines.Add('    internal const int OperationVersion = 1;')
$modelLines.Add("    internal const string EvidenceDomain = $(ConvertTo-CSharpString $domain);")
$modelLines.Add("    internal const int EvidenceVersion = $evidenceVersion;")
$modelLines.Add('    internal const int MaximumReplayEvents = ' +
    $maximumReplayEvents + ';')
$modelLines.Add('    internal const CompilerEffectReplayPathKind ReplayPathKind =')
$modelLines.Add("        CompilerEffectReplayPathKind.$replayPathKind;")
$modelLines.Add('    internal static readonly WorkerClaimReason[] UnknownReasons = [')
foreach ($reason in $unknownReasons) {
    $modelLines.Add("        WorkerClaimReason.$reason,")
}
$modelLines.Add('    ];')
$modelLines.Add('    internal static readonly CompilerEffectConstraintRule[] ConstraintRules = [')
foreach ($kind in $constraintRuleKinds) {
    $effectsEmpty = if ($kind -eq $combinedKind) { 'false' } else { 'true' }
    $capabilitiesEmpty = if ($kind -in $capabilitiesKind, $combinedKind) { 'false' } else { 'true' }
    $exceptionsEmpty = if ($kind -in $exceptionsKind, $combinedKind) { 'false' } else { 'true' }
    $modelLines.Add(
        "        new(WorkerEffectContractKind.$kind, $effectsEmpty, " +
        "$capabilitiesEmpty, $exceptionsEmpty),")
}
$modelLines.Add('    ];')
$modelLines.Add('    internal static readonly CompilerEffectReplayEventKind[] SupportedReplayEventKinds = [')
foreach ($kind in $supportedReplayEventKinds) {
    $modelLines.Add("        CompilerEffectReplayEventKind.$kind,")
}
$modelLines.Add('    ];')
$modelLines.Add('}')

$outputs = [ordered]@{
    $ModelOutputPath = $modelLines
    $PortableOutputPath = $portableLines
    $CompilationOutputPath = $compilationLines
    $CollectorOutputPath = $collectorLines
}
foreach ($output in $outputs.GetEnumerator()) {
    [IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($output.Key)) |
        Out-Null
    Update-SharpProofGeneratedFile `
        -Path $output.Key `
        -Content ($output.Value -join "`n") `
        -DisplayPath $output.Key `
        -GeneratorCommand '.\scripts\Generate-CompilerArtifactModel.ps1' `
        -Verify:$Verify
}
$verb = if ($Verify) { 'Verified' } else { 'Generated' }
Write-Host "$verb deterministic compiler-artifact model."
