[CmdletBinding()]
param(
    [Parameter()][string]$CatalogPath,
    [Parameter()][string]$OutputPath,
    [Parameter()][Alias('Check')][switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'GeneratedFileHelpers.ps1')

$repositoryRoot = Get-SharpProofRepositoryRoot $PSScriptRoot
$CatalogPath = Resolve-SharpProofPath $CatalogPath (
    Join-Path $repositoryRoot 'SharpProof.Analyzer.Core\AnalyzerDiagnostic.catalog.json')
$OutputPath = Resolve-SharpProofPath $OutputPath (
    Join-Path $repositoryRoot 'SharpProof.Analyzer.Core\AnalyzerDiagnosticCatalog.generated.cs')
$catalog = Get-Content -LiteralPath $CatalogPath -Raw | ConvertFrom-Json
if ([int]$catalog.schemaVersion -ne 1) {
    throw 'Only analyzer-diagnostic catalog schema version 1 is supported.'
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated>')
$lines.Add('// Generated by scripts/Generate-AnalyzerDiagnosticCatalog.ps1 from')
$lines.Add('// SharpProof.Analyzer.Core/AnalyzerDiagnostic.catalog.json.')
$lines.Add('// Declarative diagnostic projections only; analysis remains handwritten.')
$lines.Add('// Do not edit this file directly.')
$lines.Add('// </auto-generated>')
$lines.Add('#nullable enable')
$lines.Add('')
$lines.Add('namespace SharpProof.Analyzer;')
$lines.Add('')
$lines.Add('internal static class AnalyzerDiagnosticCatalog')
$lines.Add('{')
$lines.Add('    internal static (string Argument, string Reason) DescribeIntrinsicViolation(')
$lines.Add('        ContractBindingFailure failure, bool isOld)')
$lines.Add('    {')
$lines.Add('        return (failure, isOld) switch')
$lines.Add('        {')
$seenIntrinsic = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($entry in @($catalog.intrinsicDescriptions)) {
    Assert-Identifier ([string]$entry.failure) 'Analyzer diagnostic intrinsic failure'
    $key = ([string]$entry.failure) + '|' + ([bool]$entry.isOld).ToString()
    if (-not $seenIntrinsic.Add($key)) {
        throw "Analyzer diagnostic intrinsic mapping repeats '$key'."
    }
    $suffix = if ([bool]$entry.isOld) { 'true' } else { 'false' }
    $lines.Add("            (ContractBindingFailure.$($entry.failure), $suffix) => (")
    $lines.Add("                $(ConvertTo-CSharpString ([string]$entry.argument)),")
    $lines.Add("                $(ConvertTo-CSharpString ([string]$entry.reason))),")
}
$intrinsicFallback = $catalog.intrinsicFallback
$lines.Add("            _ => ($(ConvertTo-CSharpString ([string]$intrinsicFallback.argument)),")
$lines.Add("                $(ConvertTo-CSharpString ([string]$intrinsicFallback.reason)))")
$lines.Add('        };')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    internal static string DescribePlacement(ContractClausePlacement placement)')
$lines.Add('    {')
$lines.Add('        return placement switch')
$lines.Add('        {')
$seenPlacement = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($entry in @($catalog.placementDescriptions)) {
    Assert-Identifier ([string]$entry.placement) 'Analyzer diagnostic placement'
    if (-not $seenPlacement.Add([string]$entry.placement)) {
        throw "Analyzer diagnostic placement mapping repeats '$($entry.placement)'."
    }
    $lines.Add("            ContractClausePlacement.$($entry.placement) =>")
    $lines.Add("                $(ConvertTo-CSharpString ([string]$entry.description)),")
}
$lines.Add("            _ => $(ConvertTo-CSharpString ([string]$catalog.placementFallback))")
$lines.Add('        };')
$lines.Add('    }')
$lines.Add('}')

Update-SharpProofGeneratedFile `
    -Path $OutputPath `
    -Content ($lines -join "`n") `
    -DisplayPath $OutputPath `
    -GeneratorCommand '.\scripts\Generate-AnalyzerDiagnosticCatalog.ps1' `
    -Verify:$Verify
$verb = if ($Verify) { 'Verified' } else { 'Generated' }
Write-Host "$verb deterministic analyzer-diagnostic catalog."
