#!/usr/bin/env python3
"""Rank similar C# production members using cached local embeddings.

This is an audit tool, not an automatic refactoring tool. It extracts members
with tree-sitter, embeds changed members only, and combines semantic and token
similarity to produce a high-yield review queue.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


DEFAULT_MODEL = "BAAI/bge-small-en-v1.5"
MEMBER_TYPES = {
    "method_declaration",
    "constructor_declaration",
    "destructor_declaration",
    "operator_declaration",
    "conversion_operator_declaration",
    "accessor_declaration",
    "local_function_statement",
}
EXPRESSION_MEMBER_TYPES = {
    "property_declaration",
    "indexer_declaration",
    "event_declaration",
}
IDENTIFIER_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
TOKEN_RE = re.compile(
    r"[A-Za-z_][A-Za-z0-9_]*|(?:==|!=|<=|>=|=>|&&|\|\||\?\?|\+\+|--)|[^\s]"
)
COMMENT_RE = re.compile(r"//[^\n]*|/\*.*?\*/", re.DOTALL)
STRING_RE = re.compile(r'@?"(?:""|\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'')
NUMBER_RE = re.compile(r"\b(?:0x[0-9A-Fa-f]+|\d+(?:\.\d+)?)\b")


@dataclass(frozen=True)
class Member:
    key: str
    path: str
    kind: str
    name: str
    start_line: int
    end_line: int
    significant_lines: int
    source: str
    normalized: str
    tokens: frozenset[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--minimum-lines", type=int, default=8)
    parser.add_argument("--neighbors", type=int, default=12)
    parser.add_argument("--minimum-semantic-similarity", type=float, default=0.76)
    parser.add_argument("--top", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--include-within-file", action="store_true")
    parser.add_argument("--local-files-only", action="store_true")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("artifacts/semantic-clones/inventory.json"),
    )
    return parser.parse_args()


def is_production_source(root: Path, path: Path) -> bool:
    relative = path.relative_to(root).as_posix()
    parts = relative.split("/")
    return (
        "bin" not in parts
        and "obj" not in parts
        and not relative.startswith("artifacts/")
        and not relative.startswith("docs/readme-examples/")
        and not any(part.startswith(".") for part in parts)
        and not relative.startswith("SharpProof.Test/")
        and not relative.startswith("SharpProof.ToolingTest/")
        and not relative.startswith("SharpProof.Demo/")
        and not relative.startswith("SharpProof.Smoke.Net472/")
    )


def is_generated(path: Path, source: str) -> bool:
    return path.name.endswith((".g.cs", ".generated.cs")) or bool(
        re.search(r"^\s*//\s*<auto-generated(?:\s*/>|>)", source, re.MULTILINE | re.IGNORECASE)
    )


def significant_line_count(source: str) -> int:
    without_comments = COMMENT_RE.sub("", source)
    return sum(
        1
        for line in without_comments.splitlines()
        if line.strip() and line.strip() not in {"{", "}", "};"}
    )


def normalize_source(source: str) -> str:
    source = COMMENT_RE.sub(" ", source)
    source = STRING_RE.sub(" STRING_LITERAL ", source)
    source = NUMBER_RE.sub(" NUMBER_LITERAL ", source)
    return " ".join(source.split())


def token_signature(normalized: str) -> frozenset[str]:
    tokens = TOKEN_RE.findall(normalized)
    identifiers = defaultdict(int)
    result: set[str] = set()
    keywords = {
        "abstract", "as", "async", "await", "base", "bool", "break", "byte",
        "case", "catch", "char", "checked", "class", "const", "continue",
        "decimal", "default", "delegate", "do", "double", "else", "enum",
        "event", "explicit", "extern", "false", "finally", "fixed", "float",
        "for", "foreach", "goto", "if", "implicit", "in", "int", "interface",
        "internal", "is", "lock", "long", "namespace", "new", "null", "object",
        "operator", "out", "override", "params", "private", "protected", "public",
        "readonly", "record", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
        "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe",
        "ushort", "using", "var", "virtual", "void", "volatile", "while", "yield",
        "STRING_LITERAL", "NUMBER_LITERAL",
    }
    for token in tokens:
        if IDENTIFIER_RE.fullmatch(token) and token not in keywords:
            lowered = token.lower()
            identifiers[lowered] += 1
            result.add(f"id:{lowered}")
        else:
            result.add(token)
    result.update(f"freq:{min(count, 5)}" for count in identifiers.values())
    return frozenset(result)


def member_name(node, source_bytes: bytes) -> str:
    name_node = node.child_by_field_name("name")
    if name_node is not None:
        return source_bytes[name_node.start_byte:name_node.end_byte].decode("utf-8", "replace")
    if node.type == "accessor_declaration":
        for child in node.children:
            if child.type in {"get", "set", "init", "add", "remove"}:
                return child.type
        text = source_bytes[node.start_byte:node.end_byte].decode("utf-8", "replace")
        return text.split(None, 1)[0] if text else "accessor"
    return node.type


def has_arrow_body(node) -> bool:
    return any(child.type == "arrow_expression_clause" for child in node.children)


def iter_nodes(node) -> Iterable:
    stack = [node]
    while stack:
        current = stack.pop()
        yield current
        stack.extend(reversed(current.children))


def extract_members(root: Path, minimum_lines: int) -> list[Member]:
    try:
        from tree_sitter import Language, Parser
        import tree_sitter_c_sharp
    except ImportError as error:
        raise SystemExit(
            "Missing parser dependency. Run: python -m pip install tree-sitter tree-sitter-c-sharp"
        ) from error

    parser = Parser(Language(tree_sitter_c_sharp.language()))
    members: list[Member] = []
    for path in sorted(root.rglob("*.cs")):
        if not is_production_source(root, path):
            continue
        source = path.read_text(encoding="utf-8-sig")
        if is_generated(path, source):
            continue
        source_bytes = source.encode("utf-8")
        tree = parser.parse(source_bytes)
        relative = path.relative_to(root).as_posix()
        for node in iter_nodes(tree.root_node):
            if node.type not in MEMBER_TYPES and not (
                node.type in EXPRESSION_MEMBER_TYPES and has_arrow_body(node)
            ):
                continue
            member_source = source_bytes[node.start_byte:node.end_byte].decode("utf-8", "replace")
            lines = significant_line_count(member_source)
            if lines < minimum_lines:
                continue
            normalized = normalize_source(member_source)
            name = member_name(node, source_bytes)
            start_line = node.start_point.row + 1
            end_line = node.end_point.row + 1
            # Line numbers are deliberately excluded so edits above a member do not
            # invalidate its embedding. A moved or materially changed member is
            # re-embedded; an unchanged member shifted within its file is not.
            key_material = f"{relative}:{node.type}:{name}:{normalized}".encode("utf-8")
            members.append(
                Member(
                    key=hashlib.sha256(key_material).hexdigest(),
                    path=relative,
                    kind=node.type,
                    name=name,
                    start_line=start_line,
                    end_line=end_line,
                    significant_lines=lines,
                    source=member_source,
                    normalized=normalized,
                    tokens=token_signature(normalized),
                )
            )
    return members


def model_cache_name(model_name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", model_name)


def embed_members(
    members: list[Member], model_name: str, cache_dir: Path, batch_size: int, local_only: bool
) -> np.ndarray:
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError as error:
        raise SystemExit("Missing embedding dependency. Run: python -m pip install sentence-transformers") from error

    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_path = cache_dir / f"{model_cache_name(model_name)}.npz"
    cached: dict[str, np.ndarray] = {}
    if cache_path.exists():
        archive = np.load(cache_path, allow_pickle=False)
        cached = {key: vector for key, vector in zip(archive["keys"].tolist(), archive["vectors"])}

    missing = [member for member in members if member.key not in cached]
    if missing:
        model = SentenceTransformer(model_name, local_files_only=local_only)
        texts = [
            f"C# {member.kind} named {member.name}.\n{member.normalized}"
            for member in missing
        ]
        vectors = model.encode(
            texts,
            batch_size=batch_size,
            normalize_embeddings=True,
            show_progress_bar=True,
        ).astype(np.float32)
        cached.update(zip((member.key for member in missing), vectors))
        ordered_keys = sorted(cached)
        np.savez_compressed(
            cache_path,
            keys=np.asarray(ordered_keys),
            vectors=np.asarray([cached[key] for key in ordered_keys], dtype=np.float32),
        )

    return np.asarray([cached[member.key] for member in members], dtype=np.float32)


def jaccard(left: frozenset[str], right: frozenset[str]) -> float:
    union = left | right
    return len(left & right) / len(union) if union else 1.0


def rank_candidates(
    members: list[Member],
    embeddings: np.ndarray,
    neighbors: int,
    minimum_semantic_similarity: float,
    include_within_file: bool,
) -> list[dict]:
    from sklearn.neighbors import NearestNeighbors

    count = min(neighbors + 1, len(members))
    index = NearestNeighbors(n_neighbors=count, metric="cosine", algorithm="brute", n_jobs=-1)
    index.fit(embeddings)
    distances, indices = index.kneighbors(embeddings)
    candidates: list[dict] = []
    seen: set[tuple[int, int]] = set()
    for left_index, (row_distances, row_indices) in enumerate(zip(distances, indices)):
        for distance, right_index in zip(row_distances[1:], row_indices[1:]):
            pair = tuple(sorted((left_index, int(right_index))))
            if pair in seen:
                continue
            seen.add(pair)
            left, right = members[pair[0]], members[pair[1]]
            if not include_within_file and left.path == right.path:
                continue
            semantic = 1.0 - float(distance)
            if semantic < minimum_semantic_similarity:
                continue
            lexical = jaccard(left.tokens, right.tokens)
            confidence = 0.78 * semantic + 0.22 * lexical
            removable_lines = min(left.significant_lines, right.significant_lines)
            priority = removable_lines * max(0.0, confidence - 0.65) ** 1.35
            candidates.append(
                {
                    "priority": round(priority, 4),
                    "semanticSimilarity": round(semantic, 4),
                    "tokenSimilarity": round(lexical, 4),
                    "combinedSimilarity": round(confidence, 4),
                    "potentialRemovableLines": removable_lines,
                    "left": member_record(left),
                    "right": member_record(right),
                }
            )
    return sorted(
        candidates,
        key=lambda item: (
            item["priority"], item["combinedSimilarity"], item["potentialRemovableLines"]
        ),
        reverse=True,
    )


def member_record(member: Member) -> dict:
    return {
        "path": member.path,
        "kind": member.kind,
        "name": member.name,
        "startLine": member.start_line,
        "endLine": member.end_line,
        "significantLines": member.significant_lines,
    }


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = args.output if args.output.is_absolute() else root / args.output
    members = extract_members(root, args.minimum_lines)
    if len(members) < 2:
        raise SystemExit("Fewer than two eligible production members were found.")
    embeddings = embed_members(
        members,
        args.model,
        output.parent / "embedding-cache",
        args.batch_size,
        args.local_files_only,
    )
    candidates = rank_candidates(
        members,
        embeddings,
        args.neighbors,
        args.minimum_semantic_similarity,
        args.include_within_file,
    )
    report = {
        "schemaVersion": 1,
        "model": args.model,
        "memberCount": len(members),
        "candidateCount": len(candidates),
        "parameters": {
            "minimumLines": args.minimum_lines,
            "neighbors": args.neighbors,
            "minimumSemanticSimilarity": args.minimum_semantic_similarity,
            "includeWithinFile": args.include_within_file,
        },
        "candidates": candidates[: args.top],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n", encoding="ascii")
    print(
        f"Embedded {len(members)} members; found {len(candidates)} candidates; "
        f"wrote top {min(args.top, len(candidates))} to {output}"
    )
    for rank, candidate in enumerate(candidates[: min(args.top, 15)], 1):
        left, right = candidate["left"], candidate["right"]
        print(
            f"{rank:>2}. score={candidate['combinedSimilarity']:.3f} "
            f"lines={candidate['potentialRemovableLines']:>3} "
            f"{left['path']}:{left['startLine']} {left['name']} <-> "
            f"{right['path']}:{right['startLine']} {right['name']}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
