<#
.SYNOPSIS
Reports SharpProof production source size and refactoring pressure by module.

.DESCRIPTION
This is a read-only inventory aid for refactoring. It excludes tests, build
output, dot-prefixed local folders, demo, and smoke projects. Generated source
is reported but excluded from handwritten-size pressure metrics.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Json,

    [Parameter()]
    [ValidateRange(1, 200)]
    [int]$Top = 25,

    [Parameter()]
    [ValidateRange(1, 100000)]
    [int]$FileLineLimit = 2000,

    [Parameter()]
    [ValidateRange(1, 100000)]
    [int]$PartialTypeLineLimit = 3000
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Convert-ToRepoPath
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    $repoPrefix = $repoRoot.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
    if (-not $fullPath.StartsWith($repoPrefix, [System.StringComparison]::OrdinalIgnoreCase))
    {
        throw "Path is outside the repository root: $fullPath"
    }

    return $fullPath.Substring($repoRoot.Length).TrimStart('\', '/').Replace('\', '/')
}

function Get-ModuleName
{
    param([Parameter(Mandatory = $true)][string]$Path)

    switch -Regex ($Path)
    {
        '^SharpProof\.Analyzer/' { return 'Analyzer' }
        '^SharpProof\.Symbolic/' { return 'Symbolic' }
        '^SharpProof\.ProofCore/' { return 'ProofCore' }
        '^Tools/' { return 'Tools' }
        '^Shared/' { return 'Shared' }
        '^SharpProof\.CodeFixes/' { return 'CodeFixes' }
        '^SharpProof\.Attributes/' { return 'Attributes' }
        '^SharpProof\.Package/' { return 'Packaging' }
        '^SharpProof\.Vsix/' { return 'VSIX' }
        '^samples/' { return 'Samples' }
        '^scripts/package-consumers/' { return 'PackageConsumers' }
        default { return 'Other' }
    }
}

function Test-IsGeneratedSource
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Source
    )

    return $Path -match '\.(g|generated)\.cs$' -or
        $Source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
}

function Get-PartialTypeNames
{
    param([Parameter(Mandatory = $true)][string]$Source)

    $namespaceMatch = [regex]::Match(
        $Source,
        '(?m)^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)')
    $namespaceName = if ($namespaceMatch.Success) { $namespaceMatch.Groups[1].Value } else { '<global>' }
    $matches = [regex]::Matches(
        $Source,
        '\bpartial\s+(?:class|struct|record(?:\s+(?:class|struct))?)\s+([A-Za-z_][A-Za-z0-9_]*)')

    return @($matches |
        ForEach-Object { "$namespaceName.$($_.Groups[1].Value)" } |
        Sort-Object -Unique)
}

Push-Location $repoRoot
try
{
    $files = Get-ChildItem -Path $repoRoot -Recurse -Filter '*.cs' |
        Where-Object {
            $repoPath = Convert-ToRepoPath $_.FullName
             $repoPath -notmatch '(^|/)(bin|obj)/' -and
             $repoPath -notmatch '^artifacts/' -and
             $repoPath -notmatch '^docs/readme-examples/' -and
             $repoPath -notmatch '(^|/)\.[^/]+/' -and
             $repoPath -notmatch '^SharpProof\.(Test|ToolingTest)/' -and
             $repoPath -notmatch '^SharpProof\.(Demo|Smoke\.Net472)/'
        } |
        ForEach-Object {
            $repoPath = Convert-ToRepoPath $_.FullName
            $source = Get-Content -LiteralPath $_.FullName -Raw
            [pscustomobject]@{
                path = $repoPath
                module = Get-ModuleName $repoPath
                lines = [int](Get-Content -LiteralPath $_.FullName | Measure-Object -Line).Lines
                generated = Test-IsGeneratedSource $repoPath $source
                partialTypeNames = @(Get-PartialTypeNames $source)
            }
        } |
        Sort-Object path

    $handwrittenFiles = @($files | Where-Object { -not $_.generated })

    $modules = $files |
        Group-Object module |
        ForEach-Object {
            [pscustomobject]@{
                module = $_.Name
                files = [int]$_.Count
                lines = [int](($_.Group | Measure-Object lines -Sum).Sum)
            }
        } |
        Sort-Object lines -Descending

    $largestFiles = $files |
        Sort-Object lines -Descending |
        Select-Object -First $Top

    $oversizedFiles = @($handwrittenFiles |
        Where-Object { $_.lines -gt $FileLineLimit } |
        Sort-Object lines -Descending)

    $partialTypeContributions = @($handwrittenFiles |
        ForEach-Object {
            $file = $_
            foreach ($typeName in $file.partialTypeNames)
            {
                [pscustomobject]@{
                    type = $typeName
                    module = $file.module
                    path = $file.path
                    lines = $file.lines
                }
            }
        })
    $partialTypes = @($partialTypeContributions |
        Group-Object type |
        ForEach-Object {
            $group = @($_.Group)
            [pscustomobject]@{
                type = $_.Name
                module = $group[0].module
                files = [int]$group.Count
                lines = [int](($group | Measure-Object lines -Sum).Sum)
                paths = @($group.path | Sort-Object -Unique)
            }
        } |
        Sort-Object lines -Descending)
    $oversizedPartialTypes = @($partialTypes |
        Where-Object { $_.lines -gt $PartialTypeLineLimit })

    $report = [ordered]@{
        schemaVersion = 2
        totalFiles = [int]$files.Count
        totalLines = [int](($files | Measure-Object lines -Sum).Sum)
        handwrittenFiles = [int]$handwrittenFiles.Count
        handwrittenLines = [int](($handwrittenFiles | Measure-Object lines -Sum).Sum)
        fileLineLimit = $FileLineLimit
        partialTypeLineLimit = $PartialTypeLineLimit
        modules = @($modules)
        largestFiles = @($largestFiles)
        oversizedFiles = @($oversizedFiles)
        partialTypes = @($partialTypes)
        oversizedPartialTypes = @($oversizedPartialTypes)
    }

    if ($Json)
    {
        $report | ConvertTo-Json -Depth 4
        exit 0
    }

    "Production source: $($report.totalLines) lines across $($report.totalFiles) files"
    ''
    'Modules'
    $modules | Format-Table -AutoSize | Out-String
    'Largest files'
    $largestFiles | Format-Table -AutoSize | Out-String
    "Handwritten files over $FileLineLimit lines"
    $oversizedFiles | Select-Object path, module, lines | Format-Table -AutoSize | Out-String
    "Partial types over $PartialTypeLineLimit aggregate lines"
    $oversizedPartialTypes | Select-Object type, module, files, lines | Format-Table -AutoSize | Out-String
}
finally
{
    Pop-Location
}
