<#
.SYNOPSIS
Reports progress against the tracked handwritten LOC reduction baseline.

.DESCRIPTION
Production scope comes from Get-SharpProofProductionMetrics.ps1. Test scope is
limited to tracked C# files under the two test projects. Generated sources are
excluded in both scopes. Build output and untracked audit artifacts never
affect the result.
#>
[CmdletBinding()]
param([Parameter()][switch]$Json)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$repoPrefix = $repoRoot.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
$baselinePath = Join-Path $PSScriptRoot 'refactoring-baseline.json'
$productionMetricsPath = Join-Path $PSScriptRoot 'Get-SharpProofProductionMetrics.ps1'
$baseline = Get-Content -LiteralPath $baselinePath -Raw | ConvertFrom-Json
$production = & $productionMetricsPath -Json | ConvertFrom-Json

function Convert-ToRepoPath
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    if (-not $fullPath.StartsWith($repoPrefix, [System.StringComparison]::OrdinalIgnoreCase))
    {
        throw "Path is outside the repository root: $fullPath"
    }

    return $fullPath.Substring($repoRoot.Length).TrimStart('\', '/').Replace('\', '/')
}

function Test-IsGeneratedSource
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Source
    )

    return $Path -match '\.(g|generated)\.cs$' -or
        $Source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
}

Push-Location $repoRoot
try
{
    $trackedPaths = @(git ls-files -- '*.cs')
    if ($LASTEXITCODE -ne 0) { throw 'git ls-files failed.' }
    $tracked = [System.Collections.Generic.HashSet[string]]::new(
        [System.StringComparer]::OrdinalIgnoreCase)
    foreach ($path in $trackedPaths) { [void]$tracked.Add($path.Replace('\', '/')) }

    $productionLines = 0
    $productionFiles = 0
    foreach ($file in @($production.fileAssignments))
    {
        $path = [string]$file.path
        if (-not $tracked.Contains($path) -or [bool]$file.generated) { continue }

        $fullPath = Join-Path $repoRoot $path
        $productionLines += (Get-Content -LiteralPath $fullPath | Measure-Object -Line).Lines
        $productionFiles++
    }

    $testGroups = foreach ($root in @($baseline.testRoots))
    {
        $files = @($trackedPaths | Where-Object {
            $_.Replace('\', '/').StartsWith([string]$root, [System.StringComparison]::Ordinal)
        })
        $lines = 0
        $handwrittenFiles = 0
        foreach ($path in $files)
        {
            $fullPath = Join-Path $repoRoot $path
            $source = Get-Content -LiteralPath $fullPath -Raw
            if (Test-IsGeneratedSource $path $source) { continue }

            $lines += (Get-Content -LiteralPath $fullPath | Measure-Object -Line).Lines
            $handwrittenFiles++
        }

        [pscustomobject]@{
            root = [string]$root
            files = $handwrittenFiles
            lines = $lines
        }
    }

    $testLines = [int](($testGroups | Measure-Object lines -Sum).Sum)
    $testFiles = [int](($testGroups | Measure-Object files -Sum).Sum)
    $totalLines = $productionLines + $testLines
    $removedLines = [int]$baseline.totalHandwrittenLines - $totalLines

    $report = [ordered]@{
        schemaVersion = 1
        baseline = Convert-ToRepoPath $baselinePath
        baselineCommit = [string]$baseline.commit
        production = [ordered]@{
            baselineLines = [int]$baseline.productionHandwrittenLines
            files = $productionFiles
            lines = $productionLines
            removedLines = [int]$baseline.productionHandwrittenLines - $productionLines
        }
        tests = [ordered]@{
            baselineLines = [int]$baseline.testHandwrittenLines
            files = $testFiles
            lines = $testLines
            removedLines = [int]$baseline.testHandwrittenLines - $testLines
            roots = @($testGroups)
        }
        total = [ordered]@{
            baselineLines = [int]$baseline.totalHandwrittenLines
            lines = $totalLines
            removedLines = $removedLines
            minimumReduction = [int]$baseline.minimumReduction
            minimumRemaining = [Math]::Max(0, [int]$baseline.minimumReduction - $removedLines)
            stretchReduction = [int]$baseline.stretchReduction
            stretchRemaining = [Math]::Max(0, [int]$baseline.stretchReduction - $removedLines)
        }
        testBaseline = [ordered]@{
            passing = [int]$baseline.passingTests
            skipped = [int]$baseline.skippedTests
        }
    }

    if ($Json)
    {
        $report | ConvertTo-Json -Depth 5
        exit 0
    }

    "Tracked handwritten LOC: $totalLines"
    "Removed from baseline: $removedLines"
    "Production: $productionLines ($($report.production.removedLines) removed)"
    "Tests: $testLines ($($report.tests.removedLines) removed)"
    "Minimum remaining: $($report.total.minimumRemaining)"
    "Stretch remaining: $($report.total.stretchRemaining)"
}
finally
{
    Pop-Location
}
