<#
.SYNOPSIS
Finds exact normalized code clones in handwritten SharpProof production sources.

.DESCRIPTION
This read-only audit reports repeated windows of significant C# lines across
different production files. Whitespace is normalized; comments, imports,
namespace declarations, attributes, and brace-only lines are excluded.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [ValidateRange(4, 100)]
    [int]$MinimumLines = 8,

    [Parameter()]
    [ValidateRange(1, 500)]
    [int]$Top = 50,

    [Parameter()]
    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Convert-ToRepoPath
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [IO.Path]::GetFullPath($Path)
    $repoPath = $fullPath.Substring($repoRoot.Length).TrimStart('\', '/')
    return $repoPath.Replace('\', '/')
}

function Test-IsProductionSource
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $repoPath = Convert-ToRepoPath $Path
    return $repoPath -notmatch '(^|/)(bin|obj)/' -and
        $repoPath -notmatch '^artifacts/' -and
        $repoPath -notmatch '^docs/readme-examples/' -and
        $repoPath -notmatch '(^|/)\.[^/]+/' -and
        $repoPath -notmatch '^SharpProof\.(Test|ToolingTest)/' -and
        $repoPath -notmatch '^SharpProof\.(Demo|Smoke\.Net472)/'
}

function Test-IsGeneratedSource
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Source
    )

    return $Path -match '\.(g|generated)\.cs$' -or
        $Source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
}

function Convert-ToSignificantLine
{
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Line)

    $normalized = [regex]::Replace($Line.Trim(), '\s+', ' ')
    if ($normalized.Length -eq 0 -or
        $normalized -match '^(//|/\*|\*|\*/)' -or
        $normalized -match '^(using|global using|namespace)\b' -or
        $normalized -match '^\[.*\]$' -or
        $normalized -match '^[{}]+[;,]?$')
    {
        return $null
    }

    return $normalized
}

$windows = [Collections.Generic.Dictionary[string, Collections.Generic.List[object]]]::new(
    [StringComparer]::Ordinal)
$files = Get-ChildItem -LiteralPath $repoRoot -Recurse -Filter '*.cs' |
    Where-Object { Test-IsProductionSource $_.FullName }

foreach ($file in $files)
{
    $source = [IO.File]::ReadAllText($file.FullName)
    if (Test-IsGeneratedSource $file.FullName $source) { continue }

    $significantLines = [Collections.Generic.List[object]]::new()
    $sourceLines = @($source -split "`r?`n")
    for ($lineIndex = 0; $lineIndex -lt $sourceLines.Count; $lineIndex++)
    {
        $normalized = Convert-ToSignificantLine $sourceLines[$lineIndex]
        if ($null -ne $normalized)
        {
            $significantLines.Add([pscustomobject]@{
                number = $lineIndex + 1
                text = $normalized
            })
        }
    }

    for ($start = 0; $start -le $significantLines.Count - $MinimumLines; $start++)
    {
        $slice = @($significantLines.GetRange($start, $MinimumLines))
        $normalizedLines = @($slice.text)
        $uniqueLines = @($normalizedLines | Sort-Object -Unique)
        if ($uniqueLines.Count -lt 4) { continue }
        $key = [string]::Join("`n", $normalizedLines)
        if ($key.Length -lt 180) { continue }

        $locations = $null
        if (-not $windows.TryGetValue($key, [ref]$locations))
        {
            $locations = [Collections.Generic.List[object]]::new()
            $windows.Add($key, $locations)
        }
        $locations.Add([pscustomobject]@{
            path = Convert-ToRepoPath $file.FullName
            startLine = $slice[0].number
            endLine = $slice[-1].number
        })
    }
}

$clones = @($windows.GetEnumerator() |
    ForEach-Object {
        $locations = @($_.Value)
        $distinctFiles = @($locations.path | Sort-Object -Unique)
        if ($distinctFiles.Count -lt 2) { return }

        [pscustomobject]@{
            significantLines = $MinimumLines
            normalizedCharacters = $_.Key.Length
            normalizedSource = $_.Key
            locations = $locations
        }
    } |
    Sort-Object normalizedCharacters -Descending |
    Select-Object -First $Top)

if ($Json)
{
    [ordered]@{
        schemaVersion = 1
        minimumLines = $MinimumLines
        cloneCount = $clones.Count
        clones = $clones
    } | ConvertTo-Json -Depth 6
    exit 0
}

foreach ($clone in $clones)
{
    "[$($clone.normalizedCharacters) chars]"
    $clone.locations | ForEach-Object { "  $($_.path):$($_.startLine)-$($_.endLine)" }
    $clone.normalizedSource
    ''
}
