<#
.SYNOPSIS
Reports SharpProof production source size and refactoring pressure by module.

.DESCRIPTION
This is a read-only inventory aid for refactoring. It excludes tests, build
output, dot-prefixed local folders, demo, and smoke projects. Generated source
is reported but excluded from handwritten-size pressure metrics.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Json,

    [Parameter()]
    [ValidateRange(1, 200)]
    [int]$Top = 25,

    [Parameter()]
    [ValidateRange(1, 100000)]
    [int]$FileLineLimit = 2000,

    [Parameter()]
    [ValidateRange(1, 100000)]
    [int]$PartialTypeLineLimit = 3000,

    [Parameter()]
    [ValidateRange(1, 100)]
    [int]$PartialTypePartLimit = 8
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
. (Join-Path $PSScriptRoot 'SharpProofSourceInventory.ps1')
$architectureManifestPath = Join-Path $PSScriptRoot 'architecture-modules.json'
$architecture = Get-Content -LiteralPath $architectureManifestPath -Raw | ConvertFrom-Json
$moduleRules = @($architecture.modules)

function Get-ModuleMatches
{
    param([Parameter(Mandatory = $true)][string]$Path)

    return @($moduleRules | Where-Object {
        $rule = $_
        @($rule.pathPrefixes | Where-Object {
            $Path.StartsWith([string]$_, [System.StringComparison]::OrdinalIgnoreCase)
        }).Count -gt 0
    })
}

function Test-IsGeneratedSource
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Source
    )

    return $Path -match '\.(g|generated)\.cs$' -or
        $Source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
}

function Get-PartialTypeNames
{
    param([Parameter(Mandatory = $true)][string]$Source)

    $namespaceMatch = [regex]::Match(
        $Source,
        '(?m)^\s*namespace\s+([A-Za-z_][A-Za-z0-9_.]*)')
    $namespaceName = if ($namespaceMatch.Success) { $namespaceMatch.Groups[1].Value } else { '<global>' }
    $matches = [regex]::Matches(
        $Source,
        '\bpartial\s+(?:class|struct|record(?:\s+(?:class|struct))?)\s+([A-Za-z_][A-Za-z0-9_]*)')

    return @($matches |
        ForEach-Object { "$namespaceName.$($_.Groups[1].Value)" } |
        Sort-Object -Unique)
}

Push-Location $repoRoot
try
{
    $files = Get-SharpProofProductionSourceFiles -RepositoryRoot $repoRoot |
        ForEach-Object {
            $repoPath = $_.RepoPath
            $source = Get-Content -LiteralPath $_.FullName -Raw
            $moduleMatches = @(Get-ModuleMatches $repoPath)
            $module = if ($moduleMatches.Count -eq 1) { [string]$moduleMatches[0].name }
                elseif ($moduleMatches.Count -eq 0) { 'Unassigned' }
                else { 'Ambiguous' }
            $layer = if ($moduleMatches.Count -eq 1) { [int]$moduleMatches[0].layer } else { -1 }
            [pscustomobject]@{
                path = $repoPath
                module = $module
                layer = $layer
                moduleMatchCount = [int]$moduleMatches.Count
                lines = [int](Get-Content -LiteralPath $_.FullName | Measure-Object -Line).Lines
                generated = Test-IsGeneratedSource $repoPath $source
                partialTypeNames = @(Get-PartialTypeNames $source)
            }
        } |
        Sort-Object path

    $handwrittenFiles = @($files | Where-Object { -not $_.generated })

    $modules = $files |
        Group-Object module |
        ForEach-Object {
            [pscustomobject]@{
                module = $_.Name
                layer = [int]$_.Group[0].layer
                files = [int]$_.Count
                lines = [int](($_.Group | Measure-Object lines -Sum).Sum)
            }
        } |
        Sort-Object lines -Descending

    $largestFiles = $files |
        Sort-Object lines -Descending |
        Select-Object -First $Top

    $oversizedFiles = @($handwrittenFiles |
        Where-Object { $_.lines -gt $FileLineLimit } |
        Sort-Object lines -Descending)

    $partialTypeContributions = @($handwrittenFiles |
        ForEach-Object {
            $file = $_
            foreach ($typeName in $file.partialTypeNames)
            {
                [pscustomobject]@{
                    type = $typeName
                    module = $file.module
                    path = $file.path
                    lines = $file.lines
                }
            }
        })
    $partialTypes = @($partialTypeContributions |
        Group-Object type |
        ForEach-Object {
            $group = @($_.Group)
            [pscustomobject]@{
                type = $_.Name
                module = $group[0].module
                files = [int]$group.Count
                lines = [int](($group | Measure-Object lines -Sum).Sum)
                paths = @($group.path | Sort-Object -Unique)
            }
        } |
        Sort-Object lines -Descending)
    $oversizedPartialTypes = @($partialTypes |
        Where-Object { $_.lines -gt $PartialTypeLineLimit })
    $overpartedPartialTypes = @($partialTypes |
        Where-Object { $_.files -gt $PartialTypePartLimit })

    $unassignedFiles = @($files | Where-Object { $_.moduleMatchCount -eq 0 })
    $ambiguousFiles = @($files | Where-Object { $_.moduleMatchCount -gt 1 })
    $dependencyViolations = @()
    $projectFiles = Get-ChildItem -Path $repoRoot -Recurse -Filter '*.csproj' |
        Where-Object {
            $repoPath = ConvertTo-SharpProofRepoPath -RepositoryRoot $repoRoot -Path $_.FullName
            $repoPath -notmatch '(^|/)(bin|obj)/' -and
            $repoPath -notmatch '(^|/)\.[^/]+/' -and
            $repoPath -notmatch '^SharpProof\.(Test|ToolingTest|Demo|Smoke\.Net472)/'
        }
    foreach ($projectFile in $projectFiles)
    {
        $projectPath = ConvertTo-SharpProofRepoPath -RepositoryRoot $repoRoot -Path $projectFile.FullName
        $sourceMatches = @(Get-ModuleMatches $projectPath)
        if ($sourceMatches.Count -ne 1) { continue }

        $sourceRule = $sourceMatches[0]
        [xml]$projectXml = Get-Content -LiteralPath $projectFile.FullName -Raw
        foreach ($reference in @($projectXml.SelectNodes('//ProjectReference')))
        {
            if ($null -eq $reference) { continue }
            $referencePath = [string]$reference.GetAttribute('Include')
            if ([string]::IsNullOrWhiteSpace($referencePath)) { continue }

            $targetFullPath = [System.IO.Path]::GetFullPath(
                (Join-Path $projectFile.DirectoryName $referencePath))
            $targetPath = ConvertTo-SharpProofRepoPath -RepositoryRoot $repoRoot -Path $targetFullPath
            $targetMatches = @(Get-ModuleMatches $targetPath)
            if ($targetMatches.Count -ne 1)
            {
                $dependencyViolations += [pscustomobject]@{
                    project = $projectPath
                    target = $targetPath
                    reason = 'unassigned_or_ambiguous_target'
                }
                continue
            }

            $targetRule = $targetMatches[0]
            $allowedDependencies = @($sourceRule.allowedProjectReferences)
            $isAllowed = [string]$sourceRule.name -eq [string]$targetRule.name -or
                $allowedDependencies -contains [string]$targetRule.name
            $isForwardDependency = [int]$targetRule.layer -gt [int]$sourceRule.layer
            if (-not $isAllowed -or $isForwardDependency)
            {
                $dependencyViolations += [pscustomobject]@{
                    project = $projectPath
                    module = [string]$sourceRule.name
                    target = $targetPath
                    targetModule = [string]$targetRule.name
                    reason = if ($isForwardDependency) { 'forward_layer_dependency' } else { 'module_dependency_not_allowed' }
                }
            }
        }
    }

    $report = [ordered]@{
        schemaVersion = 4
        architectureManifest = ConvertTo-SharpProofRepoPath `
            -RepositoryRoot $repoRoot `
            -Path $architectureManifestPath
        totalFiles = [int]$files.Count
        totalLines = [int](($files | Measure-Object lines -Sum).Sum)
        handwrittenFiles = [int]$handwrittenFiles.Count
        handwrittenLines = [int](($handwrittenFiles | Measure-Object lines -Sum).Sum)
        fileLineLimit = $FileLineLimit
        partialTypeLineLimit = $PartialTypeLineLimit
        partialTypePartLimit = $PartialTypePartLimit
        modules = @($modules)
        fileAssignments = @($files | Select-Object path, module, layer, generated)
        unassignedFiles = @($unassignedFiles | Select-Object path)
        ambiguousFiles = @($ambiguousFiles | Select-Object path)
        dependencyViolations = @($dependencyViolations)
        largestFiles = @($largestFiles)
        oversizedFiles = @($oversizedFiles)
        partialTypes = @($partialTypes)
        oversizedPartialTypes = @($oversizedPartialTypes)
        overpartedPartialTypes = @($overpartedPartialTypes)
    }

    if ($Json)
    {
        $report | ConvertTo-Json -Depth 5
        exit 0
    }

    "Production source: $($report.totalLines) lines across $($report.totalFiles) files"
    ''
    'Modules'
    $modules | Format-Table -AutoSize | Out-String
    'Largest files'
    $largestFiles | Format-Table -AutoSize | Out-String
    "Handwritten files over $FileLineLimit lines"
    $oversizedFiles | Select-Object path, module, lines | Format-Table -AutoSize | Out-String
    "Partial types over $PartialTypeLineLimit aggregate lines"
    $oversizedPartialTypes | Select-Object type, module, files, lines | Format-Table -AutoSize | Out-String
    "Partial types over $PartialTypePartLimit parts"
    $overpartedPartialTypes | Select-Object type, module, files, lines | Format-Table -AutoSize | Out-String
}
finally
{
    Pop-Location
}
