<#
.SYNOPSIS
Finds exact normalized code clones in handwritten SharpProof production sources.

.DESCRIPTION
This read-only audit reports repeated windows of significant C# lines across
different production files. Whitespace is normalized; comments, imports,
namespace declarations, attributes, and brace-only lines are excluded.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [ValidateRange(4, 100)]
    [int]$MinimumLines = 8,

    [Parameter()]
    [ValidateRange(1, 500)]
    [int]$Top = 50,

    [Parameter()]
    [switch]$IncludeWithinFile,

    [Parameter()]
    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Convert-ToRepoPath
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $fullPath = [IO.Path]::GetFullPath($Path)
    $repoPath = $fullPath.Substring($repoRoot.Length).TrimStart('\', '/')
    return $repoPath.Replace('\', '/')
}

function Test-IsProductionSource
{
    param([Parameter(Mandatory = $true)][string]$Path)

    $repoPath = Convert-ToRepoPath $Path
    return $repoPath -notmatch '(^|/)(bin|obj)/' -and
        $repoPath -notmatch '^artifacts/' -and
        $repoPath -notmatch '^docs/readme-examples/' -and
        $repoPath -notmatch '(^|/)\.[^/]+/' -and
        $repoPath -notmatch '^SharpProof\.(Test|ToolingTest)/' -and
        $repoPath -notmatch '^SharpProof\.(Demo|Smoke\.Net472)/'
}

function Test-IsGeneratedSource
{
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Source
    )

    return $Path -match '\.(g|generated)\.cs$' -or
        $Source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
}

function Convert-ToSignificantLine
{
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Line)

    $normalized = [regex]::Replace($Line.Trim(), '\s+', ' ')
    if ($normalized.Length -eq 0 -or
        $normalized -match '^(//|/\*|\*|\*/)' -or
        $normalized -match '^(using|global using|namespace)\b' -or
        $normalized -match '^\[.*\]$' -or
        $normalized -match '^[{}]+[;,]?$')
    {
        return $null
    }

    return $normalized
}

$windows = [Collections.Generic.Dictionary[string, Collections.Generic.List[object]]]::new(
    [StringComparer]::Ordinal)
$files = Get-ChildItem -LiteralPath $repoRoot -Recurse -Filter '*.cs' |
    Where-Object { Test-IsProductionSource $_.FullName }

foreach ($file in $files)
{
    $source = [IO.File]::ReadAllText($file.FullName)
    if (Test-IsGeneratedSource $file.FullName $source) { continue }

    $significantLines = [Collections.Generic.List[object]]::new()
    $sourceLines = @($source -split "`r?`n")
    for ($lineIndex = 0; $lineIndex -lt $sourceLines.Count; $lineIndex++)
    {
        $normalized = Convert-ToSignificantLine $sourceLines[$lineIndex]
        if ($null -ne $normalized)
        {
            $significantLines.Add([pscustomobject]@{
                number = $lineIndex + 1
                text = $normalized
            })
        }
    }

    for ($start = 0; $start -le $significantLines.Count - $MinimumLines; $start++)
    {
        $slice = @($significantLines.GetRange($start, $MinimumLines))
        $normalizedLines = @($slice.text)
        $uniqueLines = @($normalizedLines | Sort-Object -Unique)
        if ($uniqueLines.Count -lt 4) { continue }
        $key = [string]::Join("`n", $normalizedLines)
        if ($key.Length -lt 180) { continue }

        $locations = $null
        if (-not $windows.TryGetValue($key, [ref]$locations))
        {
            $locations = [Collections.Generic.List[object]]::new()
            $windows.Add($key, $locations)
        }
        $locations.Add([pscustomobject]@{
            path = Convert-ToRepoPath $file.FullName
            startLine = $slice[0].number
            endLine = $slice[-1].number
        })
    }
}

$allClones = @($windows.GetEnumerator() |
    ForEach-Object {
        $locations = @($_.Value)
        $distinctFiles = @($locations.path | Sort-Object -Unique)
        if ($locations.Count -lt 2 -or
            (-not $IncludeWithinFile -and $distinctFiles.Count -lt 2)) { return }

        [pscustomobject]@{
            significantLines = $MinimumLines
            normalizedCharacters = $_.Key.Length
            normalizedSource = $_.Key
            locations = $locations
        }
    } |
    Sort-Object normalizedCharacters -Descending)
$clones = @($allClones | Select-Object -First $Top)

$adjudicationManifestPath = Join-Path $PSScriptRoot 'architecture-clone-adjudications.json'
$adjudicationApplied = $false
$detectedCloneSets = @()
$unadjudicatedCloneSets = @()
$staleAdjudications = @()
$adjudicatedCloneSetCount = 0
if (Test-Path -LiteralPath $adjudicationManifestPath)
{
    $manifest = Get-Content -LiteralPath $adjudicationManifestPath -Raw | ConvertFrom-Json
    if ([int]$manifest.minimumLines -eq $MinimumLines)
    {
        $adjudicationApplied = $true
        $detectedByKey = [Collections.Generic.Dictionary[string, object]]::new([StringComparer]::Ordinal)
        foreach ($clone in $allClones)
        {
            $paths = @($clone.locations.path | Sort-Object -Unique)
            $key = [string]::Join("`n", $paths)
            if (-not $detectedByKey.ContainsKey($key))
            {
                $detectedByKey.Add($key, [pscustomobject]@{
                    paths = $paths
                    windowCount = 1
                })
            }
            else
            {
                $detectedByKey[$key].windowCount++
            }
        }

        $adjudicationByKey = [Collections.Generic.Dictionary[string, object]]::new([StringComparer]::Ordinal)
        foreach ($adjudication in @($manifest.adjudications))
        {
            $paths = @($adjudication.paths | Sort-Object -Unique)
            if ($paths.Count -lt 2 -or [string]::IsNullOrWhiteSpace([string]$adjudication.reason))
            {
                throw 'Clone adjudications require at least two paths and a non-empty reason.'
            }

            $key = [string]::Join("`n", $paths)
            if ($adjudicationByKey.ContainsKey($key))
            {
                throw "Duplicate clone adjudication for '$([string]::Join(', ', $paths))'."
            }

            $adjudicationByKey.Add($key, [pscustomobject]@{
                paths = $paths
                category = [string]$adjudication.category
                reason = [string]$adjudication.reason
            })
        }

        $detectedCloneSets = @($detectedByKey.GetEnumerator() | ForEach-Object {
            $adjudication = $null
            $isAdjudicated = $adjudicationByKey.TryGetValue($_.Key, [ref]$adjudication)
            [pscustomobject]@{
                paths = $_.Value.paths
                windowCount = $_.Value.windowCount
                adjudicated = $isAdjudicated
                category = if ($isAdjudicated) { $adjudication.category } else { $null }
                reason = if ($isAdjudicated) { $adjudication.reason } else { $null }
            }
        } | Sort-Object { [string]::Join("`n", $_.paths) })
        $unadjudicatedCloneSets = @($detectedCloneSets | Where-Object { -not $_.adjudicated })
        $adjudicatedCloneSetCount = $detectedCloneSets.Count - $unadjudicatedCloneSets.Count
        $staleAdjudications = @($adjudicationByKey.GetEnumerator() |
            Where-Object { -not $detectedByKey.ContainsKey($_.Key) } |
            ForEach-Object { $_.Value } |
            Sort-Object { [string]::Join("`n", $_.paths) })
    }
}

if ($Json)
{
    [ordered]@{
        schemaVersion = 2
        minimumLines = $MinimumLines
        totalCloneCount = $allClones.Count
        cloneCount = $clones.Count
        clones = $clones
        adjudicationManifest = Convert-ToRepoPath $adjudicationManifestPath
        adjudicationApplied = $adjudicationApplied
        cloneSetCount = $detectedCloneSets.Count
        adjudicatedCloneSetCount = $adjudicatedCloneSetCount
        detectedCloneSets = $detectedCloneSets
        unadjudicatedCloneSets = $unadjudicatedCloneSets
        staleAdjudications = $staleAdjudications
    } | ConvertTo-Json -Depth 6
    exit 0
}

foreach ($clone in $clones)
{
    "[$($clone.normalizedCharacters) chars]"
    $clone.locations | ForEach-Object { "  $($_.path):$($_.startLine)-$($_.endLine)" }
    $clone.normalizedSource
    ''
}
