[CmdletBinding()]
param(
    [Parameter()][int]$MaximumLines = 20000,
    [Parameter()][switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$roots = @(
    'SharpProof.Attributes/',
    'SharpProof.Analyzer/',
    'SharpProof.Package/',
    'SharpProof.ProofCore/',
    'SharpProof.Symbolic/',
    'SharpProof.Smoke.Net472/',
    'Tools/'
)

Push-Location $repoRoot
try
{
    $paths = @(git ls-files --cached --others --exclude-standard -- '*.cs')
    if ($LASTEXITCODE -ne 0) { throw 'git ls-files failed.' }
    $files = @($paths | Where-Object {
        $path = $_.Replace('\', '/')
        (Test-Path -LiteralPath $path) -and
            @($roots | Where-Object { $path.StartsWith($_, [StringComparison]::Ordinal) }).Count -ne 0
    })
    $lineCount = 0
    $handwrittenFiles = 0
    foreach ($path in $files)
    {
        $source = Get-Content -LiteralPath $path -Raw
        if ($path -match '\.(g|generated)\.cs$' -or
            $source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)') { continue }
        $lineCount += (Get-Content -LiteralPath $path | Measure-Object -Line).Lines
        $handwrittenFiles++
    }
    $result = [ordered]@{
        baselineLines = 33366
        targetLines = $MaximumLines
        files = $handwrittenFiles
        lines = $lineCount
        removedLines = 33366 - $lineCount
        passed = $lineCount -le $MaximumLines
    }
    if ($Json) { $result | ConvertTo-Json; return }
    "Production C# files: $handwrittenFiles"
    "Production C# lines: $lineCount"
    "Net lines removed: $($result.removedLines)"
    "Target maximum: $MaximumLines"
    if (-not $result.passed) { exit 1 }
}
finally
{
    Pop-Location
}
