[CmdletBinding()]
param(
    [Parameter()][int]$MaximumLines = 20000,
    [Parameter()][switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$roots = @(
    'SharpProof.Attributes/',
    'SharpProof.Analyzer/',
    'SharpProof.Package/',
    'SharpProof.ProofCore/',
    'SharpProof.Symbolic/',
    'Tools/SharpProof.SymbolicCli/'
)

Push-Location $repoRoot
try
{
    $paths = @(git ls-files --cached --others --exclude-standard -- '*.cs')
    if ($LASTEXITCODE -ne 0) { throw 'git ls-files failed.' }
    $files = @($paths | Where-Object {
        $path = $_.Replace('\', '/')
        (Test-Path -LiteralPath $path) -and
            @($roots | Where-Object { $path.StartsWith($_, [StringComparison]::Ordinal) }).Count -ne 0
    })
    $physicalLineCount = 0
    $lineCount = 0
    $handwrittenFiles = 0
    foreach ($path in $files)
    {
        $source = Get-Content -LiteralPath $path -Raw
        if ($path -match '\.(g|generated)\.cs$' -or
            $source -match '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)') { continue }
        $lines = @(Get-Content -LiteralPath $path)
        $physicalLineCount += $lines.Count
        $lineCount += @($lines | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }).Count
        $handwrittenFiles++
    }
    $result = [ordered]@{
        baselinePhysicalLines = 33366
        targetLines = $MaximumLines
        files = $handwrittenFiles
        physicalLines = $physicalLineCount
        lines = $lineCount
        removedPhysicalLines = 33366 - $physicalLineCount
        passed = $lineCount -le $MaximumLines
    }
    if ($Json) { $result | ConvertTo-Json; return }
    "Production C# files: $handwrittenFiles"
    "Production C# nonblank lines: $lineCount"
    "Production C# physical lines: $physicalLineCount"
    "Net physical lines removed: $($result.removedPhysicalLines)"
    "Target maximum nonblank lines: $MaximumLines"
    if (-not $result.passed) { exit 1 }
}
finally
{
    Pop-Location
}
