[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'CSharpSourceMetrics.ps1')

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$contractPath = Join-Path $repositoryRoot 'eng\acceptance\contract.json'
$contract = Get-Content -LiteralPath $contractPath -Raw |
    ConvertFrom-Json
if ($null -eq $contract.productionComplexity) {
    throw 'The active acceptance contract must define productionComplexity.'
}
$maximumExpressionNodes =
    [int]$contract.productionComplexity.maximumExpressionNodes
$maximumDecisionPoints =
    [int]$contract.productionComplexity.maximumDecisionPoints
$maximumMembers =
    [int]$contract.productionComplexity.maximumMembers
$limits = @(
    $maximumExpressionNodes,
    $maximumDecisionPoints,
    $maximumMembers
)
if (@($limits | Where-Object { $_ -le 0 }).Count -ne 0) {
    throw 'Production-complexity ceilings must be positive.'
}
$ceilingRationale =
    [string]$contract.productionComplexity.ceilingRationale
if ([string]::IsNullOrWhiteSpace($ceilingRationale)) {
    throw 'Production-complexity ceilings require an architectural rationale.'
}
$ceilingBinding =
    "ceilings:$maximumExpressionNodes/$maximumDecisionPoints/$maximumMembers"
if ($ceilingRationale.IndexOf(
        $ceilingBinding,
        [StringComparison]::Ordinal) -lt 0) {
    throw (
        'Production-complexity rationale must bind the exact current ' +
        "limits with '$ceilingBinding'.")
}

$compactProbe = @'
class Probe { int Absolute(int value) { if (value >= 0) return value; return -value; } }
'@
$readableProbe = @'
class Probe
{
    int Absolute(int value)
    {
        if (value >= 0)
        {
            return value;
        }

        return -value;
    }
}
'@
$compactMetrics = Measure-CSharpSourceText `
    -Source $compactProbe `
    -Path '<compact-formatting-probe>'
$readableMetrics = Measure-CSharpSourceText `
    -Source $readableProbe `
    -Path '<readable-formatting-probe>'
foreach ($metric in @('expressionNodes', 'decisionPoints', 'members')) {
    if ($compactMetrics.$metric -ne $readableMetrics.$metric) {
        throw "Source-complexity metric '$metric' is formatting-sensitive."
    }
}

$buildPropertiesPath = Join-Path $repositoryRoot 'Directory.Build.props'
$buildProperties = [xml](
    Get-Content -LiteralPath $buildPropertiesPath -Raw)
$productionProjectNodes = @(
    $buildProperties.SelectNodes(
        '/Project/PropertyGroup/SharpProofProductionProject'))
if ($productionProjectNodes.Count -ne 1) {
    throw (
        'Directory.Build.props must define exactly one ' +
        'SharpProofProductionProject condition.')
}
$productionProjectPattern =
    [regex]::Escape("'`$(MSBuildProjectName)' == '") +
    "(?<name>SharpProof\.[^']+)'"
$productionProjectNames = @(
    [regex]::Matches(
        $productionProjectNodes[0].Condition,
        $productionProjectPattern) |
        ForEach-Object { $_.Groups['name'].Value } |
        Sort-Object -Unique
)
if ($productionProjectNames.Count -eq 0) {
    throw 'Could not derive production projects from Directory.Build.props.'
}
$roots = @($productionProjectNames | ForEach-Object { $_ + '/' })
$missingProductionProjects = @($productionProjectNames | Where-Object {
        $projectDirectory = Join-Path $repositoryRoot $_
        $projectPath = Join-Path $projectDirectory ($_.ToString() + '.csproj')
        -not (Test-Path -LiteralPath $projectDirectory -PathType Container) -or
        -not (Test-Path -LiteralPath $projectPath -PathType Leaf)
    })
if ($missingProductionProjects.Count -ne 0) {
    throw (
        'Production-project declarations have no matching project root: ' +
        ($missingProductionProjects -join ', '))
}
$generatedFileNamePattern = '\.(g|generated)\.cs$'
$autoGeneratedHeaderPattern = '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'
$generatedManifestPath = Join-Path `
    $repositoryRoot `
    'eng\generated\approved-outputs.v1.json'
$generatedManifest = Get-Content -LiteralPath $generatedManifestPath -Raw |
    ConvertFrom-Json
if ($generatedManifest.schemaVersion -ne 1) {
    throw 'The approved generated-output manifest must use schema version 1.'
}
$approvedGeneratedFiles = @($generatedManifest.outputs | ForEach-Object {
        ([string]$_).Replace('\', '/')
    })
if ($approvedGeneratedFiles.Count -ne
    @($approvedGeneratedFiles | Sort-Object -Unique).Count) {
    throw 'The approved generated-output manifest contains duplicate paths.'
}

Push-Location $repositoryRoot
try {
    $paths = @(git ls-files --cached --others --exclude-standard -- '*.cs')
    if ($LASTEXITCODE -ne 0) {
        throw 'git ls-files failed.'
    }
    $files = @($paths | Where-Object {
        $path = $_.Replace('\', '/')
        (Test-Path -LiteralPath $path) -and
            @($roots | Where-Object {
                $path.StartsWith($_, [StringComparison]::Ordinal)
            }).Count -ne 0
    })

    $generatedCandidates = @($files | Where-Object {
            $source = Get-Content -LiteralPath $_ -Raw
            $_ -match $generatedFileNamePattern -or
                $source -match $autoGeneratedHeaderPattern
        } | ForEach-Object { $_.Replace('\', '/') })
    $unapprovedGeneratedFiles = @($generatedCandidates | Where-Object {
            $_ -notin $approvedGeneratedFiles
        })
    $missingGeneratedFiles = @($approvedGeneratedFiles | Where-Object {
            $_ -notin $generatedCandidates
        })
    if ($unapprovedGeneratedFiles.Count -ne 0 -or
        $missingGeneratedFiles.Count -ne 0) {
        throw (
            'Generated-output manifest mismatch. Unapproved: ' +
            ($unapprovedGeneratedFiles -join ', ') + '; missing: ' +
            ($missingGeneratedFiles -join ', '))
    }

    $physicalLines = 0
    $nonblankLines = 0
    $syntaxTokens = 0
    $syntaxNodes = 0
    $expressionNodes = 0
    $decisionPoints = 0
    $members = 0
    $handwrittenFiles = 0
    foreach ($path in $files) {
        $source = Get-Content -LiteralPath $path -Raw
        if ($path.Replace('\', '/') -in $approvedGeneratedFiles) {
            continue
        }

        $metrics = Measure-CSharpSourceText -Source $source -Path $path
        $lines = @(Get-Content -LiteralPath $path)
        $physicalLines += $lines.Count
        $nonblankLines += @($lines | Where-Object {
            -not [string]::IsNullOrWhiteSpace($_)
        }).Count
        $syntaxTokens += $metrics.syntaxTokens
        $syntaxNodes += $metrics.syntaxNodes
        $expressionNodes += $metrics.expressionNodes
        $decisionPoints += $metrics.decisionPoints
        $members += $metrics.members
        $handwrittenFiles++
    }

    $passed =
        $expressionNodes -le $maximumExpressionNodes -and
        $decisionPoints -le $maximumDecisionPoints -and
        $members -le $maximumMembers
    $result = [ordered]@{
        schemaVersion = 1
        contract = 'eng/acceptance/contract.json'
        measurement = 'Roslyn expressions, decisions, and members'
        roots = $roots
        exclusions = [ordered]@{
            approvedGeneratedOutputManifest =
                'eng/generated/approved-outputs.v1.json'
        }
        files = $handwrittenFiles
        expressionNodes = $expressionNodes
        maximumExpressionNodes = $maximumExpressionNodes
        decisionPoints = $decisionPoints
        maximumDecisionPoints = $maximumDecisionPoints
        members = $members
        maximumMembers = $maximumMembers
        informationalPhysicalLines = $physicalLines
        informationalNonblankLines = $nonblankLines
        informationalSyntaxTokens = $syntaxTokens
        informationalSyntaxNodes = $syntaxNodes
        formattingInvariantProbe = $true
        passed = $passed
    }

    if ($Json) {
        $result | ConvertTo-Json -Depth 4
    }
    else {
        "Production C# files: $handwrittenFiles"
        "Expression nodes: $expressionNodes (maximum $maximumExpressionNodes)"
        "Decision points: $decisionPoints (maximum $maximumDecisionPoints)"
        "Members: $members (maximum $maximumMembers)"
        "Syntax tokens (informational only): $syntaxTokens"
        "Syntax nodes (informational only): $syntaxNodes"
        "Physical lines (informational only): $physicalLines"
        "Nonblank lines (informational only): $nonblankLines"
    }

    if (-not $passed) {
        exit 1
    }
}
finally {
    Pop-Location
}
