[CmdletBinding()]
param(
    [Parameter()][switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$contractPath = Join-Path $repositoryRoot 'eng\acceptance\contract.json'
$contract = Get-Content -LiteralPath $contractPath -Raw |
    ConvertFrom-Json
if ($null -eq $contract.productionSize) {
    throw 'The active acceptance contract must define productionSize.'
}
$maximumPhysicalLines = [int]$contract.productionSize.maximumPhysicalLines
$maximumNonblankLines = [int]$contract.productionSize.maximumNonblankLines
if ($maximumPhysicalLines -le 0 -or $maximumNonblankLines -le 0) {
    throw 'Production-size ceilings must be positive.'
}

$roots = @(
    'SharpProof.Attributes/',
    'SharpProof.Analyzer/',
    'SharpProof.CompilerArtifact/',
    'SharpProof.ContractForGenerator/',
    'SharpProof.Contracts/',
    'SharpProof.Dataflow/',
    'SharpProof.Effects/',
    'SharpProof.Frontend/',
    'SharpProof.Ir/',
    'SharpProof.Meta.Analyzers/',
    'SharpProof.Package/',
    'SharpProof.Smt/',
    'SharpProof.Specs/',
    'SharpProof.Verify/',
    'SharpProof.Worker/',
    'SharpProof.Worker.Launcher/',
    'SharpProof.Worker.Protocol/'
)
$generatedFileNamePattern = '\.(g|generated)\.cs$'
$autoGeneratedHeaderPattern = '(?im)^\s*//\s*<auto-generated(?:\s*/>|>)'

Push-Location $repositoryRoot
try {
    $paths = @(git ls-files --cached --others --exclude-standard -- '*.cs')
    if ($LASTEXITCODE -ne 0) {
        throw 'git ls-files failed.'
    }
    $files = @($paths | Where-Object {
        $path = $_.Replace('\', '/')
        (Test-Path -LiteralPath $path) -and
            @($roots | Where-Object {
                $path.StartsWith($_, [StringComparison]::Ordinal)
            }).Count -ne 0
    })
    $physicalLineCount = 0
    $nonblankLineCount = 0
    $handwrittenFiles = 0
    foreach ($path in $files) {
        $source = Get-Content -LiteralPath $path -Raw
        if ($path -match $generatedFileNamePattern -or
            $source -match $autoGeneratedHeaderPattern) {
            continue
        }
        $lines = @(Get-Content -LiteralPath $path)
        $physicalLineCount += $lines.Count
        $nonblankLineCount += @($lines | Where-Object {
            -not [string]::IsNullOrWhiteSpace($_)
        }).Count
        $handwrittenFiles++
    }

    $physicalPassed = $physicalLineCount -le $maximumPhysicalLines
    $nonblankPassed = $nonblankLineCount -le $maximumNonblankLines
    $result = [ordered]@{
        schemaVersion = 3
        contract = 'eng/acceptance/contract.json'
        maximumPhysicalLines = $maximumPhysicalLines
        maximumNonblankLines = $maximumNonblankLines
        roots = $roots
        exclusions = [ordered]@{
            generatedFileNamePattern = $generatedFileNamePattern
            autoGeneratedHeaderPattern = $autoGeneratedHeaderPattern
        }
        files = $handwrittenFiles
        physicalLines = $physicalLineCount
        nonblankLines = $nonblankLineCount
        remainingPhysicalLines =
            $maximumPhysicalLines - $physicalLineCount
        remainingNonblankLines =
            $maximumNonblankLines - $nonblankLineCount
        physicalPassed = $physicalPassed
        nonblankPassed = $nonblankPassed
        passed = $physicalPassed -and $nonblankPassed
    }
    if ($Json) {
        $result | ConvertTo-Json -Depth 4
    }
    else {
        "Production C# files: $handwrittenFiles"
        "Production C# nonblank lines: $nonblankLineCount"
        "Production C# physical lines: $physicalLineCount"
        "Maximum nonblank lines: $maximumNonblankLines"
        "Maximum physical lines: $maximumPhysicalLines"
    }
    if (-not $result.passed) {
        exit 1
    }
}
finally {
    Pop-Location
}
