<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
  </ItemGroup>
</Project>
