// <auto-generated>
// Generated by scripts/Generate-CompilerArtifactModel.ps1 from
// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.
// Output: CompilerArtifactModel.generated.cs.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.CompilerArtifact;

internal static class CompilerManifestArtifactVersions
{
    internal const string Schema = "SharpProof.CompilerManifest";
    internal const int Current = 6;
}

internal enum CompilerContractKind
{
    Requires = 0,
    Ensures = 1,
    Assume = 2
}

internal enum CompilerContractEvidence
{
    CompilerBoundInvocation = 0,
    ClosedAttribute = 1,
    Companion = 2
}

internal enum CompilerVariableRole
{
    Receiver = 0,
    Parameter = 1,
    Result = 2,
    PreState = 3
}

internal enum CompilerPreparedBodyKind
{
    Trivial = 0,
    Program = 1
}

internal sealed record CompilerCallablePreparation(
    IrFactory Factory,
    WorkerCallableManifestEntry Entry,
    ImmutableArray<CompilerPreparedClause> Clauses,
    ImmutableArray<CompilerCanonicalVariable> Variables,
    WorkerClaimReason FailureReason,
    CompilerPreparedBody? Body
)
{
    internal bool IsSuccess => FailureReason == WorkerClaimReason.None;
    internal ImmutableArray<CompilerEffectClaimArtifact> EffectClaims { get; init; } = [];
}

internal sealed record CompilerPreparedClause(
    CompilerContractKind Kind,
    IrTerm Condition,
    CompilerContractEvidence Evidence,
    string? ClaimId,
    string? AssumptionId
);

internal readonly record struct CompilerIntegerInterval(
    long Minimum,
    long Maximum
);

internal sealed record CompilerCanonicalVariable(
    CompilerVariableRole Role,
    int Ordinal,
    IrVarId Variable,
    IrVarId? CurrentStateVariable,
    CompilerIntegerInterval? SourceIntegerInterval,
    string ModelLabel
);

internal sealed record CompilerPreparedBody(
    CompilerPreparedBodyKind Kind,
    IrProgram? Program,
    ImmutableDictionary<IrVarId, IrVarId> ParameterBindings,
    ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> SpecCalls
)
{
    internal const int MaximumInstructions = 4096;

    internal static CompilerPreparedBody Trivial() =>
        new(
            CompilerPreparedBodyKind.Trivial,
            null,
            ImmutableDictionary<IrVarId, IrVarId>.Empty,
            ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall>.Empty);

    internal static CompilerPreparedBody ProgramBody(
        IrProgram program,
        ImmutableDictionary<IrVarId, IrVarId> parameterBindings,
        ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> specCalls) =>
        new(
            CompilerPreparedBodyKind.Program,
            program ?? throw new ArgumentNullException(nameof(program)),
            parameterBindings,
            specCalls);
}

internal sealed record CompilerPreparedSpecCall(
    IrInstructionId Instruction,
    string CallIdentity,
    string WitnessIdentifier,
    bool ConsumesMemoryHavoc
);

internal sealed class CompilerCallableArtifact
{
    public string CallableId { get; set; } = string.Empty;
    public WorkerClaimReason FailureReason { get; set; }
    public PortableIrGraph? Graph { get; set; }
    public CompilerClauseArtifact[] Clauses { get; set; } = [];
    public CompilerVariableArtifact[] Variables { get; set; } = [];
    public CompilerBodyArtifact? Body { get; set; }
    public CompilerEffectClaimArtifact[] EffectClaims { get; set; } = [];
}

internal sealed class CompilerEffectClaimArtifact
{
    public string ClaimId { get; set; } = string.Empty;
    public WorkerEffectContractKind ContractKind { get; set; }
    public WorkerClaimOutcome Outcome { get; set; }
    public WorkerClaimReason Reason { get; set; }
    public WorkerEffectEvidenceCertainty Certainty { get; set; }
    public CompilerEffectConstraintArtifact Constraint { get; set; } = new();
    public WorkerEffectViolationWitness? Witness { get; set; }
    public string Evidence { get; set; } = string.Empty;
    public string EvidenceSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerEffectConstraintArtifact
{
    public WorkerEffectSet AllowedEffects { get; set; }
    public WorkerEffectCapabilitySet AllowedCapabilities { get; set; }
    public string[] AllowedExceptionTypes { get; set; } = [];
}

internal sealed class CompilerClauseArtifact
{
    public CompilerContractKind Kind { get; set; }
    public CompilerContractEvidence Evidence { get; set; }
    public int Root { get; set; } = -1;
    public string? ClaimId { get; set; }
    public string? AssumptionId { get; set; }
    public string PredicateSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerVariableArtifact
{
    public CompilerVariableRole Role { get; set; }
    public int Ordinal { get; set; }
    public int Variable { get; set; } = -1;
    public int CurrentStateVariable { get; set; } = -1;
    public long? Minimum { get; set; }
    public long? Maximum { get; set; }
    public string ModelLabel { get; set; } = string.Empty;
}

internal sealed class CompilerBodyArtifact
{
    public CompilerPreparedBodyKind Kind { get; set; }
    public CompilerVariableMappingArtifact[] ParameterBindings { get; set; } = [];
    public CompilerCallIdentityArtifact[] Calls { get; set; } = [];
    public CompilerSpecCallArtifact[] SpecCalls { get; set; } = [];
}

internal sealed class CompilerVariableMappingArtifact
{
    public int Source { get; set; } = -1;
    public int Target { get; set; } = -1;
}

internal sealed class CompilerCallIdentityArtifact
{
    public int Instruction { get; set; } = -1;
    public string Identity { get; set; } = string.Empty;
}

internal sealed class CompilerSpecCallArtifact
{
    public int Instruction { get; set; } = -1;
    public string WitnessIdentifier { get; set; } = string.Empty;
    public bool ConsumesMemoryHavoc { get; set; }
}

internal enum CompilerOutputKind
{
    ConsoleApplication = 0,
    WindowsApplication = 1,
    DynamicallyLinkedLibrary = 2,
    NetModule = 3,
    WindowsRuntimeMetadata = 4,
    WindowsRuntimeApplication = 5
}

internal enum CompilerOptimizationLevel
{
    Debug = 0,
    Release = 1
}

internal enum CompilerPlatform
{
    AnyCpu = 0,
    AnyCpu32BitPreferred = 1,
    Arm = 2,
    Arm64 = 3,
    Itanium = 4,
    X64 = 5,
    X86 = 6
}

internal enum CompilerNullableContext
{
    Disable = 0,
    Warnings = 1,
    Annotations = 2,
    Enable = 3
}

internal enum CompilerMetadataImportOptions
{
    Public = 0,
    Internal = 1,
    All = 2
}

internal enum CompilerAssemblyIdentityComparer
{
    Default = 0,
    Desktop = 1
}

internal enum CompilerResolverPolicy
{
    EvidenceOnly = 0
}

internal sealed class CompilerDiagnosticArtifact
{
    public string Code { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public WorkerSourceLocation Location { get; set; } = new();
}

internal sealed class CompilerManifestArtifact
{
    public string Schema { get; set; } = CompilerManifestArtifactVersions.Schema;
    public int SchemaVersion { get; set; } = CompilerManifestArtifactVersions.Current;
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public WorkerFeatureSet Features { get; set; }
    public string CompilationSha256 { get; set; } = string.Empty;
    public CompilerCompilationSnapshot Compilation { get; set; } = new();
    public WorkerClaimManifest Manifest { get; set; } = new();
    public int MaximumExpressionDepth { get; set; } = WorkerBudgets.DefaultMaximumExpressionDepth;
    public CompilerDiagnosticArtifact[] CompilerDiagnostics { get; set; } = [];
    public CompilerCallableArtifact[] Callables { get; set; } = [];
}

internal static class CompilerEffectClaimArtifactCodec
{
    internal static void Seal(CompilerEffectClaimArtifact value) =>
        value.EvidenceSha256 = ComputeSha256(value);

    internal static void Validate(CompilerEffectClaimArtifact value)
    {
        if (value == null || string.IsNullOrWhiteSpace(value.ClaimId) ||
            string.IsNullOrWhiteSpace(value.Evidence) ||
            !WorkerProtocolJson.IsDefined(value.ContractKind, WorkerEffectContractKind.Unspecified) ||
            !Enum.IsDefined(typeof(WorkerClaimReason), value.Reason) ||
            !WorkerProtocolJson.IsDefined(value.Certainty, WorkerEffectEvidenceCertainty.Unspecified) ||
            !HasValidConstraint(value.ContractKind, value.Constraint) ||
            !HasValidOutcome(value) ||
            value.EvidenceSha256 != ComputeSha256(value))
            throw new InvalidDataException("Compiler effect-claim evidence is invalid.");
    }

    private static bool HasValidOutcome(CompilerEffectClaimArtifact value) =>
        WorkerProtocolJson.HasValidEffectCertainty(value.Outcome, value.Reason, value.Certainty) &&
        (value.Outcome, value.Reason, value.Certainty, value.Witness) switch
        {
            (WorkerClaimOutcome.Proven, WorkerClaimReason.None, _, null) => true,
            (WorkerClaimOutcome.Refuted, WorkerClaimReason.None,
                _, { } witness) => WorkerProtocolJson.HasValidEffectWitness(witness) &&
                    WorkerProtocolJson.HasValidLocation(witness.Location),
            (WorkerClaimOutcome.Unknown,
                WorkerClaimReason.UnsupportedContract or
                WorkerClaimReason.EffectSummaryIncomplete or
                WorkerClaimReason.EffectContractNotEstablished,
                _, null) => true,
            _ => false
        };

    private static bool HasValidConstraint(
        WorkerEffectContractKind kind,
        CompilerEffectConstraintArtifact? constraint)
    {
        if (constraint == null ||
            !WorkerProtocolJson.HasKnownEffects(
                constraint.AllowedEffects, constraint.AllowedCapabilities) ||
            !WorkerProtocolJson.AreDistinctNonblank(constraint.AllowedExceptionTypes))
            return false;
        return kind switch
        {
            WorkerEffectContractKind.AllowedCapabilities =>
                constraint.AllowedEffects == WorkerEffectSet.None &&
                constraint.AllowedExceptionTypes.Length == 0,
            WorkerEffectContractKind.AllowedExceptions =>
                constraint.AllowedEffects == WorkerEffectSet.None &&
                constraint.AllowedCapabilities == WorkerEffectCapabilitySet.None,
            WorkerEffectContractKind.EffectContract => true,
            _ => constraint.AllowedEffects == WorkerEffectSet.None &&
                constraint.AllowedCapabilities == WorkerEffectCapabilitySet.None &&
                constraint.AllowedExceptionTypes.Length == 0
        };
    }

    private static string ComputeSha256(CompilerEffectClaimArtifact value)
    {
        var witness = value.Witness;
        var constraint = value.Constraint;
        using var hash = new CanonicalHashWriter();
        hash.Add("SharpProof.CompilerEffectClaimEvidence", 6, value.ClaimId,
            value.ContractKind, value.Outcome, value.Reason, value.Certainty,
            constraint.AllowedEffects, constraint.AllowedCapabilities);
        foreach (var type in constraint.AllowedExceptionTypes
                     .OrderBy(static item => item, StringComparer.Ordinal))
            hash.Add(type);
        hash.Add(witness?.Kind, witness?.Detail, witness?.Effects ?? WorkerEffectSet.None,
            witness?.Capabilities ?? WorkerEffectCapabilitySet.None);
        foreach (var type in (witness?.ExactExceptionTypeHierarchy ?? [])
                     .OrderBy(static item => item, StringComparer.Ordinal))
            hash.Add(type);
        return hash.Add(witness?.Location.Path, witness?.Location.Start ?? -1,
            witness?.Location.Length ?? -1, witness?.Location.Line ?? -1,
            witness?.Location.Column ?? -1, value.Evidence).Finish();
    }
}
