// <auto-generated>
// Generated by scripts/Generate-CompilerArtifactModel.ps1 from
// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.
// Output: CompilerCompilationModel.generated.cs.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.CompilerArtifact;

internal sealed class CompilerCompilationSnapshot {
    public string ProjectDirectory { get; set; } = string.Empty;
    public string AssemblyName { get; set; } = string.Empty;
    public string AssemblyIdentity { get; set; } = string.Empty;
    public string TargetFramework { get; set; } = string.Empty;
    public string CompilerVersion { get; set; } = string.Empty;
    public string CompilerMvid { get; set; } = string.Empty;
    public string CSharpCompilerVersion { get; set; } = string.Empty;
    public string CSharpCompilerMvid { get; set; } = string.Empty;
    public CompilerCompilationOptionsSnapshot Options { get; set; } = new();
    public CompilerSyntaxTreeSnapshot[] SyntaxTrees { get; set; } = [];
    public CompilerReferenceSnapshot[] References { get; set; } = [];
    public CompilerAdditionalFileSnapshot[] AdditionalFiles { get; set; } = [];
}

internal sealed class CompilerCompilationOptionsSnapshot {
    public string OutputKind { get; set; } = string.Empty;
    public string OptimizationLevel { get; set; } = string.Empty;
    public string Platform { get; set; } = string.Empty;
    public string NullableContext { get; set; } = string.Empty;
    public string MetadataImportOptions { get; set; } = string.Empty;
    public bool CheckOverflow { get; set; }
    public bool AllowUnsafe { get; set; }
    public bool Deterministic { get; set; }
    public bool ReferencesSupersedeLowerVersions { get; set; }
    public string AssemblyIdentityComparer { get; set; } = string.Empty;
    public string[] Usings { get; set; } = [];
    public string ResolverPolicy { get; set; } = string.Empty;
}

internal sealed class CompilerSyntaxTreeSnapshot {
    public string Path { get; set; } = string.Empty;
    public string Sha256 { get; set; } = string.Empty;
    public string LanguageVersion { get; set; } = string.Empty;
    public string DocumentationMode { get; set; } = string.Empty;
    public string Kind { get; set; } = string.Empty;
    public string[] PreprocessorSymbols { get; set; } = [];
    public CompilerFeatureSnapshot[] Features { get; set; } = [];
}

internal sealed class CompilerReferenceSnapshot {
    public string Path { get; set; } = string.Empty;
    public string Kind { get; set; } = string.Empty;
    public bool EmbedInteropTypes { get; set; }
    public string[] Aliases { get; set; } = [];
    public string Identity { get; set; } = string.Empty;
    public string Sha256 { get; set; } = string.Empty;
}

internal sealed class CompilerAdditionalFileSnapshot {
    public string Path { get; set; } = string.Empty;
    public string Sha256 { get; set; } = string.Empty;
}

internal sealed class CompilerFeatureSnapshot {
    public string Key { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
}
