// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable

using System.Collections.Immutable;
using System.Text.Json.Serialization;
using SharpProof.Ir;
using SharpProof.Worker.Protocol;

namespace SharpProof.CompilerArtifact;

internal static class CompilerManifestArtifactVersions
{
    internal const string Schema = "SharpProof.CompilerManifest";
    internal const int Current = 29;
}

internal static class CompilerRelationalSummaryVersions
{
    internal const int Current = 2;
}

internal static class CompilerSpecificationPackCatalogVersions
{
    internal const int Current = 2;
    internal const string Sha256 = "53be86bbf2cd6b4c093caf96e308220809cbaa7cb39e0d475f84d34df5f6a178";
    internal const string PackIds = "dotnet.scalar";
    internal const string PackIdentities = "dotnet.scalar@1";
}

internal static class CompilerSpecificationPackVersions
{
    internal const int Current = 1;
}

internal enum CompilerContractKind
{
    Requires = 0,
    Ensures = 1,
    Assume = 2
}

internal enum CompilerContractEvidence
{
    CompilerBoundInvocation = 0,
    ClosedAttribute = 1,
    Companion = 2
}

internal sealed record CompilerCallablePreparation(
    WorkerCallableManifestEntry Entry,
    WorkerClaimReason FailureReason
)
{
    internal bool IsSuccess => FailureReason == WorkerClaimReason.None;
    internal ImmutableArray<CompilerEffectClaimArtifact> EffectClaims { get; init; } = [];
    internal CompilerCompilationSnapshot Compilation { get; init; } = new();
    internal CompilerTotalCallablePreparation? Total { get; init; }
    internal CompilerTotalEntryPreparation? TotalEntry { get; init; }
}

internal sealed record CompilerTotalEntryPreparation(string CallableId, IrFactory Factory,
    ImmutableArray<CompilerTotalParameter> Parameters, ImmutableArray<CompilerTotalClause> Clauses)
{
    // The last parameter is `this`, which is never null.
    internal bool HasReceiver { get; init; }
}

internal sealed record CompilerTotalCallablePreparation(
    string CallableId,
    IrProgram Program,
    ImmutableArray<CompilerTotalParameter> Parameters,
    IrVarId? Result,
    ImmutableArray<CompilerTotalClause> Clauses,
    bool IsBodyAbstraction = false)
{
    internal ImmutableArray<CompilerDisjointInputPair> DisjointInputs { get; init; } = [];
    internal ImmutableArray<CompilerTotalExceptionConstraint> ExceptionConstraints { get; init; } = [];
    internal ImmutableArray<CompilerTotalCallPrecondition> CallPreconditions { get; init; } = [];
    internal bool EffectsCompleteAtEntry { get; init; }
    internal ImmutableArray<string> ValidEffectClaimIds { get; init; } = [];
    // The last parameter is `this`, which is never null.
    internal bool HasReceiver { get; init; }
}

// Detached graph validation only. External source ownership is established
// separately by the shadow envelope; the owner label is not authentication.
internal sealed class CompilerDecodedShadowBody
{
    private CompilerDecodedShadowBody(CompilerTotalCallablePreparation body)
    { Body = body; }

    internal CompilerTotalCallablePreparation Body { get; }

    internal static CompilerDecodedShadowBody Decode(string ownerId,
        CompilerTotalCallableArtifact artifact, CancellationToken cancellationToken, CompilerReferenceSnapshot[]? metadataReferences = null)
    {
        return new(CompilerTotalCallableArtifactCodec.DecodeShadowBodyCore(ownerId, artifact, cancellationToken, metadataReferences));
    }
}

internal sealed record CompilerTotalExceptionConstraint(string ClaimId, ImmutableArray<IrExceptionKind> AllowedKinds);

internal sealed record CompilerTotalCallPrecondition(IrInstructionId Instruction, string CalleeIdentity,
    int ClauseOrdinal, OperationId ClauseSite, IrTerm Value, IrTerm Safe,
    CompilerMetadataClauseOrigin? MetadataClause = null)
{
    internal ImmutableArray<CompilerShadowCallHop> Ancestry { get; init; } = [];
}

internal sealed record CompilerShadowCallHop(string CallerIdentity, string CalleeIdentity, IrSourceSpan Site);

internal readonly record struct CompilerTotalParameter(IrVarId Entry, IrVarId Current, IrVarId Old);

internal sealed record CompilerDisjointInputPair([property: JsonRequired] int Left, [property: JsonRequired] int Right);

internal sealed record CompilerTotalClause(CompilerContractKind Kind, IrTerm Value, IrTerm Safe,
    OperationId Operation, string? ClaimId, string? AssumptionId);

internal sealed class CompilerTotalCallableArtifact
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompilerDisjointInputPair[]? DisjointInputs { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool EffectsCompleteAtEntry { get; set; }
    public string[] ValidEffectClaimIds { get; set; } = [];
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsBodyAbstraction { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool HasReceiver { get; set; }
    public PortableIrGraph Graph { get; set; } = new();
    public CompilerTotalParameterArtifact[] Parameters { get; set; } = [];
    public int Result { get; set; } = -1;
    public CompilerTotalClauseArtifact[] Clauses { get; set; } = [];
    public CompilerTotalExceptionConstraintArtifact[] ExceptionConstraints { get; set; } = [];
    public CompilerTotalCallPreconditionArtifact[] CallPreconditions { get; set; } = [];
}

internal sealed record CompilerMetadataClauseOrigin(string AssemblyIdentity, string ImageSha256,
    string ModuleName, string ModuleMvid, int MethodToken, int ParameterOrdinal, int ParameterSequence,
    int ParameterToken, int AttributeToken, int ConstructorToken, string AttributeIdentity,
    string ConstructorIdentity, string Kind, long Minimum, long Maximum,
    ImmutableArray<byte> ConstructorSignature, ImmutableArray<byte> ValueBlob);

internal sealed class CompilerTotalCallPreconditionArtifact
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompilerMetadataClauseOrigin? MetadataClause { get; set; }

    public int InstructionIndex { get; set; } = -1;
    public string CalleeIdentity { get; set; } = string.Empty;
    public int ClauseOrdinal { get; set; } = -1;
    public int ClauseSite { get; set; } = -1;
    public int ValueRoot { get; set; } = -1;
    public int SafeRoot { get; set; } = -1;
}

internal sealed class CompilerTotalExceptionConstraintArtifact
{
    public string ClaimId { get; set; } = string.Empty;
    public IrExceptionKind[] AllowedKinds { get; set; } = [];
}

internal sealed class CompilerTotalParameterArtifact
{
    public int Entry { get; set; } = -1;
    public int Current { get; set; } = -1;
    public int Old { get; set; } = -1;
}

internal sealed class CompilerTotalClauseArtifact
{
    public CompilerContractKind Kind { get; set; }
    public int ValueRoot { get; set; } = -1;
    public int SafeRoot { get; set; } = -1;
    public int Operation { get; set; } = -1;
    public string? ClaimId { get; set; }
    public string? AssumptionId { get; set; }
}

internal static class CompilerArtifactLimits
{
    internal const int MaximumInstructions = 4096;
}

internal sealed class CompilerSpecificationPackConfiguration
{
    public string[] SpecificationPackIds { get; set; } = [];
    public int SpecificationPackCatalogVersion { get; set; } = CompilerSpecificationPackCatalogVersions.Current;
    public string SpecificationPackCatalogSha256 { get; set; } = CompilerSpecificationPackCatalogVersions.Sha256;
}

internal sealed class CompilerCallableArtifact
{
    public string CallableId { get; set; } = string.Empty;
    public WorkerClaimReason FailureReason { get; set; }
    public CompilerEffectClaimArtifact[] EffectClaims { get; set; } = [];
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompilerTotalCallableArtifact? Total { get; set; }
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public CompilerTotalCallableArtifact? TotalEntry { get; set; }
}

internal sealed class CompilerEffectClaimArtifact
{
    public string ClaimId { get; set; } = string.Empty;
    public WorkerEffectContractKind ContractKind { get; set; }
    public WorkerClaimOutcome Outcome { get; set; }
    public WorkerClaimReason Reason { get; set; }
    public WorkerEffectEvidenceCertainty Certainty { get; set; }
    public CompilerEffectConstraintArtifact Constraint { get; set; } = new();
    public string Evidence { get; set; } = string.Empty;
    public string EvidenceSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerEffectConstraintArtifact
{
    public WorkerEffectSet AllowedEffects { get; set; }
    public WorkerEffectCapabilitySet AllowedCapabilities { get; set; }
    public string[] AllowedExceptionTypes { get; set; } = [];
}

internal enum CompilerOutputKind
{
    ConsoleApplication = 0,
    WindowsApplication = 1,
    DynamicallyLinkedLibrary = 2,
    NetModule = 3,
    WindowsRuntimeMetadata = 4,
    WindowsRuntimeApplication = 5
}

internal enum CompilerOptimizationLevel
{
    Debug = 0,
    Release = 1
}

internal enum CompilerPlatform
{
    AnyCpu = 0,
    AnyCpu32BitPreferred = 1,
    Arm = 2,
    Arm64 = 3,
    Itanium = 4,
    X64 = 5,
    X86 = 6
}

internal enum CompilerNullableContext
{
    Disable = 0,
    Warnings = 1,
    Annotations = 2,
    Enable = 3
}

internal enum CompilerMetadataImportOptions
{
    Public = 0,
    Internal = 1,
    All = 2
}

internal enum CompilerAssemblyIdentityComparer
{
    Default = 0,
    Desktop = 1
}

internal enum CompilerResolverPolicy
{
    EvidenceOnly = 0
}

internal sealed class CompilerDiagnosticArtifact
{
    public string Code { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public bool IsSource { get; set; }
    public WorkerSourceLocation Location { get; set; } = new();
    [JsonIgnore]
    public int SourceTreeOrdinal { get; set; } = -1;
    [JsonIgnore]
    public string SourceTreePath { get; set; } = string.Empty;
    [JsonIgnore]
    public string SourceTreeSha256 { get; set; } = string.Empty;
    [JsonIgnore]
    public string SourceLineMapSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerManifestArtifact
{
    public string Schema { get; set; } = CompilerManifestArtifactVersions.Schema;
    public int SchemaVersion { get; set; } = CompilerManifestArtifactVersions.Current;
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public int RelationalSummarySchemaVersion { get; set; } = CompilerRelationalSummaryVersions.Current;
    public int SpecificationPackSchemaVersion { get; set; } = CompilerSpecificationPackVersions.Current;
    public string[] SpecificationPackIds { get; set; } = [];
    public int SpecificationPackCatalogVersion { get; set; } = CompilerSpecificationPackCatalogVersions.Current;
    public string SpecificationPackCatalogSha256 { get; set; } = CompilerSpecificationPackCatalogVersions.Sha256;
    public WorkerFeatureSet Features { get; set; }
    public CompilerCompilationSnapshot Compilation { get; set; } = new();
    public WorkerClaimManifest Manifest { get; set; } = new();
    public int MaximumExpressionDepth { get; set; } = WorkerBudgets.DefaultMaximumExpressionDepth;
    public CompilerDiagnosticArtifact[] CompilerDiagnostics { get; set; } = [];
    public CompilerCallableArtifact[] Callables { get; set; } = [];
    public CompilerReachableSourceArtifact? ReachableSource { get; set; }
}

// Shadow input for interprocedural effect analysis. An absent or incomplete
// body never supplies an effect fact or a normal-completion guarantee.
internal sealed class CompilerReachableSourceArtifact
{
    public bool CollectionComplete { get; set; }
    public CompilerSourceRootArtifact[] Roots { get; set; } = [];
    public CompilerSourceBodyArtifact[] Bodies { get; set; } = [];
    public CompilerSourceDocumentArtifact[] Documents { get; set; } = [];
}

internal sealed class CompilerSourceDocumentArtifact
{
    public int SourceTreeOrdinal { get; set; }
    public string Path { get; set; } = string.Empty;
    public int MaximumBodyEnd { get; set; }
}

internal sealed class CompilerSourceRootArtifact
{
    public string CallableId { get; set; } = string.Empty;
    public string BodyId { get; set; } = string.Empty;
}

internal sealed class CompilerSourceBodyArtifact
{
    public string BodyId { get; set; } = string.Empty;
    public string MethodIdentity { get; set; } = string.Empty;
    public string CallIdentity { get; set; } = string.Empty;
    public bool IsStatic { get; set; }
    public string[] ParameterTypes { get; set; } = [];
    public string? ReturnType { get; set; }
    public int SourceTreeOrdinal { get; set; }
    public int Start { get; set; }
    public int Length { get; set; }
    public bool CallsComplete { get; set; }
    public bool EffectsCompleteAtEntry { get; set; }
    public string[] Callees { get; set; } = [];
    public PortableIrGraph? Graph { get; set; }
    public bool IsCallSkeleton { get; set; }
    public CompilerSourceCallArtifact[] SourceCalls { get; set; } = [];
}

internal sealed class CompilerSourceCallArtifact
{
    public int InstructionIndex { get; set; }
    public string CalleeBodyId { get; set; } = string.Empty;
}

internal readonly struct CompilerEffectConstraintRule(
    WorkerEffectContractKind kind,
    bool effectsMustBeEmpty,
    bool capabilitiesMustBeEmpty,
    bool exceptionsMustBeEmpty)
{
    internal WorkerEffectContractKind Kind { get; } = kind;
    internal bool EffectsMustBeEmpty { get; } = effectsMustBeEmpty;
    internal bool CapabilitiesMustBeEmpty { get; } = capabilitiesMustBeEmpty;
    internal bool ExceptionsMustBeEmpty { get; } = exceptionsMustBeEmpty;
}

internal static class CompilerEffectEvidenceCatalog
{
    internal const string EvidenceDomain = "SharpProof.CompilerEffectClaimEvidence";
    internal const int EvidenceVersion = 10;
    internal static readonly ImmutableArray<WorkerClaimReason> UnknownReasons = [
        WorkerClaimReason.UnsupportedContract,
        WorkerClaimReason.CounterexampleNotReplayable,
        WorkerClaimReason.EffectSummaryIncomplete,
        WorkerClaimReason.EffectContractNotEstablished,
        WorkerClaimReason.ResourceLimit,
        WorkerClaimReason.UnsupportedBody,
    ];
    internal static readonly ImmutableArray<(WorkerClaimOutcome Outcome, WorkerClaimReason Reason,
        WorkerEffectEvidenceCertainty Certainty)> SupportedEffectTuples = [
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary),
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.VacuousEntry),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedContract, WorkerEffectEvidenceCertainty.Unavailable),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.CounterexampleNotReplayable, WorkerEffectEvidenceCertainty.Unavailable),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
    ];
    internal static bool HasValidEffectTuple(
        WorkerClaimOutcome outcome, WorkerClaimReason reason,
        WorkerEffectEvidenceCertainty certainty)
    {
        foreach (var tuple in SupportedEffectTuples)
        {
            if (tuple.Outcome == outcome && tuple.Reason == reason &&
                tuple.Certainty == certainty)
            {
                return true;
            }
        }
        return outcome == WorkerClaimOutcome.Unknown &&
            certainty == WorkerEffectEvidenceCertainty.Unavailable &&
            UnknownReasons.Contains(reason);
    }
    internal static readonly ImmutableArray<CompilerEffectConstraintRule> ConstraintRules = [
        new(WorkerEffectContractKind.EnforcePure, true, true, true),
        new(WorkerEffectContractKind.ZeroAllocations, true, true, true),
        new(WorkerEffectContractKind.AllowedCapabilities, true, false, true),
        new(WorkerEffectContractKind.DoesNotThrow, true, true, true),
        new(WorkerEffectContractKind.AllowedExceptions, true, true, false),
        new(WorkerEffectContractKind.EffectContract, false, false, false),
    ];
}

internal static class CompilerCallableArtifactReasonCatalog
{
    internal const WorkerClaimReason SuccessReason = WorkerClaimReason.None;
    internal const WorkerClaimReason DiagnosticFailureReason = WorkerClaimReason.UnsupportedCallable;
    internal static readonly ImmutableArray<WorkerClaimReason> FailureReasons = [
        WorkerClaimReason.UnsupportedCallable,
        WorkerClaimReason.UnsupportedContract,
        WorkerClaimReason.UnsupportedBody,
        WorkerClaimReason.UnsupportedExpression,
    ];
    internal static bool IsFailureReason(WorkerClaimReason reason) =>
        FailureReasons.Contains(reason);
}
