// <auto-generated>
// Generated by scripts/Generate-CompilerArtifactModel.ps1 from
// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.
// Output: CompilerArtifactModel.generated.cs.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.CompilerArtifact;

internal static class CompilerManifestArtifactVersions
{
    internal const string Schema = "SharpProof.CompilerManifest";
    internal const int Current = 12;
}

internal static class CompilerRelationalSummaryVersions
{
    internal const int Current = 1;
}

internal static class CompilerSpecificationPackVersions
{
    internal const int Current = 1;
}

internal enum CompilerContractKind
{
    Requires = 0,
    Ensures = 1,
    Assume = 2
}

internal enum CompilerContractEvidence
{
    CompilerBoundInvocation = 0,
    ClosedAttribute = 1,
    Companion = 2
}

internal enum CompilerVariableRole
{
    Receiver = 0,
    Parameter = 1,
    Result = 2,
    PreState = 3
}

internal enum CompilerPreparedBodyKind
{
    Trivial = 0,
    Program = 1
}

internal enum CompilerSummaryOrigin
{
    Source = 0,
    ImplementationIl = 1,
    SpecificationPack = 2
}

internal sealed record CompilerCallablePreparation(
    IrFactory Factory,
    WorkerCallableManifestEntry Entry,
    ImmutableArray<CompilerPreparedClause> Clauses,
    ImmutableArray<CompilerCanonicalVariable> Variables,
    WorkerClaimReason FailureReason,
    CompilerPreparedBody? Body
)
{
    internal bool IsSuccess => FailureReason == WorkerClaimReason.None;
    internal ImmutableArray<CompilerEffectClaimArtifact> EffectClaims { get; init; } = [];
    internal CompilerCompilationSnapshot Compilation { get; init; } = new();
}

internal sealed record CompilerPreparedClause(
    CompilerContractKind Kind,
    IrTerm Condition,
    CompilerContractEvidence Evidence,
    string? ClaimId,
    string? AssumptionId
);

internal readonly record struct CompilerIntegerInterval(
    long Minimum,
    long Maximum
);

internal sealed record CompilerCanonicalVariable(
    CompilerVariableRole Role,
    int Ordinal,
    IrVarId Variable,
    IrVarId? CurrentStateVariable,
    CompilerIntegerInterval? SourceIntegerInterval,
    string ModelLabel
);

internal sealed record CompilerPreparedBody(
    CompilerPreparedBodyKind Kind,
    IrProgram? Program,
    ImmutableDictionary<IrVarId, IrVarId> ParameterBindings,
    ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> SpecCalls,
    ImmutableDictionary<IrInstructionId, CompilerPreparedSummaryCall> SummaryCalls
)
{
    internal const int MaximumInstructions = 4096;

    internal static CompilerPreparedBody Trivial() =>
        new(
            CompilerPreparedBodyKind.Trivial,
            null,
            ImmutableDictionary<IrVarId, IrVarId>.Empty,
            ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall>.Empty,
            ImmutableDictionary<IrInstructionId, CompilerPreparedSummaryCall>.Empty);

    internal static CompilerPreparedBody ProgramBody(
        IrProgram program,
        ImmutableDictionary<IrVarId, IrVarId> parameterBindings,
        ImmutableDictionary<IrInstructionId, CompilerPreparedSpecCall> specCalls,
        ImmutableDictionary<IrInstructionId, CompilerPreparedSummaryCall> summaryCalls) =>
        new(
            CompilerPreparedBodyKind.Program,
            program ?? throw new ArgumentNullException(nameof(program)),
            parameterBindings,
            specCalls,
            summaryCalls);
}

internal sealed record CompilerPreparedSpecCall(
    IrInstructionId Instruction,
    string CallIdentity,
    string WitnessIdentifier,
    bool ConsumesMemoryHavoc
);

internal sealed record CompilerPreparedSummaryEvidence(
    CompilerSummaryOrigin Origin,
    string EvidenceSha256,
    string EvidenceIdentity
);

internal sealed record CompilerPreparedSummaryCall(
    IrInstructionId Instruction,
    string CallIdentity,
    CompilerSummaryOrigin Origin,
    IrVarId Result,
    ImmutableArray<IrVarId> ExistentialVariables,
    IrTerm NormalRelation,
    string EvidenceSha256,
    string EvidenceIdentity,
    ImmutableArray<CompilerPreparedSummaryEvidence> DependencyEvidence
);

internal sealed class CompilerCallableArtifact
{
    public string CallableId { get; set; } = string.Empty;
    public WorkerClaimReason FailureReason { get; set; }
    public PortableIrGraph? Graph { get; set; }
    public CompilerClauseArtifact[] Clauses { get; set; } = [];
    public CompilerVariableArtifact[] Variables { get; set; } = [];
    public CompilerBodyArtifact? Body { get; set; }
    public CompilerEffectClaimArtifact[] EffectClaims { get; set; } = [];
}

internal sealed class CompilerEffectClaimArtifact
{
    public string ClaimId { get; set; } = string.Empty;
    public WorkerEffectContractKind ContractKind { get; set; }
    public WorkerClaimOutcome Outcome { get; set; }
    public WorkerClaimReason Reason { get; set; }
    public WorkerEffectEvidenceCertainty Certainty { get; set; }
    public CompilerEffectConstraintArtifact Constraint { get; set; } = new();
    public WorkerEffectViolationWitness? Witness { get; set; }
    public CompilerEffectReplayArtifact? Replay { get; set; }
    public string Evidence { get; set; } = string.Empty;
    public string EvidenceSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerEffectConstraintArtifact
{
    public WorkerEffectSet AllowedEffects { get; set; }
    public WorkerEffectCapabilitySet AllowedCapabilities { get; set; }
    public string[] AllowedExceptionTypes { get; set; } = [];
}

internal enum CompilerEffectReplayPathKind
{
    Unspecified = 0,
    Unconditional = 1
}

internal enum CompilerEffectReplayEventKind
{
    Unspecified = 0,
    ManagedObjectAllocation = 1,
    ManagedArrayAllocation = 2,
    ExplicitThrow = 3,
    ReceiverFieldRead = 4,
    ReceiverFieldWrite = 5,
    MonitorCall = 6,
    EmptyLock = 7
}

internal sealed class CompilerEffectReplayArtifact
{
    public CompilerEffectReplayPathKind PathKind { get; set; }
    public string ConstraintSha256 { get; set; } = string.Empty;
    public CompilerEffectReplayEventArtifact[] Events { get; set; } = [];
}

internal sealed class CompilerEffectReplayEventArtifact
{
    public int Ordinal { get; set; } = -1;
    public CompilerEffectReplayEventKind Kind { get; set; }
    public int SyntaxTreeOrdinal { get; set; } = -1;
    public string SyntaxTreeSha256 { get; set; } = string.Empty;
    public int SyntaxStart { get; set; } = -1;
    public int SyntaxLength { get; set; } = -1;
    public string OperationIdentitySha256 { get; set; } = string.Empty;
    public string MemberIdentity { get; set; } = string.Empty;
    public string? MemberDocumentationId { get; set; }
    public string TypeIdentity { get; set; } = string.Empty;
    public string? TypeDocumentationId { get; set; }
    public string? SpecWitnessIdentifier { get; set; }
    public long[] ScalarOperands { get; set; } = [];
    public string[] ExactExceptionTypeHierarchy { get; set; } = [];
    public WorkerSourceLocation Location { get; set; } = new();
}

internal sealed class CompilerClauseArtifact
{
    public CompilerContractKind Kind { get; set; }
    public CompilerContractEvidence Evidence { get; set; }
    public int Root { get; set; } = -1;
    public string? ClaimId { get; set; }
    public string? AssumptionId { get; set; }
    public string PredicateSha256 { get; set; } = string.Empty;
}

internal sealed class CompilerVariableArtifact
{
    public CompilerVariableRole Role { get; set; }
    public int Ordinal { get; set; }
    public int Variable { get; set; } = -1;
    public int CurrentStateVariable { get; set; } = -1;
    public long? Minimum { get; set; }
    public long? Maximum { get; set; }
    public string ModelLabel { get; set; } = string.Empty;
}

internal sealed class CompilerBodyArtifact
{
    public CompilerPreparedBodyKind Kind { get; set; }
    public CompilerVariableMappingArtifact[] ParameterBindings { get; set; } = [];
    public CompilerCallIdentityArtifact[] Calls { get; set; } = [];
    public CompilerSpecCallArtifact[] SpecCalls { get; set; } = [];
    public CompilerSummaryCallArtifact[] SummaryCalls { get; set; } = [];
}

internal sealed class CompilerVariableMappingArtifact
{
    public int Source { get; set; } = -1;
    public int Target { get; set; } = -1;
}

internal sealed class CompilerCallIdentityArtifact
{
    public int Instruction { get; set; } = -1;
    public string Identity { get; set; } = string.Empty;
}

internal sealed class CompilerSpecCallArtifact
{
    public int Instruction { get; set; } = -1;
    public string WitnessIdentifier { get; set; } = string.Empty;
    public bool ConsumesMemoryHavoc { get; set; }
}

internal sealed class CompilerSummaryEvidenceArtifact
{
    public CompilerSummaryOrigin Origin { get; set; }
    public string EvidenceSha256 { get; set; } = string.Empty;
    public string EvidenceIdentity { get; set; } = string.Empty;
}

internal sealed class CompilerSummaryCallArtifact
{
    public int Instruction { get; set; } = -1;
    public string Identity { get; set; } = string.Empty;
    public CompilerSummaryOrigin Origin { get; set; }
    public int Result { get; set; } = -1;
    public int[] ExistentialVariables { get; set; } = [];
    public int NormalRelationRoot { get; set; } = -1;
    public string EvidenceSha256 { get; set; } = string.Empty;
    public string EvidenceIdentity { get; set; } = string.Empty;
    public CompilerSummaryEvidenceArtifact[] DependencyEvidence { get; set; } = [];
}

internal enum CompilerOutputKind
{
    ConsoleApplication = 0,
    WindowsApplication = 1,
    DynamicallyLinkedLibrary = 2,
    NetModule = 3,
    WindowsRuntimeMetadata = 4,
    WindowsRuntimeApplication = 5
}

internal enum CompilerOptimizationLevel
{
    Debug = 0,
    Release = 1
}

internal enum CompilerPlatform
{
    AnyCpu = 0,
    AnyCpu32BitPreferred = 1,
    Arm = 2,
    Arm64 = 3,
    Itanium = 4,
    X64 = 5,
    X86 = 6
}

internal enum CompilerNullableContext
{
    Disable = 0,
    Warnings = 1,
    Annotations = 2,
    Enable = 3
}

internal enum CompilerMetadataImportOptions
{
    Public = 0,
    Internal = 1,
    All = 2
}

internal enum CompilerAssemblyIdentityComparer
{
    Default = 0,
    Desktop = 1
}

internal enum CompilerResolverPolicy
{
    EvidenceOnly = 0
}

internal sealed class CompilerDiagnosticArtifact
{
    public string Code { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
    public WorkerSourceLocation Location { get; set; } = new();
}

internal sealed class CompilerManifestArtifact
{
    public string Schema { get; set; } = CompilerManifestArtifactVersions.Schema;
    public int SchemaVersion { get; set; } = CompilerManifestArtifactVersions.Current;
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public int RelationalSummarySchemaVersion { get; set; } = CompilerRelationalSummaryVersions.Current;
    public int SpecificationPackSchemaVersion { get; set; } = CompilerSpecificationPackVersions.Current;
    public WorkerFeatureSet Features { get; set; }
    public string CompilationSha256 { get; set; } = string.Empty;
    public CompilerCompilationSnapshot Compilation { get; set; } = new();
    public WorkerClaimManifest Manifest { get; set; } = new();
    public int MaximumExpressionDepth { get; set; } = WorkerBudgets.DefaultMaximumExpressionDepth;
    public CompilerDiagnosticArtifact[] CompilerDiagnostics { get; set; } = [];
    public CompilerCallableArtifact[] Callables { get; set; } = [];
}

internal readonly struct CompilerEffectConstraintRule(
    WorkerEffectContractKind kind,
    bool effectsMustBeEmpty,
    bool capabilitiesMustBeEmpty,
    bool exceptionsMustBeEmpty)
{
    internal WorkerEffectContractKind Kind { get; } = kind;
    internal bool EffectsMustBeEmpty { get; } = effectsMustBeEmpty;
    internal bool CapabilitiesMustBeEmpty { get; } = capabilitiesMustBeEmpty;
    internal bool ExceptionsMustBeEmpty { get; } = exceptionsMustBeEmpty;
}

internal static class CompilerEffectEvidenceCatalog
{
    internal const string ConstraintDomain = "SharpProof.CompilerEffectReplayConstraint";
    internal const int ConstraintVersion = 1;
    internal const string OperationDomain = "SharpProof.CompilerEffectReplayOperation";
    internal const int OperationVersion = 1;
    internal const string EvidenceDomain = "SharpProof.CompilerEffectClaimEvidence";
    internal const int EvidenceVersion = 8;
    internal const int MaximumReplayEvents = 256;
    internal const CompilerEffectReplayPathKind ReplayPathKind =
        CompilerEffectReplayPathKind.Unconditional;
    internal static readonly WorkerClaimReason[] UnknownReasons = [
        WorkerClaimReason.UnsupportedContract,
        WorkerClaimReason.CounterexampleNotReplayable,
        WorkerClaimReason.EffectSummaryIncomplete,
        WorkerClaimReason.EffectContractNotEstablished,
        WorkerClaimReason.ResourceLimit,
        WorkerClaimReason.UnsupportedBody,
    ];
    internal static readonly (WorkerClaimOutcome Outcome, WorkerClaimReason Reason,
        WorkerEffectEvidenceCertainty Certainty)[] SupportedEffectTuples = [
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary),
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.VacuousEntry),
        (WorkerClaimOutcome.Refuted, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.DefiniteViolation),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedContract, WorkerEffectEvidenceCertainty.Unavailable),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.CounterexampleNotReplayable, WorkerEffectEvidenceCertainty.Unavailable),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary),
        (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary),
    ];
    internal static bool HasValidEffectTuple(
        WorkerClaimOutcome outcome, WorkerClaimReason reason,
        WorkerEffectEvidenceCertainty certainty)
    {
        foreach (var tuple in SupportedEffectTuples)
        {
            if (tuple.Outcome == outcome && tuple.Reason == reason &&
                tuple.Certainty == certainty)
            {
                return true;
            }
        }
        return outcome == WorkerClaimOutcome.Unknown &&
            certainty == WorkerEffectEvidenceCertainty.Unavailable &&
            UnknownReasons.Contains(reason);
    }
    internal static readonly CompilerEffectConstraintRule[] ConstraintRules = [
        new(WorkerEffectContractKind.EnforcePure, true, true, true),
        new(WorkerEffectContractKind.ZeroAllocations, true, true, true),
        new(WorkerEffectContractKind.AllowedCapabilities, true, false, true),
        new(WorkerEffectContractKind.DoesNotThrow, true, true, true),
        new(WorkerEffectContractKind.AllowedExceptions, true, true, false),
        new(WorkerEffectContractKind.EffectContract, false, false, false),
    ];
    internal static readonly CompilerEffectReplayEventKind[] SupportedReplayEventKinds = [
        CompilerEffectReplayEventKind.ManagedObjectAllocation,
        CompilerEffectReplayEventKind.ManagedArrayAllocation,
    ];
}

internal static class CompilerCallableArtifactReasonCatalog
{
    internal const WorkerClaimReason SuccessReason = WorkerClaimReason.None;
    internal const WorkerClaimReason DiagnosticFailureReason = WorkerClaimReason.UnsupportedCallable;
    internal static readonly WorkerClaimReason[] FailureReasons = [
        WorkerClaimReason.UnsupportedCallable,
        WorkerClaimReason.UnsupportedContract,
        WorkerClaimReason.UnsupportedBody,
        WorkerClaimReason.UnsupportedExpression,
    ];
    internal static bool IsFailureReason(WorkerClaimReason reason) =>
        Array.IndexOf(FailureReasons, reason) >= 0;
}
