// <auto-generated>
// Generated by scripts/Generate-CompilerArtifactModel.ps1 from
// SharpProof.CompilerArtifact/CompilerArtifactModel.schema.json.
// Output: PortableIrModel.generated.cs.
// Do not edit this file directly.
// </auto-generated>
#nullable enable

namespace SharpProof.CompilerArtifact;

internal sealed class PortableIrGraph {
    public bool HasProgram { get; set; }
    public PortableIrType[] Types { get; set; } = [];
    public int[] Identities { get; set; } = [];
    public PortableIrVariable[] Variables { get; set; } = [];
    public PortableIrMember[] Members { get; set; } = [];
    public PortableIrOperation[] Operations { get; set; } = [];
    public PortableIrTerm[] Terms { get; set; } = [];
    public PortableIrBlock[] Blocks { get; set; } = [];
    public int Entry { get; set; } = -1;
    public int[] Roots { get; set; } = [];
}

internal sealed class PortableIrType(
    IrTypeKind kind = default,
    string? name = null,
    int element = -1
) {
    public IrTypeKind Kind { get; set; } = kind;
    public string Name { get; set; } = name ?? string.Empty;
    public int Element { get; set; } = element;
}

internal sealed class PortableIrVariable(
    string? name = null,
    int type = -1
) {
    public string Name { get; set; } = name ?? string.Empty;
    public int Type { get; set; } = type;
}

internal sealed class PortableIrMember(
    int identity = -1,
    int declaringType = -1,
    string? name = null,
    int returnType = -1,
    bool isStatic = false,
    int[]? parameterTypes = null
) {
    public int Identity { get; set; } = identity;
    public int DeclaringType { get; set; } = declaringType;
    public string Name { get; set; } = name ?? string.Empty;
    public int ReturnType { get; set; } = returnType;
    public bool IsStatic { get; set; } = isStatic;
    public int[] ParameterTypes { get; set; } = parameterTypes ?? [];
    public string? DocumentationCommentId { get; set; }
}

internal sealed class PortableIrOperation(
    string? description = null
) {
    public string? Description { get; set; } = description;
}

internal sealed class PortableIrTerm(
    IrTermKind kind = default,
    int type = -1,
    int a = -1,
    int b = -1,
    int c = -1,
    int d = -1,
    long number = 0,
    string? text = null,
    int[]? items = null
) {
    public IrTermKind Kind { get; set; } = kind;
    public int Type { get; set; } = type;
    public int A { get; set; } = a;
    public int B { get; set; } = b;
    public int C { get; set; } = c;
    public int D { get; set; } = d;
    public long Number { get; set; } = number;
    public string? Text { get; set; } = text;
    public int[] Items { get; set; } = items ?? [];
}

internal sealed class PortableIrLocation(
    IrLocationKind kind = default,
    int type = -1,
    int a = -1,
    int b = -1,
    int[]? items = null
) {
    public IrLocationKind Kind { get; set; } = kind;
    public int Type { get; set; } = type;
    public int A { get; set; } = a;
    public int B { get; set; } = b;
    public int[] Items { get; set; } = items ?? [];
}

internal sealed class PortableIrInstruction(
    IrInstructionKind kind = default,
    int operation = -1,
    int a = -1,
    int b = -1,
    int c = -1,
    int[]? items = null,
    PortableIrLocation? location = null
) {
    public IrInstructionKind Kind { get; set; } = kind;
    public int Operation { get; set; } = operation;
    public int A { get; set; } = a;
    public int B { get; set; } = b;
    public int C { get; set; } = c;
    public int[] Items { get; set; } = items ?? [];
    public PortableIrLocation? Location { get; set; } = location;
}

internal sealed class PortableIrBlock(
    string? name = null,
    PortableIrInstruction[]? instructions = null
) {
    public string? Name { get; set; } = name;
    public PortableIrInstruction[] Instructions { get; set; } = instructions ?? [];
}

internal sealed class DecodedPortableIrGraph(
    IrFactory factory,
    IrProgram? program,
    IrTerm[] roots,
    IrVarId[] variables,
    IrBlockId[] blocks,
    IrInstruction[] instructions
) {
    internal IrFactory Factory { get; } = factory;
    internal IrProgram? Program { get; } = program;
    internal IReadOnlyList<IrTerm> Roots { get; } = roots;
    internal IReadOnlyList<IrVarId> Variables { get; } = variables;
    internal IReadOnlyList<IrBlockId> Blocks { get; } = blocks;
    internal IReadOnlyList<IrInstruction> Instructions { get; } = instructions;
}

internal sealed class EncodedPortableIrGraph(
    PortableIrGraph graph,
    IReadOnlyDictionary<IrVarId, int> variableIndices,
    IReadOnlyDictionary<IrInstructionId, int> instructionIndices
) {
    internal PortableIrGraph Graph { get; } = graph;
    internal IReadOnlyDictionary<IrVarId, int> VariableIndices { get; } = variableIndices;
    internal IReadOnlyDictionary<IrInstructionId, int> InstructionIndices { get; } = instructionIndices;
}

internal static partial class PortableIrGraphCodec {
    private static readonly IrOpaquePurity[] OpaquePurities = [
        IrOpaquePurity.Pure,
        IrOpaquePurity.Impure
    ];
    private static readonly IrUnaryOperator[] UnaryOperators = [
        IrUnaryOperator.Not,
        IrUnaryOperator.Negate
    ];
    private static readonly IrBinaryOperator[] BinaryOperators = [
        IrBinaryOperator.Add,
        IrBinaryOperator.Subtract,
        IrBinaryOperator.Multiply,
        IrBinaryOperator.Divide,
        IrBinaryOperator.Remainder,
        IrBinaryOperator.AndAlso,
        IrBinaryOperator.OrElse,
        IrBinaryOperator.Equal,
        IrBinaryOperator.NotEqual,
        IrBinaryOperator.LessThan,
        IrBinaryOperator.LessThanOrEqual,
        IrBinaryOperator.GreaterThan,
        IrBinaryOperator.GreaterThanOrEqual,
        IrBinaryOperator.StringConcat
    ];
    private static readonly IrHavocKind[] HavocKinds = [
        IrHavocKind.Variables,
        IrHavocKind.Memory,
        IrHavocKind.VariablesAndMemory
    ];

    internal static bool HasCompleteWireEnumCatalogs =>
        IsComplete(OpaquePurities) &&
        IsComplete(UnaryOperators) &&
        IsComplete(BinaryOperators) &&
        IsComplete(HavocKinds);

    private static bool IsComplete<T>(T[] values) where T : struct, Enum =>
        values.SequenceEqual(Enum.GetValues(typeof(T)).Cast<T>());
}
