<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <SharpProofUsesMetaAnalyzer>true</SharpProofUsesMetaAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharpProof.Specs\Polyfills\IsExternalInit.cs"
             Link="Polyfills\IsExternalInit.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpProof.Ir\SharpProof.Ir.csproj" />
    <ProjectReference Include="..\SharpProof.Worker.Protocol\SharpProof.Worker.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.Analyzer.Test" />
    <InternalsVisibleTo Include="SharpProof.CompilerCollector" />
    <InternalsVisibleTo Include="SharpProof.Gates" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
    <InternalsVisibleTo Include="SharpProof.Worker.Launcher" />
    <InternalsVisibleTo Include="SharpProof.Package.Test" />
    <InternalsVisibleTo Include="SharpProof.Worker.Test" />
  </ItemGroup>
</Project>
