<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>SharpProof.Demo</AssemblyName>
		<RootNamespace>SharpProof.Demo</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SharpProof.Attributes\SharpProof.Attributes.csproj" />
		<ProjectReference Include="..\SharpProof.Analyzer\SharpProof.Analyzer.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\SharpProof.CodeFixes\SharpProof.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>


