// <auto-generated>
// Generated by scripts/Generate-ProtocolModel.ps1 from
// SharpProof.Worker.Protocol/ProtocolModel.schema.json.
// Do not edit this file directly.
// </auto-generated>
#nullable enable
using System.Collections.Immutable;

namespace SharpProof.Worker.Protocol;

public static class WorkerProtocolVersions
{
    public const string Current = "11";
    public const string EmptySha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
}

public static class WorkerCacheVersions
{
    public const int Current = 13;
}

public static class WorkerManifestVersions
{
    public const int Current = 4;
}

public static class WorkerLauncherDefaults
{
    public const int TerminationGraceMilliseconds = 1000;
    public const int MaximumTerminationGraceMilliseconds = 300000;
}

public sealed class WorkerVerifyRequest
{
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public WorkerFileReference CompilerManifest { get; set; } = new();
    public WorkerBudgets Budgets { get; set; } = new();
    public WorkerCacheOptions Cache { get; set; } = new();
    public WorkerVerifyPolicy VerifyPolicy { get; set; } = WorkerVerifyPolicy.Advisory;
    public WorkerAssumptionPolicy AssumptionPolicy { get; set; } = WorkerAssumptionPolicy.Allow;
}

public sealed class WorkerFileReference
{
    public string Path { get; set; } = string.Empty;
    public string Sha256 { get; set; } = string.Empty;
}

public enum WorkerFeatureSet
{
    Unspecified = 0,
    Effects = 1,
    Contracts = 2,
    All = 3
}

public enum WorkerVerifyPolicy
{
    Unspecified = 0,
    Advisory = 1,
    WarnOnUnknown = 2,
    RequireProven = 3
}

public enum WorkerAssumptionPolicy
{
    Unspecified = 0,
    Allow = 1,
    Warn = 2,
    Error = 3
}

public sealed class WorkerBudgets
{
    public const int MaximumParallelism = 4;
    public const uint DefaultQueryRlimit = 3000000U;
    public const uint DefaultMethodRlimit = 20000000U;
    public const int DefaultMethodWallTimeMilliseconds = 10000;
    public const int DefaultProjectWallTimeMilliseconds = 300000;
    public const int DefaultMaximumExpressionDepth = 64;
    public uint QueryRlimit { get; set; } = DefaultQueryRlimit;
    public uint MethodRlimit { get; set; } = DefaultMethodRlimit;
    public int MethodWallTimeMilliseconds { get; set; } = DefaultMethodWallTimeMilliseconds;
    public int ProjectWallTimeMilliseconds { get; set; } = DefaultProjectWallTimeMilliseconds;
    public int MaxParallelism { get; set; } = MaximumParallelism;
    public int MaximumExpressionDepth { get; set; } = DefaultMaximumExpressionDepth;
}

public sealed class WorkerCacheOptions
{
    public const long DefaultMaximumBytes = 536870912L;
    public bool Enabled { get; set; } = true;
    public string? Directory { get; set; }
    public long MaximumBytes { get; set; } = DefaultMaximumBytes;
}

public enum WorkerSelectedFeature
{
    Unspecified = 0,
    Effects = 1,
    Contracts = 2
}

public enum WorkerSelectionReason
{
    Unspecified = 0,
    ExplicitAnnotation = 1,
    DiscoveredPostcondition = 2
}

public enum WorkerClaimKind
{
    Unspecified = 0,
    Postcondition = 1,
    Effect = 2
}

public enum WorkerClaimEvidence
{
    Unspecified = 0,
    DirectClause = 1,
    CompanionClause = 2,
    ReturnAttribute = 3,
    Attribute = 4
}

public enum WorkerEffectContractKind
{
    Unspecified = 0,
    EnforcePure = 1,
    ZeroAllocations = 2,
    AllowedCapabilities = 3,
    DoesNotThrow = 4,
    AllowedExceptions = 5,
    EffectContract = 6
}

public sealed class WorkerSourceLocation
{
    public string Path { get; set; } = string.Empty;
    public int Start { get; set; }
    public int Length { get; set; }
    public int Line { get; set; }
    public int Column { get; set; }
}

public sealed class WorkerCallableManifestEntry
{
    public string CallableId { get; set; } = string.Empty;
    public WorkerSelectedFeature[] SelectedFeatures { get; set; } = [];
    public WorkerSelectionReason[] SelectionReasons { get; set; } = [];
    public WorkerSourceLocation Location { get; set; } = new();
    public string[] ClaimIds { get; set; } = [];
    public WorkerAssumptionEvidence[] Assumptions { get; set; } = [];
}

public sealed class WorkerClaimManifestEntry
{
    public string ClaimId { get; set; } = string.Empty;
    public string CallableId { get; set; } = string.Empty;
    public int Ordinal { get; set; }
    public WorkerClaimKind Kind { get; set; }
    public WorkerClaimEvidence Evidence { get; set; }
    public WorkerEffectContractKind EffectContractKind { get; set; }
    public WorkerSourceLocation Location { get; set; } = new();
}

public sealed class WorkerClaimManifest
{
    public int SchemaVersion { get; set; } = WorkerManifestVersions.Current;
    public string Hash { get; set; } = string.Empty;
    public WorkerCallableManifestEntry[] Callables { get; set; } = [];
    public WorkerClaimManifestEntry[] Claims { get; set; } = [];
}

public enum WorkerRunStatus
{
    Unspecified = 0,
    Complete = 1,
    TimedOut = 2,
    Canceled = 3,
    Failed = 4
}

public enum WorkerRunFailureReason
{
    Unspecified = 0,
    None = 1,
    InvalidRequest = 2,
    InputUnavailable = 3,
    CompilationFailure = 4,
    CompilerManifestMismatch = 5,
    BackendUnavailable = 6,
    InfrastructureFailure = 7,
    MalformedResult = 8,
    CounterexampleReplayFailed = 9,
    ContainmentFailure = 10
}

public enum WorkerCallableCoverage
{
    Unspecified = 0,
    Complete = 1,
    Incomplete = 2
}

public enum WorkerCallableCoverageReason
{
    Unspecified = 0,
    None = 1,
    UnsupportedCallable = 2,
    UnsupportedContract = 3,
    SemanticUnknown = 4,
    MissingClaimResult = 5,
    MethodTimeout = 6,
    ProjectTimeout = 7,
    Canceled = 8,
    InfrastructureFailure = 9
}

public enum WorkerClaimOutcome
{
    Unspecified = 0,
    Proven = 1,
    Refuted = 2,
    Unknown = 3
}

public enum WorkerEffectEvidenceCertainty
{
    Unspecified = 0,
    IncompleteMayEffectSummary = 1,
    CompleteMayEffectSummary = 2,
    TrustedCompleteBoundary = 3,
    DefiniteViolation = 4,
    Unavailable = 5,
    VacuousEntry = 6
}

[Flags]
public enum WorkerEffectSet : long
{
    None = 0L,
    ReadsReceiverState = 1L,
    ReadsArgumentState = 2L,
    ReadsCapturedState = 4L,
    ReadsStaticState = 8L,
    ReadsAmbientState = 16L,
    WritesReceiverState = 32L,
    WritesArgumentState = 64L,
    WritesCapturedState = 128L,
    WritesStaticState = 256L,
    WritesAmbientState = 512L,
    Allocates = 1024L,
    Throws = 2048L,
    Synchronizes = 4096L,
    UsesNondeterminism = 8192L,
    UsesNativeCode = 16384L,
    UsesReflection = 32768L,
    AllKnown = 65535L
}

[Flags]
public enum WorkerEffectCapabilitySet
{
    None = 0,
    IO = 1,
    FileRead = 2,
    FileWrite = 4,
    Network = 8,
    Console = 16,
    Process = 32,
    Environment = 64,
    Registry = 128,
    Clock = 256,
    Randomness = 512,
    Reflection = 1024,
    Synchronization = 2048,
    NativeInterop = 4096,
    AllKnown = 8191
}

public enum WorkerVacuityKind
{
    None = 0,
    ContradictoryPreconditions = 1,
    NoModeledNormalReturn = 2
}

public enum WorkerClaimReason
{
    Unspecified = 0,
    None = 1,
    UnsupportedCallable = 2,
    UnsupportedContract = 3,
    UnsupportedBody = 4,
    UnsupportedExpression = 5,
    DeepPostcondition = 6,
    MissingReturnValue = 7,
    ResourceLimit = 8,
    MethodTimeout = 9,
    ProjectTimeout = 10,
    Canceled = 11,
    BackendUnavailable = 12,
    InfrastructureFailure = 13,
    MalformedBackendResult = 14,
    CounterexampleReplayFailed = 15,
    PostconditionMayBeUndefined = 16,
    CounterexampleNotReplayable = 17,
    EffectSummaryIncomplete = 18,
    EffectContractNotEstablished = 19
}

public enum WorkerAssumptionKind
{
    Unspecified = 0,
    Precondition = 1,
    UserAssume = 2,
    TrustedBoundary = 3,
    ApiSpecification = 4,
    SourceDomain = 5,
    NormalCompletion = 6
}

public sealed class WorkerAssumptionEvidence
{
    public string Id { get; set; } = string.Empty;
    public WorkerAssumptionKind Kind { get; set; }
    public bool Used { get; set; }
}

public sealed class WorkerCallableResult
{
    public string CallableId { get; set; } = string.Empty;
    public WorkerCallableCoverage Coverage { get; set; }
    public WorkerCallableCoverageReason Reason { get; set; }
    public WorkerAssumptionEvidence[] Assumptions { get; set; } = [];
}

public sealed class WorkerClaimResult
{
    public string ClaimId { get; set; } = string.Empty;
    public WorkerClaimOutcome Outcome { get; set; }
    public WorkerClaimReason Reason { get; set; }
    public WorkerEffectEvidenceCertainty EffectCertainty { get; set; }
    public WorkerEffectViolationWitness? EffectWitness { get; set; }
    public WorkerVacuityKind Vacuity { get; set; }
    public string[] ProofCore { get; set; } = [];
    public WorkerModelValue[] Model { get; set; } = [];
    public WorkerAssumptionEvidence[] Assumptions { get; set; } = [];
}

public sealed class WorkerEffectViolationWitness
{
    public string Kind { get; set; } = string.Empty;
    public string Detail { get; set; } = string.Empty;
    public WorkerEffectSet Effects { get; set; }
    public WorkerEffectCapabilitySet Capabilities { get; set; }
    public string[] ExactExceptionTypeHierarchy { get; set; } = [];
    public WorkerSourceLocation Location { get; set; } = new();
}

public sealed class WorkerModelValue
{
    public string Variable { get; set; } = string.Empty;
    public string Kind { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
}

public sealed class WorkerClaimOutcomeCount
{
    public WorkerClaimOutcome Outcome { get; set; }
    public int Count { get; set; }
}

public sealed class WorkerClaimReasonCount
{
    public WorkerClaimReason Reason { get; set; }
    public int Count { get; set; }
}

public sealed class WorkerAssumptionSummary
{
    public int Total { get; set; }
    public int Used { get; set; }
    public int User { get; set; }
    public int Trusted { get; set; }
}

public enum WorkerCacheStatus
{
    Unspecified = 0,
    Disabled = 1,
    Miss = 2,
    Hit = 3,
    Written = 4,
    Rejected = 5,
    Unavailable = 6
}

public sealed class WorkerVersionSummary
{
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public int ManifestSchemaVersion { get; set; } = WorkerManifestVersions.Current;
    public int CacheSchemaVersion { get; set; } = WorkerCacheVersions.Current;
    public string WorkerVersion { get; set; } = string.Empty;
    public string ApiSpecVersion { get; set; } = string.Empty;
    public string WorkerBinarySha256 { get; set; } = WorkerProtocolVersions.EmptySha256;
    public string ApiSpecContentSha256 { get; set; } = WorkerProtocolVersions.EmptySha256;
}

public sealed class WorkerVerificationSummary
{
    public int CallableCount { get; set; }
    public int ClaimCount { get; set; }
    public WorkerClaimOutcomeCount[] OutcomeCounts { get; set; } = [];
    public WorkerClaimReasonCount[] ReasonCounts { get; set; } = [];
    public WorkerAssumptionSummary Assumptions { get; set; } = new();
    public bool CacheHit { get; set; }
    public WorkerCacheStatus CacheStatus { get; set; }
    public WorkerVersionSummary Versions { get; set; } = new();
    public WorkerBudgets Budgets { get; set; } = new();
    public long ElapsedMilliseconds { get; set; }
}

public sealed class WorkerProtocolError
{
    public string Code { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;
}

public sealed class WorkerVerifyResponse
{
    public string ProtocolVersion { get; set; } = WorkerProtocolVersions.Current;
    public string RequestHash { get; set; } = WorkerProtocolVersions.EmptySha256;
    public string InputHash { get; set; } = string.Empty;
    public WorkerClaimManifest Manifest { get; set; } = new();
    public WorkerRunStatus RunStatus { get; set; }
    public WorkerRunFailureReason FailureReason { get; set; }
    public WorkerCallableResult[] CallableResults { get; set; } = [];
    public WorkerClaimResult[] ClaimResults { get; set; } = [];
    public WorkerVerificationSummary Summary { get; set; } = new();
    public WorkerProtocolError[] Errors { get; set; } = [];
}

public sealed class WorkerProtocolValidationResult
{
    internal WorkerProtocolValidationResult(IEnumerable<WorkerProtocolError> errors) =>
        Errors = [.. errors];
    public ImmutableArray<WorkerProtocolError> Errors { get; }
    public bool IsValid => Errors.IsDefaultOrEmpty;
}

internal readonly struct WorkerProtocolRule<T>(string code, Func<T, bool> isValid)
{
    internal readonly string Code = code;
    internal readonly Func<T, bool> IsValid = isValid;
}

internal static class WorkerProtocolMetadata
{
    internal static readonly string[] WorkerVerifyRequestJsonProperties = [
        "protocolVersion", "compilerManifest", "budgets", "cache", "verifyPolicy", "assumptionPolicy",
    ];
    internal static readonly string[] WorkerVerifyResponseJsonProperties = [
        "protocolVersion", "requestHash", "inputHash", "manifest", "runStatus", "failureReason", "callableResults", "claimResults",
        "summary", "errors",
    ];

    internal static readonly IReadOnlyDictionary<string, WorkerProtocolJsonObjectShape> JsonObjectShapes =
        new Dictionary<string, WorkerProtocolJsonObjectShape>(StringComparer.Ordinal)
        {
            ["WorkerVerifyRequest"] = new([
                new("protocolVersion", "string"),
                new("compilerManifest", "WorkerFileReference"),
                new("budgets", "WorkerBudgets"),
                new("cache", "WorkerCacheOptions"),
                new("verifyPolicy", "WorkerVerifyPolicy"),
                new("assumptionPolicy", "WorkerAssumptionPolicy"),
            ]),
            ["WorkerFileReference"] = new([
                new("path", "string"),
                new("sha256", "string"),
            ]),
            ["WorkerBudgets"] = new([
                new("queryRlimit", "uint"),
                new("methodRlimit", "uint"),
                new("methodWallTimeMilliseconds", "int"),
                new("projectWallTimeMilliseconds", "int"),
                new("maxParallelism", "int"),
                new("maximumExpressionDepth", "int"),
            ]),
            ["WorkerCacheOptions"] = new([
                new("enabled", "bool"),
                new("directory", "string?"),
                new("maximumBytes", "long"),
            ]),
            ["WorkerSourceLocation"] = new([
                new("path", "string"),
                new("start", "int"),
                new("length", "int"),
                new("line", "int"),
                new("column", "int"),
            ]),
            ["WorkerCallableManifestEntry"] = new([
                new("callableId", "string"),
                new("selectedFeatures", "WorkerSelectedFeature[]"),
                new("selectionReasons", "WorkerSelectionReason[]"),
                new("location", "WorkerSourceLocation"),
                new("claimIds", "string[]"),
                new("assumptions", "WorkerAssumptionEvidence[]"),
            ]),
            ["WorkerClaimManifestEntry"] = new([
                new("claimId", "string"),
                new("callableId", "string"),
                new("ordinal", "int"),
                new("kind", "WorkerClaimKind"),
                new("evidence", "WorkerClaimEvidence"),
                new("effectContractKind", "WorkerEffectContractKind"),
                new("location", "WorkerSourceLocation"),
            ]),
            ["WorkerClaimManifest"] = new([
                new("schemaVersion", "int"),
                new("hash", "string"),
                new("callables", "WorkerCallableManifestEntry[]"),
                new("claims", "WorkerClaimManifestEntry[]"),
            ]),
            ["WorkerAssumptionEvidence"] = new([
                new("id", "string"),
                new("kind", "WorkerAssumptionKind"),
                new("used", "bool"),
            ]),
            ["WorkerCallableResult"] = new([
                new("callableId", "string"),
                new("coverage", "WorkerCallableCoverage"),
                new("reason", "WorkerCallableCoverageReason"),
                new("assumptions", "WorkerAssumptionEvidence[]"),
            ]),
            ["WorkerClaimResult"] = new([
                new("claimId", "string"),
                new("outcome", "WorkerClaimOutcome"),
                new("reason", "WorkerClaimReason"),
                new("effectCertainty", "WorkerEffectEvidenceCertainty"),
                new("effectWitness", "WorkerEffectViolationWitness?"),
                new("vacuity", "WorkerVacuityKind"),
                new("proofCore", "string[]"),
                new("model", "WorkerModelValue[]"),
                new("assumptions", "WorkerAssumptionEvidence[]"),
            ]),
            ["WorkerEffectViolationWitness"] = new([
                new("kind", "string"),
                new("detail", "string"),
                new("effects", "WorkerEffectSet"),
                new("capabilities", "WorkerEffectCapabilitySet"),
                new("exactExceptionTypeHierarchy", "string[]"),
                new("location", "WorkerSourceLocation"),
            ]),
            ["WorkerModelValue"] = new([
                new("variable", "string"),
                new("kind", "string"),
                new("value", "string"),
            ]),
            ["WorkerClaimOutcomeCount"] = new([
                new("outcome", "WorkerClaimOutcome"),
                new("count", "int"),
            ]),
            ["WorkerClaimReasonCount"] = new([
                new("reason", "WorkerClaimReason"),
                new("count", "int"),
            ]),
            ["WorkerAssumptionSummary"] = new([
                new("total", "int"),
                new("used", "int"),
                new("user", "int"),
                new("trusted", "int"),
            ]),
            ["WorkerVersionSummary"] = new([
                new("protocolVersion", "string"),
                new("manifestSchemaVersion", "int"),
                new("cacheSchemaVersion", "int"),
                new("workerVersion", "string"),
                new("apiSpecVersion", "string"),
                new("workerBinarySha256", "string"),
                new("apiSpecContentSha256", "string"),
            ]),
            ["WorkerVerificationSummary"] = new([
                new("callableCount", "int"),
                new("claimCount", "int"),
                new("outcomeCounts", "WorkerClaimOutcomeCount[]"),
                new("reasonCounts", "WorkerClaimReasonCount[]"),
                new("assumptions", "WorkerAssumptionSummary"),
                new("cacheHit", "bool"),
                new("cacheStatus", "WorkerCacheStatus"),
                new("versions", "WorkerVersionSummary"),
                new("budgets", "WorkerBudgets"),
                new("elapsedMilliseconds", "long"),
            ]),
            ["WorkerProtocolError"] = new([
                new("code", "string"),
                new("message", "string"),
            ]),
            ["WorkerVerifyResponse"] = new([
                new("protocolVersion", "string"),
                new("requestHash", "string"),
                new("inputHash", "string"),
                new("manifest", "WorkerClaimManifest"),
                new("runStatus", "WorkerRunStatus"),
                new("failureReason", "WorkerRunFailureReason"),
                new("callableResults", "WorkerCallableResult[]"),
                new("claimResults", "WorkerClaimResult[]"),
                new("summary", "WorkerVerificationSummary"),
                new("errors", "WorkerProtocolError[]"),
            ]),
            ["WorkerProtocolValidationResult"] = new([
                new("errors", "ImmutableArray<WorkerProtocolError>"),
                new("isValid", "bool"),
            ]),
        };

    private static readonly HashSet<Enum> s_knownValues = [
        WorkerFeatureSet.Unspecified, WorkerFeatureSet.Effects, WorkerFeatureSet.Contracts, WorkerFeatureSet.All,
        WorkerVerifyPolicy.Unspecified, WorkerVerifyPolicy.Advisory, WorkerVerifyPolicy.WarnOnUnknown, WorkerVerifyPolicy.RequireProven,
        WorkerAssumptionPolicy.Unspecified, WorkerAssumptionPolicy.Allow, WorkerAssumptionPolicy.Warn, WorkerAssumptionPolicy.Error,
        WorkerSelectedFeature.Unspecified, WorkerSelectedFeature.Effects, WorkerSelectedFeature.Contracts,
        WorkerSelectionReason.Unspecified, WorkerSelectionReason.ExplicitAnnotation, WorkerSelectionReason.DiscoveredPostcondition,
        WorkerClaimKind.Unspecified, WorkerClaimKind.Postcondition, WorkerClaimKind.Effect,
        WorkerClaimEvidence.Unspecified, WorkerClaimEvidence.DirectClause, WorkerClaimEvidence.CompanionClause,
        WorkerClaimEvidence.ReturnAttribute, WorkerClaimEvidence.Attribute,
        WorkerEffectContractKind.Unspecified, WorkerEffectContractKind.EnforcePure, WorkerEffectContractKind.ZeroAllocations,
        WorkerEffectContractKind.AllowedCapabilities, WorkerEffectContractKind.DoesNotThrow, WorkerEffectContractKind.AllowedExceptions,
        WorkerEffectContractKind.EffectContract,
        WorkerRunStatus.Unspecified, WorkerRunStatus.Complete, WorkerRunStatus.TimedOut, WorkerRunStatus.Canceled, WorkerRunStatus.Failed,
        WorkerCallableCoverage.Unspecified, WorkerCallableCoverage.Complete, WorkerCallableCoverage.Incomplete,
        WorkerClaimOutcome.Unspecified, WorkerClaimOutcome.Proven, WorkerClaimOutcome.Refuted, WorkerClaimOutcome.Unknown,
        WorkerClaimReason.Unspecified, WorkerClaimReason.None, WorkerClaimReason.UnsupportedCallable,
        WorkerClaimReason.UnsupportedContract, WorkerClaimReason.UnsupportedBody, WorkerClaimReason.UnsupportedExpression,
        WorkerClaimReason.DeepPostcondition, WorkerClaimReason.MissingReturnValue, WorkerClaimReason.ResourceLimit,
        WorkerClaimReason.MethodTimeout, WorkerClaimReason.ProjectTimeout, WorkerClaimReason.Canceled,
        WorkerClaimReason.BackendUnavailable, WorkerClaimReason.InfrastructureFailure, WorkerClaimReason.MalformedBackendResult,
        WorkerClaimReason.CounterexampleReplayFailed, WorkerClaimReason.PostconditionMayBeUndefined,
        WorkerClaimReason.CounterexampleNotReplayable, WorkerClaimReason.EffectSummaryIncomplete,
        WorkerClaimReason.EffectContractNotEstablished,
        WorkerEffectEvidenceCertainty.Unspecified, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary,
        WorkerEffectEvidenceCertainty.CompleteMayEffectSummary, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary,
        WorkerEffectEvidenceCertainty.DefiniteViolation, WorkerEffectEvidenceCertainty.Unavailable,
        WorkerEffectEvidenceCertainty.VacuousEntry,
        WorkerAssumptionKind.Unspecified, WorkerAssumptionKind.Precondition, WorkerAssumptionKind.UserAssume,
        WorkerAssumptionKind.TrustedBoundary, WorkerAssumptionKind.ApiSpecification, WorkerAssumptionKind.SourceDomain,
        WorkerAssumptionKind.NormalCompletion,
    ];
    internal static bool IsKnown<T>(T value) where T : struct, Enum =>
        s_knownValues.Contains((Enum)(object)value);
    internal static string? GetManifestName(Enum value) => value switch
    {
        WorkerSelectedFeature.Unspecified => nameof(WorkerSelectedFeature.Unspecified),
        WorkerSelectedFeature.Effects => nameof(WorkerSelectedFeature.Effects),
        WorkerSelectedFeature.Contracts => nameof(WorkerSelectedFeature.Contracts),
        WorkerSelectionReason.Unspecified => nameof(WorkerSelectionReason.Unspecified),
        WorkerSelectionReason.ExplicitAnnotation => nameof(WorkerSelectionReason.ExplicitAnnotation),
        WorkerSelectionReason.DiscoveredPostcondition => nameof(WorkerSelectionReason.DiscoveredPostcondition),
        WorkerAssumptionKind.Unspecified => nameof(WorkerAssumptionKind.Unspecified),
        WorkerAssumptionKind.Precondition => nameof(WorkerAssumptionKind.Precondition),
        WorkerAssumptionKind.UserAssume => nameof(WorkerAssumptionKind.UserAssume),
        WorkerAssumptionKind.TrustedBoundary => nameof(WorkerAssumptionKind.TrustedBoundary),
        WorkerAssumptionKind.ApiSpecification => nameof(WorkerAssumptionKind.ApiSpecification),
        WorkerAssumptionKind.SourceDomain => nameof(WorkerAssumptionKind.SourceDomain),
        WorkerAssumptionKind.NormalCompletion => nameof(WorkerAssumptionKind.NormalCompletion),
        WorkerClaimKind.Unspecified => nameof(WorkerClaimKind.Unspecified),
        WorkerClaimKind.Postcondition => nameof(WorkerClaimKind.Postcondition),
        WorkerClaimKind.Effect => nameof(WorkerClaimKind.Effect),
        WorkerClaimEvidence.Unspecified => nameof(WorkerClaimEvidence.Unspecified),
        WorkerClaimEvidence.DirectClause => nameof(WorkerClaimEvidence.DirectClause),
        WorkerClaimEvidence.CompanionClause => nameof(WorkerClaimEvidence.CompanionClause),
        WorkerClaimEvidence.ReturnAttribute => nameof(WorkerClaimEvidence.ReturnAttribute),
        WorkerClaimEvidence.Attribute => nameof(WorkerClaimEvidence.Attribute),
        WorkerEffectContractKind.Unspecified => nameof(WorkerEffectContractKind.Unspecified),
        WorkerEffectContractKind.EnforcePure => nameof(WorkerEffectContractKind.EnforcePure),
        WorkerEffectContractKind.ZeroAllocations => nameof(WorkerEffectContractKind.ZeroAllocations),
        WorkerEffectContractKind.AllowedCapabilities => nameof(WorkerEffectContractKind.AllowedCapabilities),
        WorkerEffectContractKind.DoesNotThrow => nameof(WorkerEffectContractKind.DoesNotThrow),
        WorkerEffectContractKind.AllowedExceptions => nameof(WorkerEffectContractKind.AllowedExceptions),
        WorkerEffectContractKind.EffectContract => nameof(WorkerEffectContractKind.EffectContract),
        _ => null
    };
    internal static int GetAssumptionOrder(WorkerAssumptionKind value) => value switch
    {
        WorkerAssumptionKind.Unspecified => 0,
        WorkerAssumptionKind.Precondition => 1,
        WorkerAssumptionKind.UserAssume => 2,
        WorkerAssumptionKind.TrustedBoundary => 3,
        WorkerAssumptionKind.ApiSpecification => 4,
        WorkerAssumptionKind.SourceDomain => 5,
        WorkerAssumptionKind.NormalCompletion => 6,
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, "The manifest contains an unknown enum value.")
    };
    internal static bool HasOnlyKnownFlags(WorkerEffectSet value) => (value & ~WorkerEffectSet.AllKnown) == 0;
    internal static bool HasOnlyKnownFlags(WorkerEffectCapabilitySet value) => (value & ~WorkerEffectCapabilitySet.AllKnown) == 0;

    internal static bool MatchesClaimShape(WorkerClaimKind kind, WorkerClaimEvidence evidence, WorkerEffectContractKind effectKind) =>
        (kind, evidence, effectKind) is
            (WorkerClaimKind.Postcondition, WorkerClaimEvidence.DirectClause, WorkerEffectContractKind.Unspecified)
            or (WorkerClaimKind.Postcondition, WorkerClaimEvidence.CompanionClause, WorkerEffectContractKind.Unspecified)
            or (WorkerClaimKind.Postcondition, WorkerClaimEvidence.ReturnAttribute, WorkerEffectContractKind.Unspecified)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.EnforcePure)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.ZeroAllocations)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.AllowedCapabilities)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.DoesNotThrow)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.AllowedExceptions)
            or (WorkerClaimKind.Effect, WorkerClaimEvidence.Attribute, WorkerEffectContractKind.EffectContract);
    internal static bool MatchesCallableCoverage(WorkerCallableCoverage coverage, WorkerCallableCoverageReason reason) =>
        coverage switch
        {
            WorkerCallableCoverage.Complete => reason is WorkerCallableCoverageReason.None,
            WorkerCallableCoverage.Incomplete => reason is WorkerCallableCoverageReason.UnsupportedCallable
                or WorkerCallableCoverageReason.UnsupportedContract or WorkerCallableCoverageReason.SemanticUnknown
                or WorkerCallableCoverageReason.MissingClaimResult or WorkerCallableCoverageReason.MethodTimeout
                or WorkerCallableCoverageReason.ProjectTimeout or WorkerCallableCoverageReason.Canceled
                or WorkerCallableCoverageReason.InfrastructureFailure,
            _ => false
        };
    internal static bool MatchesClaimOutcome(WorkerClaimOutcome outcome, WorkerClaimReason reason) =>
        outcome switch
        {
            WorkerClaimOutcome.Proven or WorkerClaimOutcome.Refuted => reason is WorkerClaimReason.None,
            WorkerClaimOutcome.Unknown => reason is WorkerClaimReason.UnsupportedCallable or WorkerClaimReason.UnsupportedContract
                or WorkerClaimReason.UnsupportedBody or WorkerClaimReason.UnsupportedExpression or WorkerClaimReason.DeepPostcondition
                or WorkerClaimReason.MissingReturnValue or WorkerClaimReason.ResourceLimit or WorkerClaimReason.MethodTimeout
                or WorkerClaimReason.ProjectTimeout or WorkerClaimReason.Canceled or WorkerClaimReason.BackendUnavailable
                or WorkerClaimReason.InfrastructureFailure or WorkerClaimReason.MalformedBackendResult
                or WorkerClaimReason.CounterexampleReplayFailed or WorkerClaimReason.PostconditionMayBeUndefined
                or WorkerClaimReason.CounterexampleNotReplayable or WorkerClaimReason.EffectSummaryIncomplete
                or WorkerClaimReason.EffectContractNotEstablished,
            _ => false
        };
    internal static bool MatchesClaimKindOutcome(WorkerClaimKind kind, WorkerClaimOutcome outcome, WorkerClaimReason reason) =>
        (kind, outcome, reason) is
            (_, WorkerClaimOutcome.Proven, WorkerClaimReason.None) or (_, WorkerClaimOutcome.Refuted, WorkerClaimReason.None)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedCallable)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedContract)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedExpression)
            or (WorkerClaimKind.Postcondition, WorkerClaimOutcome.Unknown, WorkerClaimReason.DeepPostcondition)
            or (WorkerClaimKind.Postcondition, WorkerClaimOutcome.Unknown, WorkerClaimReason.MissingReturnValue)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.MethodTimeout)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.ProjectTimeout)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.Canceled)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.BackendUnavailable)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.InfrastructureFailure)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.MalformedBackendResult)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.CounterexampleReplayFailed)
            or (WorkerClaimKind.Postcondition, WorkerClaimOutcome.Unknown, WorkerClaimReason.PostconditionMayBeUndefined)
            or (_, WorkerClaimOutcome.Unknown, WorkerClaimReason.CounterexampleNotReplayable)
            or (WorkerClaimKind.Effect, WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete)
            or (WorkerClaimKind.Effect, WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished);
    internal static bool MatchesEffectCertainty(WorkerClaimOutcome outcome, WorkerClaimReason reason, WorkerEffectEvidenceCertainty certainty) =>
        (outcome, reason, certainty) is
            (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary)
            or (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary)
            or (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.VacuousEntry)
            or (WorkerClaimOutcome.Refuted, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.DefiniteViolation)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedContract, WorkerEffectEvidenceCertainty.Unavailable)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.CounterexampleNotReplayable, WorkerEffectEvidenceCertainty.Unavailable)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary)
            or (WorkerClaimOutcome.Unknown, _, WorkerEffectEvidenceCertainty.Unavailable);
    internal static bool MatchesEffectEvidenceTuple(WorkerClaimOutcome outcome, WorkerClaimReason reason, WorkerEffectEvidenceCertainty certainty, WorkerVacuityKind vacuity, bool hasProofCore, bool hasTrustedProvenance, bool trustedProvenanceUsed) =>
        (outcome, reason, certainty, vacuity, hasProofCore, hasTrustedProvenance, trustedProvenanceUsed) is
            (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary, WorkerVacuityKind.None, _, _, _)
            or (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary, WorkerVacuityKind.None, _, true, true)
            or (WorkerClaimOutcome.Proven, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.VacuousEntry, WorkerVacuityKind.ContradictoryPreconditions, true, _, _)
            or (WorkerClaimOutcome.Refuted, WorkerClaimReason.None, WorkerEffectEvidenceCertainty.DefiniteViolation, WorkerVacuityKind.None, false, _, _)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary, WorkerVacuityKind.None, false, _, _)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectSummaryIncomplete, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary, WorkerVacuityKind.None, false, true, true)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.CompleteMayEffectSummary, WorkerVacuityKind.None, false, _, _)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.EffectContractNotEstablished, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary, WorkerVacuityKind.None, false, true, true)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary, WorkerVacuityKind.None, false, _, _)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.ResourceLimit, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary, WorkerVacuityKind.None, false, true, true)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.IncompleteMayEffectSummary, WorkerVacuityKind.None, false, _, _)
            or (WorkerClaimOutcome.Unknown, WorkerClaimReason.UnsupportedBody, WorkerEffectEvidenceCertainty.TrustedCompleteBoundary, WorkerVacuityKind.None, false, true, true)
            or (WorkerClaimOutcome.Unknown, _, WorkerEffectEvidenceCertainty.Unavailable, WorkerVacuityKind.None, false, _, _);
    internal static bool MatchesVacuity(WorkerClaimKind kind, WorkerClaimOutcome outcome, WorkerVacuityKind vacuity) =>
        (kind, outcome, vacuity) is
            (_, _, WorkerVacuityKind.None)
            or (WorkerClaimKind.Postcondition, WorkerClaimOutcome.Proven, WorkerVacuityKind.ContradictoryPreconditions)
            or (WorkerClaimKind.Postcondition, WorkerClaimOutcome.Proven, WorkerVacuityKind.NoModeledNormalReturn)
            or (WorkerClaimKind.Effect, WorkerClaimOutcome.Proven, WorkerVacuityKind.ContradictoryPreconditions);
    internal static bool MatchesRunFailure(WorkerRunStatus status, WorkerRunFailureReason reason) =>
        status switch
        {
            WorkerRunStatus.Complete or WorkerRunStatus.TimedOut or WorkerRunStatus.Canceled => reason is WorkerRunFailureReason.None,
            WorkerRunStatus.Failed => reason is WorkerRunFailureReason.InvalidRequest or WorkerRunFailureReason.InputUnavailable
                or WorkerRunFailureReason.CompilationFailure or WorkerRunFailureReason.CompilerManifestMismatch
                or WorkerRunFailureReason.BackendUnavailable or WorkerRunFailureReason.InfrastructureFailure
                or WorkerRunFailureReason.MalformedResult or WorkerRunFailureReason.CounterexampleReplayFailed
                or WorkerRunFailureReason.ContainmentFailure,
            _ => false
        };
    internal static bool MatchesCacheState(WorkerCacheStatus status, bool hit) =>
        (status, hit) is
            (WorkerCacheStatus.Disabled, false) or (WorkerCacheStatus.Miss, false) or (WorkerCacheStatus.Hit, true)
            or (WorkerCacheStatus.Written, false) or (WorkerCacheStatus.Rejected, false) or (WorkerCacheStatus.Unavailable, false);
    internal static bool MatchesClaimPayload(WorkerClaimOutcome outcome, bool hasProofCore, bool hasModel) =>
        (outcome, hasProofCore, hasModel) is
            (WorkerClaimOutcome.Proven, _, false) or (WorkerClaimOutcome.Refuted, false, _) or (WorkerClaimOutcome.Unknown, false, false);
    internal static bool MatchesAssumptionKind(WorkerAssumptionKind kind) =>
        (kind) is
            (WorkerAssumptionKind.Precondition) or (WorkerAssumptionKind.UserAssume) or (WorkerAssumptionKind.TrustedBoundary);

    internal static readonly WorkerProtocolRule<WorkerVerifyRequest>[] RequestRules = [
        new("protocol.unsupported", static value => value.ProtocolVersion == WorkerProtocolVersions.Current),
        new("project.compiler_manifest", static value =>
            (value.CompilerManifest != null
            && !string.IsNullOrWhiteSpace(value.CompilerManifest.Path)
            && WorkerProtocolJson.IsSha256(value.CompilerManifest.Sha256))),
        new("cache.null", static value => value.Cache != null),
        new("cache.maximum_bytes", static value =>
            (!(value.Cache != null)
            || (value.Cache.MaximumBytes is >= 1 and <= WorkerCacheOptions.DefaultMaximumBytes))),
        new("policy.verify", static value => WorkerProtocolJson.IsDefined(value.VerifyPolicy, WorkerVerifyPolicy.Unspecified)),
        new("policy.assumption", static value => WorkerProtocolJson.IsDefined(value.AssumptionPolicy, WorkerAssumptionPolicy.Unspecified)),
    ];
    internal static readonly WorkerProtocolRule<WorkerBudgets>[] BudgetsRules = [
        new("rlimit", static value => value.QueryRlimit > 0),
        new("method_rlimit", static value => value.MethodRlimit > 0),
        new("rlimit_order", static value => value.QueryRlimit <= value.MethodRlimit),
        new("method_wall", static value => value.MethodWallTimeMilliseconds > 0),
        new("project_wall", static value => value.ProjectWallTimeMilliseconds > 0),
        new("parallelism", static value => value.MaxParallelism is >= 1 and <= WorkerBudgets.MaximumParallelism),
        new("expression_depth", static value => value.MaximumExpressionDepth is >= 1 and <= 256),
        new("wall_order", static value => value.MethodWallTimeMilliseconds <= value.ProjectWallTimeMilliseconds),
    ];
    internal static bool IsSourceLocationValid(WorkerSourceLocation value) =>
        (!string.IsNullOrWhiteSpace(value.Path)
        && value.Start >= 0
        && value.Length >= 0
        && value.Line > 0
        && value.Column > 0);
    internal static readonly WorkerProtocolRule<WorkerCallableManifestEntry>[] ManifestCallableRules = [
        new("selected_features", static value =>
            WorkerProtocolJson.AreDefinedUnique(value.SelectedFeatures, WorkerSelectedFeature.Unspecified, true)),
        new("selection_reasons", static value =>
            WorkerProtocolJson.AreDefinedUnique(value.SelectionReasons, WorkerSelectionReason.Unspecified, true)),
        new("callable_claim_ids", static value => WorkerProtocolJson.AreDistinctNonblank(value.ClaimIds)),
        new("callable_assumptions", static value => WorkerProtocolJson.AreValidAssumptions(value.Assumptions)),
        new("callable_assumption_usage", static value => (value.Assumptions ?? []).All(static item => item != null && !item.Used)),
    ];
    internal static readonly WorkerProtocolRule<WorkerClaimManifestEntry>[] ManifestClaimRules = [
        new("claim_ordinal", static value => value.Ordinal >= 0),
        new("claim_kind", static value => WorkerProtocolJson.IsDefined(value.Kind, WorkerClaimKind.Unspecified)),
        new("claim_evidence", static value => WorkerProtocolJson.IsDefined(value.Evidence, WorkerClaimEvidence.Unspecified)),
        new("claim_shape", static value => WorkerProtocolMetadata.MatchesClaimShape(value.Kind, value.Evidence, value.EffectContractKind)),
    ];
    internal static bool IsAssumptionValid(WorkerAssumptionEvidence value) =>
        (!string.IsNullOrWhiteSpace(value.Id)
        && WorkerProtocolMetadata.MatchesAssumptionKind(value.Kind));
    internal static readonly WorkerProtocolRule<WorkerCallableResult>[] CallableResultRules = [
        new("response.callable_coverage", static value => WorkerProtocolJson.IsDefined(value.Coverage, WorkerCallableCoverage.Unspecified)),
        new("response.callable_reason", static value => WorkerProtocolMetadata.MatchesCallableCoverage(value.Coverage, value.Reason)),
        new("response.callable_assumptions", static value => WorkerProtocolJson.AreValidAssumptions(value.Assumptions)),
        new("response.callable_assumption_usage", static value => (value.Assumptions ?? []).All(static item => item != null && !item.Used)),
    ];
    internal static readonly WorkerProtocolRule<WorkerClaimResult>[] ClaimResultRules = [
        new("response.claim_outcome", static value => WorkerProtocolJson.IsDefined(value.Outcome, WorkerClaimOutcome.Unspecified)),
        new("response.claim_reason", static value => WorkerProtocolMetadata.MatchesClaimOutcome(value.Outcome, value.Reason)),
        new("response.proof_core", static value => WorkerProtocolJson.AreDistinctNonblank(value.ProofCore)),
        new("response.model", static value => WorkerProtocolJson.AreValidModel(value.Model)),
        new("response.assumptions", static value => WorkerProtocolJson.AreValidAssumptions(value.Assumptions)),
        new("response.vacuity_evidence", static value =>
            (!(value.Vacuity != WorkerVacuityKind.None)
            || (value.ProofCore is { Length: > 0 }))),
        new("response.claim_payload", static value =>
            WorkerProtocolMetadata.MatchesClaimPayload(value.Outcome, value.ProofCore is { Length: > 0 }, value.Model is { Length: > 0 })),
    ];
    internal static bool IsEffectWitnessValid(WorkerEffectViolationWitness value) =>
        (!string.IsNullOrWhiteSpace(value.Kind)
        && !string.IsNullOrWhiteSpace(value.Detail)
        && WorkerProtocolMetadata.HasOnlyKnownFlags(value.Effects)
        && WorkerProtocolMetadata.HasOnlyKnownFlags(value.Capabilities)
        && (value.Effects != WorkerEffectSet.None
        || value.Capabilities != WorkerEffectCapabilitySet.None)
        && (!(value.ExactExceptionTypeHierarchy is { Length: > 0 })
        || ((value.Effects & WorkerEffectSet.Throws) != 0))
        && WorkerProtocolJson.AreDistinctNonblank(value.ExactExceptionTypeHierarchy));
    internal static bool IsVersionsValid(WorkerVersionSummary value) =>
        (value.ProtocolVersion == WorkerProtocolVersions.Current
        && value.ManifestSchemaVersion == WorkerManifestVersions.Current
        && value.CacheSchemaVersion == WorkerCacheVersions.Current
        && !string.IsNullOrWhiteSpace(value.WorkerVersion)
        && !string.IsNullOrWhiteSpace(value.ApiSpecVersion)
        && WorkerProtocolJson.IsSha256(value.WorkerBinarySha256)
        && WorkerProtocolJson.IsSha256(value.ApiSpecContentSha256));
    internal static readonly WorkerProtocolRule<WorkerVerificationSummary>[] SummaryRules = [
        new("summary.cache", static value => WorkerProtocolMetadata.MatchesCacheState(value.CacheStatus, value.CacheHit)),
        new("summary.versions", static value =>
            (value.Versions != null
            && WorkerProtocolMetadata.IsVersionsValid(value.Versions))),
        new("summary.elapsed", static value => value.ElapsedMilliseconds >= 0),
    ];
    internal static bool IsProtocolErrorValid(WorkerProtocolError value) =>
        (!string.IsNullOrWhiteSpace(value.Code)
        && WorkerProtocolJson.IsSingleLineText(value.Code)
        && !string.IsNullOrWhiteSpace(value.Message)
        && WorkerProtocolJson.IsSingleLineText(value.Message));
}

internal enum WorkerManifestIdentityFieldKind
{
    String,
    Int,
    Enum,
    Location,
    EnumArray,
    OrdinalStringArray,
    AssumptionArray,
}

internal readonly struct WorkerManifestIdentityField
{
    internal WorkerManifestIdentityField(
        string label, string property,
        WorkerManifestIdentityFieldKind kind, string? defaultMember)
    {
        Label = label;
        Property = property;
        Kind = kind;
        DefaultMember = defaultMember;
    }
    internal string Label { get; }
    internal string Property { get; }
    internal WorkerManifestIdentityFieldKind Kind { get; }
    internal string? DefaultMember { get; }
}
internal readonly struct WorkerManifestIdentityOrder
{
    internal WorkerManifestIdentityOrder(string property, string kind)
    {
        Property = property;
        Kind = kind;
    }
    internal string Property { get; }
    internal string Kind { get; }
}
internal readonly struct WorkerManifestIdentityCollection
{
    internal WorkerManifestIdentityCollection(
        string property, string lengthLabel, string entryLabel,
        WorkerManifestIdentityOrder[] order,
        WorkerManifestIdentityField[] fields)
    {
        Property = property;
        LengthLabel = lengthLabel;
        EntryLabel = entryLabel;
        Order = order;
        Fields = fields;
    }
    internal string Property { get; }
    internal string LengthLabel { get; }
    internal string EntryLabel { get; }
    internal WorkerManifestIdentityOrder[] Order { get; }
    internal WorkerManifestIdentityField[] Fields { get; }
}

internal static class WorkerManifestIdentityCatalog
{
    internal const string Domain = "SharpProof.Worker.ManifestHash";
    internal static readonly WorkerManifestIdentityField[] RootFields = [
        new("manifest.schemaVersion", "SchemaVersion", WorkerManifestIdentityFieldKind.Int, null),
    ];
    internal static readonly WorkerManifestIdentityCollection[] Collections = [
        new("Callables", "manifest.callables", "callable", [
            new("CallableId", "ordinalString"),
        ], [
            new("callable.id", "CallableId", WorkerManifestIdentityFieldKind.String, null),
            new("callable.selectedFeatures", "SelectedFeatures", WorkerManifestIdentityFieldKind.EnumArray, null),
            new("callable.selectionReasons", "SelectionReasons", WorkerManifestIdentityFieldKind.EnumArray, null),
            new("callable.location", "Location", WorkerManifestIdentityFieldKind.Location, null),
            new("callable.claimIds", "ClaimIds", WorkerManifestIdentityFieldKind.OrdinalStringArray, null),
            new("callable.assumptions", "Assumptions", WorkerManifestIdentityFieldKind.AssumptionArray, null),
        ]),
        new("Claims", "manifest.claims", "claim", [
            new("CallableId", "ordinalString"),
            new("Ordinal", "integer"),
            new("ClaimId", "ordinalString"),
        ], [
            new("claim.id", "ClaimId", WorkerManifestIdentityFieldKind.String, null),
            new("claim.callableId", "CallableId", WorkerManifestIdentityFieldKind.String, null),
            new("claim.ordinal", "Ordinal", WorkerManifestIdentityFieldKind.Int, null),
            new("claim.kind", "Kind", WorkerManifestIdentityFieldKind.Enum, "WorkerClaimKind.Unspecified"),
            new("claim.evidence", "Evidence", WorkerManifestIdentityFieldKind.Enum, "WorkerClaimEvidence.Unspecified"),
            new("claim.effectContractKind", "EffectContractKind", WorkerManifestIdentityFieldKind.Enum, "WorkerEffectContractKind.Unspecified"),
            new("claim.location", "Location", WorkerManifestIdentityFieldKind.Location, null),
        ]),
    ];
}
