<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DefineConstants>$(DefineConstants);SHARPPROOF_WORKER_PROTOCOL</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\SharpProof.Ir\HashEncoding.cs"
             Link="HashEncoding.cs" />
    <Compile Include="..\SharpProof.Ir\Utf16WellFormedness.cs"
             Link="Utf16WellFormedness.cs" />
    <Compile Update="ProtocolModel.generated.cs">
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
      <DependentUpon>ProtocolModel.schema.json</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpProof.BuildTasks" />
    <InternalsVisibleTo Include="SharpProof.CompilerArtifact" />
    <InternalsVisibleTo Include="SharpProof.Gates" />
    <InternalsVisibleTo Include="SharpProof.Worker" />
    <InternalsVisibleTo Include="SharpProof.Worker.Launcher" />
    <InternalsVisibleTo Include="SharpProof.Worker.Test" />
    <InternalsVisibleTo Include="SharpProof.Package.Test" />
  </ItemGroup>
</Project>
