// <auto-generated>
// Hand-maintained. Originally emitted by a retired generator; the marker
// keeps analyzers treating this declarative code as generated.
// </auto-generated>
#nullable enable

namespace SharpProof.Worker.Protocol;

internal static class WorkerInvocationArguments
{
    internal const string Command = "verify";
    internal const string RequestOption = "--request";
    internal const string ResultOption = "--result";
}
